import { ArchivePattern } from './types/knowledgeEngine';
import { SIGNALS } from './signalDefinitions';

export const ARCHIVE_PATTERNS: ArchivePattern[] = [
  {
    key: 'overextended_caregiver',
    title: 'Your Relationship with Care',
    category: 'relationships',
    requiredSignals: [SIGNALS.HIGH_RESPONSIBILITY.key],
    supportingSignals: [SIGNALS.SUPPORT_NEED.key, SIGNALS.LOW_ENERGY.key, SIGNALS.BODY_KNOWS_FIRST.key],
    minConfidence: 0.7,
    minEvidenceCount: 4,
    lookbackDays: 30,
    copyFrame: {
      observation: 'A repeated signal is that care often leaves your system before it returns to you.',
      pattern: 'Across recent entries, you seem quick to notice what others need, what might help, and what could fall apart if you do not step in.',
      reframe: {
        shame: 'This does not read as poor boundaries alone.',
        clarity: 'It reads as a generous system that has not yet learned to count itself as someone worth protecting too.',
      },
    },
    dailyAngles: [
      {
        key: 'giving_vs_receiving',
        triggerSignals: [SIGNALS.SUPPORT_NEED.key],
        title: 'Giving vs Receiving',
        shameFrame: 'This does not read as being needy.',
        clarityFrame: 'It reads as a generous heart learning that its own needs are valid too.',
        prompt: 'What is one thing you need today that you usually provide for others?',
      },
    ],
  },
  {
    key: 'quiet_hero',
    title: 'The Cost of Quiet Strength',
    category: 'identity',
    requiredSignals: [SIGNALS.HIGH_RESPONSIBILITY.key],
    supportingSignals: [SIGNALS.LOW_ENERGY.key, SIGNALS.OVEREXTENSION.key, SIGNALS.BODY_KNOWS_FIRST.key],
    minConfidence: 0.7,
    minEvidenceCount: 4,
    lookbackDays: 30,
    copyFrame: {
      observation: 'What keeps surfacing is that your strength often works silently in the background.',
      pattern: 'Across recent patterns, you appear to keep going, solving, protecting, or enduring without always naming how much it costs.',
      reframe: {
        shame: 'This does not read as needing attention.',
        clarity: 'It reads as a quiet strength that deserves to be witnessed before it becomes exhaustion.',
      },
    },
    dailyAngles: [],
  },
  {
    key: 'deep_processor',
    title: 'How You Process pain',
    category: 'selfTrust',
    requiredSignals: [SIGNALS.DEEP_PROCESSING.key],
    supportingSignals: [SIGNALS.MEANING_MAKING.key, SIGNALS.NEED_FOR_EXACT_WORDS.key, SIGNALS.PATTERN_RECOGNITION.key],
    minConfidence: 0.7,
    minEvidenceCount: 5,
    lookbackDays: 90,
    copyFrame: {
      observation: 'One consistent thread is that understanding is one of the ways you regulate.',
      pattern: 'Across recent entries, you return often to meaning, context, cause, and the deeper thread beneath what happened.',
      reframe: {
        shame: 'This does not read as overthinking.',
        clarity: 'It reads as your mind trying to make something emotionally safe enough to feel.',
      },
    },
    dailyAngles: [
      {
        key: 'daily_questions_as_depth',
        triggerSignals: [SIGNALS.DEEP_PROCESSING.key, SIGNALS.PATTERN_RECOGNITION.key],
        title: 'The Question Underneath the Question',
        shameFrame: 'This does not read as spiraling.',
        clarityFrame: 'It reads as your daily questions giving shape to something your system has been trying to understand for a while.',
        prompt: 'Which answer from your daily questions feels most alive in the rest of your archive right now?',
      },
    ],
  },
  {
    key: 'boundary_rebuilder',
    title: 'Where You Draw the Line',
    category: 'boundaries',
    requiredSignals: [SIGNALS.BOUNDARY_GROWTH.key],
    supportingSignals: [SIGNALS.SELF_TRUST_GROWTH.key, SIGNALS.OVEREXTENSION.key],
    minConfidence: 0.65,
    minEvidenceCount: 3,
    lookbackDays: 60,
    copyFrame: {
      observation: 'Your archive shows a growing shift in how you hold your limits.',
      pattern: 'Across recent entries, there is less energy spent asking whether your boundary is acceptable and more attention given to whether it is true.',
      reframe: {
        shame: 'This does not read as becoming cold.',
        clarity: 'It reads as self-trust beginning to stand without needing everyone’s permission.',
      },
    },
    dailyAngles: [
      {
        key: 'boundary_across_sources',
        triggerSignals: [SIGNALS.BOUNDARY_GROWTH.key],
        title: 'A Boundary Appearing in More Than One Place',
        shameFrame: 'This does not read as distance.',
        clarityFrame: 'It reads as the same self-protective truth showing up through your answers, logs, body, and relationships.',
        prompt: 'Where is the archive asking you to believe your no the first time?',
      },
    ],
  },
  {
    key: 'support_starved_achiever',
    title: 'When Capability Hides Need',
    category: 'support',
    requiredSignals: [SIGNALS.HIGH_RESPONSIBILITY.key, SIGNALS.SUPPORT_NEED.key],
    supportingSignals: [SIGNALS.LOW_CAPACITY.key, SIGNALS.OVEREXTENSION.key],
    minConfidence: 0.7,
    minEvidenceCount: 4,
    lookbackDays: 30,
    copyFrame: {
      observation: 'The pattern points to competence making your need for support harder to see.',
      pattern: 'Across recent patterns, you keep functioning, planning, producing, or showing up even when your emotional reserves are thin.',
      reframe: {
        shame: 'This does not read as weakness.',
        clarity: 'It reads as the exhaustion of being capable in places where you still deserve care.',
      },
    },
    dailyAngles: [],
  },
  {
    key: 'meaning_maker',
    title: 'The Pattern Beneath the Pain',
    category: 'values',
    requiredSignals: [SIGNALS.MEANING_MAKING.key],
    supportingSignals: [SIGNALS.DEEP_PROCESSING.key, SIGNALS.TRANSFORMATION.key],
    minConfidence: 0.6,
    minEvidenceCount: 3,
    lookbackDays: 90,
    copyFrame: {
      observation: 'The recurring shape here is that you rarely leave pain as only pain.',
      pattern: 'Across recent entries, difficult experiences often become questions about meaning, growth, truth, and what can be carried forward.',
      reframe: {
        shame: 'This does not read as forcing positivity.',
        clarity: 'It reads as your refusal to let hard things have the final word.',
      },
    },
    dailyAngles: [
      {
        key: 'meaning_from_daily_questions',
        triggerSignals: [SIGNALS.MEANING_MAKING.key, SIGNALS.TRANSFORMATION.key],
        title: 'Meaning Is Starting to Repeat',
        shameFrame: 'This does not read as needing an answer immediately.',
        clarityFrame: 'It reads as your daily questions and lived entries circling the same truth from different angles.',
        prompt: 'What meaning keeps returning even when the details change?',
      },
    ],
  },
  {
    key: 'rest_resistance',
    title: 'Your Relationship with Rest',
    category: 'rest',
    requiredSignals: [SIGNALS.REST_RESISTANCE.key],
    supportingSignals: [
      SIGNALS.LOW_ENERGY.key,
      SIGNALS.OVEREXTENSION.key,
      SIGNALS.HIGH_RESPONSIBILITY.key,
      SIGNALS.SLEEP_DEBT.key,
      SIGNALS.BODY_KNOWS_FIRST.key,
      SIGNALS.GUILT_AROUND_STOPPING.key,
    ],
    minConfidence: 0.72,
    minEvidenceCount: 4,
    lookbackDays: 30,
    copyFrame: {
      observation: 'A repeated signal shows exhaustion becoming the moment you finally allow yourself to pause.',
      pattern: 'Across recent entries, there is a pattern of moving quickly until your body forces a full stop.',
      reframe: {
        shame: 'This does not read as a lack of self-care.',
        clarity: 'It reads as resilience that has not yet learned it is safe to put the armor down.',
      },
    },
    dailyAngles: [
      {
        key: 'rest_before_depletion',
        triggerSignals: [SIGNALS.LOW_ENERGY.key],
        title: 'Rest Before the Full Stop',
        shameFrame: 'This does not read as laziness.',
        clarityFrame: 'It reads as your system asking for care before depletion becomes the only reason you stop.',
        prompt: 'What would help before you hit empty?',
      },
      {
        key: 'guilt_around_stopping',
        triggerSignals: [SIGNALS.GUILT_AROUND_STOPPING.key],
        title: 'The Guilt Around Stopping',
        shameFrame: 'This does not read as weakness.',
        clarityFrame: 'It reads as a body trying to rest inside a mind that learned to keep proving its usefulness.',
        prompt: 'What would change if rest did not need to be justified first?',
      },
      {
        key: 'quiet_as_repair',
        triggerSignals: [SIGNALS.QUIET_AS_REPAIR.key],
        title: 'When Quiet Actually Helped',
        shameFrame: 'This does not read as doing nothing.',
        clarityFrame: 'It reads as repair beginning in a small enough form to feel safe.',
        prompt: 'What kind of support would feel easiest to receive today?',
      },
    ],
  },
  {
    key: 'emotionally_precise_communicator',
    title: 'The Need for Exact Words',
    category: 'selfTrust',
    requiredSignals: [SIGNALS.NEED_FOR_EXACT_WORDS.key],
    supportingSignals: [SIGNALS.DEEP_PROCESSING.key, SIGNALS.MEANING_MAKING.key],
    minConfidence: 0.7,
    minEvidenceCount: 4,
    lookbackDays: 60,
    copyFrame: {
      observation: 'What keeps showing up is that vague language rarely feels like enough.',
      pattern: 'Across recent entries, you seem to search for the sentence that finally lands: not too soft, not too harsh, not too exposed, not too small.',
      reframe: {
        shame: 'This does not read as perfectionism alone.',
        clarity: 'It reads as a need to be emotionally accurate after too many experiences were flattened or misunderstood.',
      },
    },
    dailyAngles: [],
  },
  {
    key: 'relational_scanner',
    title: 'How You Measure Safety',
    category: 'relationships',
    requiredSignals: [SIGNALS.MUTUALITY_NEED.key],
    supportingSignals: [SIGNALS.REASSURANCE_NEED.key, SIGNALS.SUPPORT_NEED.key],
    minConfidence: 0.7,
    minEvidenceCount: 5,
    lookbackDays: 90,
    copyFrame: {
      observation: 'A clear thread is that safety is something you read through patterns, not promises.',
      pattern: 'Across recent relational entries, you seem to notice consistency, tone, follow-through, repair, and whether care remains steady when you have needs.',
      reframe: {
        shame: 'This does not read as suspicion.',
        clarity: 'It reads as discernment formed around the need for care to be real, not just spoken.',
      },
    },
    dailyAngles: [
      {
        key: 'attachment_pattern_active',
        triggerSignals: [SIGNALS.MUTUALITY_NEED.key, SIGNALS.REASSURANCE_NEED.key],
        title: 'Attachment Data Is Active Today',
        shameFrame: 'This does not read as being too much.',
        clarityFrame: 'It reads as your system checking whether connection is steady enough to relax into.',
        prompt: 'What did your relationship data ask for today: reassurance, space, repair, or reciprocity?',
      },
    ],
  },
  {
    key: 'support_scarcity',
    title: 'Your Relationship with Being Caught',
    category: 'support',
    requiredSignals: [SIGNALS.SUPPORT_SCARCITY.key],
    supportingSignals: [
      SIGNALS.SUPPORT_NEED.key,
      SIGNALS.SELF_BLAME.key,
      SIGNALS.LONELINESS.key,
      SIGNALS.SMALL_CIRCLE.key,
      SIGNALS.FEAR_OF_BURDENING.key,
    ],
    minConfidence: 0.7,
    minEvidenceCount: 4,
    lookbackDays: 30,
    copyFrame: {
      observation: 'The pattern around support is not just about what you want. It is something your system keeps looking for.',
      pattern: 'Across recent entries, the same emotional shape appears around needing backup, feeling grateful for the people you do have, and still aching for a wider safety net.',
      reframe: {
        shame: 'This does not read as greed.',
        clarity: 'It reads as grief for the kind of care that arrives before you have to prove how much you need it.',
      },
    },
    dailyAngles: [
      {
        key: 'support_without_proving',
        triggerSignals: [SIGNALS.SUPPORT_NEED.key, SIGNALS.SELF_BLAME.key],
        title: 'Support Without Proving the Fall',
        shameFrame: 'This does not read as neediness.',
        clarityFrame: 'It reads as a need for care that arrives before crisis.',
        prompt: 'What kind of support would feel easiest to receive today?',
      },
      {
        key: 'gratitude_and_grief',
        triggerSignals: [SIGNALS.GRATITUDE.key, SIGNALS.ENVY.key],
        title: 'Gratitude and Grief Can Coexist',
        shameFrame: 'This does not read as greed.',
        clarityFrame: 'It reads as grief for support that has felt too scarce.',
        prompt: 'What kind of support would feel easiest to receive today?',
      },
    ],
  },
  {
    key: 'justice_advocate',
    title: 'The Value Beneath Your Anger',
    category: 'values',
    requiredSignals: [SIGNALS.INJUSTICE_SENSITIVITY.key],
    supportingSignals: [SIGNALS.MEANING_MAKING.key, SIGNALS.BOUNDARY_GROWTH.key],
    minConfidence: 0.7,
    minEvidenceCount: 3,
    lookbackDays: 90,
    copyFrame: {
      observation: 'One recurring signal is that anger often rises when something violates a core value.',
      pattern: 'Across recent entries, your strongest emotional charge appears near unfairness, dismissal, harm, or people not being protected.',
      reframe: {
        shame: 'This does not read as being reactive.',
        clarity: 'It reads as your ethics becoming impossible to silence.',
      },
    },
    dailyAngles: [],
  },
  {
    key: 'calm_bracer',
    title: 'How You Hold Stillness',
    category: 'rest',
    requiredSignals: [SIGNALS.CALM_BRACING.key],
    supportingSignals: [SIGNALS.STOMACH_UNEASE.key, SIGNALS.JAW_TENSION.key],
    minConfidence: 0.65,
    minEvidenceCount: 3,
    lookbackDays: 30,
    copyFrame: {
      observation: 'Your archive shows a complex relationship with calm.',
      pattern: 'When things become easier, quieter, or more stable, there may still be a quiet bracing for the next interruption.',
      reframe: {
        shame: 'This does not read as pessimism.',
        clarity: 'It reads as protection learning how to recognize safety without scanning for danger.',
      },
    },
    dailyAngles: [
      {
        key: 'body_bracing_today',
        triggerSignals: [SIGNALS.CALM_BRACING.key, SIGNALS.STOMACH_UNEASE.key, SIGNALS.JAW_TENSION.key],
        title: 'The Body Is Bracing Before the Story Is Clear',
        shameFrame: 'This does not read as irrational.',
        clarityFrame: 'It reads as body data arriving before the mind has found words for it.',
        prompt: 'What would your body need before your mind tries to explain the feeling?',
      },
    ],
  },
  {
    key: 'dream_processor',
    title: 'When Dreams Continue the Conversation',
    category: 'dreams',
    requiredSignals: [SIGNALS.DREAM_UNFINISHED_PROCESSING.key],
    supportingSignals: [SIGNALS.LOW_CAPACITY.key, SIGNALS.DEEP_PROCESSING.key],
    minConfidence: 0.6,
    minEvidenceCount: 3,
    lookbackDays: 14,
    copyFrame: {
      observation: 'The dream pattern points to dreams picking up what the day could not finish.',
      pattern: 'Across recent entries, dream activity appears near emotional pressure, unresolved questions, or lower-capacity weeks.',
      reframe: {
        shame: 'This does not read as random.',
        clarity: 'It reads as your inner world trying another language.',
      },
    },
    dailyAngles: [
      {
        key: 'dream_journal_thread',
        triggerSignals: [SIGNALS.DREAM_UNFINISHED_PROCESSING.key],
        title: 'The Dream Journal Is Continuing the Thread',
        shameFrame: 'This does not read as noise.',
        clarityFrame: 'It reads as your dream life carrying material the day did not have room to finish.',
        prompt: 'What theme from the dream also appears in a check-in, question answer, body map, or journal entry?',
      },
    ],
  },
];
