/**
 * Daily Reflection Question Banks
 *
 * 365 unique questions per category (values, archetypes, cognitive).
 * Each day the user answers 2–3 questions from each category.
 * Over 12 months the system builds a deep psychological profile.
 *
 * Questions are indexed 0–364 and rotated deterministically by day-of-year.
 */

export type ReflectionCategory = 'values' | 'archetypes' | 'cognitive';

export interface ReflectionQuestion {
  id: number;
  text: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// CORE VALUES — 365 questions
// Themes: purpose, priorities, authenticity, boundaries, relationships,
//         growth, resilience, legacy, creativity, community, freedom,
//         security, justice, compassion, courage, spirituality
// ─────────────────────────────────────────────────────────────────────────────

export const VALUES_QUESTIONS: ReflectionQuestion[] = [
  // Purpose & meaning (1–30)
  { id: 0, text: 'What felt most meaningful about your day today?' },
  { id: 1, text: 'If you could only accomplish one thing this week, what would matter most?' },
  { id: 2, text: 'When did you last feel completely aligned with your purpose?' },
  { id: 3, text: 'What would you do differently if nobody was watching?' },
  { id: 4, text: 'What gives your life a sense of direction right now?' },
  { id: 5, text: 'Describe a moment recently when you felt fully alive.' },
  { id: 6, text: 'What problem in the world do you most wish you could solve?' },
  { id: 7, text: 'When do you feel most like yourself?' },
  { id: 8, text: 'What would you keep doing even if you were never paid for it?' },
  { id: 9, text: 'What legacy do you want to leave in the lives you touch?' },
  { id: 10, text: 'What does a "well-lived day" look like to you?' },
  { id: 11, text: 'If you had one year left, what would you prioritise?' },
  { id: 12, text: 'What work feels like play to you?' },
  { id: 13, text: 'What conversation have you been avoiding that matters deeply?' },
  { id: 14, text: 'What is the most important question you are living with right now?' },
  { id: 15, text: 'When do you feel most proud of who you are?' },
  { id: 16, text: 'Describe an experience that fundamentally changed what you value.' },
  { id: 17, text: 'What do you want to be remembered for?' },
  { id: 18, text: 'What recurring dream or desire keeps calling you?' },
  { id: 19, text: 'If you could write a message to the world, what would it say?' },
  { id: 20, text: 'What are you most grateful for that money cannot buy?' },
  { id: 21, text: 'What does integrity mean to you in daily practice?' },
  { id: 22, text: 'When did you last sacrifice something important for something more important?' },
  { id: 23, text: 'What gives you the deepest sense of satisfaction?' },
  { id: 24, text: 'What causes you to lose track of time in the best way?' },
  { id: 25, text: 'What truth about yourself are you still learning to accept?' },
  { id: 26, text: 'What would you regret not doing if your life ended tomorrow?' },
  { id: 27, text: 'Name one value you wish you honoured more consistently.' },
  { id: 28, text: 'What does success truly mean to you, not to the world?' },
  { id: 29, text: 'Describe a time you chose purpose over comfort.' },

  // Priorities & trade-offs (30–59)
  { id: 30, text: 'What did you say yes to recently that should have been a no?' },
  { id: 31, text: 'If you could only keep three commitments, which would they be?' },
  { id: 32, text: 'When did you last choose growth over safety?' },
  { id: 33, text: 'What are you tolerating in your life that conflicts with your values?' },
  { id: 34, text: 'How do you decide between two things that both matter?' },
  { id: 35, text: 'What is the hardest trade-off you have had to make recently?' },
  { id: 36, text: 'What would you give up to have more peace?' },
  { id: 37, text: 'When was the last time you chose rest over productivity?' },
  { id: 38, text: 'Is there anything you are over-investing in at the expense of something else?' },
  { id: 39, text: 'What obligation do you carry that no longer serves you?' },
  { id: 40, text: 'How do you balance ambition with contentment?' },
  { id: 41, text: 'What would your ideal morning look like if nothing was required of you?' },
  { id: 42, text: 'What habit would you start if time were unlimited?' },
  { id: 43, text: 'If you could delegate one thing from your life permanently, what would it be?' },
  { id: 44, text: 'What are you spending time on that does not align with who you want to be?' },
  { id: 45, text: 'How do you know when something deserves your energy?' },
  { id: 46, text: 'What would you do more of if you stopped worrying about judgment?' },
  { id: 47, text: 'What is the biggest sacrifice you have made for someone you love?' },
  { id: 48, text: "What would change if you took your own needs as seriously as others' needs?" },
  { id: 49, text: 'How do you handle competing priorities between family and career?' },
  { id: 50, text: 'What would your life look like if you followed your values perfectly for one month?' },
  { id: 51, text: 'What do you wish you had the courage to quit?' },
  { id: 52, text: 'When did you last feel torn between loyalty and honesty?' },
  { id: 53, text: 'What matters to you that you rarely talk about?' },
  { id: 54, text: 'How do you distinguish between wants and needs?' },
  { id: 55, text: 'What is one thing you refuse to compromise on?' },
  { id: 56, text: 'When was the last time you chose long-term over short-term gratification?' },
  { id: 57, text: 'Do you value freedom or stability more right now, and why?' },
  { id: 58, text: 'What would you protect at all costs?' },
  { id: 59, text: 'When you feel conflicted, which value wins most often?' },

  // Authenticity & self-expression (60–89)
  { id: 60, text: 'Where in your life do you feel most authentic?' },
  { id: 61, text: 'What mask do you wear most often, and with whom?' },
  { id: 62, text: 'What opinion do you hold that most people in your life would disagree with?' },
  { id: 63, text: 'When did you last say something hard because it was true?' },
  { id: 64, text: 'What part of yourself do you hide to keep the peace?' },
  { id: 65, text: 'How do you express yourself when you feel safest?' },
  { id: 66, text: 'What would change if you stopped seeking approval?' },
  { id: 67, text: 'Describe a time you surprised yourself with your own honesty.' },
  { id: 68, text: 'What is the difference between who you are and who people expect you to be?' },
  { id: 69, text: 'What do you pretend not to care about?' },
  { id: 70, text: 'When did you last compromise your authenticity, and how did it feel?' },
  { id: 71, text: 'What would your most authentic self do more of?' },
  { id: 72, text: 'How do you feel when someone truly sees you?' },
  { id: 73, text: 'What story about yourself are you ready to let go of?' },
  { id: 74, text: 'What is the bravest way you have expressed who you really are?' },
  { id: 75, text: 'What emotion are you least comfortable showing publicly?' },
  { id: 76, text: 'Who in your life loves the real you, no performance needed?' },
  { id: 77, text: 'What part of your identity has shifted the most in the last year?' },
  { id: 78, text: 'What would you say if you were 100% honest about how you feel right now?' },
  { id: 79, text: 'What do you admire in others that you suppress in yourself?' },
  { id: 80, text: 'When do you feel most free to be imperfect?' },
  { id: 81, text: 'What version of yourself do you project on social media vs. real life?' },
  { id: 82, text: 'What would people be surprised to learn about you?' },
  { id: 83, text: 'How do you respond when someone challenges your beliefs?' },
  { id: 84, text: 'What part of growing up did you have to unlearn to find yourself?' },
  { id: 85, text: 'What is one thing you wish you could tell your younger self?' },
  { id: 86, text: 'When did you last feel misunderstood, and what was the core need beneath it?' },
  { id: 87, text: 'What do you value more: being liked or being respected?' },
  { id: 88, text: 'Describe a way you have grown that nobody noticed.' },
  { id: 89, text: 'What does your truest self need right now?' },

  // Relationships & connection (90–119)
  { id: 90, text: 'What quality do you most value in a close relationship?' },
  { id: 91, text: 'How do you show love in ways words cannot capture?' },
  { id: 92, text: 'What does healthy closeness feel like to you?' },
  { id: 93, text: 'When did someone\'s kindness change everything for you?' },
  { id: 94, text: 'What do you need from others to feel emotionally safe?' },
  { id: 95, text: 'How do you repair trust when it breaks?' },
  { id: 96, text: 'What pattern do you notice in the people you are drawn to?' },
  { id: 97, text: 'What is the most important lesson a relationship has taught you?' },
  { id: 98, text: 'How do you balance giving and receiving in your relationships?' },
  { id: 99, text: 'What does loyalty mean to you, and where does it have limits?' },
  { id: 100, text: 'Describe a relationship that helped you become who you are.' },
  { id: 101, text: 'What do you struggle to forgive, and what does that reveal about your values?' },
  { id: 102, text: 'How do you know when a relationship is nourishing vs. draining?' },
  { id: 103, text: 'What do you wish someone understood about how you love?' },
  { id: 104, text: 'When do you feel most connected to another person?' },
  { id: 105, text: 'How do you hold space for someone whose values differ from yours?' },
  { id: 106, text: 'What role do you tend to play in group settings?' },
  { id: 107, text: 'What is the hardest boundary you have set, and would you set it again?' },
  { id: 108, text: 'How do you handle disagreements with someone you deeply care about?' },
  { id: 109, text: 'What does community mean to you?' },
  { id: 110, text: 'When do you feel most generous, and what drives that impulse?' },
  { id: 111, text: 'What is one thing you wish people asked you about yourself?' },
  { id: 112, text: 'How do you decide who to let close and who to keep at a distance?' },
  { id: 113, text: 'What emotional inheritance did you receive from your family?' },
  { id: 114, text: 'How do you celebrate the people you love?' },
  { id: 115, text: 'What relationship dynamic triggers you the most?' },
  { id: 116, text: 'What would your ideal friendship look like?' },
  { id: 117, text: 'How do you handle someone who needs you more than you can give?' },
  { id: 118, text: 'When was the last time you felt truly heard?' },
  { id: 119, text: 'What is more important to you: harmony or honesty?' },

  // Growth & resilience (120–149)
  { id: 120, text: 'What is your current growing edge — the thing you are working on?' },
  { id: 121, text: 'How do you respond when life does not go as planned?' },
  { id: 122, text: 'What failure taught you the most valuable lesson?' },
  { id: 123, text: 'What is one belief you held five years ago that you no longer believe?' },
  { id: 124, text: 'How do you stay grounded during uncertainty?' },
  { id: 125, text: 'What is the hardest thing you have overcome?' },
  { id: 126, text: 'What does resilience mean to you personally?' },
  { id: 127, text: 'When did you last grow because of discomfort rather than in spite of it?' },
  { id: 128, text: 'What inner dialogue helps you when things are hard?' },
  { id: 129, text: 'Describe a setback that redirected you somewhere better.' },
  { id: 130, text: 'What skill or quality are you actively developing right now?' },
  { id: 131, text: 'How do you know the difference between giving up and letting go?' },
  { id: 132, text: 'What does patience look like in your life right now?' },
  { id: 133, text: 'How do you rebuild after something falls apart?' },
  { id: 134, text: 'What pattern of thought you have outgrown are you still carrying?' },
  { id: 135, text: 'When you are overwhelmed, what is the first thing you reach for?' },
  { id: 136, text: 'What does it take for you to ask for help?' },
  { id: 137, text: 'How do you process grief or loss?' },
  { id: 138, text: 'What are you willing to be a beginner at right now?' },
  { id: 139, text: 'How do you distinguish between a challenge worth pushing through and one to walk away from?' },
  { id: 140, text: 'What fear have you overcome that once seemed impossible?' },
  { id: 141, text: 'What strength do you have that emerged from pain?' },
  { id: 142, text: 'How do you celebrate your own progress?' },
  { id: 143, text: 'What does self-compassion look like when you fail?' },
  { id: 144, text: 'What habit are you trying to build and why does it matter to you?' },
  { id: 145, text: 'How do you stay motivated when progress feels invisible?' },
  { id: 146, text: 'What is the most courageous choice you made this year?' },
  { id: 147, text: 'What are you still healing from, and how is it shaping you?' },
  { id: 148, text: 'When did you last choose vulnerability over protection?' },
  { id: 149, text: 'What does your relationship with change say about you?' },

  // Boundaries & energy (150–179)
  { id: 150, text: 'Describe a boundary you set that changed a relationship for the better.' },
  { id: 151, text: 'How do you know when your boundaries are being tested?' },
  { id: 152, text: 'What drains your energy the fastest?' },
  { id: 153, text: 'What recharges you when nothing else works?' },
  { id: 154, text: 'How do you say no without guilt?' },
  { id: 155, text: 'When did you last override your own limits, and what happened?' },
  { id: 156, text: 'What emotional labour do you carry that is invisible to others?' },
  { id: 157, text: 'How do you protect your peace without becoming distant?' },
  { id: 158, text: 'What does burnout look like for you, and what are the early signs?' },
  { id: 159, text: 'How do you balance generosity with self-preservation?' },
  { id: 160, text: 'What would change if you guarded your time as fiercely as you guard others feelings?' },
  { id: 161, text: 'Where in your life do you need stronger boundaries right now?' },
  { id: 162, text: 'What people-pleasing habit costs you the most?' },
  { id: 163, text: 'How do you handle someone who repeatedly crosses your boundaries?' },
  { id: 164, text: 'What does healthy solitude feel like vs. unhealthy isolation?' },
  { id: 165, text: 'Describe a time you chose yourself and it felt right.' },
  { id: 166, text: 'What obligation do you need to release?' },
  { id: 167, text: "How do you distinguish between your responsibility and someone else's?" },
  { id: 168, text: 'What is one thing you do purely for your own wellbeing?' },
  { id: 169, text: 'When do you feel most drained by social interaction?' },
  { id: 170, text: 'How does your body signal when a boundary has been crossed?' },
  { id: 171, text: 'What is the kindest thing you do for yourself regularly?' },
  { id: 172, text: 'How do you decide what deserves your emotional energy?' },
  { id: 173, text: 'What does rest mean to you beyond sleep?' },
  { id: 174, text: 'When was the last time you prioritised restoration over obligation?' },
  { id: 175, text: 'What do you need permission to stop doing?' },
  { id: 176, text: 'How do you communicate your limits to someone who matters to you?' },
  { id: 177, text: 'What energises you in ways that surprise you?' },
  { id: 178, text: 'What situation regularly depletes you that you haven\'t addressed?' },
  { id: 179, text: 'How would your life change if you fully honoured your own boundaries?' },

  // Creativity & expression (180–209)
  { id: 180, text: 'How do you express your inner life — through words, art, movement, or something else?' },
  { id: 181, text: 'What creative urge have you been neglecting?' },
  { id: 182, text: 'When do you feel most creatively alive?' },
  { id: 183, text: 'What would you create if you knew it didn\'t have to be good?' },
  { id: 184, text: 'How does beauty influence your daily experience?' },
  { id: 185, text: 'What music, art, or book has shaped who you are?' },
  { id: 186, text: 'When did you last make something just for the joy of it?' },
  { id: 187, text: 'How do you process emotions through creation?' },
  { id: 188, text: 'What creative dream have you set aside that still whispers to you?' },
  { id: 189, text: 'How does your environment affect your creative energy?' },
  { id: 190, text: 'What does playfulness look like in your adult life?' },
  { id: 191, text: 'What is the most creative solution you have found to a life problem?' },
  { id: 192, text: 'How do you balance structure with spontaneity?' },
  { id: 193, text: 'What childhood creative activity do you wish you still did?' },
  { id: 194, text: 'When you daydream, where does your mind go?' },
  { id: 195, text: 'What is the role of imagination in your daily life?' },
  { id: 196, text: 'How do you nurture inspiration when it fades?' },
  { id: 197, text: 'What does your creative side need that it is not getting?' },
  { id: 198, text: 'How do you handle creative blocks or stagnation?' },
  { id: 199, text: 'What would you write, build, or design if you had infinite time?' },
  { id: 200, text: 'How does creating something make you feel about yourself?' },
  { id: 201, text: 'What form of expression feels most natural to you?' },
  { id: 202, text: 'How has your creative life changed as you have grown older?' },
  { id: 203, text: 'What emotion is easiest to express creatively?' },
  { id: 204, text: 'What emotion is hardest to express creatively?' },
  { id: 205, text: 'If your inner world were a landscape, what would it look like today?' },
  { id: 206, text: 'What does curiosity feel like in your body?' },
  { id: 207, text: 'When do you feel most intellectually stimulated?' },
  { id: 208, text: 'How do you share your creative gifts with others?' },
  { id: 209, text: 'What story are you telling yourself about your own creativity?' },

  // Justice & ethics (210–239)
  { id: 210, text: 'What injustice moves you to action the most?' },
  { id: 211, text: 'How do you navigate moral grey areas?' },
  { id: 212, text: 'When did you last stand up for something even when it was costly?' },
  { id: 213, text: 'What does fairness look like in your relationships?' },
  { id: 214, text: 'How do you handle situations where your ethics conflict with social expectations?' },
  { id: 215, text: 'What principle would you defend even if you stood alone?' },
  { id: 216, text: 'How do you reconcile compassion with accountability?' },
  { id: 217, text: 'What is the difference between mercy and enabling, in your experience?' },
  { id: 218, text: 'How do privilege and responsibility relate in your life?' },
  { id: 219, text: 'What ethical standard do you hold yourself to that you don\'t apply to others?' },
  { id: 220, text: 'When was the last time you changed your mind on a moral issue?' },
  { id: 221, text: 'How do you respond when someone you respect does something wrong?' },
  { id: 222, text: 'What is one area where your actions don\'t fully match your stated values?' },
  { id: 223, text: 'How do you decide when to speak up vs. stay quiet?' },
  { id: 224, text: 'What role does empathy play in your moral reasoning?' },
  { id: 225, text: 'How do you handle moral fatigue in a world with endless need?' },
  { id: 226, text: 'What small act of justice can you practise daily?' },
  { id: 227, text: 'How do you forgive someone who is not sorry?' },
  { id: 228, text: 'What does accountability look like when you are the one who made a mistake?' },
  { id: 229, text: 'What ethical lesson did you learn from experience rather than instruction?' },
  { id: 230, text: 'How do you teach values without imposing them?' },
  { id: 231, text: 'When was the last time you were tested ethically and how did you respond?' },
  { id: 232, text: 'What does responsibility mean to you beyond obligation?' },
  { id: 233, text: 'How do you hold space for someone whose actions you disagree with?' },
  { id: 234, text: 'What would you want done if you were the harmed party in a conflict?' },
  { id: 235, text: 'How do you decide what causes deserve your energy?' },
  { id: 236, text: 'What does honour mean in your personal code?' },
  { id: 237, text: 'How do you model values you want to see in the world?' },
  { id: 238, text: 'What is more important: intention or impact?' },
  { id: 239, text: 'How do you handle guilt when you fall short of your own standards?' },

  // Freedom & independence (240–269)
  { id: 240, text: 'What does freedom mean to you right now?' },
  { id: 241, text: 'What are you free from that you once weren\'t?' },
  { id: 242, text: 'Where do you feel most confined, and by what?' },
  { id: 243, text: 'How do you balance independence with interdependence?' },
  { id: 244, text: 'What rules do you follow by choice vs. out of habit?' },
  { id: 245, text: 'When did you last break a self-imposed rule and how did it feel?' },
  { id: 246, text: 'What does autonomy look like in your daily decisions?' },
  { id: 247, text: 'How do you create space for spontaneity in a structured life?' },
  { id: 248, text: 'What would you do if you felt completely free from expectations?' },
  { id: 249, text: 'How do you protect your inner freedom when external conditions are restrictive?' },
  { id: 250, text: 'What kind of freedom do you value more — freedom from, or freedom to?' },
  { id: 251, text: 'How do you handle feeling trapped in a situation you chose?' },
  { id: 252, text: 'What does liberation look like in your emotional life?' },
  { id: 253, text: 'When do you feel most free in your body?' },
  { id: 254, text: 'What expectation of others would you shed if you could?' },
  { id: 255, text: 'How do you balance personal freedom with responsibility to people you love?' },
  { id: 256, text: 'What scares you about total freedom?' },
  { id: 257, text: 'What does sovereignty over your own life look like in practice?' },
  { id: 258, text: 'When have you chosen constraint that ultimately felt freeing?' },
  { id: 259, text: 'How does your need for freedom show up in your relationships?' },
  { id: 260, text: 'What tradition gives you comfort vs. what tradition feels confining?' },
  { id: 261, text: 'How do you make decisions that are truly your own?' },
  { id: 262, text: 'What does it mean to be free and responsible at the same time?' },
  { id: 263, text: 'Where in your life do you over-control, and what are you afraid of?' },
  { id: 264, text: 'How do you find freedom within routine?' },
  { id: 265, text: 'What attachment is holding you back from feeling free?' },
  { id: 266, text: 'How do you express individuality without alienating those close to you?' },
  { id: 267, text: 'What would your most liberated self look like in five years?' },
  { id: 268, text: 'What choice made you feel most powerfully free?' },
  { id: 269, text: 'How do you reclaim yourself after giving too much away?' },

  // Security & stability (270–299)
  { id: 270, text: 'What makes you feel safe in an uncertain world?' },
  { id: 271, text: 'How do you build stability without becoming rigid?' },
  { id: 272, text: 'What is your relationship with financial security?' },
  { id: 273, text: 'When uncertainty rises, what is the first thing you protect?' },
  { id: 274, text: 'How do you find comfort without becoming complacent?' },
  { id: 275, text: 'What does emotional security look like in your closest relationship?' },
  { id: 276, text: 'What habit or ritual gives you a sense of grounding?' },
  { id: 277, text: 'How do you handle the tension between wanting security and wanting adventure?' },
  { id: 278, text: 'What childhood experience shaped your need for safety?' },
  { id: 279, text: 'When did you last feel truly at home somewhere?' },
  { id: 280, text: 'What is your relationship with risk, and has it changed over time?' },
  { id: 281, text: 'How do you provide stability for others while managing your own needs?' },
  { id: 282, text: 'What does it take for you to feel secure enough to be vulnerable?' },
  { id: 283, text: 'How do you prepare for the unknown without living in anxiety?' },
  { id: 284, text: 'What area of life feels most stable right now, and why?' },
  { id: 285, text: 'What area of life feels most unstable, and what would improve it?' },
  { id: 286, text: 'How do you build inner stability that is not dependent on circumstances?' },
  { id: 287, text: 'What does trust look like in its early stages for you?' },
  { id: 288, text: 'How do you handle sudden change that threatens your sense of stability?' },
  { id: 289, text: 'What possession, place, or person represents home to you?' },
  { id: 290, text: 'When did instability teach you something valuable about yourself?' },
  { id: 291, text: 'How do you balance planning with surrendering to what you cannot control?' },
  { id: 292, text: 'What does a safe space look like for you emotionally?' },
  { id: 293, text: 'What do you hoard — things, people, certainty — and what drives that?' },
  { id: 294, text: 'How do you react when your sense of control is taken away?' },
  { id: 295, text: 'What roots do you want to grow deeper?' },
  { id: 296, text: 'How do you soothe yourself in moments of deep uncertainty?' },
  { id: 297, text: 'What makes you feel grounded when everything is shifting?' },
  { id: 298, text: 'How does your body signal when you feel safe vs. when you feel threatened?' },
  { id: 299, text: 'What is the most stabilising belief you hold?' },

  // Compassion & care (300–329)
  { id: 300, text: 'How do you show yourself compassion after a difficult day?' },
  { id: 301, text: 'Who do you find it hardest to be compassionate toward, and why?' },
  { id: 302, text: 'When did someone\'s compassion change the course of your day?' },
  { id: 303, text: 'How do you balance self-care with caring for others?' },
  { id: 304, text: 'What is the difference between sympathy and empathy in your experience?' },
  { id: 305, text: 'How do you respond when you can not fix someone\'s pain?' },
  { id: 306, text: 'What does kindness cost you, and is it worth it?' },
  { id: 307, text: 'How do you offer compassion without absorbing someone else\'s suffering?' },
  { id: 308, text: 'When do you struggle to be gentle with yourself?' },
  { id: 309, text: 'What does unconditional acceptance feel like?' },
  { id: 310, text: 'How do you remain caring when you are exhausted?' },
  { id: 311, text: 'What wounded part of you needs the most tenderness right now?' },
  { id: 312, text: 'How do you practise compassion for someone who has hurt you?' },
  { id: 313, text: 'What does nurturing look like when you turn it inward?' },
  { id: 314, text: 'When was the last time you were moved to tears by someone else\'s experience?' },
  { id: 315, text: 'How do you hold hope for someone who has lost theirs?' },
  { id: 316, text: 'What act of care are you most proud of giving?' },
  { id: 317, text: 'How do you stay compassionate without becoming a martyr?' },
  { id: 318, text: 'What does your inner critic need to hear from your inner nurturer?' },
  { id: 319, text: 'How do you handle compassion fatigue?' },
  { id: 320, text: 'What has taught you the most about empathy?' },
  { id: 321, text: 'How do you want to be cared for when you are at your lowest?' },
  { id: 322, text: 'What small form of compassion could you practise today?' },
  { id: 323, text: 'How do you balance honesty and kindness when they conflict?' },
  { id: 324, text: 'What does self-forgiveness look like for you, and what blocks it?' },
  { id: 325, text: 'Who taught you the most about how to care for others?' },
  { id: 326, text: 'How do you express love to someone whose love language differs from yours?' },
  { id: 327, text: 'What does gentle strength look like in your life?' },
  { id: 328, text: 'When has your compassion been taken for granted, and how did you respond?' },
  { id: 329, text: 'How do you replenish your capacity for care?' },

  // Legacy & depth (330–364)
  { id: 330, text: 'What do you want your grandchildren to know about you?' },
  { id: 331, text: 'How do you want to be spoken about when you are not in the room?' },
  { id: 332, text: 'What impact do you hope to leave on your community?' },
  { id: 333, text: 'What values do you want to pass on?' },
  { id: 334, text: 'How has your understanding of love evolved?' },
  { id: 335, text: 'What is the most important thing you have learned about life so far?' },
  { id: 336, text: 'What unfinished emotional business would you like to resolve?' },
  { id: 337, text: 'If you could plant one idea in every mind, what would it be?' },
  { id: 338, text: 'How do you want your presence to feel to others?' },
  { id: 339, text: 'What is the deepest need beneath your strongest emotion right now?' },
  { id: 340, text: 'How has your definition of happiness changed?' },
  { id: 341, text: 'What is one truth you discovered late but are glad you found?' },
  { id: 342, text: 'How do you reconcile the person you are with the person you want to be?' },
  { id: 343, text: 'What are you building that will outlast you?' },
  { id: 344, text: 'What does your spirit need that your life is not currently providing?' },
  { id: 345, text: 'How do you honour the people who shaped you?' },
  { id: 346, text: 'What does ageing teach you about values?' },
  { id: 347, text: 'What conversation would you love to have with a wise mentor?' },
  { id: 348, text: 'How do you make meaning from suffering?' },
  { id: 349, text: 'What chapter of your life are you in, and what is its theme?' },
  { id: 350, text: 'What are you most curious about in the world?' },
  { id: 351, text: 'How do you practise wonder in everyday life?' },
  { id: 352, text: 'What lesson keeps returning until you learn it?' },
  { id: 353, text: 'What does spiritual growth mean to you, regardless of religion?' },
  { id: 354, text: 'How do you find sacredness in the ordinary?' },
  { id: 355, text: 'What is the most generous interpretation of your own life story?' },
  { id: 356, text: 'How do you want to grow in the next year?' },
  { id: 357, text: 'What would you write in a letter to your future self?' },
  { id: 358, text: 'How do you remain hopeful in dark times?' },
  { id: 359, text: 'What is one thing you know for certain about yourself?' },
  { id: 360, text: 'How do you maintain depth in a world that rewards surface?' },
  { id: 361, text: 'What does it mean to live with intention?' },
  { id: 362, text: 'What is the most important promise you have kept to yourself?' },
  { id: 363, text: 'How has your relationship with time changed as you have aged?' },
  { id: 364, text: 'What wisdom would you want written on your tombstone?' },
];

// ─────────────────────────────────────────────────────────────────────────────
// ARCHETYPES — 365 questions
// Themes: heroism, caregiving, seeking, wisdom, rebellion, shadow,
//         transformation, identity, masks, power, vulnerability
// ─────────────────────────────────────────────────────────────────────────────

export const ARCHETYPE_QUESTIONS: ReflectionQuestion[] = [
  // Hero patterns (0–29)
  { id: 0, text: 'What challenge are you facing right now that demands courage?' },
  { id: 1, text: 'How do you respond when someone needs rescuing?' },
  { id: 2, text: 'What do you fight for, even when it is hard?' },
  { id: 3, text: 'When was the last time you put yourself at risk for something you believed in?' },
  { id: 4, text: 'How do you handle a situation where no one else steps up?' },
  { id: 5, text: 'What does strength look like when it is quiet and internal?' },
  { id: 6, text: 'How do you deal with the pressure to be strong for others?' },
  { id: 7, text: 'Describe a battle — literal or figurative — that defined you.' },
  { id: 8, text: 'How do you know when to fight and when to walk away?' },
  { id: 9, text: 'What is the hardest thing you have had to face this year?' },
  { id: 10, text: 'How do you recover after giving everything you have?' },
  { id: 11, text: 'What do you do when your strength is not enough?' },
  { id: 12, text: 'Who is the hero you needed but never had?' },
  { id: 13, text: 'How do you balance being protective with being controlling?' },
  { id: 14, text: 'What does bravery look like in your ordinary life?' },
  { id: 15, text: 'When have you been the villain in someone else\'s story without realising?' },
  { id: 16, text: 'What kind of hero do you want to be — flashy or quiet?' },
  { id: 17, text: 'How do you handle being let down by your own hero?' },
  { id: 18, text: 'What quest, figuratively, are you on right now?' },
  { id: 19, text: 'How do you show up in a crisis vs. in everyday life?' },
  { id: 20, text: 'What does sacrifice mean to you, and how far would you go?' },
  { id: 21, text: 'When did you last feel like you had to be the hero and resented it?' },
  { id: 22, text: 'How do you handle the gap between who you are and who others need you to be?' },
  { id: 23, text: 'What weakness do you hide behind strength?' },
  { id: 24, text: 'How do you define honour in your own life?' },
  { id: 25, text: 'What does true courage look like when fear is overwhelming?' },
  { id: 26, text: 'When was the last time you asked for help instead of pushing through alone?' },
  { id: 27, text: 'What responsibility feels noble and what feels like a burden?' },
  { id: 28, text: 'How do you recover your sense of agency after a defeat?' },
  { id: 29, text: 'What would you defend even if you were the only one standing?' },

  // Caregiver patterns (30–59)
  { id: 30, text: 'Who do you take care of, and who takes care of you?' },
  { id: 31, text: 'How do you know when you are giving too much?' },
  { id: 32, text: 'What drives your instinct to nurture — love or obligation?' },
  { id: 33, text: 'How do you respond when your care is not appreciated?' },
  { id: 34, text: 'What part of yourself do you neglect while caring for others?' },
  { id: 35, text: 'Describe a time your caring backfired.' },
  { id: 36, text: 'How do you handle the guilt of saying no to someone in need?' },
  { id: 37, text: 'What does healthy nurturing look like vs. codependency?' },
  { id: 38, text: 'When you are drained, how do you continue to care?' },
  { id: 39, text: 'What role did caregiving play in your childhood?' },
  { id: 40, text: 'How do you receive care from others without deflecting?' },
  { id: 41, text: 'What is the difference between helping and rescuing in your relationships?' },
  { id: 42, text: 'How do you balance emotional generosity with your own needs?' },
  { id: 43, text: 'What does maternal or paternal energy mean to you?' },
  { id: 44, text: 'When did your caring nature become your prison?' },
  { id: 45, text: 'How do you care for someone without trying to fix them?' },
  { id: 46, text: 'What does it mean to be held by someone emotionally?' },
  { id: 47, text: 'How do you respond when people depend on you too much?' },
  { id: 48, text: 'What part of your caring is genuine and what part is performed?' },
  { id: 49, text: 'How do you find the line between empathy and enmeshment?' },
  { id: 50, text: 'What would your life look like if you cared for yourself first?' },
  { id: 51, text: 'How do you handle someone who refuses the help they clearly need?' },
  { id: 52, text: 'What emotional wound makes you a better caregiver?' },
  { id: 53, text: 'How do you nurture without losing yourself?' },
  { id: 54, text: 'When was the last time someone truly took care of you?' },
  { id: 55, text: 'What does it feel like when your care is deeply received?' },
  { id: 56, text: 'How do you celebrate others without diminishing yourself?' },
  { id: 57, text: 'What is the most selfless thing you have done that you never told anyone about?' },
  { id: 58, text: 'How does your need to be needed shape your relationships?' },
  { id: 59, text: 'What would happen if you stopped taking care of everyone for a week?' },

  // Seeker patterns (60–89)
  { id: 60, text: 'What are you searching for in your life right now?' },
  { id: 61, text: 'How do you satisfy a restless spirit without burning bridges?' },
  { id: 62, text: 'What journey, internal or external, has changed you the most?' },
  { id: 63, text: 'When do you feel the strongest pull to wander or explore?' },
  { id: 64, text: 'How do you balance the desire for newness with appreciation for what you have?' },
  { id: 65, text: 'What question drives your life forward?' },
  { id: 66, text: 'How do you know when you have found what you were looking for?' },
  { id: 67, text: 'What are you running from when you are chasing something new?' },
  { id: 68, text: 'How do you handle the loneliness of walking your own path?' },
  { id: 69, text: 'What does homecoming feel like after a long internal journey?' },
  { id: 70, text: 'How do you decide which opportunities to pursue and which to pass on?' },
  { id: 71, text: 'What truth have you discovered through exploration that you could not have found at home?' },
  { id: 72, text: 'How do you stay present when your nature is to always look ahead?' },
  { id: 73, text: 'What is the cost of your seeking nature on your relationships?' },
  { id: 74, text: 'When did settling feel right instead of suffocating?' },
  { id: 75, text: 'How do you distinguish between genuine seeking and avoidance?' },
  { id: 76, text: 'What unknown territory excites you the most right now?' },
  { id: 77, text: 'How do you find meaning in the search itself, not just the destination?' },
  { id: 78, text: 'What have you been seeking that was inside you all along?' },
  { id: 79, text: 'How does your need for freedom affect your ability to commit?' },
  { id: 80, text: 'What would your ideal adventure look like?' },
  { id: 81, text: 'How do you navigate the tension between depth and breadth in life?' },
  { id: 82, text: 'What spiritual or philosophical question do you keep returning to?' },
  { id: 83, text: 'How do you find stillness as someone who always wants more?' },
  { id: 84, text: 'What does fulfilment look like for someone who is always seeking?' },
  { id: 85, text: 'How do you handle the fear that you might never find what you are looking for?' },
  { id: 86, text: 'What experience outside your comfort zone shaped who you are?' },
  { id: 87, text: 'How do you bring the lessons of your seeking back to those you love?' },
  { id: 88, text: 'What horizon are you looking toward right now?' },
  { id: 89, text: 'How do you stay grounded without feeling anchored?' },

  // Sage patterns (90–119)
  { id: 90, text: 'What wisdom have you earned through experience that books could not teach?' },
  { id: 91, text: 'How do you share what you know without being condescending?' },
  { id: 92, text: 'What is the difference between knowledge and wisdom in your experience?' },
  { id: 93, text: 'How do you handle being wrong about something you were certain about?' },
  { id: 94, text: 'What is the most important thing you have learned about human nature?' },
  { id: 95, text: 'How do you balance analysis with intuition?' },
  { id: 96, text: 'When does your need to understand prevent you from simply feeling?' },
  { id: 97, text: 'What truth are you still struggling to accept?' },
  { id: 98, text: 'How do you sit with the discomfort of not knowing?' },
  { id: 99, text: 'What mentor or teacher changed your life, and what did they give you?' },
  { id: 100, text: 'How do you discern truth from comfortable illusion?' },
  { id: 101, text: 'What wisdom would you share with someone going through what you went through?' },
  { id: 102, text: 'How does your analytical mind serve you, and how does it limit you?' },
  { id: 103, text: 'When was the last time you chose not to give advice and just listened?' },
  { id: 104, text: 'What pattern in life have you finally understood after years of living it?' },
  { id: 105, text: 'How do you handle intellectual disagreements without making them personal?' },
  { id: 106, text: 'What idea has changed your worldview the most?' },
  { id: 107, text: 'How do you cultivate discernment in a world of noise?' },
  { id: 108, text: 'What does thinking deeply cost you emotionally?' },
  { id: 109, text: 'How do you use your understanding of people to build trust rather than manipulate?' },
  { id: 110, text: 'What book, talk, or idea are you currently sitting with?' },
  { id: 111, text: 'How do you stay curious when you feel like an expert?' },
  { id: 112, text: 'What is the wisest decision you have made this year?' },
  { id: 113, text: 'How do you balance being a voice of reason with being emotionally present?' },
  { id: 114, text: 'What do you think most people misunderstand about wisdom?' },
  { id: 115, text: 'How do you remain humble in your knowing?' },
  { id: 116, text: 'What is your relationship with doubt?' },
  { id: 117, text: 'How do you teach without taking over?' },
  { id: 118, text: 'What have you been overthinking that needs feeling instead?' },
  { id: 119, text: 'How do you turn insight into action rather than staying in your head?' },

  // Rebel patterns (120–149)
  { id: 120, text: 'What rule have you broken that you are proud of breaking?' },
  { id: 121, text: 'How do you rebel in ways that are constructive rather than destructive?' },
  { id: 122, text: 'What authority do you naturally question?' },
  { id: 123, text: 'When does your contrarian nature help you, and when does it isolate you?' },
  { id: 124, text: 'How do you channel anger into change?' },
  { id: 125, text: 'What system in your life needs disrupting?' },
  { id: 126, text: 'How do you handle being seen as difficult when you are just being honest?' },
  { id: 127, text: 'What is the difference between rebellion and self-destruction?' },
  { id: 128, text: 'When did going against the grain turn out to be the right choice?' },
  { id: 129, text: 'How do you stay connected to community while maintaining your radical independence?' },
  { id: 130, text: 'What would you burn down metaphorically to build something better?' },
  { id: 131, text: 'How do you handle the loneliness of nonconformity?' },
  { id: 132, text: 'What provokes your inner rebel the fastest?' },
  { id: 133, text: 'How do you rebel against your own patterns and habits?' },
  { id: 134, text: 'What do you refuse to accept about the way things are?' },
  { id: 135, text: 'How do you lead a revolution in your own life?' },
  { id: 136, text: 'When was the last time your rebellious streak got you into trouble?' },
  { id: 137, text: 'How do you distinguish between fighting a good fight and picking unnecessary battles?' },
  { id: 138, text: 'What would you change about the world if you had no fear of consequences?' },
  { id: 139, text: 'How do you make peace with structures you cannot change?' },
  { id: 140, text: 'What is your relationship with rules in intimate relationships?' },
  { id: 141, text: 'How do you handle conformity pressure from people you care about?' },
  { id: 142, text: 'What establishment have you challenged that made a real difference?' },
  { id: 143, text: 'How do you balance your need for disruption with others\' need for stability?' },
  { id: 144, text: 'What would a mature version of your rebellious energy look like?' },
  { id: 145, text: 'When is your resistance actually fear in disguise?' },
  { id: 146, text: 'How do you use your voice for change without alienating allies?' },
  { id: 147, text: 'What inner authority do you most need to challenge right now?' },
  { id: 148, text: 'How do you stay true to your disruptive nature while being kind?' },
  { id: 149, text: 'What would it mean to rebel against your own rebel?' },

  // Shadow work (150–179)
  { id: 150, text: 'What trait in others triggers you the most, and why might it reflect something in you?' },
  { id: 151, text: 'What is your most uncomfortable emotion, and how do you usually avoid it?' },
  { id: 152, text: 'What pattern do you keep repeating even though you know better?' },
  { id: 153, text: 'How do you act when no one is watching?' },
  { id: 154, text: 'What do you lie to yourself about?' },
  { id: 155, text: 'What part of yourself do you disown when you are in public?' },
  { id: 156, text: 'How does your shadow show up in your relationships?' },
  { id: 157, text: 'What part of your personality do you judge most harshly?' },
  { id: 158, text: 'What would you discover if you sat with your darkest feeling for five minutes?' },
  { id: 159, text: 'How do you project your own unresolved issues onto others?' },
  { id: 160, text: 'What is the gift hidden inside your greatest flaw?' },
  { id: 161, text: 'When was the last time jealousy showed you something about your desires?' },
  { id: 162, text: 'How do you handle the parts of yourself you do not like?' },
  { id: 163, text: 'What self-sabotaging behaviour keeps returning, and what need does it serve?' },
  { id: 164, text: 'How does your shadow express itself when you are under stress?' },
  { id: 165, text: 'What anger are you suppressing, and what would happen if you expressed it?' },
  { id: 166, text: 'How do you integrate your dark side without acting it out destructively?' },
  { id: 167, text: 'What part of you needs to be seen but is too afraid to be visible?' },
  { id: 168, text: 'How do you use humor to hide something deeper?' },
  { id: 169, text: 'What would your shadow self say if it could speak freely?' },
  { id: 170, text: 'How do you practice accepting all parts of who you are?' },
  { id: 171, text: 'What makes you feel shame, and what does that shame protect?' },
  { id: 172, text: 'How do you react when someone sees a part of you that you try to hide?' },
  { id: 173, text: 'What childhood wound still drives your adult behaviour?' },
  { id: 174, text: 'How does your need for control reveal your deepest fear?' },
  { id: 175, text: 'What would radical self-honesty look like for you today?' },
  { id: 176, text: 'How do you befriend the parts of yourself you were taught to suppress?' },
  { id: 177, text: 'What defence mechanism are you most attached to?' },
  { id: 178, text: 'How do you turn self-awareness into actual change rather than just insight?' },
  { id: 179, text: 'What is the most difficult thing you have had to accept about yourself?' },

  // Transformation & identity (180–209)
  { id: 180, text: 'Who were you five years ago, and how have you changed?' },
  { id: 181, text: 'What identity have you outgrown but not yet released?' },
  { id: 182, text: 'How do you reinvent yourself without losing your core?' },
  { id: 183, text: 'What transformation is happening in you right now?' },
  { id: 184, text: 'How do you hold onto yourself during major life transitions?' },
  { id: 185, text: 'What version of yourself are you becoming?' },
  { id: 186, text: 'How does your past self influence your present choices?' },
  { id: 187, text: 'What do you need to let die in order to grow?' },
  { id: 188, text: 'How do you grieve the person you used to be?' },
  { id: 189, text: 'What emerging part of yourself are you most excited about?' },
  { id: 190, text: 'How do you navigate the disorientation of becoming someone new?' },
  { id: 191, text: 'What chrysalis are you currently inside of?' },
  { id: 192, text: 'How do your roles — parent, partner, professional — compete for dominance?' },
  { id: 193, text: 'What label no longer fits you?' },
  { id: 194, text: 'How do you define yourself when you are between identities?' },
  { id: 195, text: 'What transformation scared you the most but turned out beautifully?' },
  { id: 196, text: 'How do you handle people who knew the old you and do not recognise the new you?' },
  { id: 197, text: 'What is one way you have surprised yourself by changing?' },
  { id: 198, text: 'How do you stay authentic during periods of rapid growth?' },
  { id: 199, text: 'What does evolution look like in your emotional life?' },
  { id: 200, text: 'How do you make peace with the fact that growth means some relationships change?' },
  { id: 201, text: 'What part of your identity feels most under construction right now?' },
  { id: 202, text: 'How do you honour your past while stepping into your future?' },
  { id: 203, text: 'What old story about yourself are you rewriting?' },
  { id: 204, text: 'How does physical change mirror internal transformation for you?' },
  { id: 205, text: 'What are the signs that you are growing even when it does not feel like it?' },
  { id: 206, text: 'How do you recognise when resistance is blocking your transformation?' },
  { id: 207, text: 'What milestone of growth are you approaching?' },
  { id: 208, text: 'How do you handle the vulnerability of being in between who you were and who you are becoming?' },
  { id: 209, text: 'What is the most transformative conversation you have ever had?' },

  // Masks & personas (210–239)
  { id: 210, text: 'What mask do you wear at work that you take off at home?' },
  { id: 211, text: 'How many versions of yourself exist, and which one is the most real?' },
  { id: 212, text: 'What persona do you adopt in social situations?' },
  { id: 213, text: 'When did you realise you were performing instead of being?' },
  { id: 214, text: 'How do you feel when you slip into a persona that is not authentically you?' },
  { id: 215, text: 'What mask did you wear as a child to stay safe?' },
  { id: 216, text: 'How do you slowly reveal your true self to someone new?' },
  { id: 217, text: 'What would happen if you dropped all your masks for a day?' },
  { id: 218, text: 'Which of your personas is the most exhausting to maintain?' },
  { id: 219, text: 'How do you build trust slowly enough to be vulnerable?' },
  { id: 220, text: 'What role do you play in your family that was never officially assigned?' },
  { id: 221, text: 'How do you feel when someone expects you to be the version of yourself they prefer?' },
  { id: 222, text: 'What persona serves a genuine purpose vs. what is just armour?' },
  { id: 223, text: 'How has your public identity diverged from your private one?' },
  { id: 224, text: 'When do masks help you and when do they trap you?' },
  { id: 225, text: 'What character do you play when you are trying to impress someone?' },
  { id: 226, text: 'How do you handle the exhaustion of being "on" all day?' },
  { id: 227, text: 'What is the most honest persona you have — the one closest to your core?' },
  { id: 228, text: 'How do you recalibrate after performing a role for too long?' },
  { id: 229, text: 'What mask are you ready to retire?' },
  { id: 230, text: 'How does your sense of self shift depending on who you are with?' },
  { id: 231, text: 'What part of your personality is a survival strategy from the past?' },
  { id: 232, text: 'How do you know when you are code-switching vs. losing yourself?' },
  { id: 233, text: 'What would your most unguarded self say to your most guarded self?' },
  { id: 234, text: 'How do you adapt socially without feeling fake?' },
  { id: 235, text: 'What persona do you retreat to when you are afraid?' },
  { id: 236, text: 'How do you let people in without feeling exposed?' },
  { id: 237, text: 'What is the cost of maintaining a version of yourself for someone else?' },
  { id: 238, text: 'When has showing your real face been met with acceptance?' },
  { id: 239, text: 'How do you reconnect with your true self after a day of performing?' },

  // Power & vulnerability (240–269)
  { id: 240, text: 'What does personal power mean to you?' },
  { id: 241, text: 'When do you feel most powerful, and is it sustainable?' },
  { id: 242, text: 'How do you handle being the most powerful person in a room?' },
  { id: 243, text: 'What is your relationship with authority figures?' },
  { id: 244, text: 'How do you express power without dominating?' },
  { id: 245, text: 'When has vulnerability been your greatest strength?' },
  { id: 246, text: 'How do you lead without needing to control?' },
  { id: 247, text: 'What does powerlessness feel like in your body?' },
  { id: 248, text: 'How do you reclaim your power after someone has taken it?' },
  { id: 249, text: 'What is the relationship between surrender and strength in your life?' },
  { id: 250, text: 'How do you use your influence ethically?' },
  { id: 251, text: 'When was the last time you felt powerless, and how did you respond?' },
  { id: 252, text: 'How do you balance confidence with humility?' },
  { id: 253, text: 'What does empowerment look like when it comes from within?' },
  { id: 254, text: 'How do you handle someone who tries to diminish your power?' },
  { id: 255, text: 'What story about weakness do you need to rewrite?' },
  { id: 256, text: 'How do you share power in your relationships?' },
  { id: 257, text: 'What does it mean to be vulnerable without being weak?' },
  { id: 258, text: 'How do you empower others without depleting yourself?' },
  { id: 259, text: 'What fear underlies your need for control?' },
  { id: 260, text: 'How do you convert fear into fuel?' },
  { id: 261, text: 'What does it take for you to show vulnerable emotions?' },
  { id: 262, text: 'How do you handle the discomfort of asking for help?' },
  { id: 263, text: 'What does standing in your power look like on an ordinary day?' },
  { id: 264, text: 'How do you remain open when you feel threatened?' },
  { id: 265, text: 'What is the most empowering thing someone has said to you?' },
  { id: 266, text: 'How do you resist the temptation to use power to avoid painful feelings?' },
  { id: 267, text: 'What does it mean to be strong without being hard?' },
  { id: 268, text: 'How do you maintain dignity when life strips away your defences?' },
  { id: 269, text: 'What power do you have that you are not yet using?' },

  // Inner conflicts & integration (270–299)
  { id: 270, text: 'What two parts of yourself are at war right now?' },
  { id: 271, text: 'How do you resolve internal conflicts between desire and duty?' },
  { id: 272, text: 'What inner contradiction makes you who you are?' },
  { id: 273, text: 'How do you hold space for conflicting emotions at the same time?' },
  { id: 274, text: 'What part of you wants stability while another part craves chaos?' },
  { id: 275, text: 'How do you negotiate between your head and your heart?' },
  { id: 276, text: 'What paradox within you has become a source of creative tension?' },
  { id: 277, text: 'How do you handle the tension between who you are and who you think you should be?' },
  { id: 278, text: 'What inner voice do you listen to most, and is it the right one?' },
  { id: 279, text: 'How do you integrate opposing aspects of your personality?' },
  { id: 280, text: 'What ambivalence are you sitting with right now?' },
  { id: 281, text: 'How do you make decisions when different parts of you want different things?' },
  { id: 282, text: 'What inner child need is your adult self neglecting?' },
  { id: 283, text: 'How do you honour both your light and your darkness?' },
  { id: 284, text: 'What would your rational mind say to your emotional mind today?' },
  { id: 285, text: 'How do you balance your desire for connection with your need for solitude?' },
  { id: 286, text: 'What unresolved tension within you keeps you growing?' },
  { id: 287, text: 'How do you reconcile past trauma with present strength?' },
  { id: 288, text: 'What part of you is ready to grow that another part resists?' },
  { id: 289, text: 'How do you manage the conflict between ambition and contentment?' },
  { id: 290, text: 'What opposing traits in you create your unique character?' },
  { id: 291, text: 'How do you let go of the need for internal consistency?' },
  { id: 292, text: 'What would integration of your conflicting parts look like?' },
  { id: 293, text: 'How do you respect both your extraverted and introverted needs?' },
  { id: 294, text: 'What part of yourself have you exiled, and what would welcoming it back require?' },
  { id: 295, text: 'How do you create peace between your perfectionism and your humanity?' },
  { id: 296, text: 'What opposing desires are you trying to satisfy simultaneously?' },
  { id: 297, text: 'How do you hold complexity without collapsing into confusion?' },
  { id: 298, text: 'What would your wisest self advise your most conflicted self today?' },
  { id: 299, text: 'How do you honour contradictions rather than resolve them?' },

  // Role & purpose (300–329)
  { id: 300, text: 'What role in life do you play most naturally?' },
  { id: 301, text: 'How do you find your purpose through your relationships?' },
  { id: 302, text: 'What would your ideal role in the world be if nothing held you back?' },
  { id: 303, text: 'How has your sense of purpose evolved over the years?' },
  { id: 304, text: 'What archetype do you admire the most, and what does that say about you?' },
  { id: 305, text: 'How do you balance multiple roles without losing yourself?' },
  { id: 306, text: 'What role have you been forced into that you secretly enjoy?' },
  { id: 307, text: 'How do you show up differently in each of your life roles?' },
  { id: 308, text: 'What calling keeps whispering to you?' },
  { id: 309, text: 'How do you know when a role has become a trap?' },
  { id: 310, text: 'What part of your potential remains unlived?' },
  { id: 311, text: 'How do you mentor or guide others without trying to control their path?' },
  { id: 312, text: 'What does service mean to you as a way of being in the world?' },
  { id: 313, text: 'How do you contribute to life beyond your immediate circle?' },
  { id: 314, text: 'What would a fearless version of you pursue?' },
  { id: 315, text: 'How do you express the best of your nature in daily life?' },
  { id: 316, text: 'What archetype are you embodying this season of life?' },
  { id: 317, text: 'How do you respond when your purpose feels unclear?' },
  { id: 318, text: 'What role do you play in your friends\' stories?' },
  { id: 319, text: 'How do you channel your energy into something meaningful today?' },
  { id: 320, text: 'What would it mean to live your archetype at its highest expression?' },
  { id: 321, text: 'How do you navigate between your ideal self and your real self?' },
  { id: 322, text: 'What role are you ready to step into that feels both exciting and terrifying?' },
  { id: 323, text: 'How do you define yourself beyond your job title or social roles?' },
  { id: 324, text: 'What would your archetype say is your greatest unfullfilled potential?' },
  { id: 325, text: 'How do you find meaning in mundane moments?' },
  { id: 326, text: 'What energy do you bring to a room, and is it intentional?' },
  { id: 327, text: 'How do you align your daily actions with your deeper purpose?' },
  { id: 328, text: 'What role do you play in your own healing?' },
  { id: 329, text: 'How do you know when you are living your most authentic archetype?' },

  // Depth & soul (330–364)
  { id: 330, text: 'What does your soul need that your ego keeps ignoring?' },
  { id: 331, text: 'How do you connect with the deepest part of yourself?' },
  { id: 332, text: 'What recurring dream or image keeps appearing in your life?' },
  { id: 333, text: 'How do you find the sacred in the everyday?' },
  { id: 334, text: 'What is the story your life is telling?' },
  { id: 335, text: 'How do you navigate seasons of the soul — growth, decay, dormancy, rebirth?' },
  { id: 336, text: 'What is the myth you are living?' },
  { id: 337, text: 'How do you honour the mystery within yourself?' },
  { id: 338, text: 'What does your deepest intuition say about where your life is headed?' },
  { id: 339, text: 'How do you maintain connection with the unseen parts of yourself?' },
  { id: 340, text: 'What symbol represents your current inner state?' },
  { id: 341, text: 'How do you listen to the quiet voice beneath all the noise?' },
  { id: 342, text: 'What archetype is calling you to evolve right now?' },
  { id: 343, text: 'How do you honour your inner world in a culture that rewards the outer?' },
  { id: 344, text: 'What would your life look like if you trusted your deepest knowing?' },
  { id: 345, text: 'How do you process life experiences on a symbolic level?' },
  { id: 346, text: 'What does the nighttime version of you know that the daytime version denies?' },
  { id: 347, text: 'How do you stay in contact with the mythic dimension of your life?' },
  { id: 348, text: 'What ancestral pattern are you breaking or continuing?' },
  { id: 349, text: 'How do you hold the tension between rational understanding and deeper knowing?' },
  { id: 350, text: 'What is your relationship with silence and what does it reveal?' },
  { id: 351, text: 'How do you differentiate between intuition and impulse?' },
  { id: 352, text: 'What is the most important invisible thing in your life?' },
  { id: 353, text: 'How do you nurture the parts of yourself that cannot be measured?' },
  { id: 354, text: 'What does enchantment look like in your adult life?' },
  { id: 355, text: 'How do you keep your inner fire alive?' },
  { id: 356, text: 'What does your core want that the world does not make easy?' },
  { id: 357, text: 'How do you create rituals that feed your soul?' },
  { id: 358, text: 'What do you know to be true that you cannot prove?' },
  { id: 359, text: 'How do you make space for awe in a busy life?' },
  { id: 360, text: 'What does the voice of your authentic self sound like?' },
  { id: 361, text: 'How do you honour endings as part of your journey?' },
  { id: 362, text: 'What is the most beautiful thing about being human, in your experience?' },
  { id: 363, text: 'How would you describe the essence of who you are in one sentence?' },
  { id: 364, text: 'What is the question only you can answer, and are you answering it?' },
];

// ─────────────────────────────────────────────────────────────────────────────
// COGNITIVE STYLE — 365 questions
// Themes: decision-making, information processing, problem-solving,
//         learning, intuition, analysis, patterns, communication,
//         risk, creativity, attention, memory
// ─────────────────────────────────────────────────────────────────────────────

export const COGNITIVE_QUESTIONS: ReflectionQuestion[] = [
  // Decision-making (0–29)
  { id: 0, text: 'How did you make your most recent important decision?' },
  { id: 1, text: 'Do you tend to deliberate long or decide quickly — and which do you trust more?' },
  { id: 2, text: 'What role does gut feeling play in your decision-making?' },
  { id: 3, text: 'Describe a decision you made quickly that turned out well.' },
  { id: 4, text: 'How do you handle decision fatigue at the end of a long day?' },
  { id: 5, text: 'What is the biggest decision you are currently postponing?' },
  { id: 6, text: 'How do you weigh risks vs. rewards in personal decisions?' },
  { id: 7, text: 'When you face a fork in the road, do you think first or feel first?' },
  { id: 8, text: 'How does your confidence in a decision change after you make it?' },
  { id: 9, text: 'How do you handle regret about past decisions?' },
  { id: 10, text: 'What information do you need before you can commit to a choice?' },
  { id: 11, text: 'How do other people influence your decision-making process?' },
  { id: 12, text: 'Do you make better decisions alone or by talking things through?' },
  { id: 13, text: 'How do you handle choices where there is no clear right answer?' },
  { id: 14, text: 'What is your process for making financial decisions?' },
  { id: 15, text: 'How do you decide when something is "good enough" vs. worth perfecting?' },
  { id: 16, text: 'How do you handle the anxiety of an irreversible decision?' },
  { id: 17, text: 'What decision-making strategy do you fall back on under pressure?' },
  { id: 18, text: 'How do you balance logic and emotion when making choices?' },
  { id: 19, text: 'Describe a decision that changed the trajectory of your life.' },
  { id: 20, text: 'How do you handle conflicting advice from people you trust?' },
  { id: 21, text: 'What is one decision rule you live by?' },
  { id: 22, text: 'How quickly can you tell if a decision was right or wrong?' },
  { id: 23, text: 'How do you prioritise when everything feels urgent?' },
  { id: 24, text: 'What is the most counterintuitive decision you have made that worked?' },
  { id: 25, text: 'How do you recognize when you are overthinking a decision?' },
  { id: 26, text: 'What type of decisions do you avoid making, and why?' },
  { id: 27, text: 'How do you re-evaluate a decision once new information appears?' },
  { id: 28, text: 'Do you prefer having many options or having a clear recommendation?' },
  { id: 29, text: 'How does time pressure affect the quality of your decisions?' },

  // Information processing (30–59)
  { id: 30, text: 'Do you prefer to read instructions or figure things out by doing?' },
  { id: 31, text: 'How do you organize information in your mind — visually, verbally, or spatially?' },
  { id: 32, text: 'How do you decide what information to pay attention to and what to ignore?' },
  { id: 33, text: 'Do you prefer getting the big picture first or the details first?' },
  { id: 34, text: 'How do you handle information overload?' },
  { id: 35, text: 'What kind of information sticks in your memory most easily?' },
  { id: 36, text: 'How do you fact-check your own assumptions?' },
  { id: 37, text: 'Do you prefer structured data or narrative storytelling to understand something?' },
  { id: 38, text: 'How do you process bad news differently from good news?' },
  { id: 39, text: 'What is your preferred way to take in new information?' },
  { id: 40, text: 'How do you distinguish between relevant and irrelevant information?' },
  { id: 41, text: 'How do you handle ambiguity in data or situations?' },
  { id: 42, text: 'Do you think in words, images, sounds, or feelings?' },
  { id: 43, text: 'How do you summarize complex information for yourself?' },
  { id: 44, text: 'What is your relationship with numbers and quantitative data?' },
  { id: 45, text: 'How do you evaluate the credibility of a new source of information?' },
  { id: 46, text: 'Do you prefer to consume information alone or discuss it with others?' },
  { id: 47, text: 'How do you handle contradictory information from trusted sources?' },
  { id: 48, text: 'What is your process for absorbing a book or article?' },
  { id: 49, text: 'How quickly do you form an opinion when presented with new information?' },
  { id: 50, text: 'How do you keep track of important ideas or thoughts?' },
  { id: 51, text: 'Do you prefer learning from experts, from peers, or from experience?' },
  { id: 52, text: 'How do you notice patterns in information that others miss?' },
  { id: 53, text: 'What information bias do you know you have?' },
  { id: 54, text: 'How do you store and retrieve memories of important conversations?' },
  { id: 55, text: 'Do you tend to seek confirming or disconfirming evidence for your beliefs?' },
  { id: 56, text: 'How does your emotional state affect what information you absorb?' },
  { id: 57, text: 'What kind of learning experience engages you most deeply?' },
  { id: 58, text: 'How do you handle being wrong about a deeply held belief?' },
  { id: 59, text: 'How do you balance breadth and depth when exploring a new topic?' },

  // Problem-solving (60–89)
  { id: 60, text: 'What is your go-to approach when facing a new problem?' },
  { id: 61, text: 'Do you prefer solving problems alone or collaboratively?' },
  { id: 62, text: 'How do you handle a problem that seems to have no solution?' },
  { id: 63, text: 'Describe a creative solution you found to a stubborn problem.' },
  { id: 64, text: 'How do you break a large problem into smaller pieces?' },
  { id: 65, text: 'When you are stuck, what unblocks you?' },
  { id: 66, text: 'How do you know when to push harder vs. step away from a problem?' },
  { id: 67, text: 'What role does trial and error play in how you solve things?' },
  { id: 68, text: 'How do you approach problems differently in work vs. personal life?' },
  { id: 69, text: 'What kind of problems energise you the most?' },
  { id: 70, text: 'How do you deal with problems that are emotionally charged?' },
  { id: 71, text: 'Do you solve problems from the top down or the bottom up?' },
  { id: 72, text: 'How do you handle the frustration of repeated failure?' },
  { id: 73, text: 'What is your process for debugging something that is not working in life?' },
  { id: 74, text: 'How does sleep or rest affect your ability to solve problems?' },
  { id: 75, text: 'Do you prefer to prevent problems or fix them as they come?' },
  { id: 76, text: 'How do you handle problems that require expertise you do not have?' },
  { id: 77, text: 'What problem-solving method have you learned from someone else?' },
  { id: 78, text: 'How does your mood influence how you approach obstacles?' },
  { id: 79, text: 'What is the most elegant solution you have ever seen to a complex problem?' },
  { id: 80, text: 'How do you know when a problem is solved "enough"?' },
  { id: 81, text: 'How do you approach interpersonal problems vs. logical problems?' },
  { id: 82, text: 'What is your relationship with asking for help when you are stuck?' },
  { id: 83, text: 'How do you evaluate multiple possible solutions?' },
  { id: 84, text: 'What unconventional approach to problem-solving do you use?' },
  { id: 85, text: 'How do you handle problems with high stakes and limited information?' },
  { id: 86, text: 'How does physical movement affect your thinking when you are stuck?' },
  { id: 87, text: 'What problem in your life right now would benefit from a completely different approach?' },
  { id: 88, text: 'How do you reframe a problem when the first framing leads nowhere?' },
  { id: 89, text: 'How do you handle the discomfort of working on a problem you cannot yet see the end of?' },

  // Learning & growth (90–119)
  { id: 90, text: 'How do you learn best: reading, listening, watching, or doing?' },
  { id: 91, text: 'What is the most recent thing you learned that excited you?' },
  { id: 92, text: 'How do you stay curious about things outside your expertise?' },
  { id: 93, text: 'What learning environment brings out your best performance?' },
  { id: 94, text: 'How do you handle the discomfort of being a beginner?' },
  { id: 95, text: 'What skill took you the longest to learn, and what did the process teach you?' },
  { id: 96, text: 'How do you integrate new knowledge with what you already know?' },
  { id: 97, text: 'What subject do you find yourself returning to again and again?' },
  { id: 98, text: 'How do you retain information long-term?' },
  { id: 99, text: 'What is your attention span like, and has it changed over the years?' },
  { id: 100, text: 'How do you learn from failure vs. success?' },
  { id: 101, text: 'What learning habit serves you well that others do not know about?' },
  { id: 102, text: 'How do you teach yourself something completely new?' },
  { id: 103, text: 'What cognitive challenge do you enjoy the most?' },
  { id: 104, text: 'How does pressure affect your ability to learn and absorb?' },
  { id: 105, text: 'What do you wish you had been taught earlier in life?' },
  { id: 106, text: 'How do deadlines affect the quality of your thinking?' },
  { id: 107, text: 'What is the most surprising lesson you have learned from a mundane experience?' },
  { id: 108, text: 'How do you handle a learning plateau where progress feels invisible?' },
  { id: 109, text: 'What motivates you more: mastery or novelty?' },
  { id: 110, text: 'How does your learning style affect your relationships?' },
  { id: 111, text: 'What type of feedback helps you grow the most?' },
  { id: 112, text: 'How do you stay engaged during tedious but necessary learning?' },
  { id: 113, text: 'What does flow state feel like for you, and what triggers it?' },
  { id: 114, text: 'How do you balance structured learning with exploration?' },
  { id: 115, text: 'What is one thing you want to learn in the next month?' },
  { id: 116, text: 'How do you decide when you know enough about a topic to move on?' },
  { id: 117, text: 'What intellectual conversation has stayed with you the longest?' },
  { id: 118, text: 'How do you handle realizing you have been wrong about something for a long time?' },
  { id: 119, text: 'What does intellectual humility look like in your daily life?' },

  // Intuition & analysis (120–149)
  { id: 120, text: 'How do you balance intuition with data when making judgements?' },
  { id: 121, text: 'Describe a time your gut was right when the data said otherwise.' },
  { id: 122, text: 'How do you explain your intuitive hunches to people who think analytically?' },
  { id: 123, text: 'What does your intuition feel like physically?' },
  { id: 124, text: 'How do you develop your intuitive sense — is it natural or cultivated?' },
  { id: 125, text: 'When was the last time analysis paralysis stopped you from acting?' },
  { id: 126, text: 'How do you know when to trust your analysis and when to trust your instinct?' },
  { id: 127, text: 'What domain do you trust your intuition the most in?' },
  { id: 128, text: 'How do you handle situations where your intuition and your logic point in different directions?' },
  { id: 129, text: 'What is your relationship with uncertainty — do you analyse it away or sit with it?' },
  { id: 130, text: 'How do you cultivate your intuition for reading people?' },
  { id: 131, text: 'What analytical framework do you use most in daily life, even informally?' },
  { id: 132, text: 'How do you make sense of a situation that does not fit any pattern you know?' },
  { id: 133, text: 'What cognitive shortcut do you use that usually works well?' },
  { id: 134, text: 'How do you calibrate your confidence in your own judgement?' },
  { id: 135, text: 'What is the biggest mistake your intuition has led you to?' },
  { id: 136, text: 'How do you handle situations that require pure logic with no room for feeling?' },
  { id: 137, text: 'What does "overthinking" look like for you?' },
  { id: 138, text: 'How do you tell the difference between intuition and wishful thinking?' },
  { id: 139, text: 'What type of analysis do you find most satisfying?' },
  { id: 140, text: 'How has your trust in your own intuition changed over the years?' },
  { id: 141, text: 'What is the most complex thing you have had to analyse recently?' },
  { id: 142, text: 'How do you notice subtle signals that others miss?' },
  { id: 143, text: 'What does balanced thinking look like for you?' },
  { id: 144, text: 'How do you handle being "too in your head"?' },
  { id: 145, text: 'What kind of decisions do you always sleep on before finalising?' },
  { id: 146, text: 'How do you reset your thinking when you are going in circles?' },
  { id: 147, text: 'What is your first instinct when encountering a stranger — analysis or feeling?' },
  { id: 148, text: 'How do you decide when enough analysis is enough?' },
  { id: 149, text: 'What would happen if you trusted your first thought more often?' },

  // Patterns & connections (150–179)
  { id: 150, text: 'What patterns do you notice in your own behaviour that repeat across situations?' },
  { id: 151, text: 'How do you connect seemingly unrelated ideas?' },
  { id: 152, text: 'What is a pattern in your life that you have recently become aware of?' },
  { id: 153, text: 'How do you use past experience to predict future outcomes?' },
  { id: 154, text: 'What connections between events or people do you see that others might not?' },
  { id: 155, text: 'How do you notice when a situation is rhyming with one from your past?' },
  { id: 156, text: 'What thinking habit loops back the most when you are stressed?' },
  { id: 157, text: 'How do you make sense of coincidences?' },
  { id: 158, text: 'What mental model do you use to understand human behaviour?' },
  { id: 159, text: 'How do you detect when someone is not being fully honest?' },
  { id: 160, text: 'What recurring thought pattern tells you the most about your inner state?' },
  { id: 161, text: 'How do you recognise cause and effect in complex situations?' },
  { id: 162, text: 'What patterns in nature or art resonate with how your mind works?' },
  { id: 163, text: 'How do you handle being wrong about a pattern you thought you saw?' },
  { id: 164, text: 'What is the most useful metaphor you have discovered for understanding your life?' },
  { id: 165, text: 'How do you balance pattern recognition with remaining open to exception?' },
  { id: 166, text: 'What cycles in your emotional life have you identified?' },
  { id: 167, text: 'How do you trace the origin of a feeling through your thought patterns?' },
  { id: 168, text: 'What pattern-breaking experience has most shaped your thinking?' },
  { id: 169, text: 'How do you use analogies to make sense of new situations?' },
  { id: 170, text: 'What is a connection you have recently made between two different areas of your life?' },
  { id: 171, text: 'How do you notice trends in your mood, energy, or focus across a week?' },
  { id: 172, text: 'What thought pattern should you interrupt more often?' },
  { id: 173, text: 'How do abstraction and metaphor play a role in your thinking?' },
  { id: 174, text: 'What mental model would you love to better understand?' },
  { id: 175, text: 'How do you handle seeing patterns that turn out to be noise?' },
  { id: 176, text: 'What is the most interesting pattern you have noticed in your relationships?' },
  { id: 177, text: 'How do you process complex social situations — intuitively or analytically?' },
  { id: 178, text: 'What recurring theme in your life are you actively trying to shift?' },
  { id: 179, text: 'How do you use your understanding of patterns to plan ahead?' },

  // Communication & expression (180–209)
  { id: 180, text: 'How do you organize your thoughts before speaking about something complex?' },
  { id: 181, text: 'Do you think better in writing, speaking, or drawing?' },
  { id: 182, text: 'How do you adapt your communication style for different people?' },
  { id: 183, text: 'What kind of conversation energises your thinking the most?' },
  { id: 184, text: 'How do you handle communicating an idea that others do not immediately understand?' },
  { id: 185, text: 'Do you process emotions through language or through other means?' },
  { id: 186, text: 'How do you hold space in a conversation vs. filling silence?' },
  { id: 187, text: 'What is your relationship with listening vs. responding in conversations?' },
  { id: 188, text: 'How do you convey nuance when words feel insufficient?' },
  { id: 189, text: 'What is your inner monologue like — is it structured, chaotic, visual, verbal?' },
  { id: 190, text: 'How do you process disagreement in real-time conversation?' },
  { id: 191, text: 'Do you think more clearly under pressure or in calm environments?' },
  { id: 192, text: 'How has technology changed the way you think and communicate?' },
  { id: 193, text: 'What kind of question makes you think the deepest?' },
  { id: 194, text: 'How do you explain something technical to someone non-technical?' },
  { id: 195, text: 'What role does storytelling play in how you understand the world?' },
  { id: 196, text: 'How do you retain the key points from a long conversation?' },
  { id: 197, text: 'What is your relationship with small talk — valuable or draining?' },
  { id: 198, text: 'How do you formulate arguments — logically, emotionally, or narratively?' },
  { id: 199, text: 'What type of question would you love someone to ask you right now?' },
  { id: 200, text: 'How do you detect subtext and unspoken meaning in conversation?' },
  { id: 201, text: 'What communication style triggers frustration in you?' },
  { id: 202, text: 'How do you process and express gratitude — internally or outwardly?' },
  { id: 203, text: 'What is the most productive conversation format for you — structured or free-flowing?' },
  { id: 204, text: 'How do you handle misunderstandings without becoming defensive?' },
  { id: 205, text: 'What role does journaling or writing play in your cognitive life?' },
  { id: 206, text: 'How do you prepare mentally before an important conversation?' },
  { id: 207, text: 'What cognitive trick helps you stay focused during long discussions?' },
  { id: 208, text: 'How do you handle the gap between what you think and what you can articulate?' },
  { id: 209, text: 'What is the most illuminating thing someone has said to you about your communication style?' },

  // Attention & focus (210–239)
  { id: 210, text: 'What captures your attention involuntarily?' },
  { id: 211, text: 'How do you maintain focus when distractions are high?' },
  { id: 212, text: 'What is your peak focus time of day?' },
  { id: 213, text: 'How long can you sustain deep concentration, and what breaks it?' },
  { id: 214, text: 'What do you do when your mind wanders during something important?' },
  { id: 215, text: 'How does multitasking affect the quality of your thinking?' },
  { id: 216, text: 'What environment helps you focus best?' },
  { id: 217, text: 'How do you manage the tension between being focused and being open?' },
  { id: 218, text: 'What is your greatest cognitive distraction right now?' },
  { id: 219, text: 'How do you recover focus after an interruption?' },
  { id: 220, text: 'What does deep work feel like, and how often do you achieve it?' },
  { id: 221, text: 'How do you prioritise attention across multiple demands?' },
  { id: 222, text: 'What helps you enter a state of flow?' },
  { id: 223, text: 'How do you handle the mental cost of context switching?' },
  { id: 224, text: 'What is your relationship with digital distractions?' },
  { id: 225, text: 'How do you notice when your attention is being manipulated?' },
  { id: 226, text: 'What did you pay attention to today that you usually overlook?' },
  { id: 227, text: 'How does fatigue change what you focus on?' },
  { id: 228, text: 'What is the difference between your focused self and your scattered self?' },
  { id: 229, text: 'How do you direct attention to your inner life amid a busy day?' },
  { id: 230, text: 'What do you notice first when you enter a new space — people, objects, or atmosphere?' },
  { id: 231, text: 'How does background noise affect your thinking?' },
  { id: 232, text: 'What activity demands your fullest attention and how does that feel?' },
  { id: 233, text: 'How do you handle boredom, and what does it signal to you?' },
  { id: 234, text: 'What is your relationship with mindfulness or meditation?' },
  { id: 235, text: 'How do you protect your attention as a finite resource?' },
  { id: 236, text: 'What do you involuntarily ruminate on?' },
  { id: 237, text: 'How do you refocus after emotional disruption?' },
  { id: 238, text: 'What cognitive task do you find yourself procrastinating on the most?' },
  { id: 239, text: 'How do you create conditions for your best thinking?' },

  // Risk & uncertainty (240–269)
  { id: 240, text: 'How do you assess risk in a situation with incomplete information?' },
  { id: 241, text: 'What is your cognitive response to uncertainty — do you plan, freeze, or act?' },
  { id: 242, text: 'How has your relationship with risk changed as you have aged?' },
  { id: 243, text: 'What level of uncertainty are you comfortable with in daily life?' },
  { id: 244, text: 'How do you prepare for outcomes you cannot predict?' },
  { id: 245, text: 'What kind of risk excites you vs. what kind terrifies you?' },
  { id: 246, text: 'How do you distinguish productive worry from anxious rumination?' },
  { id: 247, text: 'What is your default assumption about uncertainty — opportunity or threat?' },
  { id: 248, text: 'How do you calculate whether a risk is worth taking?' },
  { id: 249, text: 'What is the smartest risk you have taken recently?' },
  { id: 250, text: 'How do you handle the unknown in relationships?' },
  { id: 251, text: 'What strategy do you use to cope when outcomes are completely out of your hands?' },
  { id: 252, text: 'How do you reframe uncertainty as possibility?' },
  { id: 253, text: 'What does your body do when you sense danger or opportunity?' },
  { id: 254, text: 'How do you evaluate worst-case scenarios without catastrophising?' },
  { id: 255, text: 'What helps you remain calm in ambiguous situations?' },
  { id: 256, text: 'How comfortable are you making bets on yourself?' },
  { id: 257, text: 'What is the most uncertain period of your life, and how did you navigate it?' },
  { id: 258, text: 'How do you handle not knowing how something will turn out?' },
  { id: 259, text: 'What is your tolerance for ambiguity in relationships?' },
  { id: 260, text: 'How do you plan when the rules of the game keep changing?' },
  { id: 261, text: 'What cognitive bias affects your risk assessment the most?' },
  { id: 262, text: 'How do you think about probability in everyday decisions?' },
  { id: 263, text: 'What does psychological safety mean to your cognitive performance?' },
  { id: 264, text: 'How do you remain open to unexpected outcomes?' },
  { id: 265, text: 'What have you learned about yourself from taking risks that failed?' },
  { id: 266, text: 'How do you stop yourself from making fear-based decisions?' },
  { id: 267, text: 'What role does optimism play in how you evaluate risk?' },
  { id: 268, text: 'How do you recognize when playing it safe is actually the riskiest choice?' },
  { id: 269, text: 'What is the relationship between uncertainty and creativity in your life?' },

  // Memory & reflection (270–299)
  { id: 270, text: 'What kind of memories are most vivid for you — visual, emotional, or conceptual?' },
  { id: 271, text: 'How do you make sense of the past — through narrative, analysis, or emotion?' },
  { id: 272, text: 'What is a memory that shaped how you think today?' },
  { id: 273, text: 'How accurate do you believe your memory is?' },
  { id: 274, text: 'What do you tend to remember about people — what they said or how they made you feel?' },
  { id: 275, text: 'How do you process and learn from a mistake after it happens?' },
  { id: 276, text: 'What role does nostalgia play in your thinking?' },
  { id: 277, text: 'How has your memory of an important event changed over time?' },
  { id: 278, text: 'What is a lesson from your past that you apply daily without thinking about it?' },
  { id: 279, text: 'How do you deal with intrusive or unwanted memories?' },
  { id: 280, text: 'What is the relationship between what you remember and who you become?' },
  { id: 281, text: 'How do you handle a memory that contradicts your current self-image?' },
  { id: 282, text: 'What triggers a flood of old memories for you?' },
  { id: 283, text: 'How do you use reflection to improve your thinking process?' },
  { id: 284, text: 'What is the most valuable thing reflection has taught you about yourself?' },
  { id: 285, text: 'How do you archive life lessons — mentally, in writing, or through ritual?' },
  { id: 286, text: 'What memory do you return to for comfort?' },
  { id: 287, text: 'How do you separate factual memory from emotional colouring?' },
  { id: 288, text: 'What part of your life story would you narrate differently now?' },
  { id: 289, text: 'How do you use hindsight productively without getting stuck in the past?' },
  { id: 290, text: 'What do your recurring memories tell you about your current needs?' },
  { id: 291, text: 'How do you review your day mentally before sleep?' },
  { id: 292, text: 'What cognitive habit helps you extract insight from experience?' },
  { id: 293, text: 'How does your mood affect which memories come forward?' },
  { id: 294, text: 'What forgotten memory would you love to recover?' },
  { id: 295, text: 'How do you handle the gap between how you remember an event and how someone else does?' },
  { id: 296, text: 'What life experience do you mentally replay the most?' },
  { id: 297, text: 'How do you synthesize daily reflections into lasting self-knowledge?' },
  { id: 298, text: 'What role does journaling play in how you process your thoughts?' },
  { id: 299, text: 'How do you know when you have truly learned from an experience?' },

  // Creativity & mental models (300–329)
  { id: 300, text: 'Where does your most creative thinking happen — time of day, place, activity?' },
  { id: 301, text: 'What mental models do you rely on most in daily life?' },
  { id: 302, text: 'How do you generate new ideas when you feel stuck?' },
  { id: 303, text: 'What is the most unusual connection your mind has made recently?' },
  { id: 304, text: 'How do you use constraints to boost creativity?' },
  { id: 305, text: 'What is your relationship between routine and innovative thinking?' },
  { id: 306, text: 'How do you distinguish a good idea from an exciting one?' },
  { id: 307, text: 'What thinking tool — lists, maps, diagrams — do you find most useful?' },
  { id: 308, text: 'How do you nurture an idea from spark to fully formed concept?' },
  { id: 309, text: 'What kills your creativity the fastest?' },
  { id: 310, text: 'How do you handle the gap between vision and execution?' },
  { id: 311, text: 'What is the most valuable mental model you have adopted from someone else?' },
  { id: 312, text: 'How do you test a crazy idea before committing to it?' },
  { id: 313, text: 'What does creative courage look like in your thinking?' },
  { id: 314, text: 'How do you balance originality with what already works?' },
  { id: 315, text: 'What is the most creative period of your life, and what enabled it?' },
  { id: 316, text: 'How do you move from thinking about an idea to actually implementing it?' },
  { id: 317, text: 'What role does boredom play in your creative process?' },
  { id: 318, text: 'How do you evaluate whether an idea is worth deeply pursuing?' },
  { id: 319, text: 'What does your creative process share with your problem-solving process?' },
  { id: 320, text: 'How do you remain creative under pressure?' },
  { id: 321, text: 'What environment stifles your creative thinking?' },
  { id: 322, text: 'How do you make room for unexpected ideas in a structured day?' },
  { id: 323, text: 'What is the most productive way you procrastinate?' },
  { id: 324, text: 'How do you handle the vulnerability of sharing a new idea?' },
  { id: 325, text: 'What do you do with ideas that seem great at night but ordinary in the morning?' },
  { id: 326, text: 'How do you balance your inner critic with your inner creator?' },
  { id: 327, text: 'What surprising input — a walk, a conversation, a random article — recently sparked a breakthrough?' },
  { id: 328, text: 'How do you invite serendipity into your thinking process?' },
  { id: 329, text: 'What is the relationship between your imagination and your reality?' },

  // Meta-cognition & self-awareness (330–364)
  { id: 330, text: 'How would you describe the way your mind works to someone who thinks very differently?' },
  { id: 331, text: 'What blind spot in your thinking are you becoming more aware of?' },
  { id: 332, text: 'How do you monitor the quality of your own thinking?' },
  { id: 333, text: 'What cognitive strength do others count on you for?' },
  { id: 334, text: 'How do you recognise when you are reasoning well vs. poorly?' },
  { id: 335, text: 'What is the relationship between your emotions and the clarity of your thinking?' },
  { id: 336, text: 'How do you adapt your thinking style for different kinds of challenges?' },
  { id: 337, text: 'What piece of self-knowledge about your cognition has been most useful?' },
  { id: 338, text: 'How has understanding your cognitive style improved your relationships?' },
  { id: 339, text: 'What thinking trap do you fall into most often?' },
  { id: 340, text: 'How do you compensate for your cognitive weaknesses?' },
  { id: 341, text: 'What is the relationship between your energy level and your thinking quality?' },
  { id: 342, text: 'How do you know when your judgement is compromised?' },
  { id: 343, text: 'What does metacognition — thinking about thinking — mean in your daily life?' },
  { id: 344, text: 'How do you help others understand how your mind processes things?' },
  { id: 345, text: 'What thinking approach serves you well that is not traditionally rewarded?' },
  { id: 346, text: 'How do you balance following your cognitive strengths with developing weaknesses?' },
  { id: 347, text: 'What does cognitive flexibility mean to you in practice?' },
  { id: 348, text: 'How has your thinking style shaped your career or life path?' },
  { id: 349, text: 'What question about your own cognition would you like answered?' },
  { id: 350, text: 'How do you handle feedback about how you think or communicate?' },
  { id: 351, text: 'What does a well-functioning mind feel like to you?' },
  { id: 352, text: 'How do you keep your mind sharp and engaged?' },
  { id: 353, text: 'What is the most important thing you have learned about yourself through these reflections?' },
  { id: 354, text: 'How does self-awareness change the way you experience your own thinking?' },
  { id: 355, text: 'What aspect of your cognition would you most like to evolve?' },
  { id: 356, text: 'How do you use self-observation to make better choices?' },
  { id: 357, text: 'What is your most effective strategy for clear thinking under emotional stress?' },
  { id: 358, text: 'How do you differentiate between your conditioned responses and your considered ones?' },
  { id: 359, text: 'What does cognitive maturity look like to you?' },
  { id: 360, text: 'How do you build on your thinking strengths in new domains?' },
  { id: 361, text: 'What is the role of self-reflection in your intellectual growth?' },
  { id: 362, text: 'How has deepening your self-knowledge changed how you approach the world?' },
  { id: 363, text: 'What is the most surprising thing daily reflection has revealed about your mind?' },
  { id: 364, text: 'Looking back over your reflections, what pattern emerges about how you think and grow?' },
];

// ─────────────────────────────────────────────────────────────────────────────
// Lookup map for ergonomic access
// ─────────────────────────────────────────────────────────────────────────────

export const QUESTION_BANKS: Record<ReflectionCategory, ReflectionQuestion[]> = {
  values: VALUES_QUESTIONS,
  archetypes: ARCHETYPE_QUESTIONS,
  cognitive: COGNITIVE_QUESTIONS,
};

export const CATEGORY_LABELS: Record<ReflectionCategory, string> = {
  values: 'Core Values',
  archetypes: 'Archetypes',
  cognitive: 'Cognitive Style',
};

export const CATEGORY_ICONS: Record<ReflectionCategory, string> = {
  values: '◈',
  archetypes: '⬡',
  cognitive: '◉',
};
