// File: app/terms.tsx
import React from 'react';
import { View, Text, ScrollView, StyleSheet, Pressable } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { SkiaGradient as LinearGradient } from '../components/ui/SkiaGradient';
import { useRouter } from 'expo-router';
import Animated, { FadeInDown } from 'react-native-reanimated';
import { Ionicons } from '@expo/vector-icons';

import { type AppTheme } from '../constants/theme';
import { SUPPORT_EMAIL } from '../constants/config';
import { MetallicText } from '../components/ui/MetallicText';
import { MetallicIcon } from '../components/ui/MetallicIcon';
import { SkiaDynamicCosmos } from '../components/ui/SkiaDynamicCosmos';
import { GoldSubtitle } from '../components/ui/GoldSubtitle';
import { useAppTheme, useThemedStyles } from '../context/ThemeContext';

export default function TermsOfServiceScreen({ onBack }: { onBack?: () => void } = {}) {
  const theme = useAppTheme();
  const styles = useThemedStyles(createStyles);
  const router = useRouter();
  const PALETTE = {
    gold: theme.textGold,
    silverBlue: '#A2C2E1',
    copper: '#CD7F5D',
    textMain: theme.textPrimary,
    glassBorder: theme.cardBorder,
    glassHighlight: theme.glass.highlight,
  };

  return (
    <View style={styles.container}>
      <SkiaDynamicCosmos />

      <View style={StyleSheet.absoluteFill} pointerEvents="none">
        <View style={[styles.glowOrb, { top: -60, right: -60, backgroundColor: 'rgba(162, 194, 225, 0.12)' }]} />
        <View style={[styles.glowOrb, { bottom: 160, left: -120, backgroundColor: 'rgba(168, 139, 235, 0.06)' }]} />
      </View>

      <SafeAreaView edges={['top']} style={styles.safeArea}>
        {/* Header */}
        <View style={styles.header}>
          <Pressable
            style={styles.backButton}
            onPress={() => onBack ? onBack() : (router.canGoBack() ? router.back() : undefined)}
            accessibilityRole="button"
            accessibilityLabel="Back"
          >
            <MetallicIcon name="chevron-back-outline" size={22} variant="gold" />
          </Pressable>
        </View>
        <View style={styles.titleArea}>
          <Text style={styles.headerTitle}>Terms</Text>
          <GoldSubtitle style={styles.headerSubtitle}>Terms of Use &amp; EULA</GoldSubtitle>
        </View>

        <ScrollView
          style={styles.scrollView}
          contentContainerStyle={styles.scrollContent}
          showsVerticalScrollIndicator={false}
        >
          <Animated.View entering={FadeInDown.delay(100).duration(600)}>
            <View style={styles.heroIconWrap}>
              <Ionicons name="document-text-outline" size={132} color={theme.textGold} />
            </View>

            <Text style={styles.lastUpdated}>Last updated: April 7, 2026</Text>

            <Text style={styles.sectionTitle}>Acceptance of Terms of Use</Text>
            <Text style={styles.paragraph}>
              By downloading, installing, or using MySky ("the App"), you agree to be bound by these Terms of Use (End User License Agreement), our Privacy Policy, and all applicable laws and regulations. If you do not agree to these Terms, do not download, install, or use the App. All personal data is stored locally on your device with <Text style={styles.highlight}>AES-256-GCM field-level encryption</Text> and hardware-backed key storage.
            </Text>

            <Text style={styles.sectionTitle}>Definitions</Text>
            <Text style={styles.bulletItem}>• <Text style={styles.boldText}>"App"</Text> means the MySky mobile application, including all updates and supplements.</Text>
            <Text style={styles.bulletItem}>• <Text style={styles.boldText}>"We," "us," or "our"</Text> refers to Brittany Apps, the developer and operator of MySky.</Text>
            <Text style={styles.bulletItem}>• <Text style={styles.boldText}>"You" or "user"</Text> refers to the individual downloading, installing, or using the App.</Text>
            <Text style={styles.bulletItem}>• <Text style={styles.boldText}>"Content"</Text> means all text, data, images, interpretations, reflections, and other materials generated by or displayed within the App.</Text>
            <Text style={styles.bulletItem}>• <Text style={styles.boldText}>"User Data"</Text> means all personal data you enter into the App, including journal entries, check-ins, birth data, dream logs, and self-discovery profiles.</Text>
            <Text style={styles.bulletItem}>• <Text style={styles.boldText}>"Deeper Sky"</Text> refers to the premium subscription tier of the App.</Text>

            <Text style={styles.sectionTitle}>Service Description</Text>
            <Text style={styles.paragraph}>
              MySky provides a local-first personal framework for self-knowledge, growth, and reflection. Tools include daily wellness tracking, dream journaling, emotional pattern mapping, self-discovery exercises (values inventory, somatic body mapping, nervous system trigger logs), and optional astrological context. The app is intended for users aged 17 and older. A free account is required, but core features work fully offline after initial sign-in.
            </Text>

            <Text style={styles.sectionTitle}>License Grant</Text>
            <Text style={styles.paragraph}>
              Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, revocable license to download, install, and use the App on a single device that you own or control, solely for your personal, non-commercial purposes. This license does not include the right to sublicense, sell, resell, or commercially exploit the App or any Content.
            </Text>

            <View style={styles.glassCard}>
              <Text style={[styles.subHeader, { color: PALETTE.gold }]}>Free & Premium Features</Text>
              <Text style={styles.paragraph}>
                <Text style={styles.boldText}>Free:</Text> Personal birth chart visualization, Big Three, daily mood/energy/stress check-ins, basic journal, sleep quality logging, AI dream interpretation using the standard Gemini model, balance dashboard, 2 rotating energy domains, 1 relationship chart, 3 personal story chapters, and daily context.
              </Text>
              <Text style={styles.paragraph}>
                <Text style={[styles.boldText, { color: PALETTE.gold }]}>Deeper Sky:</Text> Dream journal with AI interpretation using a richer Gemini model, extended personal reflection trends, unlimited relationship charts, all 10 personal story chapters, growth and attachment reflections, full chakra energy reading with all 7 chakras, emotional quality tagging, AI Reflection Insights, reflective daily guidance with action prompts, sensitivity and growth mapping, PDF chart export, encrypted .msky backup and restore, and extended pattern reflections.
              </Text>
            </View>

            <Text style={styles.sectionTitle}>Subscriptions & Payments</Text>
            <Text style={styles.paragraph}>
              Premium access ("Deeper Sky") is available via auto-renewing subscriptions (monthly or yearly) or a one-time lifetime purchase. Payment is charged through your platform account at confirmation of purchase. Subscriptions automatically renew unless cancelled at least 24 hours before the end of the current period. Your account will be charged for renewal within 24 hours prior to the end of the current period. You can manage or cancel subscriptions in your device's App Store or Google Play subscription settings. Purchases can be restored at any time.
            </Text>

            <Text style={styles.sectionTitle}>Accounts</Text>
            <Text style={styles.paragraph}>
              A free account is required to use MySky. Accounts are managed via Supabase Auth (email and password) and are used to authenticate your identity, support purchase restoration, and enable optional network-backed features such as AI dream interpretation and AI Reflection Insights. A Deeper Sky subscription is required for premium upgrades, including the richer dream model and other premium features.
            </Text>

            <LinearGradient 
              colors={['rgba(205,127,93,0.10)', theme.cardGradientEnd]} 
              style={styles.disclaimerCard}
            >
              <View style={styles.disclaimerHeader}>
                <MetallicIcon name="medical-outline" size={18} color={PALETTE.copper} />
                <MetallicText style={[styles.subHeader, { marginBottom: 0 }]} color={PALETTE.copper}>Not Medical or Therapeutic Advice</MetallicText>
              </View>
              <Text style={styles.paragraph}>
                MySky is a self-reflection and personal growth tool, not a medical app. None of its features — including chart-based content, dream reflections, somatic body mapping, nervous system trigger logs, core values exercises, psychological archetype profiles, emotional pattern analysis, cognitive style assessments, healing path prompts, or any other content — constitute medical advice, psychological diagnosis, therapy, counseling, or treatment of any kind.
              </Text>
              <Text style={styles.paragraph}>
                These tools are designed for self-awareness and personal exploration only. They are not a substitute for professional mental health care, psychotherapy, psychiatry, or medical treatment. Do not use MySky as a replacement for professional support.
              </Text>
              <Text style={[styles.paragraph, { marginBottom: 0 }]}>
                {'If you are experiencing a mental health crisis or are in danger, please reach out immediately:\n\n'}{'• Crisis & Suicide Prevention (US): call or text 988\n'}{'• Crisis Text Line: text HOME to 741741\n'}{'• International resources: findahelpline.com\n'}{'• Emergency services: 911 (US) or your local number'}
              </Text>
            </LinearGradient>

            <Text style={styles.sectionTitle}>Intellectual Property</Text>
            <Text style={styles.paragraph}>
              You retain full ownership of your personal data, including journal entries, check-ins, sleep logs, and dream content. MySky owns the app code, design, generalized interpretations, symbolic pattern mappings, and all generated chart-based content.
            </Text>

            <Text style={styles.sectionTitle}>Data & Privacy</Text>
            <Text style={styles.paragraph}>
              All core data is stored locally on your device. Sensitive fields are encrypted with AES-256-GCM. No analytics SDKs, advertising identifiers, or cross-app tracking are used. Optional AI features may transmit limited data to third-party processors only when needed to fulfill that feature, as described in our Privacy Policy.
            </Text>

            <Text style={styles.sectionTitle}>Limitation of Liability</Text>
            <Text style={styles.paragraph}>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, MySky and its developer shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of data, loss of profits, personal injury, or emotional distress, arising out of or related to your use or inability to use the App, any Content provided by the App, or any decisions or choices made based on personalized reflective content, dream interpretations, astrological readings, or behavioral insights.
            </Text>
            <Text style={styles.paragraph}>
              IN NO EVENT SHALL OUR TOTAL AGGREGATE LIABILITY EXCEED THE AMOUNT YOU PAID FOR THE APP OR SUBSCRIPTION IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR FIFTY DOLLARS ($50 USD), WHICHEVER IS GREATER. Some jurisdictions do not allow the exclusion or limitation of certain damages. In such jurisdictions, our liability shall be limited to the maximum extent permitted by law.
            </Text>

            <Text style={styles.sectionTitle}>Disclaimer of Warranties</Text>
            <Text style={styles.paragraph}>
              THE APP IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
            </Text>
            <Text style={styles.paragraph}>
              WE DO NOT WARRANT THAT: (A) THE APP WILL MEET YOUR REQUIREMENTS; (B) THE APP WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE; (C) THE RESULTS OR CONTENT OBTAINED FROM USE OF THE APP WILL BE ACCURATE, RELIABLE, OR COMPLETE; OR (D) ANY ERRORS IN THE APP WILL BE CORRECTED.
            </Text>
            <Text style={styles.paragraph}>
              ALL ASTROLOGICAL INTERPRETATIONS, DREAM REFLECTIONS, AI DREAM INTERPRETATIONS, PATTERN ANALYSES, ARCHETYPE PROFILES, AND OTHER REFLECTIVE CONTENT ARE FOR SELF-AWARENESS AND PERSONAL EXPLORATION PURPOSES ONLY AND ARE PROVIDED WITHOUT ANY WARRANTY OF ACCURACY OR APPLICABILITY.
            </Text>

            <Text style={styles.sectionTitle}>Termination</Text>
            <Text style={styles.paragraph}>
              You may stop using MySky at any time by uninstalling the app. If you want a guaranteed local wipe of protected data, use the Hard Reset option in Privacy Settings before uninstalling. You may request deletion of your Supabase account by contacting support.
            </Text>

            <Text style={styles.sectionTitle}>Age Requirement</Text>
            <Text style={styles.paragraph}>
              MySky is intended for users aged 17 and older. By using the app, you confirm that you are at least 17 years of age. We do not knowingly collect personal information from anyone under 17.
            </Text>

            <Text style={styles.sectionTitle}>User Conduct</Text>
            <Text style={styles.paragraph}>
              You agree to use MySky only for its intended purpose of personal reflection and self-awareness. You agree not to reverse-engineer, decompile, disassemble, or attempt to derive the source code of the app, or use it to develop a competing product. You are solely responsible for maintaining the confidentiality of any backup passphrases and account credentials.
            </Text>

            <Text style={styles.sectionTitle}>Changes to These Terms</Text>
            <Text style={styles.paragraph}>
              We may update these Terms from time to time. When we make material changes, the "Last updated" date will be revised, and — where required — we will re-request your consent within the app. Continued use of MySky after changes constitutes acceptance of the revised Terms. We encourage you to review this page periodically.
            </Text>

            <Text style={styles.sectionTitle}>Indemnification</Text>
            <Text style={styles.paragraph}>
              You agree to indemnify and hold harmless MySky and its developer from any claims, damages, losses, or expenses arising from your use of the app, your violation of these Terms, or your violation of any third-party rights.
            </Text>

            <Text style={styles.sectionTitle}>Governing Law</Text>
            <Text style={styles.paragraph}>
              These Terms are governed by and construed in accordance with the laws of the United States, without regard to conflict of law principles. Any disputes shall be resolved in the courts of competent jurisdiction.
            </Text>

            <Text style={styles.sectionTitle}>Dispute Resolution & Arbitration</Text>
            <Text style={styles.paragraph}>
              Any dispute, claim, or controversy arising out of or relating to these Terms or the use of the App shall first be attempted to be resolved through good-faith informal negotiation. If the dispute is not resolved within thirty (30) days of written notice, either party may initiate binding arbitration. The arbitration shall be conducted in the English language, and the arbitrator's decision shall be final and binding.
            </Text>

            <Text style={styles.sectionTitle}>Class Action Waiver</Text>
            <Text style={styles.paragraph}>
              TO THE FULLEST EXTENT PERMITTED BY LAW, YOU AGREE THAT ANY DISPUTE RESOLUTION PROCEEDINGS WILL BE CONDUCTED ONLY ON AN INDIVIDUAL BASIS AND NOT IN A CLASS, CONSOLIDATED, OR REPRESENTATIVE ACTION. If this class action waiver is found to be unenforceable, then the entirety of the arbitration provision shall be null and void.
            </Text>

            <Text style={styles.sectionTitle}>Third-Party Services</Text>
            <Text style={styles.paragraph}>
              The App may integrate with or rely on third-party services, including but not limited to Apple App Store, Google Play, RevenueCat, Supabase, OpenStreetMap Nominatim, Sentry, Anthropic Claude, and Google Gemini. Your use of these third-party services is subject to their respective terms of service and privacy policies. We are not responsible for the practices or content of any third-party services.
            </Text>

            <Text style={styles.sectionTitle}>Apple App Store Terms</Text>
            <Text style={styles.paragraph}>
              If you downloaded the App through the Apple App Store, these Terms are between you and Brittany Apps only, and not with Apple. Brittany Apps, not Apple, is solely responsible for the App and its content. Apple has no obligation to furnish any maintenance and support services with respect to the App. Apple is not responsible for addressing any claims relating to the App, including product liability claims, regulatory compliance claims, and intellectual property infringement claims. You acknowledge that Apple and its subsidiaries are third-party beneficiaries of these Terms.
            </Text>

            <Text style={styles.sectionTitle}>Export Compliance</Text>
            <Text style={styles.paragraph}>
              You represent and warrant that you are not located in a country subject to a U.S. Government embargo or designated as a "terrorist supporting" country, and that you are not listed on any U.S. Government list of prohibited or restricted parties. You agree to comply with all applicable export and re-export control laws and regulations.
            </Text>

            <Text style={styles.sectionTitle}>Force Majeure</Text>
            <Text style={styles.paragraph}>
              We shall not be liable for any failure or delay in performing our obligations under these Terms where such failure or delay results from circumstances beyond our reasonable control, including but not limited to natural disasters, pandemics, acts of government, internet outages, power failures, or telecommunications failures.
            </Text>

            <Text style={styles.sectionTitle}>Assignment</Text>
            <Text style={styles.paragraph}>
              You may not assign, transfer, or sublicense any of your rights or obligations under these Terms without our prior written consent. We may assign our rights and obligations under these Terms without restriction. Any attempted assignment in violation of this section is void.
            </Text>

            <Text style={styles.sectionTitle}>Waiver</Text>
            <Text style={styles.paragraph}>
              The failure of either party to enforce any right or provision of these Terms shall not constitute a waiver of such right or provision. Any waiver of any provision of these Terms will be effective only if in writing and signed by the waiving party.
            </Text>

            <Text style={styles.sectionTitle}>Electronic Communications</Text>
            <Text style={styles.paragraph}>
              By using the App and/or creating an account, you consent to receiving electronic communications from us. You agree that any notices, agreements, disclosures, or other communications that we send to you electronically satisfy any legal communication requirements.
            </Text>

            <Text style={styles.sectionTitle}>Severability</Text>
            <Text style={styles.paragraph}>
              If any provision of these Terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary, and the remaining provisions shall remain in full force and effect.
            </Text>

            <Text style={styles.sectionTitle}>Entire Agreement</Text>
            <Text style={styles.paragraph}>
              These Terms, together with our Privacy Policy, constitute the entire agreement between you and MySky regarding the use of the app and supersede all prior agreements, representations, and understandings.
            </Text>

            <View style={styles.contactCard}>
              <Text style={styles.sectionTitle}>Contact</Text>
              <Text style={styles.paragraph}>Questions regarding these terms? Reach us at:</Text>
              <Text style={styles.email}>{SUPPORT_EMAIL}</Text>
            </View>

          </Animated.View>
        </ScrollView>
      </SafeAreaView>
    </View>
  );
}

const createStyles = (theme: AppTheme) => StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.background },
  safeArea: { flex: 1 },
  glowOrb: { position: 'absolute', width: 320, height: 320, borderRadius: 160, opacity: 0.6 },
  header: { flexDirection: 'row', alignItems: 'center', paddingTop: 8, paddingHorizontal: 24, paddingBottom: 8 },
  titleArea: { paddingHorizontal: 24, paddingBottom: 8 },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: theme.isDark ? 'rgba(255,255,255,0.05)' : theme.cardSurface,
    borderWidth: 1,
    borderColor: theme.cardBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: theme.textPrimary,
    letterSpacing: -1,
  },
  headerSubtitle: { marginBottom: 4 },
  scrollView: { flex: 1 },
  scrollContent: { paddingHorizontal: 24, paddingTop: 20, paddingBottom: 140 },
  heroIconWrap: {
    alignItems: 'center',
    marginBottom: 16,
    opacity: 0.95,
  },
  lastUpdated: { fontSize: 13, color: theme.textMuted, marginBottom: 24, textAlign: 'center' },
  
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: theme.textGold,
    marginTop: 24,
    marginBottom: 12,
  },
  subHeader: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.textPrimary,
    marginBottom: 12,
  },
  paragraph: {
    fontSize: 15,
    color: theme.textSecondary,
    lineHeight: 24,
    marginBottom: 12,
  },
  glassCard: {
    borderRadius: 24,
    padding: 28,
    backgroundColor: theme.isDark ? 'rgba(255,255,255,0.05)' : theme.cardSurface,
    borderWidth: 1,
    borderColor: theme.cardBorder,
    marginVertical: 16,
  },
  disclaimerCard: {
    borderRadius: 24,
    padding: 28,
    borderWidth: 1,
    borderColor: 'rgba(205,127,93,0.20)',
    backgroundColor: theme.isDark ? 'rgba(255,255,255,0.05)' : 'rgba(255, 245, 242, 0.9)',
    marginVertical: 16,
  },
  disclaimerHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
  highlight: { color: theme.textGold, fontWeight: '600' },
  boldText: { color: theme.textPrimary, fontWeight: '600' },
  bulletItem: { fontSize: 15, color: theme.textSecondary, lineHeight: 24, marginBottom: 8, paddingLeft: 4 },
  email: { color: theme.textGold, fontWeight: '700', fontSize: 16 },
  contactCard: { marginTop: 24, paddingBottom: 40 },
});
