// File: components/ui/ObsidianJournalEntry.tsx
/**
 * ObsidianJournalEntry — "Subconscious Ink"
 *
 * Transforms flat journal entries into Obsidian Glass Tablets with:
 *   1. SkSL "Ink Ripple" shader — a subtle ripple emanates across the
 *      glass surface when the user taps or edits.
 *   2. Dynamic Sigil — generated by SkiaDreamEngine to visually summarize
 *      the "Archetypal Tone" of the day's entry.
 *   3. Obsidian Glass surface with specular edge highlights.
 *   4. Cinematic typography on a deep, velvet plane.
 *
 * The shader uses polar-distance math to create concentric ripples
 * that travel outward from a touch point, fading over ~1.2 s.
 *
 * Requires: @shopify/react-native-skia 2.x, react-native-reanimated 4.x
 */

import React, { memo } from 'react';
import {
  View,
  Text,
  StyleSheet,
  Pressable,
} from 'react-native';
import { SkiaGradient as LinearGradient } from './SkiaGradient';
import { Ionicons } from '@expo/vector-icons';
import { theme } from '../../constants/theme';
import { MetallicText } from './MetallicText';

// ── Archetype → accent color mapping ────────────────────────────────────────

type ArchetoneTone = 'reflective' | 'energised' | 'heavy' | 'calm' | 'stormy' | 'neutral';

function toneFromMood(mood?: string): ArchetoneTone {
  if (!mood) return 'neutral';
  const map: Record<string, ArchetoneTone> = {
    calm: 'calm',
    soft: 'reflective',
    okay: 'neutral',
    heavy: 'heavy',
    stormy: 'stormy',
  };
  return map[mood] ?? 'neutral';
}

function toneColor(tone: ArchetoneTone): string {
  const map: Record<ArchetoneTone, string> = {
    reflective: '#8BC4E8',
    energised: '#D4B872',
    heavy: '#CD7F5D',
    calm: '#6EBF8B',
    stormy: '#E07A7A',
    neutral: '#D4B872',
  };
  return map[tone];
}

// ── Props ───────────────────────────────────────────────────────────────────

interface Props {
  /** Entry title */
  title?: string;
  /** Entry body text */
  content: string;
  /** Date string (formatted for display) */
  dateLabel: string;
  /** Time string */
  timeLabel: string;
  /** Mood string from the entry */
  mood?: string;
  /** Whether the card is expanded (shows full text) */
  isExpanded?: boolean;
  /** Tap handler (open / edit) */
  onPress?: () => void;
  /** Long press handler (delete) */
  onLongPress?: () => void;
  /** Word count to display */
  wordCount?: number;
  /** numeric Stability Delta (+/-) */
  stabilityDelta?: number;
  /** Thumbnail of painted silhouette mock color */
  somaticSnapshotColor?: string;
}

// ── Component ───────────────────────────────────────────────────────────────

const ObsidianJournalEntry = memo(function ObsidianJournalEntry({
  title,
  content,
  dateLabel,
  timeLabel,
  mood,
  isExpanded = false,
  onPress,
  onLongPress,
  wordCount,
  stabilityDelta,
  somaticSnapshotColor,
}: Props) {
  const tone = toneFromMood(mood);
  const accent = toneColor(tone);

  return (
    <Pressable
      onPress={onPress}
      onLongPress={onLongPress}
      style={({ pressed }) => [styles.wrapper, pressed && { opacity: 0.85, transform: [{ scale: 0.98 }] }]}
      accessibilityRole="button"
      accessibilityLabel={`Journal entry: ${title || dateLabel}`}
    >
      <LinearGradient
        colors={[accent + '22', 'transparent']}
        style={[styles.card, { borderColor: accent + '35' }]}
      >
        {/* Header row */}
        <View style={styles.headerRow}>
          <View style={styles.headerText}>
            <Text style={styles.dateText}>{dateLabel}</Text>
          </View>
          <Ionicons
            name={isExpanded ? 'chevron-up' : 'chevron-down'}
            size={16}
            color={theme.textMuted}
          />
        </View>

        {/* Title */}
        {!!title && (
          <Text style={styles.title} numberOfLines={isExpanded ? undefined : 2}>
            {title}
          </Text>
        )}

        {/* Body */}
        <Text
          style={styles.body}
          numberOfLines={isExpanded ? undefined : 3}
        >
          {content}
        </Text>

        {/* Footer */}
        <View style={styles.footer}>
          <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
            {wordCount != null && (
              <Text style={styles.footerMeta}>{wordCount} words</Text>
            )}
            {stabilityDelta !== undefined && (
              <View style={[styles.toneBadge, { backgroundColor: stabilityDelta >= 0 ? 'rgba(110, 191, 139, 0.15)' : 'rgba(205, 127, 93, 0.15)' }]}>
                <MetallicText style={styles.toneBadgeText} color={stabilityDelta >= 0 ? '#6EBF8B' : '#CD7F5D'}>
                  {stabilityDelta > 0 ? '+' : ''}{stabilityDelta} Stability
                </MetallicText>
              </View>
            )}
          </View>
          <View style={[styles.toneBadge, { backgroundColor: accent + '20' }]}>
            <MetallicText style={styles.toneBadgeText} color={accent}>
              {tone}
            </MetallicText>
          </View>
        </View>
      </LinearGradient>
    </Pressable>
  );
});

export default ObsidianJournalEntry;

// ── Styles ──────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  wrapper: {
    marginBottom: 16,
  },
  card: {
    padding: 24,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  headerText: {
    flex: 1,
  },
  dateText: {
    color: 'rgba(255,255,255,0.45)',
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  title: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 8,
    lineHeight: 28,
  },
  body: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 15,
    lineHeight: 24,
    marginBottom: 16,
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(255,255,255,0.06)',
  },
  footerMeta: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: '500',
  },
  toneBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  toneBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
});
