// File: components/ui/ObsidianJournalEntry.tsx
/**
 * ObsidianJournalEntry — "Subconscious Ink"
 *
 * Transforms flat journal entries into Obsidian Glass Tablets with:
 *   1. SkSL "Ink Ripple" shader — a subtle ripple emanates across the
 *      glass surface when the user taps or edits.
 *   2. Dynamic Sigil — generated by SkiaDreamEngine to visually summarize
 *      the "Archetypal Tone" of the day's entry.
 *   3. Obsidian Glass surface with specular edge highlights.
 *   4. Cinematic typography on a deep, velvet plane.
 *
 * The shader uses polar-distance math to create concentric ripples
 * that travel outward from a touch point, fading over ~1.2 s.
 *
 * Requires: @shopify/react-native-skia 2.x, react-native-reanimated 4.x
 */

import React, { memo } from 'react';
import {
  View,
  Text,
  StyleSheet,
  Pressable,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { type AppTheme } from '../../constants/theme';
import { MetallicText } from './MetallicText';
import { useAppTheme, useThemedStyles } from '../../context/ThemeContext';

// ── Archetype → accent color mapping ────────────────────────────────────────

type ArchetoneTone = 'reflective' | 'energised' | 'heavy' | 'calm' | 'stormy' | 'neutral';

function toneFromMood(mood?: string): ArchetoneTone {
  if (!mood) return 'neutral';
  const map: Record<string, ArchetoneTone> = {
    calm: 'calm',
    soft: 'reflective',
    okay: 'neutral',
    heavy: 'heavy',
    stormy: 'stormy',
  };
  return map[mood] ?? 'neutral';
}

const MOOD_DISPLAY_LABELS: Record<string, string> = {
  calm: 'Calm',
  soft: 'Soft',
  okay: 'Okay',
  heavy: 'Heavy',
  stormy: 'Stormy',
};

function toneColor(tone: ArchetoneTone): string {
  const map: Record<ArchetoneTone, string> = {
    reflective: '#C9AE78',
    energised: '#D4B872',
    heavy: '#CD7F5D',
    calm: '#6EBF8B',
    stormy: '#E07A7A',
    neutral: '#D4B872',
  };
  return map[tone];
}

function buildPreviewContent(title: string | undefined, content: string): string {
  const trimmedContent = content.trim();
  const trimmedTitle = title?.trim();
  if (!trimmedTitle) return trimmedContent;
  if (trimmedContent.toLowerCase().startsWith(trimmedTitle.toLowerCase())) {
    const stripped = trimmedContent.slice(trimmedTitle.length).replace(/^[:\-.–—\s]+/, '').trim();
    return stripped || trimmedContent;
  }
  return trimmedContent;
}

// ── Props ───────────────────────────────────────────────────────────────────

interface Props {
  /** Entry title */
  title?: string;
  /** Entry body text */
  content: string;
  /** Date string (formatted for display) */
  dateLabel: string;
  /** Time string */
  timeLabel: string;
  /** Mood string from the entry */
  mood?: string;
  /** Whether the card is expanded (shows full text) */
  isExpanded?: boolean;
  /** Expand/collapse handler */
  onToggleExpand?: () => void;
  /** Open entry actions */
  onOpenActions?: () => void;
  /** Word count to display */
  wordCount?: number;
  /** numeric Stability Delta (+/-) */
  stabilityDelta?: number;
  /** Thumbnail of painted silhouette mock color */
  somaticSnapshotColor?: string;
}

// ── Component ───────────────────────────────────────────────────────────────

const ObsidianJournalEntry = memo(function ObsidianJournalEntry({
  title,
  content,
  dateLabel,
  mood,
  isExpanded = false,
  onToggleExpand,
  onOpenActions,
  wordCount,
  stabilityDelta,
}: Props) {
  const theme = useAppTheme();
  const styles = useThemedStyles(createStyles);
  const tone = toneFromMood(mood);
  const accent = toneColor(tone);
  const previewContent = buildPreviewContent(title, content);

  return (
    <View style={styles.wrapper}>
      <LinearGradient
        colors={[accent + '14', 'rgba(10,10,12,0.9)']}
        style={[styles.card, { borderColor: 'rgba(255,255,255,0.08)' }]}
      >
        {/* Header row */}
        <View style={styles.headerRow}>
          <View style={styles.headerText}>
            <Text style={styles.dateText}>{dateLabel}</Text>
          </View>
          <Pressable
            onPress={onOpenActions}
            hitSlop={14}
            style={({ pressed }) => [styles.iconButton, pressed && styles.iconButtonPressed]}
            accessibilityRole="button"
            accessibilityLabel={`Actions for journal entry: ${title || dateLabel}`}
          >
            <Ionicons name="ellipsis-horizontal" size={16} color={theme.textMuted} />
          </Pressable>
        </View>

        {/* Title */}
        {!!title && (
          <Text style={styles.title} numberOfLines={isExpanded ? undefined : 2}>
            {title}
          </Text>
        )}

        {/* Body */}
        <Text
          style={styles.body}
          numberOfLines={isExpanded ? undefined : 3}
        >
          {previewContent}
        </Text>

        {/* Footer */}
        <View style={styles.footer}>
          <View style={styles.footerLeft}>
            {wordCount != null && (
              <Text style={styles.footerMeta}>{wordCount} words</Text>
            )}
            {stabilityDelta !== undefined && (
              <View style={[styles.toneBadge, { backgroundColor: stabilityDelta >= 0 ? 'rgba(110, 191, 139, 0.15)' : 'rgba(205, 127, 93, 0.15)' }]}>
                <MetallicText style={styles.toneBadgeText} color={stabilityDelta >= 0 ? '#6EBF8B' : '#CD7F5D'}>
                  {stabilityDelta > 0 ? '+' : ''}{stabilityDelta} Stability
                </MetallicText>
              </View>
            )}
            <Pressable
              onPress={onToggleExpand}
              hitSlop={8}
              pressRetentionOffset={12}
              style={({ pressed }) => [styles.expandButton, pressed && styles.expandButtonPressed]}
              accessibilityRole="button"
              accessibilityLabel={isExpanded ? 'Collapse journal entry' : 'Expand journal entry'}
            >
              <Text style={styles.expandHint}>{isExpanded ? 'Read less' : 'Read more'}</Text>
              <Ionicons
                name={isExpanded ? 'chevron-up' : 'chevron-down'}
                size={14}
                color="rgba(255,255,255,0.58)"
              />
            </Pressable>
          </View>
          <View style={styles.toneBadge}>
            <MetallicText style={styles.toneBadgeText} color={accent}>
              {mood ? (MOOD_DISPLAY_LABELS[mood] ?? mood) : tone}
            </MetallicText>
          </View>
        </View>
      </LinearGradient>
    </View>
  );
});

export default ObsidianJournalEntry;

// ── Styles ──────────────────────────────────────────────────────────────────

const createStyles = (theme: AppTheme) => StyleSheet.create({
  wrapper: {
    marginBottom: 16,
  },
  card: {
    padding: 28,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  headerText: {
    flex: 1,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconButtonPressed: {
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  dateText: {
    color: 'rgba(255,255,255,0.45)',
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  title: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 8,
    lineHeight: 28,
  },
  body: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 15,
    lineHeight: 24,
    marginBottom: 16,
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(255,255,255,0.06)',
  },
  footerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
    flex: 1,
    paddingRight: 12,
  },
  footerMeta: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: '500',
  },
  expandButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 2,
  },
  expandButtonPressed: {
    opacity: 0.72,
  },
  expandHint: {
    color: 'rgba(255,255,255,0.58)',
    fontSize: 12,
    fontWeight: '600',
  },
  toneBadge: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  toneBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
});
