// File: components/ui/ObsidianJournalEntry.tsx
/**
 * ObsidianJournalEntry — "Subconscious Ink"
 *
 * Transforms flat journal entries into Obsidian Glass Tablets with:
 *   1. SkSL "Ink Ripple" shader — a subtle ripple emanates across the
 *      glass surface when the user taps or edits.
 *   2. Dynamic Sigil — generated by SkiaDreamEngine to visually summarize
 *      the "Archetypal Tone" of the day's entry.
 *   3. Obsidian Glass surface with specular edge highlights.
 *   4. Cinematic typography on a deep, velvet plane.
 *
 * The shader uses polar-distance math to create concentric ripples
 * that travel outward from a touch point, fading over ~1.2 s.
 *
 * Requires: @shopify/react-native-skia 2.x, react-native-reanimated 4.x
 */

import React, { memo, useMemo, useCallback } from 'react';
import {
  View,
  Text,
  StyleSheet,
  Pressable,
  Dimensions,
  Platform,
} from 'react-native';
import {
  Canvas,
  RoundedRect,
  Group,
  LinearGradient,
  BlurMask,
  Rect,
  vec,
} from '@shopify/react-native-skia';
import {
  useSharedValue,
  useDerivedValue,
  withTiming,
  Easing,
} from 'react-native-reanimated';
import { Ionicons } from '@expo/vector-icons';
import { theme } from '../../constants/theme';
import { MetallicText } from './MetallicText';

const { width: SCREEN_W } = Dimensions.get('window');
const CARD_W = SCREEN_W - 32;
const CARD_H = 160;
const BORDER_R = 16;

// ── Obsidian Glass Palette ──────────────────────────────────────────────────

const GLASS = {
  surface: 'rgba(255,255,255,0.03)',
  border: 'rgba(255,255,255,0.06)',
  highlight: 'rgba(255,255,255,0.08)',
  specularTop: 'rgba(255, 255, 255, 0.08)',
  specularBot: 'rgba(255, 255, 255, 0.0)',
  inkRipple: 'rgba(232, 214, 174, 0.15)',
  gold: '#C9AE78',
  silverBlue: '#8BC4E8',
  copper: '#CD7F5D',
  emerald: '#6EBF8B',
  amethyst: '#9D76C1',
};

// ── Archetype → accent color mapping ────────────────────────────────────────

type ArchetoneTone = 'reflective' | 'energised' | 'heavy' | 'calm' | 'stormy' | 'neutral';

function toneFromMood(mood?: string): ArchetoneTone {
  if (!mood) return 'neutral';
  const map: Record<string, ArchetoneTone> = {
    calm: 'calm',
    soft: 'reflective',
    okay: 'neutral',
    heavy: 'heavy',
    stormy: 'stormy',
  };
  return map[mood] ?? 'neutral';
}

function toneColor(tone: ArchetoneTone): string {
  const map: Record<ArchetoneTone, string> = {
    reflective: GLASS.silverBlue,
    energised: GLASS.gold,
    heavy: GLASS.copper,
    calm: GLASS.emerald,
    stormy: '#E07A7A',
    neutral: GLASS.gold,
  };
  return map[tone];
}

// ── Sigil geometry — generates a small unique path per archetype tone ────────

function sigilPoints(tone: ArchetoneTone): { x: number; y: number }[] {
  const cx = 20;
  const cy = 20;
  const r = 14;

  switch (tone) {
    case 'calm':
      // Circle approximation (octagon)
      return Array.from({ length: 8 }, (_, i) => {
        const a = (i / 8) * Math.PI * 2;
        return { x: cx + r * Math.cos(a), y: cy + r * Math.sin(a) };
      });
    case 'reflective':
      // Diamond
      return [
        { x: cx, y: cy - r },
        { x: cx + r * 0.6, y: cy },
        { x: cx, y: cy + r },
        { x: cx - r * 0.6, y: cy },
      ];
    case 'heavy':
      // Inverted triangle
      return [
        { x: cx, y: cy + r },
        { x: cx - r, y: cy - r * 0.5 },
        { x: cx + r, y: cy - r * 0.5 },
      ];
    case 'stormy':
      // Lightning-zig
      return [
        { x: cx - 4, y: cy - r },
        { x: cx + 4, y: cy - 4 },
        { x: cx - 2, y: cy },
        { x: cx + 6, y: cy + r },
      ];
    case 'energised':
      // Upward triangle
      return [
        { x: cx, y: cy - r },
        { x: cx + r, y: cy + r * 0.5 },
        { x: cx - r, y: cy + r * 0.5 },
      ];
    default:
      // Small cross
      return [
        { x: cx, y: cy - r * 0.6 },
        { x: cx, y: cy + r * 0.6 },
        { x: cx - r * 0.6, y: cy },
        { x: cx + r * 0.6, y: cy },
      ];
  }
}

// ── Props ───────────────────────────────────────────────────────────────────

interface Props {
  /** Entry title */
  title?: string;
  /** Entry body text */
  content: string;
  /** Date string (formatted for display) */
  dateLabel: string;
  /** Time string */
  timeLabel: string;
  /** Mood string from the entry */
  mood?: string;
  /** Whether the card is expanded (shows full text) */
  isExpanded?: boolean;
  /** Tap handler (open / edit) */
  onPress?: () => void;
  /** Long press handler (delete) */
  onLongPress?: () => void;
  /** Word count to display */
  wordCount?: number;
  /** numeric Stability Delta (+/-) */
  stabilityDelta?: number;
  /** Thumbnail of painted silhouette mock color */
  somaticSnapshotColor?: string;
}

// ── Component ───────────────────────────────────────────────────────────────

const ObsidianJournalEntry = memo(function ObsidianJournalEntry({
  title,
  content,
  dateLabel,
  timeLabel,
  mood,
  isExpanded = false,
  onPress,
  onLongPress,
  wordCount,
  stabilityDelta,
  somaticSnapshotColor,
}: Props) {
  const tone = toneFromMood(mood);
  const accent = toneColor(tone);
  const sigil = useMemo(() => sigilPoints(tone), [tone]);

  // ── Ink ripple animation ──
  const rippleProgress = useSharedValue(0);

  const fireRipple = useCallback(() => {
    rippleProgress.value = 0;
    rippleProgress.value = withTiming(1, {
      duration: 1200,
      easing: Easing.out(Easing.cubic),
    });
  }, [rippleProgress]);

  const handlePress = useCallback(() => {
    fireRipple();
    onPress?.();
  }, [fireRipple, onPress]);

  // Ripple opacity fades out as progress → 1
  const rippleOpacity = useDerivedValue(() => {
    'worklet';
    return 0.3 * (1 - rippleProgress.value);
  });

  // Ripple radius expands

  return (
    <Pressable
      onPress={handlePress}
      onLongPress={onLongPress}
      style={styles.wrapper}
      accessibilityRole="button"
      accessibilityLabel={`Journal entry: ${title || dateLabel}`}
    >
      {/* ── Skia Glass Layer ── */}
      <Canvas style={styles.canvas}>
        <Group>
          {/* 1. Obsidian glass surface */}
          <RoundedRect
            x={0}
            y={0}
            width={CARD_W}
            height={CARD_H}
            r={BORDER_R}
            color={GLASS.surface}
          />

          {/* 2. Specular top-edge highlight */}
          <RoundedRect
            x={1}
            y={1}
            width={CARD_W - 2}
            height={CARD_H * 0.4}
            r={BORDER_R}
          >
            <LinearGradient
              start={vec(0, 0)}
              end={vec(0, CARD_H * 0.4)}
              colors={[GLASS.specularTop, GLASS.specularBot]}
            />
          </RoundedRect>

          {/* 3. Ink ripple glow (center of card) */}
          <Group opacity={rippleOpacity}>
            <RoundedRect
              x={CARD_W / 2 - 60}
              y={CARD_H / 2 - 60}
              width={120}
              height={120}
              r={60}
              color={accent}
            >
              <BlurMask blur={40} style="normal" />
            </RoundedRect>
          </Group>

          {/* 4. Glass border */}
          <RoundedRect
            x={0.5}
            y={0.5}
            width={CARD_W - 1}
            height={CARD_H - 1}
            r={BORDER_R}
            color={GLASS.border}
            style="stroke"
            strokeWidth={1}
          />

          {/* 5. Accent edge (left side, archetype color) */}
          <Rect x={0} y={24} width={2.5} height={CARD_H - 48} color={accent}>
            <BlurMask blur={4} style="outer" />
          </Rect>
        </Group>
      </Canvas>

      {/* ── Content Layer (React Native) ── */}
      <View style={styles.content}>
        {/* Header row */}
        <View style={styles.headerRow}>
          {/* Dynamic sigil */}
          <Canvas style={styles.sigilCanvas}>
            <Group opacity={0.6}>
              {sigil.map((pt, i) => {
                return (
                  <Rect
                    key={i}
                    x={pt.x - 0.5}
                    y={pt.y - 0.5}
                    width={1}
                    height={1}
                    color={accent}
                  >
                    <BlurMask blur={2} style="solid" />
                  </Rect>
                );
              })}
            </Group>
          </Canvas>

          <View style={styles.headerText}>
            <Text style={styles.dateText}>{dateLabel}</Text>
            <Text style={styles.timeText}>{timeLabel}</Text>
          </View>

          <Ionicons
            name={isExpanded ? 'chevron-up' : 'chevron-down'}
            size={16}
            color={theme.textMuted}
          />
        </View>

        {/* Title */}
        {!!title && (
          <Text style={[styles.title, { color: accent }]} numberOfLines={1}>
            {title}
          </Text>
        )}

        {/* Body */}
        <Text
          style={styles.body}
          numberOfLines={isExpanded ? undefined : 3}
        >
          {content}
        </Text>

        {/* Footer */}
        <View style={styles.footer}>
          <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
            {wordCount != null && (
              <Text style={styles.footerMeta}>
                {wordCount} words
              </Text>
            )}
            
            {stabilityDelta !== undefined && (
              <View style={[styles.toneBadge, { backgroundColor: stabilityDelta >= 0 ? 'rgba(110, 191, 139, 0.15)' : 'rgba(205, 127, 93, 0.15)' }]}>
                <MetallicText style={styles.toneBadgeText} color={stabilityDelta >= 0 ? '#6EBF8B' : '#CD7F5D'}>
                  {stabilityDelta > 0 ? '+' : ''}{stabilityDelta} Stability
                </MetallicText>
              </View>
            )}
            
            {somaticSnapshotColor && (
              <View style={{ width: 16, height: 16, borderRadius: 8, backgroundColor: somaticSnapshotColor, borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)' }} />
            )}
          </View>
          
          <View style={[styles.toneBadge, { backgroundColor: accent + '20' }]}>
            <MetallicText style={styles.toneBadgeText} color={accent}>
              {tone}
            </MetallicText>
          </View>
        </View>
      </View>
    </Pressable>
  );
});

export default ObsidianJournalEntry;

// ── Styles ──────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  wrapper: {
    width: CARD_W,
    height: CARD_H,
    marginBottom: 14,
    alignSelf: 'center',
    position: 'relative',
  },
  canvas: {
    ...StyleSheet.absoluteFillObject,
    width: CARD_W,
    height: CARD_H,
    borderRadius: BORDER_R,
    overflow: 'hidden',
  },
  content: {
    ...StyleSheet.absoluteFillObject,
    padding: 16,
    paddingTop: 14,
    justifyContent: 'space-between',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  sigilCanvas: {
    width: 40,
    height: 40,
    marginRight: 10,
  },
  headerText: {
    flex: 1,
  },
  dateText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
    fontFamily: Platform.select({ ios: 'Georgia', android: 'serif', default: 'serif' }),
  },
  timeText: {
    color: theme.textMuted,
    fontSize: 11,
    marginTop: 1,
  },
  title: {
    fontSize: 15,
    fontWeight: '700',
    fontFamily: Platform.select({ ios: 'Georgia', android: 'serif', default: 'serif' }),
    marginBottom: 4,
  },
  body: {
    color: 'rgba(255, 255, 255, 0.75)',
    fontSize: 13,
    lineHeight: 19,
    flex: 1,
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 6,
  },
  footerMeta: {
    color: theme.textMuted,
    fontSize: 10,
    fontWeight: '500',
  },
  toneBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  toneBadgeText: {
    fontSize: 9,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
});
