import type { DailyAngleArchetype } from './types';

export const DAILY_ANGLE_ARCHETYPES: DailyAngleArchetype[] = [
  {
    key: 'todays_active_signal',
    order: 1,
    title: "Today's Active Signal",
    description: 'Shows how a long-term pattern is active today.',
    formula: 'Today, this pattern seems active through [current signal].',
  },
  {
    key: 'same_pattern_new_shape',
    order: 2,
    title: 'Same Pattern, New Shape',
    description: 'Shows that an old pattern is changing form.',
    formula: 'This pattern is still present, but it is not showing up exactly the way it used to.',
  },
  {
    key: 'shame_to_clarity',
    order: 3,
    title: 'Shame to Clarity',
    description: "Directly reframes the user's self-judgment.",
    formula: 'This does not read as [shame label]. It reads as [clearer truth].',
  },
  {
    key: 'body_version',
    order: 4,
    title: 'Body Version',
    description: 'Connects the pattern to body cues.',
    formula: 'Your body may be naming this before your mind has words.',
  },
  {
    key: 'sleep_capacity_version',
    order: 5,
    title: 'Sleep + Capacity Version',
    description: 'Connects the pattern to sleep, energy, and recovery.',
    formula: 'This may feel heavier because your body has had less recovery.',
  },
  {
    key: 'relationship_version',
    order: 6,
    title: 'Relationship Version',
    description: 'Shows how the pattern appears in closeness, trust, repair, or support.',
    formula: 'This pattern becomes more visible where connection asks you to feel safe.',
  },
  {
    key: 'glimmer_version',
    order: 7,
    title: 'Glimmer Version',
    description: 'Shows where the pattern softened.',
    formula: 'A small moment of relief showed what helps this pattern loosen.',
  },
  {
    key: 'dream_version',
    order: 8,
    title: 'Dream Version',
    description: 'Connects the pattern to dream tone, symbols, or emotional residue.',
    formula: 'Your dream may be carrying the emotional shape of this pattern.',
  },
  {
    key: 'boundary_version',
    order: 9,
    title: 'Boundary Version',
    description: 'Shows where a clearer line may be needed.',
    formula: 'This pattern may be asking for a boundary before depletion makes one for you.',
  },
  {
    key: 'support_version',
    order: 10,
    title: 'Support Version',
    description: 'Shows how support could change the weight of the pattern.',
    formula: 'This may not need fixing as much as it needs to stop being carried alone.',
  },
  {
    key: 'values_version',
    order: 11,
    title: 'Values Version',
    description: 'Connects the pattern to values like honesty, safety, freedom, care, justice, or belonging.',
    formula: 'The emotional charge may be showing you what value is being touched.',
  },
  {
    key: 'growth_edge',
    order: 12,
    title: 'Growth Edge',
    description: 'Shows how the user is learning to meet the pattern differently.',
    formula: 'This pattern may be part of a current growth edge.',
  },
  {
    key: 'softening_pattern',
    order: 13,
    title: 'Softening Pattern',
    description: 'Shows that a pattern is still present but less powerful.',
    formula: 'This is still here, but it may be taking up less room than before.',
  },
  {
    key: 'intensifying_pattern',
    order: 14,
    title: 'Intensifying Pattern',
    description: 'Shows that a pattern is getting louder without making the user feel like they failed.',
    formula: 'This may be getting louder because the need underneath has not been fully met.',
  },
  {
    key: 'returning_pattern',
    order: 15,
    title: 'Returning Pattern',
    description: 'Shows that a theme has returned with a possible new layer.',
    formula: 'This pattern may be returning because something in it still wants clarity.',
  },
  {
    key: 'cross_source_match',
    order: 16,
    title: 'Cross-Source Match',
    description: 'Uses multiple data sources.',
    formula: 'Your check-ins, body cues, and journal tone are pointing in the same direction.',
  },
  {
    key: 'before_it_gets_louder',
    order: 17,
    title: 'Before It Gets Louder',
    description: 'Catches an early signal before it becomes overwhelming.',
    formula: 'This may be easier to meet now, while it is still speaking softly.',
  },
  {
    key: 'smallest_next_step',
    order: 18,
    title: 'Smallest Next Step',
    description: 'Gives one tiny, realistic action.',
    formula: 'This pattern may not need a dramatic response today.',
  },
  {
    key: 'question_to_keep',
    order: 19,
    title: 'Question to Keep',
    description: 'Gives a reflective question instead of a conclusion.',
    formula: 'Some patterns become clearer when carried as questions.',
  },
  {
    key: 'larger_monthly_thread',
    order: 20,
    title: 'Larger Monthly Thread',
    description: 'Connects the current pattern to a longer theme.',
    formula: "This may not be only today's mood. It may be part of a larger thread.",
  },
  {
    key: 'what_helped',
    order: 21,
    title: 'What Helped',
    description: 'Focuses on what softened, regulated, clarified, or supported the user.',
    formula: 'The important part is not only what hurt, but what helped you return.',
  },
  {
    key: 'what_drained_you',
    order: 22,
    title: 'What Drained You',
    description: 'Names what cost more energy than expected.',
    formula: 'This may show where energy is leaving faster than it is returning.',
  },
  {
    key: 'what_you_needed_but_did_not_ask_for',
    order: 23,
    title: 'What You Needed But Did Not Ask For',
    description: 'Names the unspoken need under the pattern.',
    formula: 'The need underneath may have been real even if it was never directly named.',
  },
  {
    key: 'what_you_kept_carrying',
    order: 24,
    title: 'What You Kept Carrying',
    description: 'Focuses on invisible emotional, practical, or relational load.',
    formula: 'This pattern may be less about one moment and more about what stayed with you afterward.',
  },
  {
    key: 'the_gentler_interpretation',
    order: 25,
    title: 'The Gentler Interpretation',
    description: "Offers a kinder explanation than the user's first self-judgment.",
    formula: 'There may be a more generous way to understand what happened inside you.',
  },
  {
    key: 'the_part_that_makes_sense',
    order: 26,
    title: 'The Part That Makes Sense',
    description: 'Validates why the pattern developed.',
    formula: 'There is a logic to this pattern, even if it is no longer the only option.',
  },
  {
    key: 'the_signal_beneath_the_emotion',
    order: 27,
    title: 'The Signal Beneath the Emotion',
    description: 'Finds the need, value, or boundary under the feeling.',
    formula: 'The emotion may be pointing toward something more specific.',
  },
  {
    key: 'the_pattern_beneath_the_pattern',
    order: 28,
    title: 'The Pattern Beneath the Pattern',
    description: 'Goes one layer deeper.',
    formula: 'This may not only be about [surface theme]. It may also be about [deeper need].',
  },
  {
    key: 'what_is_becoming_visible',
    order: 29,
    title: 'What Is Becoming Visible',
    description: 'For emerging patterns.',
    formula: 'Something that may have been hard to name is beginning to come into focus.',
  },
  {
    key: 'what_is_changing',
    order: 30,
    title: 'What Is Changing',
    description: 'For progress and movement.',
    formula: 'The pattern is still here, but your relationship to it may be changing.',
  },
  {
    key: 'the_earlier_signal',
    order: 31,
    title: 'The Earlier Signal',
    description: 'Names what showed up before the main emotional reaction.',
    formula: 'Before this became a feeling, it may have appeared as [body cue / sleep shift / tension / thought pattern].',
  },
  {
    key: 'the_after_effect',
    order: 32,
    title: 'The After-Effect',
    description: 'Focuses on what lingered after an event, interaction, or dream.',
    formula: 'The pattern may be visible in what stayed with you afterward.',
  },
  {
    key: 'the_unnamed_need',
    order: 33,
    title: 'The Unnamed Need',
    description: 'Names a need the user may have been circling without directly saying.',
    formula: 'The deeper need may be [support / rest / clarity / repair / space / reassurance].',
  },
  {
    key: 'the_protective_strategy',
    order: 34,
    title: 'The Protective Strategy',
    description: 'Frames the behavior as a strategy that once made sense.',
    formula: 'This may have been a way of staying safe, steady, connected, or prepared.',
  },
  {
    key: 'the_cost_of_the_strategy',
    order: 35,
    title: 'The Cost of the Strategy',
    description: 'Shows that a protective pattern also has a cost.',
    formula: 'This strategy may help in one way while costing you in another.',
  },
  {
    key: 'the_alternative_interpretation',
    order: 36,
    title: 'The Alternative Interpretation',
    description: 'Offers a second read on the same data.',
    formula: 'Another way to understand this is not [shame story], but [clearer pattern].',
  },
  {
    key: 'the_repeated_context',
    order: 37,
    title: 'The Repeated Context',
    description: 'Names the situation where the pattern most often appears.',
    formula: 'This pattern tends to appear around [life area / relationship type / time of day / body state].',
  },
  {
    key: 'the_exception',
    order: 38,
    title: 'The Exception',
    description: 'Notices when the pattern did not happen or was less intense.',
    formula: 'The exception matters because it shows what helps the pattern loosen.',
  },
  {
    key: 'the_evidence_line',
    order: 39,
    title: 'The Evidence Line',
    description: 'Uses one small phrase, cue, or data point as the anchor.',
    formula: 'The phrase/cue "[anchor]" seems important because it points toward [pattern].',
  },
  {
    key: 'the_two_truths',
    order: 40,
    title: 'The Two Truths',
    description: 'Validates mixed or conflicting feelings.',
    formula: 'Two things may be true at once: [truth one] and [truth two].',
  },
  {
    key: 'the_threshold',
    order: 41,
    title: 'The Threshold',
    description: 'Shows where the pattern crosses from manageable to too much.',
    formula: 'This pattern may become harder to hold once [threshold] is crossed.',
  },
  {
    key: 'the_current_season',
    order: 42,
    title: 'The Current Season',
    description: 'Frames the insight as part of a season, not a permanent identity.',
    formula: 'This may be the season where [theme] is asking for more attention.',
  },
  {
    key: 'the_old_rule',
    order: 43,
    title: 'The Old Rule',
    description: 'Names an old internal rule that may be operating.',
    formula: 'An old rule may be saying, "[rule]," even though today may need something different.',
  },
  {
    key: 'the_new_permission',
    order: 44,
    title: 'The New Permission',
    description: 'Offers a permission statement based on the pattern.',
    formula: 'A newer permission might be: [permission].',
  },
  {
    key: 'the_what_if',
    order: 45,
    title: 'The What If',
    description: 'Gently opens a new possibility.',
    formula: 'What if this is less about [shame story] and more about [clearer need]?',
  },
  {
    key: 'the_difference_between',
    order: 46,
    title: 'The Difference Between',
    description: 'Clarifies two things the user may be confusing.',
    formula: 'There may be a difference between [thing A] and [thing B].',
  },
  {
    key: 'the_reframe_of_desire',
    order: 47,
    title: 'The Reframe of Desire',
    description: 'Validates wanting, longing, ambition, support, rest, love, space, or clarity.',
    formula: 'Wanting this does not make you [shame label]. It may show what matters.',
  },
  {
    key: 'the_recovery_clue',
    order: 48,
    title: 'The Recovery Clue',
    description: 'Names what helped the user return after stress.',
    formula: 'Your archive may be showing that [specific support] helps you come back.',
  },
  {
    key: 'the_patterns_request',
    order: 49,
    title: "The Pattern's Request",
    description: 'Personifies the pattern gently by naming what it is asking for.',
    formula: 'This pattern may be asking for [rest / clarity / support / repair / expression / space].',
  },
  {
    key: 'the_archive_mirror',
    order: 50,
    title: 'The Archive Mirror',
    description: 'Zooms out and shows what the archive is reflecting back.',
    formula: 'Your archive is not reducing you to this pattern. It is showing one place where your inner world has been asking to be understood.',
  },
];
