import type { PersonaProfileCopy } from './types';

export const PERSONA_PROFILES: PersonaProfileCopy[] = [
  {
    key: 'overResponsibleStabilizer',
    personNumber: 1,
    title: 'The Over-Responsible Stabilizer',
    category: 'responsibilityCare',
    secondaryCategories: ['restCapacity', 'bodySignals', 'selfWorthReceiving'],
    triggerSignals: [
      'responsibility_weight',
      'mental_load',
      'caretaking_pressure',
      'overfunctioning',
      'always_on',
      'preparedness',
    ],
    supportingSignals: [
      'invisible_labor',
      'high_standards',
      'rest_resistance',
      'recovery_gap',
      'depletion',
      'support_need',
      'capacity_strain',
    ],
    intro: [
      `This person feels safest when things are handled, clear, and emotionally contained. They often become the capable one before they realize they’re doing it.`,
    ],
    sentences: [
      `When things feel uncertain, you seem to look for the part you can control. That may help you feel less helpless, but it can also make you responsible for calming situations that were never fully yours to manage.`,
      `You may notice problems early because part of you is always scanning for what could go wrong. That awareness can be useful, but it also means your body may stay on alert even when nothing has happened yet.`,
      `You seem to move quickly from feeling something to doing something about it. Action gives the feeling somewhere to go, but it may also keep you from realizing how much the situation affected you.`,
      `When people around you are upset, you may start organizing yourself around their emotional state. You might become calmer, more useful, or more careful — not because you are unaffected, but because someone has to stay steady.`,
      `You may have a hard time trusting that things will be okay if you step back. Rest can feel risky when your mind is still tracking what needs to be fixed, watched, or prevented.`,
      `When something matters, you may hold it with your whole attention. That kind of care can be beautiful, but it can also become exhausting when every important thing starts to feel urgent.`,
      `You may feel most like yourself when you are helping, solving, or keeping things together. The harder question is whether you still feel allowed to matter when you are not being useful.`,
      `You seem to recover better when the responsibility is clearly not yours anymore. Until then, part of you may keep checking whether there is one more thing you should do.`,
      `You may mistake relief for resolution. A situation can feel better once you have handled the immediate problem, but your body may still need time to catch up with what it went through.`,
      `Your strength may show up as steadiness under pressure, but that does not mean pressure is harmless to you. You can be good at carrying something and still deserve to put it down.`,
    ],
  },
  {
    key: 'deepProcessor',
    personNumber: 2,
    title: 'The Deep Processor',
    category: 'cognitiveStyle',
    secondaryCategories: ['emotionalWeather', 'bodySignals', 'dreamsSymbols'],
    triggerSignals: [
      'deep_processing',
      'meaning_making',
      'clarity_before_release',
      'asks_why',
      'pattern_recognition',
      'analysis_as_regulation',
    ],
    supportingSignals: [
      'need_for_exact_words',
      'seeks_context',
      'intellectualizes_feeling',
      'integrates_insight',
      'emotional_heaviness',
      'dream_unfinished_processing',
    ],
    intro: [
      `This person doesn’t just “feel and move on.”`,
      `They stay with things until they understand them. Meaning matters more than speed.`,
    ],
    sentences: [
      `When something affects you, it doesn’t pass quickly. You tend to stay with it until it makes sense, even if that takes longer than you wish.`,
      `You don’t seem to like leaving things half-understood. Even when you step away, part of your mind keeps working on it in the background, trying to piece it together.`,
      `When something is unclear, it can feel harder to let it go. It’s not just about the situation — it’s about not having a way to make sense of it yet.`,
      `You may find yourself replaying moments, not because you want to stay stuck, but because you’re still trying to understand what actually happened.`,
      `When something hurts, you don’t seem to push it aside quickly. You tend to stay close to it until it either softens or becomes clearer.`,
      `You may not trust quick answers, even when they would feel easier. You tend to look for something that actually feels true, not just something that sounds right.`,
      `Your mind seems to keep working on things even after the moment is over. Insight doesn’t always come right away — sometimes it shows up later, once things have had time to settle.`,
      `You may notice that understanding something doesn’t always make it feel better right away. Clarity can come before relief.`,
      `When something doesn’t add up, it can stay with you longer than expected. It’s not just the feeling — it’s the lack of resolution that keeps it active.`,
      `You don’t seem to move on just because time has passed. You move on when something finally feels processed, even if that takes longer than others expect.`,
    ],
  },
  {
    key: 'relationalTracker',
    personNumber: 3,
    title: 'The Relational Tracker',
    category: 'relationships',
    secondaryCategories: ['supportBelonging', 'bodySignals', 'safetyRegulation'],
    triggerSignals: [
      'tone_sensitivity',
      'consistency_need',
      'relationship_safety_testing',
      'repair_need',
      'rupture_sensitivity',
      'emotional_availability_need',
    ],
    supportingSignals: [
      'closeness_uncertainty',
      'trust_builds_slowly',
      'selective_vulnerability',
      'wants_to_be_seen',
      'chest_pressure',
      'gut_signal',
    ],
    intro: [
      `This person notices shifts in people quickly. Tone, distance, warmth, silence, inconsistency, and repair all matter. They don’t just experience relationships — they track whether connection still feels safe.`,
    ],
    sentences: [
      `You may notice small changes in someone’s tone before anything is said directly. That can help you understand what is happening, but it can also keep you on alert when the other person may not even realize they shifted.`,
      `When connection feels unclear, your mind may start filling in the blanks. You’re not trying to overreact — you’re trying to understand whether the relationship still feels safe.`,
      `You may relax quickly when someone is steady with you. The steadiness matters because it lets your body stop guessing what is coming next.`,
      `Silence may not feel neutral to you. If there is no explanation, part of you may start reading the space between messages, expressions, or pauses.`,
      `When someone pulls away, even subtly, you may feel the shift before you can explain it. The hard part is that your body may respond before you know whether there is actually danger.`,
      `You may need repair to be clear, not vague. A casual “it’s fine” might not settle you if your body can still feel the rupture underneath it.`,
      `You may become more careful when you sense tension. You might soften your words, explain more, or watch closely for how the other person responds.`,
      `When connection feels safe, you may feel more like yourself. You don’t have to track as much, so there is more room to rest, play, think, or simply be.`,
      `You may struggle most with relationships that feel warm one moment and distant the next. The inconsistency can be more activating than distance itself.`,
      `You are not only asking whether someone cares. You may be asking whether their care is steady enough for your body to trust.`,
    ],
  },
  {
    key: 'quietWithdrawer',
    personNumber: 4,
    title: 'The Quiet Withdrawer',
    category: 'safetyRegulation',
    secondaryCategories: ['relationships', 'bodySignals', 'boundariesSelfTrust'],
    triggerSignals: [
      'distance_for_safety',
      'selective_vulnerability',
      'needs_pause',
      'peace_boundary',
      'body_heaviness',
      'calm_bracing',
    ],
    supportingSignals: [
      'numbness_vs_calm',
      'autonomy_need',
      'emotional_heaviness',
      'low_energy',
      'throat_tightness',
      'quiet_safety',
    ],
    intro: [
      `This person doesn’t always show distress outwardly. When things feel too much, they may get quieter, smaller, harder to reach, or more self-contained.`,
    ],
    sentences: [
      `When something hurts, you may not reach for people right away. Part of you may get quiet first, as if you need to understand what you’re feeling before anyone else comes close.`,
      `You might look calm on the outside while a lot is happening underneath. People may miss how much you’re carrying because your distress does not always announce itself loudly.`,
      `When things feel overwhelming, you may create distance without fully meaning to. Space can help you feel safer, but it can also make it harder for others to know you need care.`,
      `You may need time alone before you know what you want to say. It is not always avoidance — sometimes your words need quiet before they become clear.`,
      `When someone pushes for closeness too quickly, you may pull back more. Pressure can make connection feel like another demand instead of support.`,
      `You may be more likely to disappear emotionally than to argue. That does not mean you do not care. It may mean your system is trying to reduce the amount of stimulation coming in.`,
      `You might wait until a feeling is “manageable” before sharing it. The risk is that by the time others hear about it, you have already been alone with it for a long time.`,
      `When you withdraw, it may be your way of protecting the relationship from the intensity of what you feel. But holding everything privately can leave you without the support you actually need.`,
      `You may find it easier to say “I’m fine” than to explain something complicated. The answer may not be dishonest — it may just be the only sentence available in the moment.`,
      `Your quiet does not mean nothing is happening. Sometimes it means too much is happening, and your system is trying to lower the volume enough to breathe.`,
    ],
  },
  {
    key: 'workAmbition',
    personNumber: 6,
    title: 'Work & Ambition',
    focus: '(achievement, career pressure, standards, productivity, burnout)',
    category: 'workAmbition',
    secondaryCategories: ['responsibilityCare', 'restCapacity', 'valuesIntegrity'],
    triggerSignals: [
      'excellence_pressure',
      'high_standards',
      'overextension',
      'always_on',
      'burnout_risk',
      'responsibility_weight',
    ],
    supportingSignals: [
      'wants_to_build',
      'creative_standards',
      'vision_gap',
      'preparedness',
      'capacity_strain',
      'self_blame',
      'rest_resistance',
      'energy_scarcity',
      'purpose_signal',
      'future_self_orientation',
    ],
    intro: [
      `This person cares deeply about doing well. They may set high standards, push through tiredness, and measure safety through progress, competence, or being “on top of things.”`,
    ],
    sentences: [
      `You may feel calmer when you know you’re making progress. Even small movement can help you feel less stuck, but it can also make rest feel uncomfortable when nothing is getting done.`,
      `Your standards may rise faster than your capacity. What once felt like “enough” can start becoming the new minimum, which makes it hard to feel satisfied for long.`,
      `When you care about something, you may put pressure on yourself to do it well. That care can create beautiful work, but it can also make mistakes feel heavier than they need to.`,
      `Productivity may feel like proof that you’re okay. When you’re getting things done, it can be easier to believe you’re handling life — even if your body is still tired.`,
      `You may struggle to stop when there is still more you could improve. The finish line can keep moving, especially when your mind sees every possible detail.`,
      `When things are uncertain, working harder may feel like the safest option. Effort gives you something to hold onto, even when the outcome is not fully in your control.`,
      `You may be good at functioning under pressure, but that does not mean pressure is harmless to you. Sometimes being capable hides how much strain you’re actually under.`,
      `You may judge your day by what you completed, even when the harder work was emotional. Not every important effort leaves visible evidence.`,
      `Burnout may not arrive as one big collapse for you. It may show up slowly — less patience, less joy, more heaviness, and a growing sense that everything takes too much.`,
      `You may need permission to value the work that happens beneath the surface. Thinking, recovering, deciding, learning, and becoming clearer all count, even when they don’t look productive.`,
    ],
  },
  {
    key: 'emotionalWeather',
    personNumber: 7,
    title: 'Emotional Weather',
    focus: '(changing moods, sensitivity, internal shifts, not always tied to clear events)',
    category: 'emotionalWeather',
    secondaryCategories: ['bodySignals', 'restCapacity', 'cognitiveStyle'],
    triggerSignals: [
      'mood_drop',
      'low_mood',
      'mixed_emotions',
      'emotional_intensity',
      'emotional_heaviness',
      'sadness',
    ],
    supportingSignals: [
      'anger',
      'hope',
      'relief',
      'low_energy',
      'poor_sleep_quality',
      'high_stress',
      'glimmer_softening',
      'quiet_safety',
    ],
    intro: [
      `This person experiences emotions like weather systems — sometimes predictable, sometimes not, sometimes changing faster than expected.`,
    ],
    sentences: [
      `Your mood doesn’t always seem tied to one clear cause. It can shift even when nothing obvious has happened, which can make it hard to explain — even to yourself.`,
      `You may notice that how you feel can change within the same day. It’s not that your emotions aren’t real — it’s that they don’t always stay in one place for long.`,
      `Some feelings seem to pass through you quickly, while others linger without a clear reason. The difference isn’t always logical, which can make it harder to predict what will stick.`,
      `You might find yourself trying to “figure out” a feeling that doesn’t have a simple explanation. Not everything you feel is a problem to solve, even if your mind wants it to be.`,
      `There are moments where your mood shifts and you only realize it after the fact. The change happens first, and the awareness comes later.`,
      `You may sometimes question your own emotional consistency — wondering why something affected you more (or less) than it did before.`,
      `Your emotional state can be influenced by small things that others might overlook — tone, environment, timing, even how rested you are.`,
      `Some days feel heavier without a clear story behind them. That doesn’t mean you missed something — sometimes the feeling comes before the explanation.`,
      `You might notice that certain moods pass more easily when you don’t try to control them. The harder you try to pin them down, the longer they seem to stay.`,
      `Your emotional range may be wider than you expect. You’re not always in one consistent state — you move through different ones, sometimes more fluidly than you realize.`,
    ],
  },
  {
    key: 'restCapacity',
    personNumber: 8,
    title: 'Rest Capacity',
    focus: '(fatigue, pauses, recovery, sleep, permission to stop, how available rest feels)',
    category: 'restCapacity',
    secondaryCategories: ['bodySignals', 'responsibilityCare', 'selfWorthReceiving'],
    triggerSignals: [
      'rest_resistance',
      'rest_guilt',
      'recovery_gap',
      'depletion',
      'needs_pause',
      'low_sleep',
    ],
    supportingSignals: [
      'poor_sleep_quality',
      'burnout_risk',
      'low_capacity',
      'low_energy',
      'overextension',
      'responsibility_weight',
      'body_heaviness',
    ],
    intro: [
      `This person may want rest, but not always know how to actually receive it. Pausing can bring relief, guilt, boredom, anxiety, or a sudden awareness of everything they have been holding.`,
    ],
    sentences: [
      `Rest may not feel simple for you. Even when your body is tired, your mind may keep scanning for what still needs to be done, decided, answered, or prepared.`,
      `You may notice that stopping makes feelings louder at first. When the noise of doing gets quiet, what you’ve been carrying has more room to surface.`,
      `Sleep may be physically necessary but emotionally complicated. Your body may need it, while another part of you resists the vulnerability of fully letting go.`,
      `You may recover better from rest that feels chosen, not forced. When rest happens only because you’ve hit a wall, it can feel more like collapse than care.`,
      `Your tiredness may show up before you admit you’re tired. It might appear as impatience, fogginess, heaviness, sensitivity, or a sudden drop in your ability to handle small things.`,
      `You may struggle with the empty space that rest creates. Quiet can be calming, but it can also leave you alone with thoughts you were too busy to feel.`,
      `Your body may ask for rest long before your mind gives permission. The delay between needing rest and allowing it may be part of what makes recovery harder.`,
      `You may feel more comfortable earning rest than receiving it freely. If stopping only feels allowed after enough effort, rest becomes something you prove instead of something you need.`,
      `There may be a difference between being still and actually resting. Your body can be sitting down while your mind is still working, tracking, planning, or bracing.`,
      `Rest may become easier when it has structure. A defined pause, a clear stopping point, or a small ritual may help your body understand that nothing has to be handled for a moment.`,
    ],
  },
  {
    key: 'bodySignals',
    personNumber: 9,
    title: 'Body Signals',
    focus: '(somatic cues, physical sensations, how the body communicates before/alongside thoughts)',
    category: 'bodySignals',
    secondaryCategories: ['safetyRegulation', 'emotionalWeather', 'restCapacity'],
    triggerSignals: [
      'body_knows_first',
      'chest_pressure',
      'shoulder_burden',
      'gut_signal',
      'body_heaviness',
      'somatic_safety',
    ],
    supportingSignals: [
      'tension_release',
      'breath_change',
      'throat_tightness',
      'head_pressure',
      'jaw_restraint',
      'sensory_sensitivity',
      'body_lightness',
    ],
    intro: [
      `This person’s body gives early, specific signals. Sensations often show up before clear thoughts or words.`,
    ],
    sentences: [
      `When something is off, your body tends to signal it early. The feeling shows up physically before you can fully explain what’s wrong.`,
      `You may notice that certain emotions have consistent physical locations — tightness in the chest, heaviness in the shoulders, a knot in the stomach. The pattern is repeatable, even if the situation changes.`,
      `Sometimes your body reacts faster than your understanding. You might feel tense or uneasy before you can point to a clear reason.`,
      `You may recognize stress more easily through sensation than through thought. It’s not always “I’m stressed” — it’s “something doesn’t feel right in my body.”`,
      `Your body may hold onto things longer than your mind does. Even after something is resolved, the physical feeling can take more time to release.`,
      `You might notice a difference between mental agreement and physical agreement. You can tell yourself something is okay, but your body may not fully settle right away.`,
      `Certain environments or people may shift your body state quickly, even if nothing obvious is happening. The change can be subtle but consistent.`,
      `You may find that naming the sensation helps more than analyzing it. Simply noticing “tight,” “heavy,” or “restless” can create more movement than trying to explain it.`,
      `Your body may give you signals in layers — first tension, then fatigue, then overwhelm if nothing changes. The early signals are quieter but easier to work with.`,
      `When your body feels settled, it changes everything. The same situation can feel completely different depending on whether your body is tense or at ease.`,
    ],
  },
  {
    key: 'selfWorthReceiving',
    personNumber: 10,
    title: 'Self-Worth & Receiving',
    focus: '(enoughness, being valued without proving, receiving care, asking for help)',
    category: 'selfWorthReceiving',
    secondaryCategories: ['supportBelonging', 'responsibilityCare', 'restCapacity'],
    triggerSignals: [
      'receiving_care_difficulty',
      'receiving_openness',
      'enoughness',
      'asks_for_support',
      'minimizes_need',
      'support_need',
    ],
    supportingSignals: [
      'fear_of_being_too_much',
      'wants_to_be_seen',
      'support_abundance_shift',
      'inner_critic_softening',
      'self_forgiveness',
      'high_standards',
      'overfunctioning',
    ],
    intro: [
      `This person is often comfortable giving, contributing, showing up — but receiving without earning it can feel unfamiliar, exposed, or slightly undeserved.`,
    ],
    sentences: [
      `You may find it easier to give than to receive. Offering support can feel natural, but being on the receiving end may come with a quiet question of whether you’ve done enough to deserve it.`,
      `When someone shows up for you, you might feel a pull to balance it quickly. Not out of obligation exactly, but out of a sense that things should feel even.`,
      `You may not always notice when you minimize your own needs. It’s not that they aren’t there — they just don’t always take priority in the same way other people’s do.`,
      `Receiving care may feel more comfortable when you can point to a clear reason for it. When it’s given freely, without explanation, it may feel harder to fully take in.`,
      `You might feel most confident in your place with others when you are contributing something — support, clarity, effort, presence. Without that, your role can feel less defined.`,
      `When someone appreciates you, you may accept it intellectually but not fully feel it. The words land, but they don’t always settle.`,
      `You may hesitate to ask for help until you’re sure it’s justified. Even then, it might feel easier to figure it out on your own than to risk needing something.`,
      `There may be a difference between knowing you matter and feeling like you matter. The understanding can be there, while the feeling takes longer to catch up.`,
      `You might notice that you show up fully for others, even when you’re not fully resourced yourself. Care moves outward easily, but inward movement can take more effort.`,
      `Being valued for who you are — not just what you do — may still be something your system is learning how to trust.`,
    ],
  },
];

export const PERSONA_PROFILE_BY_KEY = Object.fromEntries(
  PERSONA_PROFILES.map(profile => [profile.key, profile]),
) as Record<PersonaProfileCopy['key'], PersonaProfileCopy>;
