import type { SignalKey, SignalRole, SignalSentiment } from './types';

const FEELING_STATE_SIGNALS = new Set<SignalKey>([
  'anger',
  'conflicted',
  'contentment',
  'confusion',
  'calm',
  'curiosity',
  'despair',
  'desire',
  'disconnected',
  'disgust',
  'emotional_heaviness',
  'emotional_intensity',
  'emotional_softening',
  'energized',
  'fear',
  'gratitude',
  'grief',
  'grief_returns',
  'guilt',
  'grounded',
  'helplessness',
  'hidden_emotional_variability',
  'hope',
  'hurt',
  'indifferent',
  'inspired',
  'internal_feeling_external_function',
  'joy',
  'loneliness',
  'longing',
  'low_mood',
  'mistrust',
  'mixed_emotions',
  'mood_drop',
  'mood_improvement',
  'numbness',
  'ongoing_high_distress',
  'overwhelm',
  'peace',
  'powerlessness',
  'quiet_emotional_change',
  'relief',
  'sadness',
  'scattered_attention',
  'self_doubt',
  'sensory_overload',
  'shame',
  'shutdown',
  'steady_not_unaffected',
  'steady_not_unaffected_inner',
  'stuck',
  'trapped',
  'trust',
  'unseen_deep_landing',
  'unsafe',
  'vulnerability',
]);

const NEGATIVE_FEELING_SIGNALS = new Set<SignalKey>([
  'anger',
  'avoidance',
  'confusion',
  'despair',
  'disconnected',
  'disgust',
  'emotional_heaviness',
  'fear',
  'grief',
  'grief_returns',
  'guilt',
  'helplessness',
  'hurt',
  'loneliness',
  'low_mood',
  'mistrust',
  'mood_drop',
  'numbness',
  'ongoing_high_distress',
  'overwhelm',
  'powerlessness',
  'sadness',
  'scattered_attention',
  'self_doubt',
  'sensory_overload',
  'shame',
  'shutdown',
  'self_blame',
  'stuck',
  'trapped',
  'unseen_deep_landing',
  'unsafe',
]);

const POSITIVE_FEELING_SIGNALS = new Set<SignalKey>([
  'calm',
  'curiosity',
  'desire',
  'emotional_softening',
  'contentment',
  'energized',
  'confidence',
  'gratitude',
  'grounded',
  'hope',
  'inspired',
  'joy',
  'mood_improvement',
  'peace',
  'relief',
  'safe',
  'trust',
]);

const RECOVERY_LEVER_SIGNALS = new Set<SignalKey>([
  'baseline_recovery',
  'body_lightness',
  'body_mind_rest',
  'bounded_rest_return',
  'care_before_owed',
  'care_strengthens_not_takes_over',
  'collaborative_not_rescuing',
  'connection_glimmer',
  'easy_rest',
  'familiar_calm',
  'glimmer_softening',
  'ordinary_downtime',
  'quiet_safety',
  'receiving_openness',
  'rest_as_care',
  'rest_without_guilt',
  'restorative_moment',
  'restorative_pause',
  'small_relief_signals_change',
  'spontaneous_play',
  'structured_pleasure',
  'support_abundance_shift',
  'support_without_dependence',
  'unbraced_stillness',
]);

const BODY_SIGNAL_SIGNALS = new Set<SignalKey>([
  'adult_body_old_position',
  'analysis_pulls_from_signal',
  'beauty_regulation',
  'body_aliveness_cues',
  'body_final_signal',
  'body_heaviness',
  'body_info_mind_organizes',
  'body_knows_first',
  'body_lightness',
  'body_mind_rest',
  'body_notices_distance_hidden',
  'body_rest_before_responsibility',
  'body_signal_interpretation',
  'body_says_mind_asks_why',
  'body_vote_when_mind_sure',
  'breath_change',
  'calm_outside_tracking_inside',
  'chest_pressure',
  'delayed_body_awareness',
  'fine_until_body_says_otherwise',
  'functioning_over_settled',
  'gut_signal',
  'head_pressure',
  'intentional_body_checkin',
  'interpretation_crowds_awareness',
  'jaw_restraint',
  'late_stress_signals',
  'later_sensation_matters',
  'logic_accurate_incomplete',
  'logic_over_sensation',
  'logical_before_physical',
  'mental_first_body_agrees',
  'mind_quick_body_slow',
  'old_expectations_body_pressure',
  'physical_pause_mind_moving',
  'practical_but_wrong_body_resist',
  'reasoning_and_body_settle',
  'same_capacity_expectation',
  'sensation_before_explanation',
  'sensation_first_mind_interprets',
  'sensation_problem_solving',
  'sensation_reason_search',
  'sensory_overload',
  'sensory_sensitivity',
  'shoulder_burden',
  'somatic_safety',
  'tension_release',
  'thought_first_processing',
  'thoughts_lead_body_confirms',
  'throat_tightness',
  'translates_body_to_thought',
]);

const RELATIONAL_CONTEXT_SIGNALS = new Set<SignalKey>([
  'appreciation_lands_slow_rest',
  'asks_for_support',
  'belonging_ache',
  'care_before_owed',
  'care_evenness_question',
  'care_strengthens_not_takes_over',
  'care_with_boundaries',
  'care_with_selfhood',
  'chosen_family',
  'closeness_uncertainty',
  'collaborative_not_rescuing',
  'connection_glimmer',
  'consistency_need',
  'direct_communication_preference',
  'distance_for_safety',
  'emotional_availability_need',
  'family_dynamics_pull_in',
  'family_individuation',
  'family_pattern_awareness',
  'family_self_with_old_roles',
  'fear_of_being_too_much',
  'help_respects_competence',
  'help_with_control',
  'home_as_safety',
  'indebted_receiving_discomfort',
  'kindness_safety_gap',
  'kindness_usefulness_pressure',
  'lets_others_handle',
  'loneliness',
  'low_relational_tracking',
  'low_reassurance_need',
  'loyalty_conflict',
  'minimizes_need',
  'mutual_flow_safety',
  'mutuality_need',
  'peacekeeping_responsibility',
  'receives_but_exposed_need',
  'receives_then_returns',
  'receiving_care_difficulty',
  'receiving_without_agency_loss',
  'relationship_safety_testing',
  'repair_need',
  'resists_managed_care',
  'rooting_need',
  'rupture_sensitivity',
  'selective_vulnerability',
  'shared_responsibility',
  'small_circle_pressure',
  'support_abundance_shift',
  'support_need',
  'support_scarcity',
  'support_too_much_fear',
  'support_trusted_when_reciprocal',
  'support_without_dependence',
  'supported_autonomy_intact',
  'tone_sensitivity',
  'trust_builds_slowly',
  'truth_over_harmony',
  'wants_to_be_caught',
  'wants_to_be_seen',
]);

const PROTECTIVE_STRATEGY_SIGNALS = new Set<SignalKey>([
  'agency',
  'always_on',
  'autonomy_need',
  'avoidance',
  'avoids_clear_boundary_for_comfort',
  'boundary_guilt',
  'boundary_rebuilding',
  'boundary_without_confirmation',
  'calm_bracing',
  'can_disappoint_others',
  'choosing_self',
  'distance_for_safety',
  'early_limit_honoring',
  'firm_inner_knowing',
  'guard_not_dropped',
  'inner_authority',
  'less_explaining',
  'limits_tested',
  'permission_shift',
  'prepared_steadiness',
  'preparedness',
  'protective_care',
  'quick_limit_clarity',
  'quiet_readiness',
  'safe',
  'says_no',
  'self_trust_growth',
  'shutdown',
  'silence_for_safety',
  'simple_boundary_answer',
  'smooth_over_limit',
  'trapped',
  'unsafe',
]);

const COGNITIVE_PROCESS_SIGNALS = new Set<SignalKey>([
  'action_forward_processing',
  'analysis_as_regulation',
  'asks_why',
  'clarity_before_release',
  'clean_closure',
  'current_moment_grounding',
  'decision_uncertainty',
  'deep_processing',
  'direct_closure_need',
  'dream_emotional_tone',
  'dream_repeated_symbol',
  'dream_unfinished_processing',
  'future_preoccupation',
  'future_self_orientation',
  'intellectualizes_feeling',
  'integrates_insight',
  'interpretation_over_action',
  'meaning_clarifies_actual_life',
  'meaning_making',
  'move_on_orientation',
  'need_for_exact_words',
  'next_step_momentum',
  'pattern_recognition',
  'planning_over_presence',
  'practical_literalist',
  'present_focus',
  'real_events_over_symbols',
  'seeks_context',
  'symbolic_self_understanding',
  'symbols_grounded_real',
  'what_now_focus',
]);

const VALUE_THEME_SIGNALS = new Set<SignalKey>([
  'compromise_discernment',
  'faith_meaning',
  'fairness_need',
  'flexible_pragmatism',
  'good_enough_acceptance',
  'integrity_cost',
  'integrity_without_perfection',
  'justice_sensitivity',
  'legacy_signal',
  'loyalty_vs_honesty',
  'meaning_deepens_truth',
  'meaning_not_action_replacement',
  'meaning_with_practical_action',
  'moral_weight',
  'non_negotiable',
  'purpose_signal',
  'reflection_and_realism',
  'spiritual_depth',
  'truth_telling',
  'values_conflict',
  'values_with_tradeoffs',
]);

const GLIMMER_SIGNALS = new Set<SignalKey>([
  'beauty_glimmer',
  'connection_glimmer',
  'glimmer_softening',
  'laughter_glimmer',
  'play_glimmer',
  'small_good_moments_matter',
  'small_relief_signals_change',
]);

const RESOURCE_CONTEXT_SIGNALS = new Set<SignalKey>([
  'abundance_healing',
  'automatic_giving_need',
  'burnout_risk',
  'capacity_strain',
  'depletion',
  'energy_scarcity',
  'excellence_pressure',
  'helps_before_capacity_check',
  'high_energy',
  'high_stress',
  'high_standards',
  'invisible_labor',
  'low_capacity',
  'low_energy',
  'low_sleep',
  'mental_load',
  'overextension',
  'overfunctioning',
  'poor_sleep_quality',
  'preparedness',
  'responsibility_weight',
  'rest_guilt',
  'rest_resistance',
  'resource_trust_with_concern',
  'scarcity_scanning',
  'sleep_mood_link',
  'structured_pleasure',
  'support_abundance_shift',
  'support_scarcity',
  'time_scarcity',
]);

const BODY_SIGNAL_KEYWORDS = [
  'body',
  'chest',
  'gut',
  'jaw',
  'nausea',
  'physical',
  'shoulder',
  'somatic',
  'sensation',
  'sensory',
  'stomach',
  'throat',
  'tension',
];

const RELATIONAL_KEYWORDS = [
  'belonging',
  'care',
  'closeness',
  'communication',
  'connection',
  'conversation',
  'family',
  'home',
  'relational',
  'relationship',
  'repair',
  'reassurance',
  'support',
  'tone',
  'trust',
];

const PROTECTIVE_KEYWORDS = [
  'autonomy',
  'avoid',
  'boundary',
  'bracing',
  'defensive',
  'distance',
  'guard',
  'agency',
  'limit',
  'no',
  'protection',
  'safe',
  'silence',
  'vulnerability',
  'safety',
  'self_trust',
];

const COGNITIVE_KEYWORDS = [
  'analysis',
  'attention',
  'clarity',
  'closure',
  'cognitive',
  'decision',
  'explain',
  'insight',
  'interpretation',
  'meaning',
  'overthinking',
  'pattern',
  'practical',
  'processing',
  'resolution',
  'understand',
  'unfinished',
];

const VALUE_KEYWORDS = [
  'fairness',
  'integrity',
  'justice',
  'truth',
  'value',
];

const RESOURCE_KEYWORDS = [
  'abundance',
  'capacity',
  'energy',
  'load',
  'money',
  'resource',
  'responsibility',
  'rest',
  'scarcity',
  'sleep',
  'time',
];

function keyText(key: SignalKey): string {
  return key.toLowerCase();
}

function hasAnyKeyword(key: SignalKey, keywords: string[]): boolean {
  const text = keyText(key);
  return keywords.some(keyword => text.includes(keyword));
}

export function getSignalRoles(key: SignalKey): SignalRole[] {
  const roles = new Set<SignalRole>();

  if (FEELING_STATE_SIGNALS.has(key)) roles.add('feeling_state');
  if (RECOVERY_LEVER_SIGNALS.has(key)) roles.add('recovery_lever');
  if (GLIMMER_SIGNALS.has(key) || keyText(key).includes('glimmer')) roles.add('glimmer');
  if (BODY_SIGNAL_SIGNALS.has(key) || hasAnyKeyword(key, BODY_SIGNAL_KEYWORDS)) roles.add('body_signal');
  if (RELATIONAL_CONTEXT_SIGNALS.has(key) || hasAnyKeyword(key, RELATIONAL_KEYWORDS)) roles.add('relational_context');
  if (PROTECTIVE_STRATEGY_SIGNALS.has(key) || hasAnyKeyword(key, PROTECTIVE_KEYWORDS)) roles.add('protective_strategy');
  if (COGNITIVE_PROCESS_SIGNALS.has(key) || hasAnyKeyword(key, COGNITIVE_KEYWORDS)) roles.add('cognitive_process');
  if (VALUE_THEME_SIGNALS.has(key) || hasAnyKeyword(key, VALUE_KEYWORDS)) roles.add('value_theme');
  if (RESOURCE_CONTEXT_SIGNALS.has(key) || hasAnyKeyword(key, RESOURCE_KEYWORDS)) roles.add('resource_context');

  return Array.from(roles);
}

export function getSignalSentiment(key: SignalKey): SignalSentiment {
  if (NEGATIVE_FEELING_SIGNALS.has(key)) return 'negative';
  if (POSITIVE_FEELING_SIGNALS.has(key)) return 'positive';
  if (RECOVERY_LEVER_SIGNALS.has(key) || keyText(key).includes('glimmer')) return 'positive';
  if (keyText(key).includes('conflict') || keyText(key).includes('mixed')) return 'mixed';
  return 'neutral';
}

export function hasSignalRole(
  signal: { key?: SignalKey; roles?: SignalRole[] },
  role: SignalRole,
): boolean {
  return signal.roles?.includes(role) ?? (signal.key ? getSignalRoles(signal.key).includes(role) : false);
}
