import type { ArchivePattern, SignalKey } from '../types';

const bodySignalPattern = (
  key: string,
  title: string,
  requiredSignals: SignalKey[],
  supportingSignals: SignalKey[],
  shameLabel: string,
  clarityReframe: string,
  description: string,
  tags: string[] = [],
): ArchivePattern => ({
  key,
  title,
  category: 'bodySignals',
  description,
  requiredSignals,
  supportingSignals,
  shameLabel,
  clarityReframe,
  lookbackDays: 60,
  minEvidenceCount: 3,
  minScore: 0.56,
  cooldownDays: 7,
  tags,
});

/**
 * Body Signals Archive Patterns
 */
export const BODY_SIGNAL_PATTERNS: ArchivePattern[] = [
  bodySignalPattern(
    'body_signals_001_body_knows_first',
    'The Body Knows First',
    ['body_knows_first'],
    ['chest_pressure', 'shoulder_burden', 'jaw_restraint', 'gut_signal', 'head_pressure'],
    'weakness',
    'body intelligence speaking before the full explanation arrives',
    'Physical signals appear before the emotional story is fully named.',
    ['body-wisdom', 'early-signal'],
  ),
  bodySignalPattern(
    'body_signals_002_chest_holds_story',
    'The Chest Holds the Story',
    ['chest_pressure'],
    ['breath_change', 'body_heaviness', 'sadness', 'emotional_heaviness'],
    'being dramatic',
    'the body giving shape to what the heart is carrying',
    'Chest tightness, breath change, or heaviness may give body shape to emotional weight.',
    ['chest', 'breath', 'heart'],
  ),
  bodySignalPattern(
    'body_signals_003_shoulder_burden',
    'The Shoulder Burden Pattern',
    ['shoulder_burden'],
    ['responsibility_weight', 'mental_load', 'invisible_labor', 'overextension'],
    'being tense for no reason',
    'the invisible load becoming visible through the body',
    'Shoulder, neck, or upper-back tension may reflect load that has been carried invisibly.',
    ['shoulders', 'load', 'responsibility'],
  ),
  bodySignalPattern(
    'body_signals_004_jaw_holds_words',
    'The Jaw Holds the Words',
    ['jaw_restraint'],
    ['anger', 'truth_telling', 'overexplaining', 'throat_tightness'],
    'being angry',
    'contained energy looking for a safe way to be expressed',
    'Jaw tension may appear around restrained words, anger, or energy that has not found safe expression.',
    ['jaw', 'expression', 'restraint'],
  ),
  bodySignalPattern(
    'body_signals_005_gut_signal',
    'The Gut Signal',
    ['gut_signal'],
    ['autonomy_need', 'boundary_rebuilding', 'tone_sensitivity', 'truth_over_harmony'],
    'overreacting',
    'intuition or discomfort speaking through sensation before language arrives',
    'Gut unease may signal discomfort, intuition, or a boundary before words are available.',
    ['gut', 'intuition', 'boundary'],
  ),
  bodySignalPattern(
    'body_signals_006_throat_tightness',
    'The Throat Tightness Pattern',
    ['throat_tightness'],
    ['truth_telling', 'voice_emerging', 'overexplaining', 'selective_vulnerability'],
    'being unable to say it right',
    'truth pressing toward expression while safety is still being assessed',
    'Throat tightness can appear when expression is needed but relational safety is still being evaluated.',
    ['throat', 'voice', 'truth'],
  ),
  bodySignalPattern(
    'body_signals_007_heavy_body',
    'The Heavy Body Pattern',
    ['body_heaviness'],
    ['low_energy', 'depletion', 'low_mood', 'rest_resistance'],
    'laziness',
    'the body making depletion visible',
    'Heaviness, fatigue, and low motivation can be the body making depletion visible.',
    ['heaviness', 'depletion', 'energy'],
  ),
  bodySignalPattern(
    'body_signals_008_body_lightness',
    'The Body-Lightness Signal',
    ['body_lightness'],
    ['relief', 'glimmer_softening', 'quiet_safety', 'mood_improvement'],
    'the moment being too small to count',
    'the body recognizing a real shift toward safety',
    'Lightness or ease in the body can mark a real shift toward safety or relief.',
    ['lightness', 'relief', 'safety'],
  ),
  bodySignalPattern(
    'body_signals_009_breath_change',
    'The Breath Change Signal',
    ['breath_change'],
    ['chest_pressure', 'high_stress', 'calm_bracing', 'tension_release'],
    'not staying calm',
    'the breath showing where the system is trying to regulate',
    'Held breath, shallow breathing, or sighs may show the system trying to regulate.',
    ['breath', 'regulation', 'stress'],
  ),
  bodySignalPattern(
    'body_signals_010_head_pressure',
    'The Head Pressure Pattern',
    ['head_pressure'],
    ['sensory_sensitivity', 'deep_processing', 'high_stress', 'overextension'],
    'being overwhelmed too easily',
    'the mind and body asking for less input',
    'Head pressure or headaches may appear when cognitive or sensory input has exceeded capacity.',
    ['head', 'overstimulation', 'input'],
  ),
  bodySignalPattern(
    'body_signals_011_tension_release',
    'The Tension Release Pattern',
    ['tension_release'],
    ['emotional_softening', 'relief', 'body_lightness', 'somatic_safety'],
    'being overly emotional',
    'the body completing a small cycle of release',
    'Yawning, tears, loosening, or deep breaths can show a small release cycle completing.',
    ['release', 'tears', 'softening'],
  ),
  bodySignalPattern(
    'body_signals_012_body_boundary',
    'The Body Boundary Signal',
    ['body_knows_first'],
    ['gut_signal', 'chest_pressure', 'boundary_rebuilding', 'limits_tested'],
    'being unfair',
    'the body noticing where something does not feel settled',
    'Discomfort around a person or situation may indicate the body is tracking unsettled boundary information.',
    ['boundary', 'discomfort', 'discernment'],
  ),
  bodySignalPattern(
    'body_signals_013_sensory_load',
    'The Sensory Load Pattern',
    ['sensory_sensitivity'],
    ['head_pressure', 'low_energy', 'needs_pause', 'calm_bracing'],
    'being too sensitive',
    'a system that notices the world in high resolution',
    'Sound, light, clutter, or stimulation may register strongly because the system notices input in detail.',
    ['sensory', 'overstimulation', 'input'],
  ),
  bodySignalPattern(
    'body_signals_014_beauty_regulated',
    'The Beauty-Regulated Pattern',
    ['beauty_regulation'],
    ['beauty_glimmer', 'ordinary_sacred', 'body_lightness', 'quiet_safety'],
    'being superficial',
    'the senses needing an environment that helps the inner world settle',
    'Light, color, atmosphere, or softness can support regulation through the senses.',
    ['beauty', 'senses', 'regulation'],
  ),
  bodySignalPattern(
    'body_signals_015_body_before_boundary',
    'The Body Before the Boundary',
    ['body_knows_first'],
    ['throat_tightness', 'gut_signal', 'boundary_rebuilding', 'says_no'],
    'being unclear',
    'the body finding the boundary before words do',
    'Body tension may appear before the user can clearly name a needed no, limit, or change.',
    ['boundary', 'body-cue', 'no'],
  ),
  bodySignalPattern(
    'body_signals_016_body_after_connection',
    'The Body After Connection',
    ['body_knows_first'],
    ['somatic_safety', 'chest_pressure', 'relationship_safety_testing', 'body_lightness'],
    'reading too much into things',
    'connection leaving a measurable imprint in the body',
    'The body may feel clearer, softer, or tenser after connection, showing what the interaction cost or restored.',
    ['connection', 'after-effect', 'somatic'],
  ),
  bodySignalPattern(
    'body_signals_017_body_after_rest',
    'The Body After Rest',
    ['restorative_moment'],
    ['body_lightness', 'tension_release', 'somatic_safety', 'emotional_softening'],
    'needing too much',
    'evidence that recovery changes what the body has to carry',
    'Body softening after pause can show that recovery materially changes the load.',
    ['rest', 'recovery', 'softening'],
  ),
  bodySignalPattern(
    'body_signals_018_body_after_conflict',
    'The Body After Conflict',
    ['body_heaviness'],
    ['rupture_sensitivity', 'repair_need', 'chest_pressure', 'shoulder_burden'],
    'not letting things go',
    'the body taking time to feel safe again',
    'Tension after rupture or conflict may show the body needing time to register safety again.',
    ['conflict', 'tension', 'repair'],
  ),
  bodySignalPattern(
    'body_signals_019_body_map_repetition',
    'The Body Map Repetition',
    ['body_knows_first'],
    ['chest_pressure', 'shoulder_burden', 'jaw_restraint', 'gut_signal', 'head_pressure'],
    'random discomfort',
    'a repeated physical signal becoming part of the archive',
    'The same body area activating repeatedly can turn a cue into a recognizable archive pattern.',
    ['repetition', 'body-map', 'archive'],
  ),
  bodySignalPattern(
    'body_signals_020_somatic_safety',
    'The Somatic Safety Signal',
    ['somatic_safety'],
    ['body_lightness', 'quiet_safety', 'tension_release', 'low_stress'],
    'the calm not counting',
    'the body showing what safety feels like in practice',
    'Grounded feet, slower heartbeat, or relaxed jaw show safety as a body state, not only a thought.',
    ['safety', 'grounding', 'calm'],
  ),
];
