import type { ArchivePattern, SignalKey } from '../types';

const boundaryPattern = (
  key: string,
  title: string,
  requiredSignals: SignalKey[],
  supportingSignals: SignalKey[],
  shameLabel: string,
  clarityReframe: string,
  description: string,
  tags: string[] = [],
): ArchivePattern => ({
  key,
  title,
  category: 'boundariesSelfTrust',
  description,
  requiredSignals,
  supportingSignals,
  shameLabel,
  clarityReframe,
  lookbackDays: 90,
  minEvidenceCount: 3,
  minScore: 0.58,
  cooldownDays: 10,
  tags,
});

/**
 * Boundaries + Self-Trust Archive Patterns
 */
export const BOUNDARY_SELF_TRUST_PATTERNS: ArchivePattern[] = [
  boundaryPattern(
    'boundaries_001_boundary_rebuilding',
    'Where You Draw the Line',
    ['boundary_rebuilding'],
    ['self_trust_growth', 'limits_tested', 'inner_authority', 'says_no'],
    'becoming cold',
    'the quiet confidence of someone who has realized their peace is no longer up for negotiation',
    'A subtle but profound shift in your relational gravity, moving away from over-explaining and toward simply observing your boundaries.',
    ['limits', 'self-trust', 'permission'],
  ),
  boundaryPattern(
    'boundaries_002_less_explaining_more_knowing',
    'Less Explaining, More Knowing',
    ['less_explaining'],
    ['inner_authority', 'self_trust_growth', 'overexplaining', 'permission_shift'],
    'being unfair',
    'the quiet confidence of someone who has realized their peace is no longer up for negotiation',
    'You are no longer asking for permission to take up the space you need to feel secure, moving away from over-explaining your boundaries.',
    ['inner-authority', 'explaining', 'knowing'],
  ),
  boundaryPattern(
    'boundaries_003_guilt_after_saying_no',
    'The Guilt After Saying No',
    ['boundary_guilt'],
    ['says_no', 'self_blame', 'guilt', 'loyalty_conflict'],
    'being selfish',
    'an old loyalty pattern adjusting to the truth that limits protect connection too',
    'Guilt after a no may reflect an old loyalty pattern learning that limits can protect connection.',
    ['guilt', 'no', 'loyalty'],
  ),
  boundaryPattern(
    'boundaries_004_peace_boundary',
    'The Peace Boundary',
    ['peace_boundary'],
    ['distance_for_safety', 'quiet_safety', 'needs_pause', 'choosing_self'],
    'giving up',
    'peace becoming important enough to stop negotiating with what drains it',
    'Choosing quiet or stepping back can be a boundary that protects peace instead of a sign of defeat.',
    ['peace', 'quiet', 'stepping-back'],
  ),
  boundaryPattern(
    'boundaries_005_inner_authority',
    'The Inner Authority Pattern',
    ['inner_authority'],
    ['self_trust_growth', 'choosing_self', 'permission_shift', 'truth_telling'],
    'being stubborn',
    'your own knowing becoming a place you can stand',
    'Self-trust and choosing self can show inner authority becoming a steadier place to stand.',
    ['authority', 'self-trust', 'confidence'],
  ),
  boundaryPattern(
    'boundaries_006_permission_shift',
    'The Permission Shift',
    ['permission_shift'],
    ['inner_authority', 'choosing_self', 'self_trust_growth', 'says_no'],
    'becoming difficult',
    'a self-protective voice getting clearer after being quieted for too long',
    'The question may be shifting from whether the user is allowed to whether the need is true.',
    ['permission', 'self-protection', 'voice'],
  ),
  boundaryPattern(
    'boundaries_007_limit_is_information',
    'The Limit Is Information',
    ['limits_tested'],
    ['low_energy', 'body_knows_first', 'capacity_strain', 'needs_pause'],
    'being inconvenient',
    'your system telling the truth before the cost gets higher',
    'Limits, fatigue, or body cues can be information before the cost becomes larger.',
    ['limits', 'capacity', 'body-cue'],
  ),
  boundaryPattern(
    'boundaries_008_boundary_before_burnout',
    'The Boundary Before the Burnout',
    ['limits_tested'],
    ['burnout_risk', 'overextension', 'depletion', 'needs_pause'],
    'not being generous enough',
    'a line appearing before depletion has to draw it for you',
    'An early boundary may be appearing before exhaustion has to create a harder stop.',
    ['burnout', 'early-boundary', 'depletion'],
  ),
  boundaryPattern(
    'boundaries_009_over_apology',
    'The Over-Apology Pattern',
    ['guilt'],
    ['boundary_guilt', 'minimizes_need', 'fear_of_being_too_much', 'support_need'],
    'being too much',
    'a learned attempt to make your needs easier to receive',
    'Apologizing for needs or taking space may be an attempt to make needs feel safer for others to receive.',
    ['apology', 'needs', 'space'],
  ),
  boundaryPattern(
    'boundaries_010_no_protects_yes',
    'The No That Protects the Yes',
    ['says_no'],
    ['energy_scarcity', 'values_conflict', 'purpose_signal', 'choosing_self'],
    'letting people down',
    'one boundary protecting the energy needed for what matters most',
    'A no may be protecting the energy and alignment needed for a more important yes.',
    ['no', 'energy', 'values'],
  ),
  boundaryPattern(
    'boundaries_011_self_abandonment_signal',
    'The Self-Abandonment Signal',
    ['choosing_self'],
    ['minimizes_need', 'boundary_guilt', 'self_blame', 'fear_of_being_too_much'],
    'not knowing better',
    'a moment where your system shows you where you are being asked to return to yourself',
    'Regret after ignoring needs may show where the user is being asked to return to themself.',
    ['self-return', 'needs', 'regret'],
  ),
  boundaryPattern(
    'boundaries_012_over_accommodation',
    'The Over-Accommodation Pattern',
    ['minimizes_need'],
    ['fear_of_being_too_much', 'mutuality_need', 'boundary_guilt', 'truth_over_harmony'],
    'being weak',
    'a connection-preserving strategy that may be ready to share space with your own truth',
    'Adjusting too much or softening needs may be a connection-preserving strategy ready for more truth.',
    ['accommodation', 'connection', 'truth'],
  ),
  boundaryPattern(
    'boundaries_013_cost_of_keeping_peace',
    'The Cost of Keeping Peace',
    ['peace_boundary'],
    ['truth_over_harmony', 'throat_tightness', 'loyalty_conflict', 'values_conflict'],
    'being fake',
    'peacekeeping that once protected connection but may now be costing too much of you',
    'Harmony or silence may have protected connection before, while now costing too much truth.',
    ['peacekeeping', 'truth', 'silence'],
  ),
  boundaryPattern(
    'boundaries_014_boundary_needs_fewer_words',
    'The Boundary That Needs Fewer Words',
    ['less_explaining'],
    ['overexplaining', 'inner_authority', 'self_trust_growth', 'boundary_rebuilding'],
    'not making sense',
    'a boundary becoming valid because it is true, not because it is perfectly explained',
    'Explanation fatigue may show a boundary that does not need perfect language to be valid.',
    ['boundary', 'explanation', 'validity'],
  ),
  boundaryPattern(
    'boundaries_015_inner_no',
    'The Inner No',
    ['gut_signal'],
    ['body_knows_first', 'boundary_rebuilding', 'autonomy_need', 'limits_tested'],
    'being judgmental',
    'an internal signal that something needs more space, clarity, or protection',
    'Discomfort or hesitation may be an internal no asking for more space or protection.',
    ['inner-no', 'body-boundary', 'hesitation'],
  ),
  boundaryPattern(
    'boundaries_016_energy_gate',
    'The Energy Gate',
    ['energy_scarcity'],
    ['low_energy', 'capacity_strain', 'choosing_self', 'limits_tested'],
    'being closed off',
    'discernment about what deserves access to your limited capacity',
    'Limited emotional energy may be asking for more discernment about what gets access.',
    ['energy', 'access', 'discernment'],
  ),
  boundaryPattern(
    'boundaries_017_autonomy_need',
    'The Autonomy Need',
    ['autonomy_need'],
    ['inner_authority', 'choosing_self', 'high_stress', 'truth_telling'],
    'being resistant',
    "the need to stay connected to yourself while responding to life's demands",
    'Pressure, control, or restricted choice may reveal a need to stay connected to the self.',
    ['autonomy', 'choice', 'pressure'],
  ),
  boundaryPattern(
    'boundaries_018_line_after_repetition',
    'The Line After Repetition',
    ['limits_tested'],
    ['boundary_rebuilding', 'self_trust_growth', 'anger', 'pattern_recognition'],
    'being impatient',
    'a limit becoming clearer after the same cost has appeared too many times',
    'A repeated issue may turn patience into boundary clarity after the same cost appears too often.',
    ['repetition', 'limit', 'clarity'],
  ),
  boundaryPattern(
    'boundaries_019_boundary_protects_softness',
    'The Boundary That Protects Softness',
    ['boundary_rebuilding'],
    ['sadness', 'emotional_softening', 'selective_vulnerability', 'self_trust_growth'],
    'being fragile',
    'protecting the softer parts of you so they do not have to become armor',
    'A boundary may protect tenderness so softness does not have to become armor.',
    ['softness', 'protection', 'vulnerability'],
  ),
  boundaryPattern(
    'boundaries_020_self_trust_after_doubt',
    'The Self-Trust After Doubt',
    ['self_trust_growth'],
    ['decision_uncertainty', 'choosing_self', 'inner_authority', 'clarity_before_release'],
    'being inconsistent',
    'self-trust forming through honest checking, not instant certainty',
    'Doubt followed by clarity can show self-trust forming through honest checking.',
    ['self-trust', 'doubt', 'clarity'],
  ),
];
