import type { ArchivePattern, SignalKey } from '../types';

const cognitivePattern = (
  key: string,
  title: string,
  requiredSignals: SignalKey[],
  supportingSignals: SignalKey[],
  shameLabel: string,
  clarityReframe: string,
  description: string,
  tags: string[] = [],
): ArchivePattern => ({
  key,
  title,
  category: 'cognitiveStyle',
  description,
  requiredSignals,
  supportingSignals,
  shameLabel,
  clarityReframe,
  lookbackDays: 90,
  minEvidenceCount: 3,
  minScore: 0.58,
  cooldownDays: 10,
  tags,
});

/**
 * Cognitive Style + Meaning-Making Archive Patterns
 */
export const COGNITIVE_STYLE_PATTERNS: ArchivePattern[] = [
  cognitivePattern(
    'cognitive_001_deep_processor',
    'How You Process Information',
    ['deep_processing'],
    ['meaning_making', 'clarity_before_release', 'need_for_exact_words', 'asks_why'],
    'overthinking',
    'your mind trying to make something emotionally survivable by making it understandable',
    'Analysis and meaning-making help you locate the deeper thread beneath what happened.',
    ['processing', 'meaning', 'information'],
  ),
  cognitivePattern(
    'cognitive_002_need_for_exact_words',
    'The Need for Exact Words',
    ['need_for_exact_words'],
    ['overexplaining', 'wants_to_be_seen', 'emotional_availability_need', 'clarity_before_release'],
    'being difficult to comfort',
    'needing care and clarity that actually find the center of the feeling',
    'Precise wording may matter because inaccurate comfort misses the center of the feeling.',
    ['language', 'precision', 'comfort'],
  ),
  cognitivePattern(
    'cognitive_003_understanding_before_release',
    'Understanding Before Release',
    ['clarity_before_release'],
    ['analysis_as_regulation', 'deep_processing', 'integrates_insight', 'emotional_heaviness'],
    'staying in your head',
    'the mind trying to give an experience a shape so it can finally be moved through',
    'You may not fully move through an experience until it has a shape: what happened, what it touched, and why it stayed.',
    ['clarity', 'release', 'analysis'],
  ),
  cognitivePattern(
    'cognitive_004_pattern_hunter',
    'The Pattern Hunter',
    ['pattern_recognition'],
    ['meaning_making', 'asks_why', 'deep_processing', 'seeks_context'],
    'obsessing',
    'a mind looking for the map because the map helps life feel less random',
    'Tracking repetition may help life feel less random and more understandable.',
    ['patterns', 'map', 'themes'],
  ),
  cognitivePattern(
    'cognitive_005_emotional_archaeologist',
    'The Emotional Archaeologist',
    ['deep_processing'],
    ['meaning_making', 'longing', 'emotional_heaviness', 'asks_why'],
    'making things complicated',
    'depth recognizing that pain often wears more than one name',
    'The user may look beneath the first feeling for an older layer or deeper need.',
    ['depth', 'older-layer', 'need'],
  ),
  cognitivePattern(
    'cognitive_006_context_need',
    'The Context Need',
    ['seeks_context'],
    ['overexplaining', 'need_for_exact_words', 'meaning_making', 'truth_over_harmony'],
    'over-explaining',
    'trying to keep the truth from being flattened into something too small',
    'Context, nuance, or backstory may matter because the user is protecting the truth from being flattened.',
    ['context', 'nuance', 'truth'],
  ),
  cognitivePattern(
    'cognitive_007_clarity_before_action',
    'The Clarity Before Action Pattern',
    ['decision_uncertainty'],
    ['clarity_before_release', 'seeks_context', 'inner_authority', 'self_trust_growth'],
    'procrastinating',
    'your system asking for enough clarity to move without abandoning itself',
    'Decision delay may reflect a need for enough clarity to move without self-abandonment.',
    ['decision', 'clarity', 'action'],
  ),
  cognitivePattern(
    'cognitive_008_mental_loop_wants_meaning',
    'The Mental Loop That Wants Meaning',
    ['asks_why'],
    ['analysis_as_regulation', 'deep_processing', 'meaning_making', 'emotional_heaviness'],
    'spiraling',
    'an unresolved need trying to become understandable',
    'Repeated thoughts may be an unresolved need trying to become understandable.',
    ['loop', 'meaning', 'unresolved'],
  ),
  cognitivePattern(
    'cognitive_009_question_keeps_returning',
    'The Question That Keeps Returning',
    ['asks_why'],
    ['pattern_recognition', 'seeks_context', 'meaning_making', 'clarity_before_release'],
    'not letting it go',
    'a question returning because something in it has not been fully answered',
    'A repeated question can point to an unresolved theme that still wants a fuller answer.',
    ['question', 'returning', 'theme'],
  ),
  cognitivePattern(
    'cognitive_010_insight_integration',
    'The Insight Integration Pattern',
    ['integrates_insight'],
    ['meaning_making', 'self_trust_growth', 'permission_shift', 'mood_improvement'],
    'only thinking, not changing',
    'understanding slowly becoming lived instead of only known',
    'Insight may be moving into behavior gradually rather than remaining only an idea.',
    ['integration', 'behavior', 'insight'],
  ),
  cognitivePattern(
    'cognitive_011_knowing_and_feeling_lag',
    'The Tension Between Knowing and Feeling',
    ['intellectualizes_feeling'],
    ['clarity_before_release', 'body_heaviness', 'emotional_heaviness', 'deep_processing'],
    'not being over it',
    'the mind arriving before the body has fully caught up',
    'The mind may understand before the body and emotions have caught up.',
    ['knowing', 'feeling', 'lag'],
  ),
  cognitivePattern(
    'cognitive_012_meaning_making_reflex',
    'The Meaning-Making Reflex',
    ['meaning_making'],
    ['purpose_signal', 'faith_meaning', 'spiritual_depth', 'hope'],
    'forcing positivity',
    'reclaiming agency from what could have stayed chaotic',
    'Turning hardship toward meaning can be a way of reclaiming agency from chaos.',
    ['meaning', 'agency', 'hardship'],
  ),
  cognitivePattern(
    'cognitive_013_detail_keeper',
    'The Detail Keeper',
    ['need_for_exact_words'],
    ['pattern_recognition', 'seeks_context', 'truth_telling', 'analysis_as_regulation'],
    'being too focused on details',
    'details helping your reality stay intact',
    'Specific details may help reality stay intact and prevent the story from being simplified away.',
    ['details', 'evidence', 'reality'],
  ),
  cognitivePattern(
    'cognitive_014_decision_weight',
    'The Decision-Weight Pattern',
    ['decision_uncertainty'],
    ['values_conflict', 'autonomy_need', 'responsibility_weight', 'meaning_making'],
    'being indecisive',
    'choices mattering because they touch more than one need or value',
    'Decisions may feel heavy when they touch multiple values, needs, or responsibilities at once.',
    ['decision', 'values', 'weight'],
  ),
  cognitivePattern(
    'cognitive_015_why_did_this_hit_me',
    'The "Why Did This Hit Me?" Pattern',
    ['asks_why'],
    ['emotional_intensity', 'body_knows_first', 'longing', 'sadness'],
    'being dramatic',
    'a current moment brushing against something deeper than the surface event',
    'Surprising intensity may mean a current moment is touching a deeper layer.',
    ['intensity', 'deeper-layer', 'question'],
  ),
  cognitivePattern(
    'cognitive_016_reframe_seeker',
    'The Reframe Seeker',
    ['meaning_making'],
    ['self_blame', 'need_for_exact_words', 'hope', 'clarity_before_release'],
    'needing reassurance',
    'your mind searching for the frame that stops pain from turning into self-blame',
    'The user may seek a better interpretation to keep pain from becoming a shame story.',
    ['reframe', 'self-blame', 'interpretation'],
  ),
  cognitivePattern(
    'cognitive_017_language_as_relief',
    'The Language as Relief Pattern',
    ['need_for_exact_words'],
    ['integrates_insight', 'tension_release', 'relief', 'meaning_making'],
    'needing too many words',
    'words becoming a way your system exhales',
    'Relief after naming, journaling, or finding words can show language acting as regulation.',
    ['language', 'relief', 'journaling'],
  ),
  cognitivePattern(
    'cognitive_018_deep_question',
    'The Deep Question Pattern',
    ['spiritual_depth'],
    ['meaning_making', 'identity_rewriting', 'faith_meaning', 'asks_why'],
    'being too intense',
    'depth being one of the ways you meet the world honestly',
    'Existential questions about identity, meaning, or life direction may be a natural depth pattern.',
    ['depth', 'meaning', 'identity'],
  ),
  cognitivePattern(
    'cognitive_019_thought_before_feeling',
    'The Thought Before the Feeling',
    ['intellectualizes_feeling'],
    ['analysis_as_regulation', 'deep_processing', 'body_knows_first', 'clarity_before_release'],
    'intellectualizing',
    'thinking creating a safer doorway into feeling',
    'Thinking may arrive before feeling because analysis creates a safer doorway into emotion.',
    ['thought', 'feeling', 'doorway'],
  ),
  cognitivePattern(
    'cognitive_020_feeling_after_insight',
    'The Feeling After the Insight',
    ['integrates_insight'],
    ['emotional_softening', 'sadness', 'relief', 'tension_release'],
    'going backward',
    'insight making enough room for the feeling to finally arrive',
    'Emotion after clarity may mean insight created enough room for the feeling to arrive.',
    ['insight', 'emotion', 'arrival'],
  ),
];
