import type { ArchivePattern, SignalKey } from '../types';

const creativityPattern = (
  key: string,
  title: string,
  requiredSignals: SignalKey[],
  supportingSignals: SignalKey[],
  shameLabel: string,
  clarityReframe: string,
  description: string,
  tags: string[] = [],
): ArchivePattern => ({
  key,
  title,
  category: 'creativityExpression',
  description,
  requiredSignals,
  supportingSignals,
  shameLabel,
  clarityReframe,
  lookbackDays: 90,
  minEvidenceCount: 3,
  minScore: 0.58,
  cooldownDays: 10,
  tags,
});

/**
 * Creativity + Expression Archive Patterns
 */
export const CREATIVITY_EXPRESSION_PATTERNS: ArchivePattern[] = [
  creativityPattern(
    'creativity_001_creative_alchemy',
    'How You Turn Feeling into Form',
    ['creative_processing'],
    ['creative_aliveness', 'expression_need', 'beauty_making', 'voice_emerging'],
    'distraction',
    'transformation through expression',
    'Creation—writing, design, making, arranging, or imagining—may become a primary way to metabolize life and emotion.',
    ['creativity', 'expression', 'processing'],
  ),
  creativityPattern(
    'creativity_002_voice_emerging',
    'The Voice Emerging Pattern',
    ['voice_emerging'],
    ['truth_telling', 'self_definition', 'expression_need', 'becoming_visible'],
    'wanting attention',
    'a self becoming easier to hear after being edited down',
    'The user may be finding language, tone, or creative form for parts of themselves that used to stay hidden.',
    ['voice', 'visibility', 'self-expression'],
  ),
  creativityPattern(
    'creativity_003_beauty_as_regulation',
    'Beauty as Regulation',
    ['beauty_making'],
    ['glimmer_softening', 'somatic_safety', 'creative_aliveness', 'quiet_safety'],
    'being superficial',
    'the nervous system finding steadiness through beauty',
    'Beauty, color, sound, texture, design, or atmosphere may help the user feel more regulated and present.',
    ['beauty', 'regulation', 'environment'],
  ),
  creativityPattern(
    'creativity_004_expression_pressure',
    'The Need to Express',
    ['expression_need'],
    ['creative_processing', 'voice_emerging', 'emotional_intensity', 'meaning_making'],
    'being dramatic',
    'emotion asking for movement instead of containment',
    'A buildup of feeling may need language, art, music, movement, or another form of expression to become easier to hold.',
    ['expression', 'emotion', 'release'],
  ),
  creativityPattern(
    'creativity_005_meaning_maker',
    'The Meaning-Making Pattern',
    ['meaning_making'],
    ['creative_processing', 'pattern_recognition', 'truth_telling', 'future_self_orientation'],
    'overthinking',
    'a mind trying to turn experience into wisdom',
    'The user may naturally search for meaning beneath events, noticing themes and shaping them into insight.',
    ['meaning', 'patterns', 'wisdom'],
  ),
  creativityPattern(
    'creativity_006_creative_aliveness',
    'When Creation Brings You Back',
    ['creative_aliveness'],
    ['creative_aliveness', 'voice_emerging', 'beauty_making', 'self_definition'],
    'wasting time',
    'aliveness returning through the act of making',
    'Creative activity may restore energy, identity, or a sense of inner movement after feeling flat or depleted.',
    ['aliveness', 'energy', 'making'],
  ),
  creativityPattern(
    'creativity_007_private_world_builder',
    'The Private World Builder',
    ['creative_processing'],
    ['creative_processing', 'creative_processing', 'meaning_making', 'quiet_safety'],
    'living in your head',
    'an inner world that helps organize feeling and possibility',
    'The user may have a rich internal landscape that helps them rehearse, imagine, process, and create meaning.',
    ['inner-world', 'creative_processing', 'solitude'],
  ),
  creativityPattern(
    'creativity_008_story_as_survival',
    'Story as Survival',
    ['creative_processing'],
    ['meaning_making', 'past_self_compassion', 'identity_rewriting', 'creative_processing'],
    'dwelling on the past',
    'story becoming a way to give shape to what was once shapeless',
    'The user may use story, memory, metaphor, or narrative structure to make difficult experiences more coherent.',
    ['story', 'memory', 'coherence'],
  ),
  creativityPattern(
    'creativity_009_designing_safety',
    'Designing Safety',
    ['beauty_making'],
    ['beauty_making', 'somatic_safety', 'quiet_safety', 'needs_pause'],
    'being particular',
    'the environment becoming part of the support system',
    'The user may regulate through atmosphere, layout, lighting, color, order, or intentional design of their surroundings.',
    ['environment', 'safety', 'design'],
  ),
  creativityPattern(
    'creativity_010_unfinished_ideas',
    'The Unfinished Ideas Pattern',
    ['vision_gap'],
    ['creative_aliveness', 'future_self_orientation', 'overextension', 'capacity_strain'],
    'never finishing anything',
    'more possibility than current capacity can carry at once',
    'The user may generate more ideas than they have capacity to complete, creating a gap between vision and follow-through.',
    ['ideas', 'capacity', 'follow-through'],
  ),
  creativityPattern(
    'creativity_011_creative_overflow',
    'Creative Overflow',
    ['vision_gap'],
    ['expression_need', 'creative_aliveness', 'creative_aliveness', 'mental_load'],
    'being scattered',
    'a surge of creative energy needing structure, not shame',
    'A wave of ideas, images, words, or plans may arrive faster than the user can organize them.',
    ['overflow', 'ideas', 'structure'],
  ),
  creativityPattern(
    'creativity_012_blocked_expression',
    'The Blocked Expression Pattern',
    ['creative_block'],
    ['throat_tightness', 'creative_block', 'wants_to_be_seen', 'voice_emerging'],
    'having nothing to say',
    'expression waiting for enough safety to move',
    'The user may feel a strong need to express something while also feeling blocked, edited, or unsafe being fully visible.',
    ['block', 'voice', 'visibility'],
  ),
  creativityPattern(
    'creativity_013_self_censorship',
    'Where You Edit Yourself Down',
    ['creative_block'],
    ['wants_to_be_seen', 'voice_emerging', 'truth_telling', 'belonging_ache'],
    'being too much',
    'a voice learning it does not have to shrink to belong',
    'The user may soften, shrink, or filter their expression to avoid rejection, conflict, or being misunderstood.',
    ['self-censorship', 'belonging', 'voice'],
  ),
  creativityPattern(
    'creativity_014_visibility_edge',
    'The Visibility Edge',
    ['wants_to_be_seen'],
    ['becoming_visible', 'voice_emerging', 'self_definition', 'selective_vulnerability'],
    'wanting attention',
    'the self approaching visibility before every part feels ready',
    'Being seen may feel both desired and exposing, especially when creative or personal expression carries emotional truth.',
    ['visibility', 'vulnerability', 'expression'],
  ),
  creativityPattern(
    'creativity_015_creative_devotion',
    'The Creative Devotion Pattern',
    ['wants_to_build'],
    ['purpose_signal', 'future_self_orientation', 'creative_aliveness', 'purpose_signal'],
    'taking it too seriously',
    'devotion to making something that carries meaning',
    'The user may treat creative work as more than a hobby: a meaningful devotion, calling, or way of becoming.',
    ['devotion', 'purpose', 'creative-work'],
  ),
  creativityPattern(
    'creativity_016_creation_after_pain',
    'Creation After Pain',
    ['creative_processing'],
    ['sadness', 'creative_processing', 'meaning_making', 'past_self_compassion'],
    'romanticizing pain',
    'pain becoming something witnessed instead of only endured',
    'The user may transform painful material into words, art, insight, design, care, or something that makes the pain visible and held.',
    ['pain', 'transformation', 'witnessing'],
  ),
  creativityPattern(
    'creativity_017_symbolic_thinking',
    'The Symbolic Thinking Pattern',
    ['meaning_making'],
    ['dream_repeated_symbol', 'meaning_making', 'pattern_recognition', 'creative_processing'],
    'reading into things',
    'a mind that understands through image, metaphor, and pattern',
    'The user may naturally understand life through symbols, metaphors, dreams, themes, signs, or repeating images.',
    ['symbols', 'metaphor', 'patterns'],
  ),
  creativityPattern(
    'creativity_018_making_to_understand',
    'Making to Understand',
    ['creative_processing'],
    ['creative_processing', 'need_for_exact_words', 'meaning_making', 'pattern_recognition'],
    'not knowing until you start',
    'clarity emerging through the act of making',
    'The user may not fully know what they think or feel until they write it, build it, arrange it, draw it, or say it out loud.',
    ['clarity', 'making', 'processing'],
  ),
  creativityPattern(
    'creativity_019_aesthetic_identity',
    'The Aesthetic Identity Pattern',
    ['beauty_making'],
    ['beauty_making', 'self_definition', 'creative_aliveness', 'becoming_visible'],
    'caring too much about how things look',
    'style becoming a language of self-recognition',
    'Aesthetic choices may carry identity, mood, values, memory, and self-recognition rather than being merely decorative.',
    ['aesthetic', 'identity', 'style'],
  ),
  creativityPattern(
    'creativity_020_expression_as_connection',
    'Expression as Connection',
    ['expression_need'],
    ['voice_emerging', 'selective_vulnerability', 'repair_need', 'truth_telling'],
    'oversharing',
    'expression reaching for honest connection',
    'The user may use words, art, stories, or creative gestures to bridge distance and invite more honest connection.',
    ['connection', 'expression', 'vulnerability'],
  ),
];
