import type { ArchivePattern, SignalKey } from '../types';

const creativityPattern = (
  key: string,
  title: string,
  requiredSignals: SignalKey[],
  supportingSignals: SignalKey[],
  shameLabel: string,
  clarityReframe: string,
  description: string,
  tags: string[] = [],
): ArchivePattern => ({
  key,
  title,
  category: 'creativityExpression',
  description,
  requiredSignals,
  supportingSignals,
  shameLabel,
  clarityReframe,
  lookbackDays: 90,
  minEvidenceCount: 3,
  minScore: 0.56,
  cooldownDays: 10,
  tags,
});

/**
 * Creativity + Expression Archive Patterns
 */
export const CREATIVITY_EXPRESSION_PATTERNS: ArchivePattern[] = [
  creativityPattern(
    'creativity_001_creative_alchemy',
    'Creative Alchemy',
    ['creative_processing'],
    ['expression_need', 'beauty_making', 'voice_emerging', 'meaning_making'],
    'distracting yourself',
    'transformation through expression',
    'Making, writing, designing, or building may metabolize emotion into form.',
    ['alchemy', 'making', 'emotion'],
  ),
  creativityPattern(
    'creativity_002_vision_gap',
    'The Vision Gap',
    ['vision_gap'],
    ['creative_standards', 'high_standards', 'creative_block', 'wants_to_build'],
    'perfectionism',
    'the ache of wanting the outside form to match the depth of the inner vision',
    'A gap between imagined quality and current reality can carry the ache of a meaningful vision.',
    ['vision', 'quality', 'gap'],
  ),
  creativityPattern(
    'creativity_003_premium_standard',
    'The Premium Standard Pattern',
    ['creative_standards'],
    ['beauty_making', 'high_standards', 'excellence_pressure', 'vision_gap'],
    'being picky',
    'creative discernment sensing the gap between usable and meaningful',
    'Polish, depth, quality, or beauty may reflect discernment instead of fussiness.',
    ['standards', 'quality', 'beauty'],
  ),
  creativityPattern(
    'creativity_004_expression_as_processing',
    'Expression as Processing',
    ['expression_need'],
    ['creative_processing', 'voice_emerging', 'need_for_exact_words', 'emotional_heaviness'],
    'being dramatic',
    'emotion finding a form it can move through',
    'Writing, art, design, voice, or making may give emotion a form it can move through.',
    ['expression', 'processing', 'voice'],
  ),
  creativityPattern(
    'creativity_005_beauty_making',
    'The Beauty-Making Pattern',
    ['beauty_making'],
    ['beauty_regulation', 'ordinary_sacred', 'creative_aliveness', 'quiet_safety'],
    'focusing on surface',
    'beauty becoming one way your inner world creates safety and meaning',
    'Aesthetic care, atmosphere, and beauty may help the inner world settle and make meaning.',
    ['beauty', 'atmosphere', 'safety'],
  ),
  creativityPattern(
    'creativity_006_creative_block',
    'The Creative Block Signal',
    ['creative_block'],
    ['vision_gap', 'creative_standards', 'self_blame', 'excellence_pressure'],
    'not being talented enough',
    'creativity protecting itself when the outcome feels too loaded',
    'Creative stuckness may appear when quality, visibility, or meaning feels too loaded.',
    ['block', 'pressure', 'quality'],
  ),
  creativityPattern(
    'creativity_007_voice_emerging',
    'The Voice Emerging Pattern',
    ['voice_emerging'],
    ['truth_telling', 'expression_need', 'self_definition', 'less_explaining'],
    'taking up too much space',
    'your voice becoming more willing to be heard without shrinking first',
    'Clearer expression can show a voice becoming more willing to be heard.',
    ['voice', 'visibility', 'truth'],
  ),
  creativityPattern(
    'creativity_008_private_vision',
    'The Private Vision Pattern',
    ['vision_gap'],
    ['wants_to_build', 'creative_processing', 'identity_rewriting', 'voice_emerging'],
    'being unrealistic',
    'an inner vision asking for form before the world can understand it',
    'A vivid private vision may be asking for form before it can be understood externally.',
    ['private-vision', 'form', 'building'],
  ),
  creativityPattern(
    'creativity_009_creative_standards_cost',
    'The Creative Standards Cost',
    ['creative_standards'],
    ['low_energy', 'excellence_pressure', 'creative_block', 'self_blame'],
    'never being satisfied',
    'standards needing support so they do not become a source of shame',
    'High creative standards may need support so discernment does not become shame.',
    ['standards', 'cost', 'support'],
  ),
  creativityPattern(
    'creativity_010_joy_of_making',
    'The Joy of Making',
    ['creative_aliveness'],
    ['play_glimmer', 'play_starved', 'joy_tolerance', 'mood_improvement'],
    'wasting time',
    'aliveness returning through the act of making',
    'Flow, play, or creative aliveness can show joy returning through making.',
    ['joy', 'making', 'flow'],
  ),
  creativityPattern(
    'creativity_011_creative_recovery',
    'The Creative Recovery Pattern',
    ['creative_processing'],
    ['mood_improvement', 'relief', 'tension_release', 'meaning_making'],
    'needing escape',
    'creation helping your system metabolize what words alone cannot',
    'Creative work may restore mood or clarity by metabolizing what words alone cannot.',
    ['recovery', 'creation', 'clarity'],
  ),
  creativityPattern(
    'creativity_012_unshared_gift',
    'The Unshared Gift Pattern',
    ['voice_emerging'],
    ['selective_vulnerability', 'fear_of_being_too_much', 'creative_aliveness', 'becoming_visible'],
    'not being ready',
    'a gift waiting for enough safety to become visible',
    'Private expression or hidden talent may be waiting for enough safety to become visible.',
    ['gift', 'visibility', 'safety'],
  ),
  creativityPattern(
    'creativity_013_environment_creativity_link',
    'The Environment and Creativity Link',
    ['beauty_regulation'],
    ['sensory_sensitivity', 'beauty_making', 'creative_aliveness', 'quiet_safety'],
    'needing perfect conditions',
    'your senses helping decide what your imagination can access',
    'The state of the space may affect what the imagination can access.',
    ['environment', 'senses', 'imagination'],
  ),
  creativityPattern(
    'creativity_014_creative_pressure',
    'The Creative Pressure Pattern',
    ['creative_block'],
    ['purpose_signal', 'creative_standards', 'vision_gap', 'self_blame'],
    'making it too serious',
    'meaning mattering enough to make the work feel vulnerable',
    'Pressure to make something meaningful may show the vulnerability of caring deeply about the work.',
    ['pressure', 'meaning', 'vulnerability'],
  ),
  creativityPattern(
    'creativity_015_play_starved',
    'The Play-Starved Pattern',
    ['play_starved'],
    ['longing', 'play_glimmer', 'creative_aliveness', 'low_energy'],
    'being childish',
    'a real need for delight that does not have to justify itself',
    'A lack of play or longing for joy can show a real need for delight.',
    ['play', 'delight', 'joy'],
  ),
  creativityPattern(
    'creativity_016_creative_courage',
    'The Creative Courage Pattern',
    ['voice_emerging'],
    ['becoming_visible', 'selective_vulnerability', 'truth_telling', 'fear_of_being_too_much'],
    'wanting attention',
    'expression becoming brave enough to be witnessed',
    'Sharing or risking visibility can mark expression becoming brave enough to be witnessed.',
    ['courage', 'sharing', 'visibility'],
  ),
  creativityPattern(
    'creativity_017_imagination_as_refuge',
    'The Imagination as Refuge Pattern',
    ['creative_processing'],
    ['dream_searching', 'beauty_making', 'spiritual_depth', 'needs_pause'],
    'escaping reality',
    'imagination giving the inner world a place to breathe',
    'Imagination or daydreaming may give the inner world a needed place to breathe.',
    ['imagination', 'refuge', 'inner-world'],
  ),
  creativityPattern(
    'creativity_018_creative_identity_shift',
    'The Creative Identity Shift',
    ['identity_rewriting'],
    ['creative_aliveness', 'voice_emerging', 'becoming_visible', 'self_definition'],
    'pretending to be something',
    'identity expanding to include what has always been alive in you',
    'Owning creative gifts may show identity expanding to include what has long been alive.',
    ['identity', 'creator', 'gifts'],
  ),
  creativityPattern(
    'creativity_019_beauty_as_truth',
    'The Beauty as Truth Pattern',
    ['beauty_glimmer'],
    ['beauty_making', 'ordinary_sacred', 'spiritual_depth', 'body_lightness'],
    'being sentimental',
    'beauty carrying a truth your system recognizes before words do',
    'Beauty may feel emotionally honest before the user has words for what it means.',
    ['beauty', 'truth', 'recognition'],
  ),
  creativityPattern(
    'creativity_020_unfinished_project_signal',
    'The Unfinished Project Signal',
    ['wants_to_build'],
    ['creative_processing', 'vision_gap', 'creative_block', 'longing'],
    'failing to follow through',
    'a project still holding energy because something in it still matters',
    'Unfinished creative work may linger because something in it still matters.',
    ['unfinished', 'project', 'desire'],
  ),
];
