import type { ArchivePattern, SignalKey } from '../types';

const dreamPattern = (
  key: string,
  title: string,
  requiredSignals: SignalKey[],
  supportingSignals: SignalKey[],
  shameLabel: string,
  clarityReframe: string,
  description: string,
  tags: string[] = [],
): ArchivePattern => ({
  key,
  title,
  category: 'dreamsSymbols',
  description,
  requiredSignals,
  supportingSignals,
  shameLabel,
  clarityReframe,
  lookbackDays: 90,
  minEvidenceCount: 3,
  minScore: 0.56,
  cooldownDays: 10,
  tags,
});

/**
 * Dreams + Symbolic Processing Archive Patterns
 */
export const DREAMS_SYMBOLS_PATTERNS: ArchivePattern[] = [
  dreamPattern(
    'dreams_001_unfinished_processing',
    'When Dreams Continue the Conversation',
    ['dream_unfinished_processing'],
    ['dream_emotional_tone', 'deep_processing', 'emotional_heaviness', 'dream_after_stress'],
    'reading too much into dreams',
    'your inner world trying another language for what has not fully settled yet',
    'Dreams may increase near unresolved waking themes or emotional residue.',
    ['unfinished-processing', 'symbolic', 'residue'],
  ),
  dreamPattern(
    'dreams_002_emotional_tone_beneath_dream',
    'The Emotional Tone Beneath the Dream',
    ['dream_emotional_tone'],
    ['emotional_heaviness', 'longing', 'relief', 'dream_unfinished_processing'],
    'making the dream mean something',
    'the feeling left behind becoming the clearest part of the message',
    'The feeling after the dream may matter more than the plot.',
    ['tone', 'feeling', 'message'],
  ),
  dreamPattern(
    'dreams_003_repeated_symbol',
    'The Repeated Dream Symbol',
    ['dream_repeated_symbol'],
    ['pattern_recognition', 'dream_home', 'dream_searching', 'dream_emotional_tone'],
    'being weird or superstitious',
    'repetition asking to be noticed as part of your symbolic archive',
    'Recurring people, places, objects, rooms, or weather may become part of the symbolic archive.',
    ['recurring-symbol', 'archive', 'repetition'],
  ),
  dreamPattern(
    'dreams_004_after_stress',
    'The Dream After Stress',
    ['dream_after_stress'],
    ['high_stress', 'emotional_intensity', 'dream_unfinished_processing', 'depletion'],
    'not letting the day go',
    'your mind continuing to metabolize what the day did not have room to finish',
    'Vivid dreams after stress may show the mind metabolizing what the day could not finish.',
    ['stress', 'metabolizing', 'vivid'],
  ),
  dreamPattern(
    'dreams_005_searching',
    'The Searching Dream Pattern',
    ['dream_searching'],
    ['longing', 'belonging_ache', 'clarity_before_release', 'autonomy_need'],
    'being restless',
    'an inner search for clarity, belonging, safety, or direction',
    'Searching in dreams may point toward clarity, belonging, safety, or direction.',
    ['searching', 'direction', 'belonging'],
  ),
  dreamPattern(
    'dreams_006_protection',
    'The Protection Dream Pattern',
    ['dream_protection'],
    ['responsibility_weight', 'protective_care', 'caretaking_pressure', 'boundary_rebuilding'],
    'always needing to be responsible',
    'your protective instincts showing up in symbolic form',
    'Guarding, hiding, rescuing, or protecting may show protective instincts in symbolic form.',
    ['protection', 'guarding', 'care'],
  ),
  dreamPattern(
    'dreams_007_loss',
    'The Loss Dream Pattern',
    ['dream_loss'],
    ['sadness', 'longing', 'fear_of_loss', 'dream_emotional_tone'],
    'being stuck in old feelings',
    'grief or attachment moving through images instead of direct language',
    'Loss, missing, or separation dreams may let grief or attachment move through image.',
    ['loss', 'grief', 'attachment'],
  ),
  dreamPattern(
    'dreams_008_home',
    'The Home Dream Pattern',
    ['dream_home'],
    ['home_as_safety', 'family_pattern_awareness', 'belonging_ache', 'identity_rewriting'],
    'dreams being random',
    'your inner world using place to explore safety, identity, memory, or belonging',
    'Houses, rooms, childhood places, or unfamiliar homes may explore safety, identity, memory, or belonging.',
    ['home', 'place', 'memory'],
  ),
  dreamPattern(
    'dreams_009_conflict',
    'The Conflict Dream Pattern',
    ['dream_conflict'],
    ['high_stress', 'repair_need', 'rupture_sensitivity', 'dream_after_stress'],
    'being unable to relax',
    'unresolved pressure rehearsing itself while your waking mind rests',
    'Arguments, chase, threat, or confrontation may rehearse unresolved pressure.',
    ['conflict', 'pressure', 'rehearsal'],
  ),
  dreamPattern(
    'dreams_010_relief',
    'The Relief Dream Pattern',
    ['dream_relief'],
    ['relief', 'quiet_safety', 'beauty_glimmer', 'connection_glimmer'],
    'escaping reality',
    'your mind offering a small experience of relief that your waking life may need more of',
    'Comfort, reunion, beauty, safety, or resolution dreams may offer relief the waking life needs.',
    ['relief', 'comfort', 'safety'],
  ),
  dreamPattern(
    'dreams_011_waking_echo',
    'The Dream-Waking Echo',
    ['dream_emotional_tone'],
    ['dream_unfinished_processing', 'pattern_recognition', 'low_mood', 'meaning_making'],
    'coincidence',
    'the same emotional theme appearing through more than one doorway',
    'A dream theme matching journal or check-in data may show the same theme through more than one doorway.',
    ['echo', 'cross-source', 'theme'],
  ),
  dreamPattern(
    'dreams_012_after_glimmer',
    'The Dream After a Glimmer',
    ['dream_relief'],
    ['glimmer_softening', 'connection_glimmer', 'nature_regulation', 'beauty_glimmer'],
    'the glimmer being too small to matter',
    'small safety signals changing what the night mind has to carry',
    'Softer dreams after relief, connection, nature, or beauty may show safety changing the night mind.',
    ['glimmer', 'night-mind', 'softening'],
  ),
  dreamPattern(
    'dreams_013_that_lingers',
    'The Dream That Lingers',
    ['dream_emotional_tone'],
    ['emotional_heaviness', 'longing', 'dream_repeated_symbol', 'asks_why'],
    'being too affected',
    'an image or feeling staying because something in it wants attention',
    'A dream that stays present through the day may contain an image or feeling asking for attention.',
    ['lingering', 'image', 'attention'],
  ),
  dreamPattern(
    'dreams_014_being_unprepared',
    'The Dream of Being Unprepared',
    ['dream_searching'],
    ['preparedness', 'always_on', 'responsibility_weight', 'high_stress'],
    'being irresponsible',
    'pressure around readiness finding a symbolic stage',
    'Being late, lost, missing items, or unfinished in a dream may stage pressure around readiness.',
    ['unprepared', 'readiness', 'pressure'],
  ),
  dreamPattern(
    'dreams_015_being_seen',
    'The Dream of Being Seen',
    ['dream_emotional_tone'],
    ['becoming_visible', 'selective_vulnerability', 'wants_to_be_seen', 'fear_of_being_too_much'],
    'insecurity',
    'the tension between wanting to be known and wanting to feel safe while being known',
    'Exposure, visibility, being watched, or being known may hold the tension between visibility and safety.',
    ['visibility', 'known', 'safety'],
  ),
  dreamPattern(
    'dreams_016_escape',
    'The Dream of Escape',
    ['dream_searching'],
    ['distance_for_safety', 'autonomy_need', 'needs_pause', 'high_stress'],
    'avoidance',
    'a part of your system looking for room, relief, or a way out of pressure',
    'Trying to leave, hide, run, or find an exit may show the system looking for relief from pressure.',
    ['escape', 'pressure', 'relief'],
  ),
  dreamPattern(
    'dreams_017_return',
    'The Dream of Return',
    ['dream_home'],
    ['old_story_loosening', 'past_self_compassion', 'identity_rewriting', 'dream_loss'],
    'going backward',
    'the archive revisiting something to understand it with more of you present',
    'Returning to an old place, relationship, or self may revisit the past with more of the current self present.',
    ['return', 'past', 'revisit'],
  ),
  dreamPattern(
    'dreams_018_water',
    'The Dream of Water',
    ['dream_emotional_tone'],
    ['emotional_intensity', 'emotional_softening', 'dream_loss', 'dream_relief'],
    'random imagery',
    'emotion showing up as movement, depth, overwhelm, cleansing, or flow',
    'Ocean, flood, rain, lake, river, or bath imagery may give emotional movement a visible form.',
    ['water', 'emotion', 'flow'],
  ),
  dreamPattern(
    'dreams_019_weather',
    'The Dream of Weather',
    ['dream_emotional_tone'],
    ['emotional_heaviness', 'hope', 'dream_conflict', 'dream_relief'],
    'meaningless background',
    'your inner climate becoming visible through atmosphere',
    'Storms, sky, wind, clouds, or light may render the inner climate as atmosphere.',
    ['weather', 'atmosphere', 'inner-climate'],
  ),
  dreamPattern(
    'dreams_020_doors_and_rooms',
    'The Dream of Doors and Rooms',
    ['dream_home'],
    ['dream_searching', 'autonomy_need', 'selective_vulnerability', 'identity_rewriting'],
    'overanalyzing symbols',
    'your inner world exploring access, privacy, possibility, and what is not yet fully opened',
    'Locked doors, new rooms, hidden rooms, or hallways may explore access, privacy, and possibility.',
    ['doors', 'rooms', 'possibility'],
  ),
];
