import type { ArchivePattern, SignalKey } from '../types';

const emotionalWeatherPattern = (
  key: string,
  title: string,
  requiredSignals: SignalKey[],
  supportingSignals: SignalKey[],
  shameLabel: string,
  clarityReframe: string,
  description: string,
  tags: string[] = [],
): ArchivePattern => ({
  key,
  title,
  category: 'emotionalWeather',
  description,
  requiredSignals,
  supportingSignals,
  shameLabel,
  clarityReframe,
  lookbackDays: 30,
  minEvidenceCount: 3,
  minScore: 0.56,
  cooldownDays: 7,
  tags,
});

/**
 * Emotional Weather Archive Patterns
 */
export const EMOTIONAL_WEATHER_PATTERNS: ArchivePattern[] = [
  emotionalWeatherPattern(
    'emotional_weather_001_low_capacity_day',
    'The Low-Light Day',
    ['low_capacity'],
    ['low_mood', 'low_energy', 'emotional_heaviness', 'sadness'],
    'being negative',
    'an inner climate asking for gentleness instead of judgment',
    'Low mood, low energy, or heaviness suggest a day where the inner weather needs gentler handling.',
    ['low-mood', 'capacity', 'gentleness'],
  ),
  emotionalWeatherPattern(
    'emotional_weather_002_heavy_morning',
    'The Heavy Morning Pattern',
    ['low_mood', 'low_energy'],
    ['poor_sleep_quality', 'low_sleep', 'body_heaviness', 'sleep_mood_link'],
    'waking up wrong',
    'the day beginning with information about what still needs care',
    'The start of the day carries useful information about sleep, recovery, and emotional residue.',
    ['morning', 'sleep', 'body-heaviness'],
  ),
  emotionalWeatherPattern(
    'emotional_weather_003_evening_drop',
    'The Evening Drop',
    ['mood_drop'],
    ['low_energy', 'emotional_heaviness', 'depletion', 'capacity_strain'],
    'losing control of the day',
    'feelings becoming louder once there is less energy to hold them back',
    'Mood may lower later in the day as fatigue reduces the energy available for emotional holding.',
    ['evening', 'fatigue', 'mood-drop'],
  ),
  emotionalWeatherPattern(
    'emotional_weather_004_fine_until_quiet',
    'Fine Until Quiet',
    ['sadness'],
    ['always_on', 'mental_load', 'emotional_heaviness', 'needs_pause'],
    'suddenly falling apart',
    'emotion finding the first quiet place available',
    'Sadness may emerge once busyness stops and the system finally has room to feel.',
    ['stillness', 'sadness', 'delayed-feeling'],
  ),
  emotionalWeatherPattern(
    'emotional_weather_005_mixed_weather',
    'The Mixed Weather Pattern',
    ['mixed_emotions'],
    ['gratitude_and_grief', 'hope', 'sadness', 'relief', 'longing'],
    'being contradictory',
    'more than one emotional truth asking to belong',
    'The archive shows more than one emotional state present at once instead of one clear mood.',
    ['mixed-emotions', 'two-truths', 'complexity'],
  ),
  emotionalWeatherPattern(
    'emotional_weather_006_high_stress_narrowing',
    'The High-Stress Narrowing',
    ['high_stress'],
    ['emotional_intensity', 'anger', 'capacity_strain', 'overextension'],
    'overreacting',
    'pressure narrowing the day until everything feels closer and louder',
    'High stress may narrow perspective, making ordinary demands feel more urgent or emotionally loud.',
    ['stress', 'urgency', 'pressure'],
  ),
  emotionalWeatherPattern(
    'emotional_weather_007_tender_day',
    'The Tender Day',
    ['sadness'],
    ['emotional_softening', 'low_mood', 'longing', 'body_heaviness'],
    'being too sensitive',
    'a softer inner state that needs gentler handling',
    'Sadness, softness, or vulnerability indicate tenderness rather than failure.',
    ['tenderness', 'sadness', 'vulnerability'],
  ),
  emotionalWeatherPattern(
    'emotional_weather_008_irritable_capacity_signal',
    'The Irritable Capacity Signal',
    ['anger'],
    ['low_energy', 'overextension', 'capacity_strain', 'high_stress'],
    'being mean or impatient',
    'a strained system asking for less pressure and more recovery',
    'Irritability may be a capacity signal when it appears near fatigue or overload.',
    ['irritability', 'capacity', 'overload'],
  ),
  emotionalWeatherPattern(
    'emotional_weather_009_emotional_static',
    'The Emotional Static Pattern',
    ['mixed_emotions'],
    ['high_stress', 'deep_processing', 'asks_why', 'emotional_intensity'],
    'being messy',
    'too many signals competing for attention at once',
    'Unclear mood, scattered thoughts, and stress can point to emotional static rather than personal messiness.',
    ['static', 'stress', 'unclear-mood'],
  ),
  emotionalWeatherPattern(
    'emotional_weather_010_quiet_hope_signal',
    'The Quiet Hope Signal',
    ['hope'],
    ['relief', 'glimmer_softening', 'quiet_safety', 'mood_improvement'],
    'not being fully better',
    'hope entering in a small enough form to be trusted',
    'Small relief or hope can be meaningful even when the larger problem is unresolved.',
    ['hope', 'glimmer', 'relief'],
  ),
  emotionalWeatherPattern(
    'emotional_weather_011_mood_after_conflict',
    'The Mood-After-Conflict Pattern',
    ['mood_drop'],
    ['repair_need', 'rupture_sensitivity', 'body_heaviness', 'chest_pressure'],
    'letting things affect you too much',
    'connection stress leaving an emotional afterimage',
    'Conflict or relational stress can leave a mood imprint after the interaction ends.',
    ['conflict', 'after-effect', 'relationships'],
  ),
  emotionalWeatherPattern(
    'emotional_weather_012_mood_after_sleep',
    'The Mood-After-Sleep Pattern',
    ['sleep_mood_link'],
    ['low_sleep', 'poor_sleep_quality', 'mood_drop', 'mood_improvement'],
    'being unpredictable',
    'recovery influencing how much emotional weight the day can hold',
    'Sleep quality appears linked to changes in mood or emotional capacity.',
    ['sleep', 'mood', 'recovery'],
  ),
  emotionalWeatherPattern(
    'emotional_weather_013_overfull_day',
    'The Overfull Day',
    ['overextension'],
    ['high_stress', 'sensory_sensitivity', 'low_energy', 'emotional_intensity'],
    'not handling enough',
    'a day with more emotional volume than your system could comfortably sort',
    'Too many inputs, demands, or emotional cues may overfill the system.',
    ['overfull', 'stress', 'inputs'],
  ),
  emotionalWeatherPattern(
    'emotional_weather_014_low_noise_need',
    'The Low-Noise Need',
    ['sensory_sensitivity'],
    ['low_energy', 'body_heaviness', 'needs_pause', 'calm_bracing'],
    'being difficult',
    'a system asking for less input so it can come back to itself',
    'Overstimulation or sensory load may signal a need for less noise and more internal space.',
    ['sensory', 'quiet', 'overstimulation'],
  ),
  emotionalWeatherPattern(
    'emotional_weather_015_emotional_hangover',
    'The Emotional Hangover',
    ['emotional_heaviness'],
    ['high_stress', 'depletion', 'body_heaviness', 'needs_pause'],
    'dragging things out',
    'the body and mind metabolizing what the moment did not have room to finish',
    'The day after a trigger or intensity may carry residual emotional heaviness.',
    ['hangover', 'post-trigger', 'metabolizing'],
  ),
  emotionalWeatherPattern(
    'emotional_weather_016_tender_recovery_window',
    'The Tender Recovery Window',
    ['emotional_softening'],
    ['needs_pause', 'low_energy', 'quiet_safety', 'somatic_safety'],
    'being fragile',
    'the period after intensity where gentleness matters most',
    'After stress or intensity, the archive may show a window where gentleness is especially important.',
    ['recovery', 'softness', 'aftercare'],
  ),
  emotionalWeatherPattern(
    'emotional_weather_017_sudden_softening',
    'The Sudden Softening',
    ['glimmer_softening'],
    ['relief', 'mood_improvement', 'body_lightness', 'quiet_safety'],
    'being inconsistent',
    'proof that the inner weather can shift when the right support appears',
    'A glimmer or supportive moment may create a noticeable shift in mood or body state.',
    ['softening', 'glimmer', 'mood-shift'],
  ),
  emotionalWeatherPattern(
    'emotional_weather_018_pressure_under_surface',
    'The Pressure Under the Surface',
    ['body_knows_first'],
    ['high_stress', 'chest_pressure', 'shoulder_burden', 'jaw_restraint'],
    'making something out of nothing',
    'the body registering pressure before the mood score changes',
    'Body tension or stress may appear before the user names a mood shift.',
    ['body-signal', 'pressure', 'subtle'],
  ),
  emotionalWeatherPattern(
    'emotional_weather_019_hidden_grief_day',
    'The Hidden Grief Day',
    ['sadness'],
    ['longing', 'low_energy', 'low_mood', 'emotional_heaviness'],
    'being stuck',
    'grief moving quietly through ordinary hours',
    'Sadness, longing, and low energy can point to grief moving quietly through an ordinary day.',
    ['grief', 'longing', 'low-energy'],
  ),
  emotionalWeatherPattern(
    'emotional_weather_020_emotional_reset',
    'The Emotional Reset',
    ['mood_improvement'],
    ['relief', 'tension_release', 'emotional_softening', 'quiet_safety'],
    'only feeling better temporarily',
    'a real moment of return, even if everything is not resolved',
    'Improved mood or regulation can be a genuine reset even when the larger story is unfinished.',
    ['reset', 'return', 'regulation'],
  ),
];
