import type { ArchivePattern, SignalKey } from '../types';

const familyPattern = (
  key: string,
  title: string,
  requiredSignals: SignalKey[],
  supportingSignals: SignalKey[],
  shameLabel: string,
  clarityReframe: string,
  description: string,
  tags: string[] = [],
): ArchivePattern => ({
  key,
  title,
  category: 'familyHome',
  description,
  requiredSignals,
  supportingSignals,
  shameLabel,
  clarityReframe,
  lookbackDays: 180,
  minEvidenceCount: 3,
  minScore: 0.56,
  cooldownDays: 14,
  tags,
});

/**
 * Family + Home Archive Patterns
 */
export const FAMILY_HOME_PATTERNS: ArchivePattern[] = [
  familyPattern(
    'family_001_pattern_awareness',
    'The Family Pattern Awareness',
    ['family_pattern_awareness'],
    ['breaks_old_pattern', 'family_loyalty_tension', 'meaning_making', 'identity_rewriting'],
    'blaming family',
    'seeing the pattern clearly enough to choose what continues and what ends',
    'Noticing inherited or repeated family patterns can support choice about what continues and what ends.',
    ['family-patterns', 'awareness', 'choice'],
  ),
  familyPattern(
    'family_002_loyalty_tension',
    'The Family Loyalty Tension',
    ['family_loyalty_tension'],
    ['loyalty_conflict', 'anger', 'truth_telling', 'sadness'],
    'being disloyal',
    'trying to honor connection without abandoning what is true',
    'Love, loyalty, anger, and honesty may pull in different directions around family.',
    ['loyalty', 'truth', 'family'],
  ),
  familyPattern(
    'family_003_chosen_family',
    'The Chosen Family Pattern',
    ['chosen_family'],
    ['belonging_ache', 'connection_glimmer', 'mutuality_need', 'support_need'],
    'not having a normal family',
    'belonging being built where love is practiced, not only inherited',
    'Chosen support can show belonging being built through practiced care.',
    ['chosen-family', 'belonging', 'care'],
  ),
  familyPattern(
    'family_004_home_as_safety',
    'Home as Safety',
    ['home_as_safety'],
    ['quiet_safety', 'somatic_safety', 'body_lightness', 'rooting_need'],
    'needing too much control over space',
    'home becoming a container where the inner world can finally exhale',
    'Space, privacy, calm, and settled body cues may make home a container for exhale.',
    ['home', 'safety', 'privacy'],
  ),
  familyPattern(
    'family_005_rooting_need',
    'The Rooting Need',
    ['rooting_need'],
    ['home_as_safety', 'ritual_regulation', 'enoughness', 'quiet_safety'],
    'being rigid',
    'roots giving growth somewhere safe to happen from',
    'Stability, routines, place, or security may give growth somewhere safe to happen from.',
    ['roots', 'stability', 'security'],
  ),
  familyPattern(
    'family_006_ritual_regulation',
    'Ritual Regulation',
    ['ritual_regulation'],
    ['ordinary_sacred', 'home_as_safety', 'quiet_safety', 'somatic_safety'],
    'being repetitive',
    'ritual helping safety become something the body can predict',
    'Family rituals, daily rhythms, or repeated comforts may help safety become predictable.',
    ['ritual', 'predictable', 'safety'],
  ),
  familyPattern(
    'family_007_protective_care',
    'The Protective Care Pattern',
    ['protective_care'],
    ['dream_protection', 'responsibility_weight', 'family_pattern_awareness', 'boundary_rebuilding'],
    'being overprotective',
    'care becoming active where vulnerability deserves attention',
    'Protecting children, pets, loved ones, or vulnerable people may show care becoming active.',
    ['protective-care', 'vulnerability', 'family'],
  ),
  familyPattern(
    'family_008_pattern_breaker',
    'The Pattern Breaker',
    ['breaks_old_pattern'],
    ['family_pattern_awareness', 'identity_rewriting', 'boundary_rebuilding', 'growth_edge'],
    'being dramatic about the past',
    'a conscious choice to stop passing forward what harmed you or others',
    'Refusing inherited patterns or choosing differently can mark conscious pattern-breaking.',
    ['pattern-breaker', 'inheritance', 'choice'],
  ),
  familyPattern(
    'family_009_home_atmosphere',
    'The Home Atmosphere Pattern',
    ['home_as_safety'],
    ['sensory_sensitivity', 'quiet_safety', 'body_heaviness', 'body_lightness'],
    'being too affected by environment',
    'atmosphere shaping what your system believes is possible inside a space',
    'The emotional tone of home may shape what the system believes is possible inside a space.',
    ['atmosphere', 'home', 'environment'],
  ),
  familyPattern(
    'family_010_family_role',
    'The Family Role Pattern',
    ['family_pattern_awareness'],
    ['caretaking_pressure', 'responsibility_weight', 'peace_boundary', 'breaks_old_pattern'],
    'being stuck in old roles',
    'an old role becoming visible enough to be renegotiated',
    'Caretaker, fixer, peacekeeper, or responsible-one roles may become visible enough to renegotiate.',
    ['roles', 'caretaker', 'renegotiation'],
  ),
  familyPattern(
    'family_011_belonging_at_home',
    'The Belonging at Home Pattern',
    ['belonging_ache'],
    ['home_as_safety', 'chosen_family', 'wants_to_be_seen', 'self_definition'],
    'being hard to satisfy',
    'the need for a place where your whole self can arrive',
    'Feeling at home or not at home may show the need for a place where the whole self can arrive.',
    ['belonging', 'home', 'whole-self'],
  ),
  familyPattern(
    'family_012_home_reset',
    'The Home Reset Pattern',
    ['home_as_safety'],
    ['ritual_regulation', 'beauty_regulation', 'quiet_safety', 'creative_processing'],
    'being controlling',
    'shaping the outer space to help the inner world settle',
    'Cleaning, organizing, rearranging, or nesting may shape outer space so the inner world can settle.',
    ['home-reset', 'nesting', 'space'],
  ),
  familyPattern(
    'family_013_safe_corner',
    'The Safe Corner Pattern',
    ['home_as_safety'],
    ['quiet_safety', 'somatic_safety', 'sensory_sensitivity', 'body_lightness'],
    'hiding',
    'a small place of refuge helping your system feel held',
    'A specific comforting room, place, or spot may provide refuge.',
    ['refuge', 'safe-corner', 'held'],
  ),
  familyPattern(
    'family_014_family_boundary',
    'The Family Boundary Pattern',
    ['boundary_rebuilding'],
    ['family_loyalty_tension', 'guilt', 'responsibility_weight', 'self_trust_growth'],
    'being cold or ungrateful',
    'love needing limits so it does not become self-abandonment',
    'Limits with family can let love continue without becoming self-abandonment.',
    ['family-boundary', 'limits', 'love'],
  ),
  familyPattern(
    'family_015_family_grief_thread',
    'The Family Grief Thread',
    ['sadness'],
    ['longing', 'family_pattern_awareness', 'belonging_ache', 'emotional_heaviness'],
    'not moving on',
    'the ache of what family should have been still asking for tenderness',
    'Grief around family, absence, or unmet needs may still ask for tenderness.',
    ['family-grief', 'absence', 'tenderness'],
  ),
  familyPattern(
    'family_016_family_joy_thread',
    'The Family Joy Thread',
    ['connection_glimmer'],
    ['ritual_regulation', 'chosen_family', 'ordinary_sacred', 'relief'],
    'it being too small to count',
    'small family joy becoming evidence of what is being built now',
    'Warmth, rituals, connection, or chosen moments may show what is being built now.',
    ['family-joy', 'warmth', 'evidence'],
  ),
  familyPattern(
    'family_017_generational_choice',
    'The Generational Choice Pattern',
    ['breaks_old_pattern'],
    ['values_conflict', 'protective_care', 'repair_need', 'truth_telling'],
    'trying too hard',
    'a deliberate choice to make the next version kinder than the one you inherited',
    'New responses, values, parenting, or repair may make the next version kinder.',
    ['generational-choice', 'repair', 'kindness'],
  ),
  familyPattern(
    'family_018_home_body_signal',
    'The Home-Body Signal',
    ['body_knows_first'],
    ['home_as_safety', 'body_lightness', 'body_heaviness', 'somatic_safety'],
    'being too particular',
    'your body telling the truth about whether a space feels safe',
    'The body relaxing or tensing at home may tell the truth about whether the space feels safe.',
    ['home-body', 'safety', 'somatic'],
  ),
  familyPattern(
    'family_019_household_load',
    'The Household Load Pattern',
    ['invisible_labor'],
    ['mental_load', 'responsibility_weight', 'caretaking_pressure', 'anger'],
    'being resentful',
    'the weight of what keeps life running becoming visible',
    'Chores, planning, logistics, and invisible labor may reveal the weight of what keeps life running.',
    ['household-load', 'invisible-labor', 'logistics'],
  ),
  familyPattern(
    'family_020_sanctuary',
    'The Sanctuary Pattern',
    ['home_as_safety'],
    ['beauty_regulation', 'quiet_safety', 'somatic_safety', 'beauty_making'],
    'being too focused on the environment',
    'building a place where your system does not have to brace',
    'Creating a beautiful, calm, safe space may build a place where the system does not have to brace.',
    ['sanctuary', 'beauty', 'brace'],
  ),
];
