import type { ArchivePattern, SignalKey } from '../types';

const glimmerPattern = (
  key: string,
  title: string,
  requiredSignals: SignalKey[],
  supportingSignals: SignalKey[],
  shameLabel: string,
  clarityReframe: string,
  description: string,
  tags: string[] = [],
): ArchivePattern => ({
  key,
  title,
  category: 'glimmersRegulation',
  description,
  requiredSignals,
  supportingSignals,
  shameLabel,
  clarityReframe,
  lookbackDays: 30,
  minEvidenceCount: 2,
  minScore: 0.5,
  cooldownDays: 7,
  tags,
});

/**
 * Glimmers + Regulation Archive Patterns
 */
export const GLIMMERS_REGULATION_PATTERNS: ArchivePattern[] = [
  glimmerPattern(
    'glimmers_001_quiet_relief',
    'What Actually Softens You',
    ['glimmer_softening'],
    ['relief', 'body_lightness', 'tension_release', 'somatic_safety'],
    'needing specific conditions',
    'your system showing what safety actually feels like in practice',
    'Glimmers, relief, and softer body cues may show what safety feels like in practice.',
    ['softening', 'safety', 'body'],
  ),
  glimmerPattern(
    'glimmers_002_quiet_safety',
    'How You Hold Calm',
    ['quiet_safety'],
    ['low_stress', 'somatic_safety', 'calm_is_new', 'restorative_moment'],
    'pessimism',
    'a protective mechanism trying to keep you safe in the unfamiliar territory of things simply being okay',
    'When the data points toward ease or joy, there is often a corresponding spike in anticipation—a quiet bracing for the next challenge.',
    ['quiet', 'calm', 'stillness'],
  ),
  glimmerPattern(
    'glimmers_003_nature_regulated',
    'The Nature-Regulated Pattern',
    ['nature_regulation'],
    ['quiet_safety', 'beauty_glimmer', 'body_lightness', 'ordinary_sacred'],
    'needing to escape',
    'the natural world giving your system a rhythm it can trust',
    'Nature, seasons, sky, water, or trees may give the system a trustworthy rhythm.',
    ['nature', 'rhythm', 'regulation'],
  ),
  glimmerPattern(
    'glimmers_004_beauty_glimmer',
    'The Beauty Glimmer',
    ['beauty_glimmer'],
    ['beauty_regulation', 'body_lightness', 'ordinary_sacred', 'quiet_safety'],
    'being superficial',
    'beauty becoming a real pathway back to steadiness',
    'Color, light, atmosphere, softness, or design may become a pathway back to steadiness.',
    ['beauty', 'steadiness', 'senses'],
  ),
  glimmerPattern(
    'glimmers_005_connection_glimmer',
    'The Connection Glimmer',
    ['connection_glimmer'],
    ['relief', 'wants_to_be_seen', 'laughter_glimmer', 'receiving_openness'],
    'needing people too much',
    'connection reminding your system that care can be safe and real',
    'Being understood, warmth, kindness, check-ins, or laughter may remind the system that care can be safe.',
    ['connection', 'care', 'warmth'],
  ),
  glimmerPattern(
    'glimmers_006_play_glimmer',
    'The Play Glimmer',
    ['play_glimmer'],
    ['play_starved', 'laughter_glimmer', 'joy_tolerance', 'creative_aliveness'],
    'being childish',
    'delight giving the inner world a low-stakes place to breathe',
    'Fun, silliness, games, play, or ease may give the inner world low-stakes breathing room.',
    ['play', 'delight', 'ease'],
  ),
  glimmerPattern(
    'glimmers_007_laughter_release',
    'The Laughter as Release Pattern',
    ['laughter_glimmer'],
    ['body_lightness', 'tension_release', 'relief', 'emotional_softening'],
    'deflecting',
    'laughter letting the body release without dismissing what mattered',
    'Humor and laughter may let the body release without dismissing the serious thing.',
    ['laughter', 'release', 'humor'],
  ),
  glimmerPattern(
    'glimmers_008_ordinary_sacred',
    'The Ordinary Sacred Pattern',
    ['ordinary_sacred'],
    ['gratitude_and_grief', 'beauty_glimmer', 'faith_meaning', 'ritual_regulation'],
    'romanticizing ordinary life',
    'depth noticing meaning where the world often rushes past it',
    'Small meaningful moments, gratitude, or ritual may reveal meaning in ordinary life.',
    ['ordinary', 'sacred', 'ritual'],
  ),
  glimmerPattern(
    'glimmers_009_joy_tolerance',
    'How You Hold Joy',
    ['joy_tolerance'],
    ['calm_bracing', 'fear_of_loss', 'hope', 'play_glimmer'],
    'pessimism',
    'a protective mechanism trying to keep you safe in the unfamiliar territory of things simply being okay',
    'Your system is highly attuned to solving problems, making the absence of conflict feel unfamiliar, and perhaps unguarded.',
    ['joy', 'bracing', 'stillness'],
  ),
  glimmerPattern(
    'glimmers_010_calm_is_new',
    'The Calm-Is-New Pattern',
    ['calm_is_new'],
    ['quiet_safety', 'calm_bracing', 'low_stress', 'somatic_safety'],
    'not knowing how to relax',
    'your system learning a newer language: nothing is required right now',
    'Calm may feel unfamiliar because the system is learning that nothing is required right now.',
    ['calm', 'new-language', 'relaxing'],
  ),
  glimmerPattern(
    'glimmers_011_numbness_versus_calm',
    'The Numbness Versus Calm Pattern',
    ['numbness_vs_calm'],
    ['calm_is_new', 'somatic_safety', 'body_heaviness', 'self_trust_growth'],
    'being broken',
    'careful self-attunement learning the difference between being settled and being far from yourself',
    'Flatness or stillness may invite careful distinction between calm and disconnection.',
    ['numbness', 'calm', 'attunement'],
  ),
  glimmerPattern(
    'glimmers_012_small_safety_signal',
    'The Small Safety Signal',
    ['quiet_safety'],
    ['glimmer_softening', 'low_stress', 'body_lightness', 'relief'],
    'too small to matter',
    'a tiny signal of safety becoming evidence your system can recognize',
    'A small relief cue, lowered stress, or softened body signal can count as evidence of safety.',
    ['small-safety', 'evidence', 'relief'],
  ),
  glimmerPattern(
    'glimmers_013_return_through_routine',
    'The Return Through Routine Pattern',
    ['ritual_regulation'],
    ['quiet_safety', 'ordinary_sacred', 'home_as_safety', 'somatic_safety'],
    'being boring',
    'repetition giving your system a way to come back to itself',
    'Routine, ritual, or familiar rhythm may give the system a way to return.',
    ['routine', 'ritual', 'return'],
  ),
  glimmerPattern(
    'glimmers_014_comfort_object',
    'The Comfort Object Pattern',
    ['quiet_safety'],
    ['sensory_sensitivity', 'beauty_regulation', 'body_lightness', 'somatic_safety'],
    'being childish or dependent',
    'comfort becoming tangible enough for the body to receive',
    'A blanket, tea, music, scent, texture, object, or place may make comfort tangible.',
    ['comfort', 'object', 'sensory'],
  ),
  glimmerPattern(
    'glimmers_015_music_shift',
    'The Music Shift Pattern',
    ['emotional_softening'],
    ['tension_release', 'relief', 'creative_processing', 'body_lightness'],
    'being overly affected',
    'sound giving emotion a path to move',
    'Music changing mood or body state may show sound giving emotion a path to move.',
    ['music', 'sound', 'emotion'],
  ),
  glimmerPattern(
    'glimmers_016_light_shift',
    'The Light Shift Pattern',
    ['beauty_glimmer'],
    ['beauty_regulation', 'mood_improvement', 'ordinary_sacred', 'quiet_safety'],
    'needing perfect conditions',
    'light helping your inner weather find its horizon',
    'Sunlight, dim light, candles, or morning/evening light may shift inner weather.',
    ['light', 'weather', 'senses'],
  ),
  glimmerPattern(
    'glimmers_017_safe_stillness',
    'When Stillness Feels Safe',
    ['somatic_safety'],
    ['quiet_safety', 'calm_is_new', 'low_stress', 'body_lightness'],
    'pessimism',
    'a protective mechanism trying to keep you safe in the unfamiliar territory of things simply being okay',
    'Your entries show a complex relationship with moments of calm, where the absence of conflict can feel unfamiliar.',
    ['stillness', 'return', 'calm'],
  ),
  glimmerPattern(
    'glimmers_018_grounding_through_making',
    'The Grounding Through Making Pattern',
    ['creative_processing'],
    ['body_lightness', 'quiet_safety', 'ritual_regulation', 'tension_release'],
    'distracting yourself',
    'hands giving the mind somewhere safe to settle',
    'Cooking, cleaning, organizing, building, art, or hands-on activity may ground the mind.',
    ['hands', 'making', 'grounding'],
  ),
  glimmerPattern(
    'glimmers_019_gentle_transition',
    'The Gentle Transition Pattern',
    ['needs_pause'],
    ['quiet_safety', 'low_stress', 'body_lightness', 'self_trust_growth'],
    'needing too much time',
    'transitions becoming kinder when your system is not rushed across them',
    'Ease after slower transitions or buffer time may show what kind transitions require.',
    ['transition', 'buffer', 'ease'],
  ),
  glimmerPattern(
    'glimmers_020_glimmer_that_lasted',
    'The Glimmer That Lasted',
    ['glimmer_softening'],
    ['mood_improvement', 'relief', 'hope', 'integrates_insight'],
    'temporary improvement not counting',
    'a small moment of relief becoming part of the archive, even if it did not fix everything',
    'Relief that carries forward can become part of the archive even without fixing everything.',
    ['lasting-glimmer', 'relief', 'archive'],
  ),
];
