import type { ArchivePattern, SignalKey } from '../types';

const identityPattern = (
  key: string,
  title: string,
  requiredSignals: SignalKey[],
  supportingSignals: SignalKey[],
  shameLabel: string,
  clarityReframe: string,
  description: string,
  tags: string[] = [],
): ArchivePattern => ({
  key,
  title,
  category: 'identityGrowth',
  description,
  requiredSignals,
  supportingSignals,
  shameLabel,
  clarityReframe,
  lookbackDays: 180,
  minEvidenceCount: 3,
  minScore: 0.58,
  cooldownDays: 14,
  tags,
});

/**
 * Identity + Growth Archive Patterns
 */
export const IDENTITY_GROWTH_PATTERNS: ArchivePattern[] = [
  identityPattern(
    'identity_002_old_story_loosening',
    'The Old Story Is Loosening',
    ['old_story_loosening'],
    ['identity_rewriting', 'self_definition', 'past_self_compassion', 'truth_telling'],
    'confusion',
    'self-definition becoming more honest than inheritance',
    'An old label or inherited self-story may be loosening as a more honest definition emerges.',
    ['old-story', 'self-definition', 'inheritance'],
  ),
  identityPattern(
    'identity_001_transformation_seeker',
    'The Person You Are Becoming',
    ['transformation_season'],
    ['future_self_orientation', 'growth_edge', 'self_definition', 'chapter_shift'],
    'not knowing who you are',
    'becoming before the new shape has fully settled',
    'The user may be living between an old identity and a still-forming future self.',
    ['becoming', 'future-self', 'growth'],
  ),
  identityPattern(
    'identity_003_chapter_shift',
    'The Chapter Shift',
    ['chapter_shift'],
    ['transformation_season', 'identity_rewriting', 'future_self_orientation', 'old_story_loosening'],
    'instability',
    'a life chapter changing before every part of you has caught up',
    'A life season may be changing before every part of the user has caught up.',
    ['chapter', 'transition', 'season'],
  ),
  identityPattern(
    'identity_004_current_season',
    'The Current Season',
    ['transformation_season'],
    ['pattern_recognition', 'growth_edge', 'chapter_shift', 'meaning_making'],
    'being stuck',
    'a season asking for attention, not a permanent identity',
    'Repeating themes across recent weeks may be a season, not a fixed identity.',
    ['season', 'theme', 'attention'],
  ),
  identityPattern(
    'identity_005_past_self_compassion',
    'The Past-Self Compassion Pattern',
    ['past_self_compassion'],
    ['self_forgiveness', 'inner_critic_softening', 'meaning_making', 'sadness'],
    'dwelling',
    'protection finally moving backward through the story',
    'Tenderness toward an earlier self can show protection moving backward through the story.',
    ['past-self', 'compassion', 'protection'],
  ),
  identityPattern(
    'identity_006_future_self_builder',
    'The Future-Self Builder',
    ['future_self_orientation'],
    ['purpose_signal', 'wants_to_build', 'growth_edge', 'self_definition'],
    'putting pressure on yourself',
    'devotion to building a life your future self can breathe inside',
    'Choices may be shaped by devotion to a life the future self can breathe inside.',
    ['future-self', 'building', 'devotion'],
  ),
  identityPattern(
    'identity_007_self_forgiveness',
    'The Self-Forgiveness Pattern',
    ['self_forgiveness'],
    ['guilt', 'repair_need', 'inner_critic_softening', 'moral_weight'],
    'letting yourself off the hook',
    'repair without turning every mistake into a sentence against yourself',
    'Accountability may be separating from shame so repair does not become self-punishment.',
    ['forgiveness', 'repair', 'accountability'],
  ),
  identityPattern(
    'identity_008_inner_critic_softening',
    'The Inner Critic Softening',
    ['inner_critic_softening'],
    ['self_blame', 'self_forgiveness', 'past_self_compassion', 'emotional_softening'],
    'making excuses',
    'truth becoming kinder without becoming less honest',
    'Self-talk may be getting kinder without becoming less truthful.',
    ['inner-critic', 'kindness', 'truth'],
  ),
  identityPattern(
    'identity_009_becoming_visible',
    'The Becoming Visible Pattern',
    ['becoming_visible'],
    ['voice_emerging', 'self_definition', 'truth_telling', 'selective_vulnerability'],
    'wanting attention',
    'the self becoming visible after being edited for too long',
    'Authenticity, expression, or being seen may show the self becoming less edited.',
    ['visibility', 'authenticity', 'self'],
  ),
  identityPattern(
    'identity_010_between_worlds',
    'The Identity Between Worlds',
    ['identity_rewriting'],
    ['old_story_loosening', 'chapter_shift', 'transformation_season', 'self_definition'],
    'being lost',
    'the disorientation of becoming someone more true',
    'An old role may be fading before a new role is fully formed.',
    ['between-worlds', 'role', 'disorientation'],
  ),
  identityPattern(
    'identity_011_role_outgrowing',
    'The Role You Are Outgrowing',
    ['old_story_loosening'],
    ['responsibility_weight', 'identity_rewriting', 'boundary_rebuilding', 'growth_edge'],
    'being ungrateful',
    'growth making an old role too small to keep living inside',
    'An old responsibility or persona may be becoming too small for current growth.',
    ['role', 'outgrowing', 'growth'],
  ),
  identityPattern(
    'identity_012_story_revising',
    'The Story You Are Revising',
    ['identity_rewriting'],
    ['meaning_making', 'past_self_compassion', 'self_forgiveness', 'truth_telling'],
    'rewriting history',
    'giving your life a more accurate and generous interpretation',
    'An old belief may be getting a more accurate and generous interpretation.',
    ['story', 'revision', 'meaning'],
  ),
  identityPattern(
    'identity_013_new_permission',
    'The New Permission Pattern',
    ['permission_shift'],
    ['choosing_self', 'self_trust_growth', 'restorative_moment', 'truth_telling'],
    'being self-indulgent',
    'permission becoming a form of self-respect',
    'New permission around wants, needs, rest, or truth may be becoming self-respect.',
    ['permission', 'self-respect', 'needs'],
  ),
  identityPattern(
    'identity_014_unlived_part',
    'The Unlived Part of You',
    ['longing'],
    ['identity_rewriting', 'voice_emerging', 'creative_aliveness', 'future_self_orientation'],
    'wanting too much',
    'a real part of you asking for room in the life you are building',
    'Hidden desire, neglected identity, or longing may be asking for room in the life being built.',
    ['longing', 'unlived', 'room'],
  ),
  identityPattern(
    'identity_015_growth_nobody_sees',
    'The Growth Nobody Sees',
    ['growth_edge'],
    ['inner_critic_softening', 'integrates_insight', 'self_trust_growth', 'past_self_compassion'],
    'not changing enough',
    'growth becoming real before it becomes visible to others',
    'Private changes may be real before they become visible externally.',
    ['invisible-growth', 'private-change', 'progress'],
  ),
  identityPattern(
    'identity_016_return_to_yourself',
    'The Return to Yourself',
    ['self_definition'],
    ['choosing_self', 'less_explaining', 'body_lightness', 'truth_telling'],
    'being selfish',
    'coming back to the self that had been making room for everyone else',
    'Feeling more authentic or less performative may be a return to self.',
    ['authenticity', 'return', 'self'],
  ),
  identityPattern(
    'identity_017_courage_to_be_different',
    'The Courage to Be Different',
    ['self_definition'],
    ['truth_telling', 'autonomy_need', 'becoming_visible', 'belonging_ache'],
    'being difficult',
    'choosing truth over belonging that requires self-erasure',
    'Nonconformity or authenticity may show truth becoming more important than self-erasing belonging.',
    ['difference', 'truth', 'belonging'],
  ),
  identityPattern(
    'identity_018_life_theme_becoming_clear',
    'The Life Theme Becoming Clear',
    ['pattern_recognition'],
    ['meaning_making', 'growth_edge', 'transformation_season', 'identity_rewriting'],
    'repeating yourself',
    'the archive revealing a life theme that deserves understanding',
    'A repeated life lesson or theme may be becoming clear enough to understand.',
    ['life-theme', 'archive', 'meaning'],
  ),
  identityPattern(
    'identity_019_milestone_before_milestone',
    'The Milestone Before the Milestone',
    ['future_self_orientation'],
    ['integrates_insight', 'inner_critic_softening', 'growth_edge', 'hope'],
    'nothing is happening',
    'the inner shift that happens before life can reflect it outwardly',
    'Subtle progress may be the inner milestone that comes before visible change.',
    ['milestone', 'inner-shift', 'progress'],
  ),
  identityPattern(
    'identity_020_wholeness',
    'The Wholeness Pattern',
    ['mixed_emotions'],
    ['self_definition', 'integrates_insight', 'emotional_softening', 'identity_rewriting'],
    'being contradictory',
    'more of you being allowed to belong at the same time',
    'Different needs, emotions, or truths may be integrating into a wider sense of wholeness.',
    ['wholeness', 'integration', 'many-truths'],
  ),
];
