import type { ArchivePattern, SignalKey } from '../types';

const chartPattern = (
  key: string,
  title: string,
  requiredSignals: SignalKey[],
  supportingSignals: SignalKey[],
  shameLabel: string,
  clarityReframe: string,
  description: string,
  tags: string[] = [],
): ArchivePattern => ({
  key,
  title,
  category: 'natalChartReflection',
  description,
  requiredSignals,
  supportingSignals,
  shameLabel,
  clarityReframe,
  lookbackDays: 365,
  minEvidenceCount: 3,
  minScore: 0.56,
  cooldownDays: 30,
  tags,
});

/**
 * Natal Chart Reflection Archive Patterns
 */
export const NATAL_CHART_REFLECTION_PATTERNS: ArchivePattern[] = [
  chartPattern(
    'chart_001_theme_confirmed',
    'When the Chart Meets the Archive',
    ['chart_theme_confirmed'],
    ['deep_processing', 'pattern_recognition', 'meaning_making', 'integrates_insight'],
    'being boxed in by a label',
    'a symbolic mirror becoming useful only when your lived archive agrees',
    'A chart theme becomes useful when repeated lived data supports it.',
    ['chart', 'archive', 'confirmation'],
  ),
  chartPattern(
    'chart_002_emotional_depth_theme',
    'The Emotional Depth Theme',
    ['chart_emotional_depth_theme'],
    ['low_mood', 'dream_emotional_tone', 'deep_processing', 'emotional_heaviness'],
    'being too intense',
    'depth becoming a real pattern in how you feel, reflect, and process',
    'Chart emotional depth may align with mood, journal, or dream data.',
    ['emotional-depth', 'mood', 'dreams'],
  ),
  chartPattern(
    'chart_003_communication_theme',
    'The Communication Theme',
    ['chart_communication_theme'],
    ['need_for_exact_words', 'overexplaining', 'voice_emerging', 'creative_processing'],
    'over-explaining',
    'language becoming one of the ways your inner world finds form',
    'Chart communication themes may align with journaling, wording, or expression patterns.',
    ['communication', 'language', 'journaling'],
  ),
  chartPattern(
    'chart_004_relationship_theme',
    'The Relationship Theme',
    ['chart_relationship_theme'],
    ['relationship_safety_testing', 'emotional_availability_need', 'connection_glimmer', 'repair_need'],
    'caring too much about connection',
    'relationship patterns becoming clearer when symbolic themes meet lived evidence',
    'Relational chart themes may become clearer when they match relationship data.',
    ['relationships', 'connection', 'symbolic'],
  ),
  chartPattern(
    'chart_005_responsibility_theme',
    'The Responsibility Theme',
    ['chart_responsibility_theme'],
    ['responsibility_weight', 'rest_resistance', 'boundary_rebuilding', 'purpose_signal'],
    'being too serious',
    'responsibility becoming meaningful when it serves what you truly value',
    'Chart responsibility themes may align with obligation, limits, or rest patterns.',
    ['responsibility', 'limits', 'rest'],
  ),
  chartPattern(
    'chart_006_creativity_theme',
    'The Creativity Theme',
    ['chart_creativity_theme'],
    ['creative_aliveness', 'expression_need', 'beauty_glimmer', 'voice_emerging'],
    'being unrealistic',
    'creative energy becoming more trustworthy when it appears in real moments of aliveness',
    'Chart creativity themes may become trustworthy when they appear in lived moments of aliveness.',
    ['creativity', 'aliveness', 'expression'],
  ),
  chartPattern(
    'chart_007_identity_theme',
    'The Identity Theme',
    ['chart_identity_theme'],
    ['identity_rewriting', 'growth_edge', 'self_definition', 'becoming_visible'],
    'being self-focused',
    'self-knowledge becoming a way to live more honestly, not a way to stay stuck on yourself',
    'Chart identity themes may align with growth, self-definition, or archive shifts.',
    ['identity', 'growth', 'self-knowledge'],
  ),
  chartPattern(
    'chart_008_home_roots_theme',
    'The Home and Roots Theme',
    ['chart_home_family_theme'],
    ['home_as_safety', 'family_pattern_awareness', 'rooting_need', 'body_knows_first'],
    'needing too much safety',
    'roots becoming part of what helps the rest of life grow',
    'Chart home or family themes may align with home, body, or family patterns.',
    ['home', 'roots', 'safety'],
  ),
  chartPattern(
    'chart_009_values_theme',
    'The Values Theme',
    ['chart_values_theme'],
    ['values_conflict', 'integrity_cost', 'purpose_signal', 'truth_telling'],
    'taking meaning too seriously',
    'values becoming the deeper thread connecting your choices',
    'Chart values themes may align with reflection data and lived choices.',
    ['values', 'meaning', 'choice'],
  ),
  chartPattern(
    'chart_010_theme_not_active_yet',
    'The Chart Theme Not Active Yet',
    ['chart_theme_not_active'],
    ['chart_theme_confirmed', 'pattern_recognition', 'self_trust_growth', 'meaning_making'],
    'not matching the chart',
    'symbolic themes are invitations for reflection, not fixed truths you have to perform',
    'A chart theme may not be supported by current data, which keeps symbolic interpretation flexible.',
    ['not-active', 'invitation', 'reflection'],
  ),
  chartPattern(
    'chart_011_moon_archive',
    'The Moon-in-the-Archive Pattern',
    ['chart_emotional_depth_theme'],
    ['low_mood', 'dream_emotional_tone', 'support_need', 'body_heaviness'],
    'being emotionally complicated',
    'emotional needs becoming more understandable when seen through both symbol and lived pattern',
    'Moon-related themes may become clearer through mood, journal, and dream data.',
    ['moon', 'emotion', 'needs'],
  ),
  chartPattern(
    'chart_012_mercury_archive',
    'The Mercury-in-the-Archive Pattern',
    ['chart_communication_theme'],
    ['need_for_exact_words', 'deep_processing', 'pattern_recognition', 'asks_why'],
    'thinking too much',
    "the mind's style becoming clearer through language, curiosity, and pattern recognition",
    'Mercury-like themes may align with cognitive style, language, curiosity, or pattern recognition.',
    ['mercury', 'mind', 'language'],
  ),
  chartPattern(
    'chart_013_venus_archive',
    'The Venus-in-the-Archive Pattern',
    ['chart_relationship_theme'],
    ['beauty_glimmer', 'connection_glimmer', 'love_scarcity', 'creative_aliveness'],
    'wanting beauty or connection too much',
    'attraction, care, and beauty showing where the system feels most alive',
    'Venus-like themes may align with love, beauty, connection, glimmers, or relationships.',
    ['venus', 'beauty', 'connection'],
  ),
  chartPattern(
    'chart_014_mars_archive',
    'The Mars-in-the-Archive Pattern',
    ['chart_values_theme'],
    ['anger', 'justice_sensitivity', 'truth_telling', 'autonomy_need'],
    'being intense or reactive',
    'energy and anger becoming clearer when connected to what they are trying to protect',
    'Mars-like themes may align with action, anger, drive, values, or protection.',
    ['mars', 'anger', 'drive'],
  ),
  chartPattern(
    'chart_015_saturn_archive',
    'The Saturn-in-the-Archive Pattern',
    ['chart_responsibility_theme'],
    ['responsibility_weight', 'limits_tested', 'boundary_rebuilding', 'rest_resistance'],
    'being burdened or too serious',
    'limits and responsibility becoming wiser when they protect life instead of only adding weight',
    'Saturn-like themes may align with responsibility, limits, boundaries, or rest.',
    ['saturn', 'limits', 'responsibility'],
  ),
  chartPattern(
    'chart_016_rising_sign_daily_life',
    'The Rising Sign in Daily Life Pattern',
    ['chart_identity_theme'],
    ['self_definition', 'becoming_visible', 'relationship_safety_testing', 'identity_rewriting'],
    'performing',
    'the way you meet the world becoming part of your self-knowledge map',
    'Self-presentation may align with identity, journal, or relationship patterns.',
    ['rising-sign', 'self-presentation', 'identity'],
  ),
  chartPattern(
    'chart_017_house_lighting_up',
    'The House That Keeps Lighting Up',
    ['chart_theme_confirmed'],
    ['pattern_recognition', 'purpose_signal', 'meaning_making', 'growth_edge'],
    'being stuck on one area',
    'one life area asking for more attention because it is currently carrying more meaning',
    'A repeated life area may carry more meaning and therefore ask for more attention.',
    ['house', 'life-area', 'meaning'],
  ),
  chartPattern(
    'chart_018_archive_difference',
    'The Chart-Archive Difference',
    ['chart_theme_not_active'],
    ['self_trust_growth', 'truth_telling', 'pattern_recognition', 'chart_theme_confirmed'],
    'being inconsistent',
    'lived data having the final say over symbolic interpretation',
    'When chart themes contrast with lived data, the archive gets the final interpretive say.',
    ['difference', 'lived-data', 'symbolic'],
  ),
  chartPattern(
    'chart_019_chart_as_language',
    'The Chart as Language Pattern',
    ['chart_theme_confirmed'],
    ['meaning_making', 'need_for_exact_words', 'spiritual_depth', 'pattern_recognition'],
    'needing labels',
    'symbolic language helping name inner patterns that were already present',
    'Chart language may help name inner patterns already present in the archive.',
    ['language', 'symbol', 'naming'],
  ),
  chartPattern(
    'chart_020_sky_map_integration',
    'The Sky Map Integration',
    ['chart_theme_confirmed'],
    ['integrates_insight', 'growth_edge', 'meaning_making', 'pattern_recognition'],
    'trying to make everything mean something',
    'different mirrors becoming useful when they help you understand your life more kindly and accurately',
    'Chart themes, archive patterns, and growth movement may integrate into a kinder self-understanding.',
    ['integration', 'sky-map', 'self-understanding'],
  ),
];
