import type { ArchivePattern, SignalKey } from '../types';

const relationshipPattern = (
  key: string,
  title: string,
  requiredSignals: SignalKey[],
  supportingSignals: SignalKey[],
  shameLabel: string,
  clarityReframe: string,
  description: string,
  tags: string[] = [],
): ArchivePattern => ({
  key,
  title,
  category: 'relationships',
  description,
  requiredSignals,
  supportingSignals,
  shameLabel,
  clarityReframe,
  lookbackDays: 90,
  minEvidenceCount: 3,
  minScore: 0.58,
  cooldownDays: 10,
  tags,
});

/**
 * Relationship Patterns Archive Patterns
 */
export const RELATIONSHIP_PATTERNS: ArchivePattern[] = [
  relationshipPattern(
    'relationships_001_safety_testing',
    'How You Measure Safety',
    ['relationship_safety_testing'],
    ['consistency_need', 'tone_sensitivity', 'repair_need', 'trust_builds_slowly'],
    'suspicion',
    'discernment formed around the need for care to be real',
    'Trust is built through repeated evidence of consistency, repair, tone, and follow-through.',
    ['safety', 'trust', 'consistency'],
  ),
  relationshipPattern(
    'relationships_002_safety_tester',
    'The Safety Tester',
    ['relationship_safety_testing'],
    ['trust_builds_slowly', 'consistency_need', 'rupture_sensitivity', 'repair_need'],
    'testing people unfairly',
    'a wise need to know whether care survives ordinary strain',
    'The user may test whether care remains steady when ordinary strain appears.',
    ['testing', 'care', 'strain'],
  ),
  relationshipPattern(
    'relationships_003_repair_seeking',
    'The Repair-Seeking Pattern',
    ['repair_need'],
    ['rupture_sensitivity', 'truth_over_harmony', 'emotional_availability_need', 'tone_sensitivity'],
    'holding a grudge',
    'wanting connection to become trustworthy again',
    'A need for apology, repair, or naming rupture can reflect a desire to restore trust.',
    ['repair', 'rupture', 'trust'],
  ),
  relationshipPattern(
    'relationships_004_rupture_sensitivity',
    'The Rupture Sensitivity Pattern',
    ['rupture_sensitivity'],
    ['tone_sensitivity', 'closeness_uncertainty', 'repair_need', 'distance_for_safety'],
    'being dramatic',
    'sensitivity to instability where connection matters',
    'Small relational shifts, distance, or tone changes may register strongly where the bond matters.',
    ['rupture', 'instability', 'sensitivity'],
  ),
  relationshipPattern(
    'relationships_005_tone_sensitivity',
    'The Tone Sensitivity Pattern',
    ['tone_sensitivity'],
    ['relationship_safety_testing', 'consistency_need', 'emotional_availability_need', 'chest_pressure'],
    'reading into things',
    'attention to emotional weather in connection',
    'Small changes in warmth, tone, or responsiveness may function as relational weather data.',
    ['tone', 'warmth', 'weather'],
  ),
  relationshipPattern(
    'relationships_006_emotional_availability_need',
    'The Emotional Availability Need',
    ['emotional_availability_need'],
    ['consistency_need', 'wants_to_be_seen', 'repair_need', 'closeness_uncertainty'],
    'needing too much',
    'connection needing to feel emotionally reachable',
    'The user may need presence and responsiveness before connection can feel truly reachable.',
    ['availability', 'presence', 'responsiveness'],
  ),
  relationshipPattern(
    'relationships_007_kindness_safety_gap',
    'The Kindness-Safety Gap',
    ['kindness_safety_gap'],
    ['tone_sensitivity', 'trust_builds_slowly', 'relationship_safety_testing', 'gut_signal'],
    'being unfair',
    'knowing that kindness and emotional safety are not always the same thing',
    'Someone may be kind while still not feeling fully emotionally safe.',
    ['kindness', 'safety', 'discernment'],
  ),
  relationshipPattern(
    'relationships_008_trust_builds_slowly',
    'Trust Builds Slowly',
    ['trust_builds_slowly'],
    ['consistency_need', 'relationship_safety_testing', 'selective_vulnerability', 'repair_need'],
    'being guarded',
    'trust growing through repeated evidence',
    'Trust may require repeated evidence rather than promises or intensity.',
    ['trust', 'evidence', 'guardedness'],
  ),
  relationshipPattern(
    'relationships_009_closeness_uncertainty',
    'The Closeness Uncertainty Pattern',
    ['closeness_uncertainty'],
    ['selective_vulnerability', 'consistency_need', 'emotional_availability_need', 'tone_sensitivity'],
    'being insecure',
    'closeness asking for steadiness before it can feel fully safe',
    'Uncertainty after closeness can show the need for steadiness around intimacy.',
    ['closeness', 'uncertainty', 'steadiness'],
  ),
  relationshipPattern(
    'relationships_010_distance_for_safety',
    'The Distance for Safety Pattern',
    ['distance_for_safety'],
    ['rupture_sensitivity', 'needs_pause', 'selective_vulnerability', 'autonomy_need'],
    'being cold',
    'space helping the system regain steadiness',
    'Pulling back may be a way to regain steadiness rather than a lack of care.',
    ['distance', 'space', 'safety'],
  ),
  relationshipPattern(
    'relationships_011_selective_vulnerability',
    'Selective Vulnerability',
    ['selective_vulnerability'],
    ['trust_builds_slowly', 'kindness_safety_gap', 'closeness_uncertainty', 'wants_to_be_seen'],
    'inconsistency',
    'discernment about where softness has been earned',
    'Being open in some places and guarded in others can reflect discernment about earned safety.',
    ['vulnerability', 'discernment', 'softness'],
  ),
  relationshipPattern(
    'relationships_012_loyalty_versus_honesty',
    'Loyalty Versus Honesty',
    ['loyalty_conflict'],
    ['truth_over_harmony', 'values_conflict', 'repair_need', 'guilt'],
    'betrayal',
    'integrity trying to love without abandoning reality',
    'Tension between truth and loyalty may show integrity trying to stay connected to reality.',
    ['loyalty', 'honesty', 'integrity'],
  ),
  relationshipPattern(
    'relationships_013_truth_over_harmony',
    'Truth Over Harmony',
    ['truth_over_harmony'],
    ['truth_telling', 'repair_need', 'loyalty_conflict', 'values_conflict'],
    'being harsh',
    'a need for reality clear enough to stand on',
    'Discomfort with avoidance or pretending can reflect a need for truthful ground.',
    ['truth', 'harmony', 'clarity'],
  ),
  relationshipPattern(
    'relationships_014_over_explaining_connection',
    'The Over-Explaining in Connection Pattern',
    ['overexplaining'],
    ['need_for_exact_words', 'fear_of_being_too_much', 'repair_need', 'selective_vulnerability'],
    'defensiveness',
    'trying to keep truth from being flattened or misunderstood',
    'Explaining feelings or context repeatedly may be an effort to keep truth intact.',
    ['overexplaining', 'truth', 'context'],
  ),
  relationshipPattern(
    'relationships_015_fear_of_misreading_others',
    'The Fear of Misreading Others',
    ['decision_uncertainty'],
    ['tone_sensitivity', 'asks_why', 'relationship_safety_testing', 'need_for_exact_words'],
    'overanalyzing',
    'wanting connection to be clear enough not to guess at',
    'Uncertainty about someone’s meaning can reflect a need for clarity in connection.',
    ['misreading', 'clarity', 'uncertainty'],
  ),
  relationshipPattern(
    'relationships_016_mutual_care',
    'The Mutual Care Pattern',
    ['mutuality_need'],
    ['receiving_openness', 'support_need', 'emotional_availability_need', 'connection_glimmer'],
    'expecting too much',
    'the healthy need for care to move both directions',
    'Balanced giving and receiving can become visible as a relational need.',
    ['mutuality', 'care', 'reciprocity'],
  ),
  relationshipPattern(
    'relationships_017_relational_energy_drain',
    'The Relational Energy Drain',
    ['depletion'],
    ['body_heaviness', 'distance_for_safety', 'tone_sensitivity', 'low_energy'],
    'being judgmental',
    'the body and mood tracking what connection costs',
    'Certain relationships may leave fatigue, body heaviness, or mood shifts that reveal connection cost.',
    ['energy-drain', 'connection-cost', 'body'],
  ),
  relationshipPattern(
    'relationships_018_relationship_that_restores',
    'The Relationship That Restores',
    ['connection_glimmer'],
    ['relief', 'body_lightness', 'somatic_safety', 'receiving_openness'],
    'being dependent on people',
    'connection becoming a real source of regulation and return',
    'Some interactions may create relief, steadiness, or body softening after stress.',
    ['restoring', 'connection', 'regulation'],
  ),
  relationshipPattern(
    'relationships_019_safe_person',
    'The Safe Person Pattern',
    ['somatic_safety'],
    ['connection_glimmer', 'trust_builds_slowly', 'quiet_safety', 'body_lightness'],
    'needing reassurance',
    'the nervous system recognizing steadiness through experience',
    'Feeling calmer with specific people can show the body recognizing steadiness.',
    ['safe-person', 'steadiness', 'body'],
  ),
  relationshipPattern(
    'relationships_020_connection_aftercare',
    'The Connection Aftercare Pattern',
    ['needs_pause'],
    ['closeness_uncertainty', 'low_energy', 'body_heaviness', 'selective_vulnerability'],
    'being too much or too sensitive',
    'meaningful connection sometimes needing space afterward to settle',
    'Intense or meaningful connection may require recovery space afterward.',
    ['aftercare', 'connection', 'settling'],
  ),
];
