import type { ArchivePattern } from '../types';

/**
 * Rest + Capacity Archive Patterns
 */

export const REST_CAPACITY_PATTERNS: ArchivePattern[] = [
  {
    key: 'rest_capacity_001_rest_resistance',
    title: 'Your Relationship with Rest',
    category: 'restCapacity',
    description:
      'Rest appears to arrive after depletion rather than being allowed as a baseline need.',
    requiredSignals: ['rest_resistance'],
    supportingSignals: [
      'low_energy',
      'low_sleep',
      'poor_sleep_quality',
      'depletion',
      'overextension',
      'responsibility_weight',
      'invisible_labor',
      'needs_pause',
      'body_knows_first',
    ],
    conflictingSignals: ['restorative_moment', 'low_stress'],
    shameLabel: 'laziness',
    clarityReframe:
      'a deeply ingrained resilience that hasn’t yet learned it is safe to put the armor down',
    lookbackDays: 90,
    minEvidenceCount: 4,
    minScore: 0.6,
    cooldownDays: 10,
    tags: ['rest', 'capacity', 'depletion', 'self-permission'],
  },

  {
    key: 'rest_capacity_002_same_load_less_fuel',
    title: 'The Same Load, Less Fuel',
    category: 'restCapacity',
    description:
      'The user may be trying to carry the same responsibilities with noticeably less energy available.',
    requiredSignals: ['capacity_strain'],
    supportingSignals: [
      'low_energy',
      'low_sleep',
      'responsibility_weight',
      'mental_load',
      'overfunctioning',
      'always_on',
      'depletion',
      'mood_drop',
    ],
    conflictingSignals: ['high_energy', 'restorative_moment'],
    shameLabel: 'falling behind',
    clarityReframe:
      'capacity telling the truth about what can realistically be carried today',
    lookbackDays: 30,
    minEvidenceCount: 3,
    minScore: 0.58,
    cooldownDays: 7,
    tags: ['energy', 'responsibility', 'capacity', 'daily-load'],
  },

  {
    key: 'rest_capacity_003_exhaustion_permission_slip',
    title: 'Your Relationship with Rest',
    category: 'restCapacity',
    description:
      'Exhaustion is often your permission slip to pause, moving at high velocity until depletion forces a full stop.',
    requiredSignals: ['rest_guilt'],
    supportingSignals: [
      'rest_resistance',
      'depletion',
      'low_energy',
      'needs_pause',
      'overextension',
      'caretaking_pressure',
      'responsibility_weight',
      'self_blame',
      'guilt',
    ],
    conflictingSignals: ['restorative_moment', 'receiving_openness'],
    shameLabel: 'not trying hard enough',
    clarityReframe:
      'a deeply ingrained resilience that hasn’t yet learned it is safe to put the armor down',
    lookbackDays: 90,
    minEvidenceCount: 4,
    minScore: 0.62,
    cooldownDays: 14,
    tags: ['rest-guilt', 'permission', 'depletion', 'self-worth'],
  },

  {
    key: 'rest_capacity_004_recovery_gap',
    title: 'The Recovery Gap',
    category: 'restCapacity',
    description:
      'The user may be spending more energy than they are able to restore, creating a widening gap between output and recovery.',
    requiredSignals: ['recovery_gap'],
    supportingSignals: [
      'low_energy',
      'poor_sleep_quality',
      'low_sleep',
      'overextension',
      'always_on',
      'burnout_risk',
      'mental_load',
      'invisible_labor',
      'body_heaviness',
    ],
    conflictingSignals: ['restorative_moment', 'glimmer_softening', 'low_stress'],
    shameLabel: 'being unable to keep up',
    clarityReframe:
      'a recovery system that has not been given enough room to replenish what life keeps asking for',
    lookbackDays: 60,
    minEvidenceCount: 5,
    minScore: 0.64,
    cooldownDays: 14,
    tags: ['recovery', 'burnout-risk', 'energy', 'restoration'],
  },

  {
    key: 'rest_capacity_005_burnout_warning',
    title: 'The Early Burnout Signal',
    category: 'restCapacity',
    description:
      'Several signals suggest the user may be approaching a sustained depletion pattern and needs earlier recovery, not more self-pressure.',
    requiredSignals: ['burnout_risk'],
    supportingSignals: [
      'depletion',
      'low_energy',
      'low_mood',
      'high_stress',
      'poor_sleep_quality',
      'overextension',
      'always_on',
      'body_heaviness',
      'emotional_heaviness',
      'self_blame',
    ],
    conflictingSignals: ['high_energy', 'low_stress', 'restorative_moment'],
    shameLabel: 'not being resilient enough',
    clarityReframe:
      'resilience asking for maintenance before strength turns into depletion',
    lookbackDays: 30,
    minEvidenceCount: 5,
    minScore: 0.68,
    cooldownDays: 14,
    tags: ['burnout', 'early-warning', 'energy', 'self-pressure'],
  },

  {
    key: 'rest_capacity_006_low_sleep_emotional_amplifier',
    title: 'When Sleep Changes the Weight of the Day',
    category: 'restCapacity',
    description:
      'Lower sleep appears to make emotions, responsibilities, and self-judgment feel heavier or more difficult to hold.',
    requiredSignals: ['sleep_mood_link'],
    supportingSignals: [
      'low_sleep',
      'poor_sleep_quality',
      'low_mood',
      'mood_drop',
      'low_energy',
      'emotional_intensity',
      'self_blame',
      'capacity_strain',
      'body_heaviness',
    ],
    conflictingSignals: ['high_energy', 'mood_improvement', 'restorative_moment'],
    shameLabel: 'being emotionally inconsistent',
    clarityReframe:
      'the very human reality that feelings become harder to hold when the body has had less recovery',
    lookbackDays: 30,
    minEvidenceCount: 3,
    minScore: 0.58,
    cooldownDays: 7,
    tags: ['sleep', 'mood', 'capacity', 'emotional-weather'],
  },

  {
    key: 'rest_capacity_007_rest_as_safety',
    title: 'When Rest Starts to Feel Safe',
    category: 'restCapacity',
    description:
      'The user is beginning to experience rest as supportive rather than only as something earned after depletion.',
    requiredSignals: ['restorative_moment'],
    supportingSignals: [
      'glimmer_softening',
      'quiet_safety',
      'low_stress',
      'tension_release',
      'somatic_safety',
      'emotional_softening',
      'body_lightness',
      'receiving_openness',
    ],
    conflictingSignals: ['rest_guilt', 'rest_resistance', 'always_on'],
    shameLabel: 'doing nothing',
    clarityReframe:
      'a nervous system learning that pause can be repair, not proof of failure',
    lookbackDays: 30,
    minEvidenceCount: 2,
    minScore: 0.5,
    cooldownDays: 7,
    tags: ['restoration', 'glimmer', 'safety', 'repair'],
  },

  {
    key: 'rest_capacity_008_the_afterward_crash',
    title: 'The Afterward Crash',
    category: 'restCapacity',
    description:
      'The user may function through a demanding moment, then feel the impact afterward when there is finally room to notice it.',
    requiredSignals: ['depletion'],
    supportingSignals: [
      'high_stress',
      'overfunctioning',
      'preparedness',
      'responsibility_weight',
      'low_energy',
      'body_heaviness',
      'emotional_heaviness',
      'mood_drop',
      'needs_pause',
    ],
    conflictingSignals: ['high_energy', 'low_stress'],
    shameLabel: 'falling apart for no reason',
    clarityReframe:
      'delayed honesty from a system that waited until it was safer to feel the cost',
    lookbackDays: 60,
    minEvidenceCount: 4,
    minScore: 0.62,
    cooldownDays: 14,
    tags: ['post-stress', 'depletion', 'delayed-processing', 'capacity'],
  },

  {
    key: 'rest_capacity_009_always_on_pattern',
    title: 'The Always-On Pattern',
    category: 'restCapacity',
    description:
      'The user may stay mentally or emotionally switched on even when there is no immediate demand.',
    requiredSignals: ['always_on'],
    supportingSignals: [
      'preparedness',
      'mental_load',
      'high_stress',
      'responsibility_weight',
      'overfunctioning',
      'calm_bracing',
      'sleep_mood_link',
      'poor_sleep_quality',
      'jaw_restraint',
      'shoulder_burden',
    ],
    conflictingSignals: ['quiet_safety', 'low_stress', 'restorative_moment'],
    shameLabel: 'being unable to relax',
    clarityReframe:
      'a system that learned to stay ready and is still learning when readiness is no longer required',
    lookbackDays: 90,
    minEvidenceCount: 4,
    minScore: 0.6,
    cooldownDays: 14,
    tags: ['readiness', 'stress', 'capacity', 'calm'],
  },

  {
    key: 'rest_capacity_010_micro_rest_need',
    title: 'The Need for Smaller Pauses',
    category: 'restCapacity',
    description:
      'The user may benefit from smaller moments of recovery before exhaustion makes a larger pause unavoidable.',
    requiredSignals: ['needs_pause'],
    supportingSignals: [
      'low_energy',
      'capacity_strain',
      'rest_resistance',
      'rest_guilt',
      'overextension',
      'mental_load',
      'body_heaviness',
      'quiet_safety',
    ],
    conflictingSignals: ['high_energy', 'restorative_moment'],
    shameLabel: 'not deserving a break yet',
    clarityReframe:
      'capacity asking to be cared for while it is still possible to recover gently',
    lookbackDays: 14,
    minEvidenceCount: 2,
    minScore: 0.52,
    cooldownDays: 5,
    tags: ['micro-rest', 'daily-support', 'capacity', 'prevention'],
  },

  {
    key: 'rest_capacity_011_emotional_fatigue',
    title: 'When the Feeling Is Tired Too',
    category: 'restCapacity',
    description:
      'The user’s emotional heaviness appears linked to fatigue, suggesting that feelings may become harder to interpret when energy is low.',
    requiredSignals: ['emotional_heaviness'],
    supportingSignals: [
      'low_energy',
      'low_sleep',
      'poor_sleep_quality',
      'low_mood',
      'depletion',
      'capacity_strain',
      'self_blame',
      'sadness',
      'body_heaviness',
    ],
    conflictingSignals: ['high_energy', 'emotional_softening', 'relief'],
    shameLabel: 'being too emotional',
    clarityReframe:
      'emotion carrying extra weight because the body has less strength available to hold it',
    lookbackDays: 30,
    minEvidenceCount: 3,
    minScore: 0.58,
    cooldownDays: 7,
    tags: ['emotional-fatigue', 'low-energy', 'mood', 'capacity'],
  },

  {
    key: 'rest_capacity_012_capacity_before_motivation',
    title: 'Capacity Before Motivation',
    category: 'restCapacity',
    description:
      'The user may interpret lower output as a motivation issue when the data points more clearly toward capacity strain.',
    requiredSignals: ['capacity_strain'],
    supportingSignals: [
      'low_energy',
      'depletion',
      'poor_sleep_quality',
      'rest_resistance',
      'self_blame',
      'guilt',
      'responsibility_weight',
      'mood_drop',
    ],
    conflictingSignals: ['high_energy', 'creative_aliveness', 'mood_improvement'],
    shameLabel: 'not being motivated enough',
    clarityReframe:
      'capacity asking to be included before the mind turns low output into a character story',
    lookbackDays: 30,
    minEvidenceCount: 3,
    minScore: 0.58,
    cooldownDays: 7,
    tags: ['motivation', 'capacity', 'self-blame', 'energy'],
  },

  {
    key: 'rest_capacity_013_sleep_debt_disguised_as_mood',
    title: 'When Sleep Debt Sounds Like a Mood',
    category: 'restCapacity',
    description:
      'Some lower moods may be partially explained by accumulated sleep strain or reduced sleep quality.',
    requiredSignals: ['low_sleep'],
    supportingSignals: [
      'poor_sleep_quality',
      'sleep_mood_link',
      'low_mood',
      'mood_drop',
      'low_energy',
      'emotional_intensity',
      'body_heaviness',
      'capacity_strain',
    ],
    conflictingSignals: ['high_energy', 'mood_improvement', 'restorative_moment'],
    shameLabel: 'being negative',
    clarityReframe:
      'a tired body changing the emotional volume before the mind has had a fair chance to respond',
    lookbackDays: 14,
    minEvidenceCount: 2,
    minScore: 0.52,
    cooldownDays: 5,
    tags: ['sleep', 'mood', 'fatigue', 'emotional-weather'],
  },

  {
    key: 'rest_capacity_014_recovery_after_care',
    title: 'The Recovery Needed After Giving',
    category: 'restCapacity',
    description:
      'Caregiving or emotional labor appears to create a recovery need that may be easy for the user to overlook.',
    requiredSignals: ['caretaking_pressure'],
    supportingSignals: [
      'low_energy',
      'invisible_labor',
      'mental_load',
      'responsibility_weight',
      'overextension',
      'receiving_care_difficulty',
      'needs_pause',
      'depletion',
    ],
    conflictingSignals: ['restorative_moment', 'receiving_openness'],
    shameLabel: 'not being generous enough',
    clarityReframe:
      'care that needs somewhere to return after it has moved outward for too long',
    lookbackDays: 60,
    minEvidenceCount: 4,
    minScore: 0.62,
    cooldownDays: 14,
    tags: ['caregiving', 'recovery', 'emotional-labor', 'capacity'],
  },

  {
    key: 'rest_capacity_015_weekend_recovery_pressure',
    title: 'When Rest Has to Catch Up',
    category: 'restCapacity',
    description:
      'The user may place too much recovery pressure on limited windows of rest after a demanding stretch.',
    requiredSignals: ['recovery_gap'],
    supportingSignals: [
      'low_energy',
      'depletion',
      'overextension',
      'low_sleep',
      'poor_sleep_quality',
      'needs_pause',
      'rest_guilt',
      'capacity_strain',
    ],
    conflictingSignals: ['restorative_moment', 'quiet_safety'],
    shameLabel: 'wasting time',
    clarityReframe:
      'a recovery system trying to repair several days of output in too small a window',
    lookbackDays: 30,
    minEvidenceCount: 3,
    minScore: 0.56,
    cooldownDays: 7,
    tags: ['recovery-window', 'rest-pressure', 'capacity', 'time'],
  },

  {
    key: 'rest_capacity_016_energy_scarcity',
    title: 'When Energy Feels Scarce',
    category: 'restCapacity',
    description:
      'The user may relate to energy as a scarce resource that must be carefully rationed or protected.',
    requiredSignals: ['energy_scarcity'],
    supportingSignals: [
      'low_energy',
      'capacity_strain',
      'depletion',
      'rest_resistance',
      'overextension',
      'time_scarcity',
      'mental_load',
      'needs_pause',
      'self_blame',
    ],
    conflictingSignals: ['high_energy', 'abundance_healing', 'restorative_moment'],
    shameLabel: 'having too little to give',
    clarityReframe:
      'energy becoming precious because the demands around it have been larger than the recovery available',
    lookbackDays: 60,
    minEvidenceCount: 3,
    minScore: 0.58,
    cooldownDays: 10,
    tags: ['energy', 'scarcity', 'capacity', 'self-protection'],
  },

  {
    key: 'rest_capacity_017_morning_capacity_signal',
    title: 'The Morning Capacity Signal',
    category: 'restCapacity',
    description:
      'The user’s morning mood or energy may reveal how much recovery was actually available overnight.',
    requiredSignals: ['low_energy'],
    supportingSignals: [
      'low_sleep',
      'poor_sleep_quality',
      'mood_drop',
      'sleep_mood_link',
      'capacity_strain',
      'body_heaviness',
      'needs_pause',
    ],
    conflictingSignals: ['high_energy', 'mood_improvement'],
    shameLabel: 'starting the day wrong',
    clarityReframe:
      'the morning giving useful information about what the night was or was not able to restore',
    lookbackDays: 14,
    minEvidenceCount: 2,
    minScore: 0.5,
    cooldownDays: 5,
    tags: ['morning', 'energy', 'sleep', 'capacity'],
  },

  {
    key: 'rest_capacity_018_responsibility_before_body',
    title: 'When Responsibility Speaks Over the Body',
    category: 'restCapacity',
    description:
      'The user may prioritize responsibility so quickly that body signals become noticeable only after they intensify.',
    requiredSignals: ['responsibility_weight'],
    supportingSignals: [
      'body_knows_first',
      'needs_pause',
      'low_energy',
      'shoulder_burden',
      'chest_pressure',
      'jaw_restraint',
      'overfunctioning',
      'always_on',
      'rest_resistance',
    ],
    conflictingSignals: ['somatic_safety', 'restorative_moment'],
    shameLabel: 'not listening to yourself',
    clarityReframe:
      'responsibility getting loud before the body has been given enough room to be heard',
    lookbackDays: 60,
    minEvidenceCount: 4,
    minScore: 0.6,
    cooldownDays: 10,
    tags: ['responsibility', 'body-signals', 'rest', 'self-attunement'],
  },

  {
    key: 'rest_capacity_019_softening_after_pause',
    title: 'What Softens After a Pause',
    category: 'restCapacity',
    description:
      'The user shows signs that even small pauses can shift emotional tone, body cues, or self-judgment.',
    requiredSignals: ['restorative_moment'],
    supportingSignals: [
      'emotional_softening',
      'glimmer_softening',
      'quiet_safety',
      'tension_release',
      'body_lightness',
      'low_stress',
      'relief',
      'somatic_safety',
    ],
    conflictingSignals: ['depletion', 'high_stress'],
    shameLabel: 'needing too much recovery',
    clarityReframe:
      'proof that small forms of care can change the emotional weather before everything is fixed',
    lookbackDays: 30,
    minEvidenceCount: 2,
    minScore: 0.5,
    cooldownDays: 7,
    tags: ['restorative', 'softening', 'glimmer', 'repair'],
  },

  {
    key: 'rest_capacity_020_the_limit_before_the_crash',
    title: 'The Limit Before the Crash',
    category: 'restCapacity',
    description:
      'The user’s archive may be starting to show earlier signs of limits before full depletion happens.',
    requiredSignals: ['needs_pause'],
    supportingSignals: [
      'body_knows_first',
      'low_energy',
      'capacity_strain',
      'rest_resistance',
      'depletion',
      'mood_drop',
      'high_stress',
      'self_trust_growth',
      'inner_authority',
    ],
    conflictingSignals: ['high_energy', 'low_stress'],
    shameLabel: 'being inconvenient',
    clarityReframe:
      'an earlier warning system trying to protect you before the only option left is collapse',
    lookbackDays: 30,
    minEvidenceCount: 3,
    minScore: 0.58,
    cooldownDays: 7,
    tags: ['early-warning', 'limits', 'rest', 'self-trust'],
  },
];
