import type { ArchivePattern, SignalKey } from '../types';

const scarcityPattern = (
  key: string,
  title: string,
  requiredSignals: SignalKey[],
  supportingSignals: SignalKey[],
  shameLabel: string,
  clarityReframe: string,
  description: string,
  tags: string[] = [],
): ArchivePattern => ({
  key,
  title,
  category: 'scarcityAbundance',
  description,
  requiredSignals,
  supportingSignals,
  shameLabel,
  clarityReframe,
  lookbackDays: 90,
  minEvidenceCount: 3,
  minScore: 0.56,
  cooldownDays: 10,
  tags,
});

/**
 * Scarcity + Abundance Archive Patterns
 */
export const SCARCITY_ABUNDANCE_PATTERNS: ArchivePattern[] = [
  scarcityPattern(
    'scarcity_001_scarcity_scanner',
    'The Scarcity Scanner',
    ['scarcity_scanning'],
    ['fear_of_loss', 'time_scarcity', 'energy_scarcity', 'love_scarcity'],
    'being anxious or ungrateful',
    'a system tracking what has not always felt secure',
    'The user may scan for loss or deficiency around time, money, support, energy, or love.',
    ['scarcity', 'security', 'scanning'],
  ),
  scarcityPattern(
    'scarcity_002_enoughness',
    'The Enoughness Pattern',
    ['enoughness'],
    ['support_abundance_shift', 'receiving_openness', 'low_stress', 'quiet_safety'],
    'wanting reassurance',
    'enoughness becoming something your system is learning to recognize',
    'Enough time, support, money, or capacity may be something the system is learning to recognize.',
    ['enoughness', 'recognition', 'support'],
  ),
  scarcityPattern(
    'scarcity_003_fear_of_losing_what_you_have',
    'The Fear of Losing What You Have',
    ['fear_of_loss'],
    ['joy_tolerance', 'calm_bracing', 'love_scarcity', 'scarcity_scanning'],
    'ruining good things',
    'protection trying to keep care, safety, or joy from disappearing suddenly',
    'Good moments or stability may trigger fear of losing what finally feels valuable.',
    ['fear-of-loss', 'stability', 'protection'],
  ),
  scarcityPattern(
    'scarcity_004_receiving_without_deflecting',
    'The Receiving Without Deflecting Pattern',
    ['receiving_openness'],
    ['receiving_care_difficulty', 'support_abundance_shift', 'connection_glimmer', 'self_forgiveness'],
    'being awkward or undeserving',
    'receiving becoming a skill your system can learn in small doses',
    'Accepting help, compliments, gifts, or care may be a receiving skill learned in small doses.',
    ['receiving', 'care', 'skill'],
  ),
  scarcityPattern(
    'scarcity_005_love_scarcity',
    'The Love Scarcity Pattern',
    ['love_scarcity'],
    ['fear_of_loss', 'closeness_uncertainty', 'consistency_need', 'relationship_safety_testing'],
    'being insecure',
    'love feeling precious where it has not always felt abundant',
    'Fear that love is limited, fragile, or conditional may come from love not always feeling abundant.',
    ['love', 'scarcity', 'conditionality'],
  ),
  scarcityPattern(
    'scarcity_006_time_scarcity',
    'The Time Scarcity Pattern',
    ['time_scarcity'],
    ['high_stress', 'responsibility_weight', 'overextension', 'needs_pause'],
    'poor time management',
    'time feeling tight because too much is asking to fit into too little room',
    'Time pressure and rushing may reflect too much trying to fit into too little room.',
    ['time', 'rushing', 'pressure'],
  ),
  scarcityPattern(
    'scarcity_007_energy_scarcity',
    'The Energy Scarcity Pattern',
    ['energy_scarcity'],
    ['low_energy', 'capacity_strain', 'depletion', 'recovery_gap'],
    'not having enough to give',
    'energy becoming precious when recovery and demand are out of balance',
    'Limited energy and careful rationing may show demand and recovery out of balance.',
    ['energy', 'recovery', 'demand'],
  ),
  scarcityPattern(
    'scarcity_008_support_abundance_shift',
    'The Support Abundance Shift',
    ['support_abundance_shift'],
    ['receiving_openness', 'connection_glimmer', 'relief', 'support_need'],
    'needing reminders',
    'the system learning that care can be present without being immediately threatened',
    'Noticing support or receiving care may soften scarcity around support.',
    ['support', 'abundance', 'care'],
  ),
  scarcityPattern(
    'scarcity_009_gift_receiving',
    'The Gift Receiving Pattern',
    ['receiving_openness'],
    ['support_abundance_shift', 'gratitude_and_grief', 'connection_glimmer', 'receiving_care_difficulty'],
    'being uncomfortable with kindness',
    'care becoming easier to receive when it is allowed to arrive without repayment',
    'Gifts, compliments, help, or generosity may become easier to receive without repayment.',
    ['gifts', 'receiving', 'kindness'],
  ),
  scarcityPattern(
    'scarcity_010_fear_of_needing_more',
    'The Fear of Needing More',
    ['support_need'],
    ['longing', 'love_scarcity', 'energy_scarcity', 'fear_of_being_too_much'],
    'being greedy',
    'desire pointing toward a real need, not a moral failure',
    'Wanting more support, rest, money, love, or space may point toward a real need.',
    ['need', 'desire', 'more'],
  ),
  scarcityPattern(
    'scarcity_011_not_enough_story',
    'The "Not Enough" Story',
    ['scarcity_scanning'],
    ['time_scarcity', 'energy_scarcity', 'support_scarcity', 'capacity_strain'],
    'failing',
    'scarcity language getting loud where the system wants more steadiness',
    'Not enough progress, time, support, or capacity may be scarcity language asking for steadiness.',
    ['not-enough', 'steadiness', 'language'],
  ),
  scarcityPattern(
    'scarcity_012_abundance_micro_signal',
    'The Abundance Micro-Signal',
    ['enoughness'],
    ['receiving_openness', 'support_abundance_shift', 'relief', 'quiet_safety'],
    'too small to matter',
    'a small proof that not everything has to be earned, chased, or protected',
    'A small moment of enoughness or unexpected help may show not everything has to be earned or chased.',
    ['micro-signal', 'help', 'enough'],
  ),
  scarcityPattern(
    'scarcity_013_holding_on',
    'The Holding-On Pattern',
    ['fear_of_loss'],
    ['scarcity_scanning', 'love_scarcity', 'support_scarcity', 'longing'],
    'being attached',
    'holding on making sense when something has felt too precious to trust',
    'Difficulty letting go may make sense when something has felt too precious to trust.',
    ['holding-on', 'attachment', 'loss'],
  ),
  scarcityPattern(
    'scarcity_014_generosity_cost',
    'The Generosity Cost Pattern',
    ['caretaking_pressure'],
    ['energy_scarcity', 'depletion', 'support_scarcity', 'mutuality_need'],
    'being resentful',
    'generosity needing enough support behind it to stay free instead of costly',
    'Giving from scarcity may leave depletion after generosity.',
    ['generosity', 'cost', 'support'],
  ),
  scarcityPattern(
    'scarcity_015_abundance_through_beauty',
    'The Abundance Through Beauty Pattern',
    ['beauty_glimmer'],
    ['beauty_regulation', 'ordinary_sacred', 'enoughness', 'body_lightness'],
    'being materialistic',
    'beauty reminding the system that abundance is also sensory, emotional, and atmospheric',
    'Beauty may create a sensory or emotional sense of richness and enoughness.',
    ['beauty', 'abundance', 'sensory'],
  ),
  scarcityPattern(
    'scarcity_016_fear_of_empty',
    'The Fear of Empty Pattern',
    ['fear_of_loss'],
    ['depletion', 'energy_scarcity', 'scarcity_scanning', 'recovery_gap'],
    'being irrational',
    'emptiness feeling threatening when reserves have not always been easy to restore',
    'Fear of running out may intensify when reserves have not been easy to restore.',
    ['empty', 'reserves', 'fear'],
  ),
  scarcityPattern(
    'scarcity_017_more_is_allowed',
    'The More-Is-Allowed Pattern',
    ['longing'],
    ['support_need', 'love_scarcity', 'autonomy_need', 'creative_aliveness'],
    'being ungrateful',
    'wanting more can coexist with appreciating what is already here',
    'Wanting more life, joy, love, freedom, or support can coexist with gratitude.',
    ['more', 'gratitude', 'desire'],
  ),
  scarcityPattern(
    'scarcity_018_scarcity_after_stability',
    'The Scarcity After Stability Pattern',
    ['fear_of_loss'],
    ['enoughness', 'calm_bracing', 'support_abundance_shift', 'scarcity_scanning'],
    'not trusting good things',
    'a protective habit trying to guard what finally feels valuable',
    'Stability may trigger fear of losing what finally feels valuable.',
    ['stability', 'guarding', 'good-things'],
  ),
  scarcityPattern(
    'scarcity_019_abundance_through_connection',
    'The Abundance Through Connection Pattern',
    ['connection_glimmer'],
    ['support_abundance_shift', 'receiving_openness', 'mutuality_need', 'relief'],
    'relying on others',
    'connection reminding the system that not every resource has to come from inside you',
    'Supportive connection may make life feel less scarce.',
    ['connection', 'resource', 'support'],
  ),
  scarcityPattern(
    'scarcity_020_enough_for_today',
    'The Enough for Today Pattern',
    ['enoughness'],
    ['low_stress', 'quiet_safety', 'relief', 'self_trust_growth'],
    'settling',
    'enoughness becoming a daily practice instead of a final destination',
    'Small sufficiency or reduced pressure may make enoughness a daily practice.',
    ['today', 'sufficiency', 'practice'],
  ),
];
