import type { ArchivePattern, SignalKey } from '../types';

const supportBelongingPattern = (
  key: string,
  title: string,
  requiredSignals: SignalKey[],
  supportingSignals: SignalKey[],
  shameLabel: string,
  clarityReframe: string,
  description: string,
  tags: string[] = [],
): ArchivePattern => ({
  key,
  title,
  category: 'supportBelonging',
  description,
  requiredSignals,
  supportingSignals,
  shameLabel,
  clarityReframe,
  lookbackDays: 90,
  minEvidenceCount: 3,
  minScore: 0.56,
  cooldownDays: 10,
  tags,
});

/**
 * Support + Belonging Archive Patterns
 */
export const SUPPORT_BELONGING_PATTERNS: ArchivePattern[] = [
  supportBelongingPattern(
    'support_belonging_001_support_scarcity',
    'Your Relationship with Being Caught',
    ['support_scarcity'],
    ['support_need', 'wants_to_be_caught', 'loneliness', 'small_circle_pressure'],
    'neediness',
    'a human need for care that arrives before crisis has to prove it',
    'Support feels precious, limited, uncertain, or difficult to trust before a breaking point.',
    ['support', 'care', 'being-caught'],
  ),
  supportBelongingPattern(
    'support_belonging_002_gratitude_and_grief',
    'Gratitude and Grief Can Coexist',
    ['gratitude_and_grief'],
    ['relief', 'envy_as_longing', 'support_need', 'loneliness'],
    'greed',
    'grief for support that has not always felt abundant',
    'Gratitude for existing care may coexist with grief about support that still feels absent or scarce.',
    ['gratitude', 'grief', 'support'],
  ),
  supportBelongingPattern(
    'support_belonging_003_small_circle_pressure',
    'The Small Circle Pressure',
    ['small_circle_pressure'],
    ['fear_of_being_too_much', 'support_scarcity', 'loneliness', 'minimizes_need'],
    'being ungrateful',
    'the pressure of needing a wider place to land',
    'A small support network can create pressure around who to lean on and how much to ask.',
    ['small-circle', 'support-network', 'pressure'],
  ),
  supportBelongingPattern(
    'support_belonging_004_support_scarcity',
    'The Support Scarcity Pattern',
    ['support_scarcity'],
    ['loneliness', 'self_blame', 'minimizes_need', 'support_need'],
    'wanting too much',
    'support becoming precious because it has not always felt available',
    'Limited support, loneliness, or strong self-reliance can point to a scarcity pattern around care.',
    ['scarcity', 'support', 'self-reliance'],
  ),
  supportBelongingPattern(
    'support_belonging_005_fear_of_being_too_much',
    'The Fear of Being Too Much',
    ['fear_of_being_too_much'],
    ['support_need', 'minimizes_need', 'selective_vulnerability', 'loneliness'],
    'being too needy',
    'a need for care that does not become fragile when you reach for it',
    'Fear of overwhelming others may keep needs hidden or softened before they are spoken.',
    ['needs', 'fear', 'care'],
  ),
  supportBelongingPattern(
    'support_belonging_006_receiving_care_difficulty',
    'The Receiving Care Difficulty',
    ['receiving_care_difficulty'],
    ['caretaking_pressure', 'support_need', 'receiving_openness', 'fear_of_being_too_much'],
    'being hard to help',
    'a system that learned giving more easily than receiving',
    'Help may feel uncomfortable to receive when giving has been the more familiar role.',
    ['receiving', 'care', 'giving'],
  ),
  supportBelongingPattern(
    'support_belonging_007_mutuality_need',
    'The Mutuality Need',
    ['mutuality_need'],
    ['caretaking_pressure', 'support_need', 'receiving_care_difficulty', 'truth_over_harmony'],
    'being demanding',
    'a longing for care to move both ways',
    'A one-sided care pattern may reveal the healthy need for mutuality.',
    ['mutuality', 'care', 'reciprocity'],
  ),
  supportBelongingPattern(
    'support_belonging_008_belonging_ache',
    'The Belonging Ache',
    ['belonging_ache'],
    ['loneliness', 'wants_to_be_seen', 'fear_of_being_too_much', 'chosen_family'],
    'being needy',
    'the human need to be included without performance',
    'Exclusion, not fitting, or wanting home can reveal a belonging need rather than a flaw.',
    ['belonging', 'inclusion', 'home'],
  ),
  supportBelongingPattern(
    'support_belonging_009_chosen_circle',
    'The Chosen Circle Pattern',
    ['chosen_family'],
    ['belonging_ache', 'wants_to_be_seen', 'connection_glimmer', 'mutuality_need'],
    'not having a normal support system',
    'belonging being built deliberately instead of inherited automatically',
    'Chosen family or intentional closeness can show belonging being built with care.',
    ['chosen-family', 'belonging', 'circle'],
  ),
  supportBelongingPattern(
    'support_belonging_010_envy_as_longing',
    'The Envy as Longing Pattern',
    ['envy_as_longing'],
    ['support_need', 'belonging_ache', 'longing', 'gratitude_and_grief'],
    'jealousy',
    'longing recognizing something deeply needed',
    'Envy of another person’s support may be longing pointing toward a real need.',
    ['envy', 'longing', 'support'],
  ),
  supportBelongingPattern(
    'support_belonging_011_loneliness_with_witnesses',
    'The Loneliness With Witnesses Pattern',
    ['loneliness'],
    ['wants_to_be_seen', 'belonging_ache', 'selective_vulnerability', 'support_need'],
    'being impossible to satisfy',
    'the difference between company and emotional support',
    'Being around people may not meet the deeper need to feel emotionally held or witnessed.',
    ['loneliness', 'witnessing', 'company'],
  ),
  supportBelongingPattern(
    'support_belonging_012_need_to_be_remembered',
    'The Need to Be Remembered',
    ['wants_to_be_seen'],
    ['wants_to_be_caught', 'consistency_need', 'support_need', 'loneliness'],
    'attention-seeking',
    'the longing to matter when you are not actively asking',
    'Wanting check-ins or follow-through can reflect the need to matter without performing need.',
    ['remembered', 'check-ins', 'mattering'],
  ),
  supportBelongingPattern(
    'support_belonging_013_hard_to_ask',
    'The Hard-to-Ask Pattern',
    ['minimizes_need'],
    ['support_need', 'fear_of_being_too_much', 'receiving_care_difficulty', 'self_blame'],
    'being indirect',
    'asking feeling risky when care has not always been easy to trust',
    'Needing help while not asking may show that reaching for care still feels risky.',
    ['asking', 'support', 'risk'],
  ),
  supportBelongingPattern(
    'support_belonging_014_support_without_explaining',
    'The Support Without Explaining Pattern',
    ['support_need'],
    ['overexplaining', 'wants_to_be_caught', 'emotional_availability_need', 'minimizes_need'],
    'expecting mind-reading',
    'wanting care that can recognize weight before a full case is made',
    'The archive may show a desire for support that does not require proof, explanation, or a full case.',
    ['support', 'proof', 'explanation'],
  ),
  supportBelongingPattern(
    'support_belonging_015_backup_person_need',
    'The Backup Person Need',
    ['wants_to_be_caught'],
    ['support_need', 'consistency_need', 'loneliness', 'trust_builds_slowly'],
    'dependency',
    'a need for reliable backup while still carrying your own life',
    'Wanting someone steady behind you can reflect backup, not helplessness.',
    ['backup', 'steadiness', 'support'],
  ),
  supportBelongingPattern(
    'support_belonging_016_over_reliance_fear',
    'The Over-Reliance Fear',
    ['fear_of_being_too_much'],
    ['receiving_care_difficulty', 'support_need', 'minimizes_need', 'trust_builds_slowly'],
    'being a burden',
    'caution around support because connection matters',
    'Worry about leaning too much may show how much connection matters and how carefully it is protected.',
    ['burden', 'leaning', 'connection'],
  ),
  supportBelongingPattern(
    'support_belonging_017_support_after_crisis',
    'The Support After Crisis Pattern',
    ['support_scarcity'],
    ['depletion', 'burnout_risk', 'support_need', 'asks_for_support'],
    'being dramatic',
    'a need for care to arrive earlier than collapse',
    'Support may be arriving after the breaking point rather than when the need first appears.',
    ['crisis', 'early-support', 'collapse'],
  ),
  supportBelongingPattern(
    'support_belonging_018_quietly_unsupported',
    'The Quietly Unsupported Pattern',
    ['loneliness'],
    ['overfunctioning', 'support_scarcity', 'responsibility_weight', 'minimizes_need'],
    'not appreciating what exists',
    'the ache of being capable and under-held at the same time',
    'Functioning well while feeling unsupported can be its own kind of ache.',
    ['capable', 'under-held', 'loneliness'],
  ),
  supportBelongingPattern(
    'support_belonging_019_specific_care_need',
    'The Need for Specific Care',
    ['support_need'],
    ['emotional_availability_need', 'wants_to_be_seen', 'repair_need', 'receiving_care_difficulty'],
    'being hard to comfort',
    'needing care accurate enough to find the real wound',
    'Generic reassurance may not land when the need is for accurate, specific care.',
    ['specific-care', 'comfort', 'accuracy'],
  ),
  supportBelongingPattern(
    'support_belonging_020_support_that_lands',
    'The Support That Lands',
    ['receiving_openness'],
    ['support_abundance_shift', 'connection_glimmer', 'quiet_safety', 'somatic_safety'],
    'being picky',
    'the body knowing the difference between shallow reassurance and real steadiness',
    'Specific, steady care may create a different body response than shallow reassurance.',
    ['support-that-lands', 'steadiness', 'receiving'],
  ),
];
