import type { ArchivePattern, SignalKey } from '../types';

const valuesPattern = (
  key: string,
  title: string,
  requiredSignals: SignalKey[],
  supportingSignals: SignalKey[],
  shameLabel: string,
  clarityReframe: string,
  description: string,
  tags: string[] = [],
): ArchivePattern => ({
  key,
  title,
  category: 'valuesIntegrity',
  description,
  requiredSignals,
  supportingSignals,
  shameLabel,
  clarityReframe,
  lookbackDays: 90,
  minEvidenceCount: 3,
  minScore: 0.58,
  cooldownDays: 10,
  tags,
});

/**
 * Values + Integrity Archive Patterns
 */
export const VALUES_INTEGRITY_PATTERNS: ArchivePattern[] = [
  valuesPattern(
    'values_001_justice_advocate',
    'The Value Beneath Your Anger',
    ['justice_sensitivity'],
    ['anger', 'fairness_need', 'moral_weight', 'truth_telling'],
    'being reactive',
    'a value becoming too important to ignore',
    'Anger may rise when fairness, care, safety, or justice is being violated.',
    ['anger', 'justice', 'value'],
  ),
  valuesPattern(
    'values_002_integrity_at_a_cost',
    'Integrity at a Cost',
    ['integrity_cost'],
    ['truth_telling', 'values_conflict', 'non_negotiable', 'self_trust_growth'],
    'making life harder',
    'choosing alignment even when the easier path would cost your self-respect',
    'The user may choose what feels right even when it creates difficulty.',
    ['integrity', 'alignment', 'cost'],
  ),
  valuesPattern(
    'values_003_moral_weight',
    'The Moral Weight Pattern',
    ['moral_weight'],
    ['guilt', 'fairness_need', 'repair_need', 'truth_telling'],
    'overcomplicating',
    'a serious relationship with integrity',
    'Conscience, accountability, and impact may carry meaningful moral weight.',
    ['moral-weight', 'accountability', 'impact'],
  ),
  valuesPattern(
    'values_004_loyalty_versus_truth',
    'Loyalty Versus Truth',
    ['loyalty_vs_honesty'],
    ['loyalty_conflict', 'truth_over_harmony', 'family_loyalty_tension', 'values_conflict'],
    'betrayal',
    'integrity trying to love without abandoning reality',
    'Loyalty and honesty may come into tension where love and reality both matter.',
    ['loyalty', 'truth', 'family'],
  ),
  valuesPattern(
    'values_005_non_negotiable',
    'The Non-Negotiable Pattern',
    ['non_negotiable'],
    ['inner_authority', 'truth_telling', 'boundary_rebuilding', 'values_conflict'],
    'being rigid',
    'a core truth becoming clear enough to protect',
    'A refusal to compromise may point to a core value becoming clear enough to protect.',
    ['non-negotiable', 'core-value', 'boundary'],
  ),
  valuesPattern(
    'values_006_fairness_alarm',
    'The Fairness Alarm',
    ['fairness_need'],
    ['justice_sensitivity', 'anger', 'moral_weight', 'truth_telling'],
    'being argumentative',
    'your system noticing when something important is being mishandled',
    'Unfairness, imbalance, or harm may activate a strong fairness alarm.',
    ['fairness', 'alarm', 'imbalance'],
  ),
  valuesPattern(
    'values_007_compassion_with_accountability',
    'Compassion With Accountability',
    ['moral_weight'],
    ['fairness_need', 'boundary_rebuilding', 'repair_need', 'truth_telling'],
    'being harsh',
    'care that refuses to erase impact',
    'Empathy and limits may both be present where care refuses to erase impact.',
    ['compassion', 'accountability', 'impact'],
  ),
  valuesPattern(
    'values_008_responsibility_beyond_obligation',
    'The Responsibility Beyond Obligation Pattern',
    ['responsibility_weight'],
    ['purpose_signal', 'moral_weight', 'legacy_signal', 'faith_meaning'],
    'taking things too seriously',
    'responsibility feeling sacred where something important is at stake',
    'Responsibility may feel deeper than obligation when something meaningful is at stake.',
    ['responsibility', 'purpose', 'sacred'],
  ),
  valuesPattern(
    'values_009_honesty_over_comfort',
    'The Honesty Over Comfort Pattern',
    ['truth_telling'],
    ['truth_over_harmony', 'integrity_cost', 'values_conflict', 'throat_tightness'],
    'being difficult',
    'truth becoming more important than short-term ease',
    'Truth-telling may become more important than temporary comfort or avoidance.',
    ['honesty', 'comfort', 'truth'],
  ),
  valuesPattern(
    'values_010_cause_that_calls_you',
    'The Cause That Calls You',
    ['purpose_signal'],
    ['justice_sensitivity', 'legacy_signal', 'meaning_making', 'wants_to_build'],
    'being too invested',
    'your values recognizing where your energy wants to serve',
    'A meaningful problem or injustice may call the user because it aligns with values.',
    ['purpose', 'cause', 'service'],
  ),
  valuesPattern(
    'values_011_empathy_cost',
    'The Empathy Cost',
    ['caretaking_pressure'],
    ['moral_weight', 'emotional_heaviness', 'boundary_rebuilding', 'depletion'],
    'being too affected',
    'empathy needing boundaries so it can stay alive without drowning you',
    'Absorbing others pain may show empathy that needs boundaries to remain sustainable.',
    ['empathy', 'boundaries', 'depletion'],
  ),
  valuesPattern(
    'values_012_mercy_versus_enabling',
    'The Mercy Versus Enabling Pattern',
    ['fairness_need'],
    ['boundary_rebuilding', 'repair_need', 'moral_weight', 'truth_telling'],
    'being unforgiving',
    'discernment about when kindness needs a boundary',
    'Compassion and accountability may meet where repeated harm requires discernment.',
    ['mercy', 'enabling', 'boundary'],
  ),
  valuesPattern(
    'values_013_guilt_points_to_value',
    'The Guilt That Points to a Value',
    ['guilt'],
    ['moral_weight', 'repair_need', 'integrity_cost', 'self_forgiveness'],
    'being bad',
    'a value asking for repair rather than punishment',
    'Guilt may be pointing toward repair and values rather than punishment.',
    ['guilt', 'repair', 'value'],
  ),
  valuesPattern(
    'values_014_personal_code',
    'The Personal Code Pattern',
    ['non_negotiable'],
    ['high_standards', 'integrity_cost', 'inner_authority', 'truth_telling'],
    'being too intense',
    'living by an inner code that gives your choices shape',
    'Honor, consistency, and standards may form an inner code that gives choices shape.',
    ['code', 'standards', 'honor'],
  ),
  valuesPattern(
    'values_015_purpose_over_comfort',
    'The Purpose Over Comfort Pattern',
    ['purpose_signal'],
    ['growth_edge', 'integrity_cost', 'truth_telling', 'non_negotiable'],
    'choosing difficulty',
    'meaning becoming stronger than avoidance',
    'The user may choose the harder right thing when meaning becomes stronger than avoidance.',
    ['purpose', 'growth', 'comfort'],
  ),
  valuesPattern(
    'values_016_sacred_ordinary',
    'The Sacred Ordinary Pattern',
    ['ordinary_sacred'],
    ['gratitude_and_grief', 'beauty_glimmer', 'faith_meaning', 'spiritual_depth'],
    'romanticizing small things',
    'depth noticing meaning where the world often rushes past it',
    'Ordinary moments may carry sacredness or meaning that the user notices deeply.',
    ['ordinary', 'sacred', 'meaning'],
  ),
  valuesPattern(
    'values_017_values_misalignment',
    'The Values Misalignment Signal',
    ['values_conflict'],
    ['integrity_cost', 'fairness_need', 'truth_telling', 'moral_weight'],
    'being dissatisfied',
    'your inner compass noticing where life no longer fits',
    'Discomfort may appear when daily life no longer matches core values.',
    ['misalignment', 'compass', 'values'],
  ),
  valuesPattern(
    'values_018_inner_standard',
    'The Inner Standard Pattern',
    ['high_standards'],
    ['excellence_pressure', 'integrity_cost', 'moral_weight', 'creative_standards'],
    'expecting too much',
    'wanting your outer life to match what you know matters inside',
    'High standards may reflect a desire for outer life to match inner values.',
    ['standards', 'excellence', 'alignment'],
  ),
  valuesPattern(
    'values_019_impact_awareness',
    'The Impact Awareness Pattern',
    ['moral_weight'],
    ['guilt', 'repair_need', 'truth_telling', 'self_forgiveness'],
    'overthinking mistakes',
    'caring enough to understand how your actions land',
    'Concern about intention, impact, and accountability may show care about how actions land.',
    ['impact', 'accountability', 'repair'],
  ),
  valuesPattern(
    'values_020_truth_you_cannot_unsee',
    'The Truth You Cannot Unsee',
    ['truth_telling'],
    ['integrity_cost', 'values_conflict', 'identity_rewriting', 'non_negotiable'],
    'being unable to move on',
    'a truth becoming visible enough to change your relationship with what came before',
    'A difficult realization may change the user relationship to what came before.',
    ['truth', 'realization', 'change'],
  ),
];
