import { SingleWordSymbol } from "../dreamSingularSymbols";

export const clothing_symbols: SingleWordSymbol[] = [
  { symbol: "hat", category: "clothing" },
  { symbol: "zipperbag", category: "clothing" },
  { symbol: "socks", category: "clothing" },
  { symbol: "socketwrench", category: "clothing" },
  { symbol: "helmetstrap", category: "clothing" },
  { symbol: "shirt", category: "clothing" },
  { symbol: "bulletvibrator", category: "clothing" },
  { symbol: "lifejacket", category: "clothing" },
  { symbol: "fireplace", category: "clothing" },
  { symbol: "pants", category: "clothing" },
  { symbol: "shoerack", category: "clothing" },
  { symbol: "pantshanger", category: "clothing" },
  { symbol: "socketset", category: "clothing" },
  { symbol: "brakepad", category: "clothing" },
  { symbol: "shoes", category: "clothing" },
  { symbol: "coat", category: "clothing" },
  { symbol: "radiatorcap", category: "clothing" },
  { symbol: "boots", category: "clothing" },
  { symbol: "uniform", category: "clothing" },
  { symbol: "hubcap", category: "clothing" },
  { symbol: "cabletie", category: "clothing" },
  { symbol: "shoelace", category: "clothing" },
  { symbol: "brakepedal", category: "clothing" },
  { symbol: "dress", category: "clothing" },
  { symbol: "coffeecapsule", category: "clothing" },
  { symbol: "helmet", category: "clothing" },
  { symbol: "glovesbox", category: "clothing" },
  { symbol: "necklace", category: "clothing" },
  { symbol: "bracketry", category: "clothing" },
  { symbol: "zipper", category: "clothing" },
  { symbol: "zipperteeth", category: "clothing" },
  { symbol: "suitcasehandle", category: "clothing" },
  { symbol: "branch", category: "clothing" },
  { symbol: "windsock", category: "clothing" },
  { symbol: "seatbelt", category: "clothing" },
  { symbol: "shoeinsert", category: "clothing" },
  { symbol: "hatbox", category: "clothing" },
  { symbol: "shoehorn", category: "clothing" },
  { symbol: "valvecap", category: "clothing" },
  { symbol: "brace", category: "clothing" },
  { symbol: "pipecap", category: "clothing" },
  { symbol: "lenscap", category: "clothing" },
  { symbol: "shoebrush", category: "clothing" },
  { symbol: "capsule", category: "clothing" },
  { symbol: "screwcap", category: "clothing" },
  { symbol: "placemat", category: "clothing" },
  { symbol: "kneebrace", category: "clothing" },
  { symbol: "cornerbrace", category: "clothing" },
  { symbol: "scarf", category: "clothing" },
  { symbol: "suitcase", category: "clothing" },
  { symbol: "hairtie", category: "clothing" },
  { symbol: "anklebrace", category: "clothing" },
  { symbol: "skullcap", category: "clothing" },
  { symbol: "toolbelt", category: "clothing" },
  { symbol: "boxinggloves", category: "clothing" },
  { symbol: "oilfiltercap", category: "clothing" },
  { symbol: "funnelcap", category: "clothing" },
  { symbol: "socketadapter", category: "clothing" },
  { symbol: "zipperpull", category: "clothing" },
  { symbol: "scooterhelmet", category: "clothing" },
  { symbol: "sweater", category: "clothing" },
  { symbol: "rainhat", category: "clothing" },
  { symbol: "dresserdrawer", category: "clothing" },
  { symbol: "raincoat", category: "clothing" },
  { symbol: "jacket", category: "clothing" },
  { symbol: "gloves", category: "clothing" },
  { symbol: "vibrator", category: "clothing" },
  { symbol: "bracket", category: "clothing" },
  { symbol: "cap", category: "clothing" },
  { symbol: "bracelet", category: "clothing" },
  { symbol: "shoebox", category: "clothing" },
  { symbol: "socket", category: "clothing" },
  { symbol: "dresser", category: "clothing" },
  { symbol: "belt", category: "clothing" },
  { symbol: "helmetvisor", category: "clothing" },
  { symbol: "beltloop", category: "clothing" },
  { symbol: "bikehelmet", category: "clothing" },
  { symbol: "nozzlecap", category: "clothing" },
  { symbol: "safetyhelmet", category: "clothing" },
  { symbol: "tie", category: "clothing" },
  { symbol: "coatrack", category: "clothing" },
  { symbol: "pipe cap", category: "clothing" },
  { symbol: "bottlecap", category: "clothing" },
  { symbol: "coathanger", category: "clothing" },
  { symbol: "sweatband", category: "clothing" },
  { symbol: "wallbracket", category: "clothing" },
  { symbol: "visorcap", category: "clothing" },

  {
    symbol: "tshirt",
    category: "clothing",
  },
  {
    symbol: "longsleeve",
    category: "clothing",
  },
  {
    symbol: "blouse",
    category: "clothing",
  },
  {
    symbol: "sweatshirt",
    category: "clothing",
  },
  {
    symbol: "hoodie",
    category: "clothing",
  },
  {
    symbol: "cardigan",
    category: "clothing",
  },
  {
    symbol: "parka",
    category: "clothing",
  },
  {
    symbol: "windbreaker",
    category: "clothing",
  },
  {
    symbol: "poncho",
    category: "clothing",
  },
  {
    symbol: "vest",
    category: "clothing",
  },
  {
    symbol: "tanktop",
    category: "clothing",
  },
  {
    symbol: "camisole",
    category: "clothing",
  },
  {
    symbol: "bodysuit",
    category: "clothing",
  },
  {
    symbol: "sundress",
    category: "clothing",
  },
  {
    symbol: "gown",
    category: "clothing",
  },
  {
    symbol: "eveninggown",
    category: "clothing",
  },
  {
    symbol: "cocktaildress",
    category: "clothing",
  },
  {
    symbol: "minidress",
    category: "clothing",
  },
  {
    symbol: "maxidress",
    category: "clothing",
  },
  {
    symbol: "skirt",
    category: "clothing",
  },
  {
    symbol: "miniskirt",
    category: "clothing",
  },
  {
    symbol: "maxiskirt",
    category: "clothing",
  },
  {
    symbol: "pencilskirt",
    category: "clothing",
  },
  {
    symbol: "jeans",
    category: "clothing",
  },
  {
    symbol: "trousers",
    category: "clothing",
  },
  {
    symbol: "leggings",
    category: "clothing",
  },
  {
    symbol: "jeggings",
    category: "clothing",
  },
  {
    symbol: "sweatpants",
    category: "clothing",
  },
  {
    symbol: "joggers",
    category: "clothing",
  },
  {
    symbol: "shorts",
    category: "clothing",
  },
  {
    symbol: "denimshorts",
    category: "clothing",
  },
  {
    symbol: "cargo shorts",
    category: "clothing",
  },
  {
    symbol: "boxer shorts",
    category: "clothing",
  },
  {
    symbol: "underwear",
    category: "clothing",
  },
  {
    symbol: "panties",
    category: "clothing",
  },
  {
    symbol: "briefs",
    category: "clothing",
  },
  {
    symbol: "boxers",
    category: "clothing",
  },
  {
    symbol: "boxerbriefs",
    category: "clothing",
  },
  {
    symbol: "thong",
    category: "clothing",
  },
  {
    symbol: "gstring",
    category: "clothing",
  },
  {
    symbol: "bralette",
    category: "clothing",
  },
  {
    symbol: "bra",
    category: "clothing",
  },
  {
    symbol: "sportsbra",
    category: "clothing",
  },
  {
    symbol: "straplessbra",
    category: "clothing",
  },
  {
    symbol: "camisolebra",
    category: "clothing",
  },
  {
    symbol: "slip",
    category: "clothing",
  },
  {
    symbol: "nightgown",
    category: "clothing",
  },
  {
    symbol: "pajamas",
    category: "clothing",
  },
  {
    symbol: "pajama pants",
    category: "clothing",
  },
  {
    symbol: "pajama shirt",
    category: "clothing",
  },
  {
    symbol: "robe",
    category: "clothing",
  },
  {
    symbol: "bathrobe",
    category: "clothing",
  },
  {
    symbol: "kimono",
    category: "clothing",
  },
  {
    symbol: "coatdress",
    category: "clothing",
  },
  {
    symbol: "jumpsuit",
    category: "clothing",
  },
  {
    symbol: "romper",
    category: "clothing",
  },
  {
    symbol: "overalls",
    category: "clothing",
  },
  {
    symbol: "coveralls",
    category: "clothing",
  },
  {
    symbol: "leotard",
    category: "clothing",
  },
  {
    symbol: "unitard",
    category: "clothing",
  },
  {
    symbol: "tights",
    category: "clothing",
  },
  {
    symbol: "stockings",
    category: "clothing",
  },
  {
    symbol: "pantyhose",
    category: "clothing",
  },
  {
    symbol: "fishnets",
    category: "clothing",
  },
  {
    symbol: "thighhighs",
    category: "clothing",
  },
  {
    symbol: "ankle socks",
    category: "clothing",
  },
  {
    symbol: "crew socks",
    category: "clothing",
  },
  {
    symbol: "knee socks",
    category: "clothing",
  },
  {
    symbol: "legwarmers",
    category: "clothing",
  },
  {
    symbol: "shawl",
    category: "clothing",
  },
  {
    symbol: "stole",
    category: "clothing",
  },
  {
    symbol: "wrap",
    category: "clothing",
  },
  {
    symbol: "mittens",
    category: "clothing",
  },
  {
    symbol: "fingerless gloves",
    category: "clothing",
  },
  {
    symbol: "beanie",
    category: "clothing",
  },
  {
    symbol: "baseballcap",
    category: "clothing",
  },
  {
    symbol: "snapback",
    category: "clothing",
  },
  {
    symbol: "visor",
    category: "clothing",
  },
  {
    symbol: "fedora",
    category: "clothing",
  },
  {
    symbol: "beret",
    category: "clothing",
  },
  {
    symbol: "cowboyhat",
    category: "clothing",
  },
  {
    symbol: "sunhat",
    category: "clothing",
  },
  {
    symbol: "bucket hat",
    category: "clothing",
  },
  {
    symbol: "hardhat",
    category: "clothing",
  },
  {
    symbol: "hood",
    category: "clothing",
  },
  {
    symbol: "mask",
    category: "clothing",
  },
  {
    symbol: "face mask",
    category: "clothing",
  },
  {
    symbol: "balaclava",
    category: "clothing",
  },
  {
    symbol: "bandana",
    category: "clothing",
  },
  {
    symbol: "headband",
    category: "clothing",
  },
  {
    symbol: "hairband",
    category: "clothing",
  },
  {
    symbol: "turban",
    category: "clothing",
  },
  {
    symbol: "hijab",
    category: "clothing",
  },
  {
    symbol: "niqab",
    category: "clothing",
  },
  {
    symbol: "chador",
    category: "clothing",
  },
  {
    symbol: "abaya",
    category: "clothing",
  },
  {
    symbol: "sari",
    category: "clothing",
  },
  {
    symbol: "saree",
    category: "clothing",
  },
  {
    symbol: "kurta",
    category: "clothing",
  },
  {
    symbol: "kimono robe",
    category: "clothing",
  },
  {
    symbol: "hanbok",
    category: "clothing",
  },
  {
    symbol: "cheongsam",
    category: "clothing",
  },
  {
    symbol: "qipao",
    category: "clothing",
  },
  {
    symbol: "poncho coat",
    category: "clothing",
  },
  {
    symbol: "trenchcoat",
    category: "clothing",
  },
  {
    symbol: "peacoat",
    category: "clothing",
  },
  {
    symbol: "overcoat",
    category: "clothing",
  },
  {
    symbol: "fleece jacket",
    category: "clothing",
  },
  {
    symbol: "varsity jacket",
    category: "clothing",
  },
  {
    symbol: "bomber jacket",
    category: "clothing",
  },
  {
    symbol: "leather jacket",
    category: "clothing",
  },
  {
    symbol: "denim jacket",
    category: "clothing",
  },
  {
    symbol: "puffer jacket",
    category: "clothing",
  },
  {
    symbol: "ski jacket",
    category: "clothing",
  },
  {
    symbol: "snowpants",
    category: "clothing",
  },
  {
    symbol: "wetsuit",
    category: "clothing",
  },
  {
    symbol: "drysuit",
    category: "clothing",
  },
  {
    symbol: "swimsuit",
    category: "clothing",
  },
  {
    symbol: "bikini",
    category: "clothing",
  },
  {
    symbol: "tankini",
    category: "clothing",
  },
  {
    symbol: "swim trunks",
    category: "clothing",
  },
  {
    symbol: "boardshorts",
    category: "clothing",
  },
  {
    symbol: "rashguard",
    category: "clothing",
  },
  {
    symbol: "bathingsuit",
    category: "clothing",
  },
  {
    symbol: "apron",
    category: "clothing",
  },
  {
    symbol: "labcoat",
    category: "clothing",
  },
  {
    symbol: "doctors coat",
    category: "clothing",
  },
  {
    symbol: "scrubs",
    category: "clothing",
  },
  {
    symbol: "policeuniform",
    category: "clothing",
  },
  {
    symbol: "firefighteruniform",
    category: "clothing",
  },
  {
    symbol: "militaryuniform",
    category: "clothing",
  },
  {
    symbol: "camouflage",
    category: "clothing",
  },
  {
    symbol: "suit",
    category: "clothing",
  },
  {
    symbol: "businesssuit",
    category: "clothing",
  },
  {
    symbol: "tuxedo",
    category: "clothing",
  },
  {
    symbol: "blazer",
    category: "clothing",
  },
  {
    symbol: "waistcoat",
    category: "clothing",
  },
  {
    symbol: "vestcoat",
    category: "clothing",
  },
  {
    symbol: "bowtie",
    category: "clothing",
  },
  {
    symbol: "necktie",
    category: "clothing",
  },
  {
    symbol: "cravat",
    category: "clothing",
  },
  {
    symbol: "suspenders",
    category: "clothing",
  },
  {
    symbol: "waistband",
    category: "clothing",
  },
  {
    symbol: "garterbelt",
    category: "clothing",
  },
  {
    symbol: "garter",
    category: "clothing",
  },
  {
    symbol: "corset",
    category: "clothing",
  },
  {
    symbol: "bustier",
    category: "clothing",
  },
  {
    symbol: "bodice",
    category: "clothing",
  },
  {
    symbol: "waistcincher",
    category: "clothing",
  },
  {
    symbol: "shapewear",
    category: "clothing",
  },
  {
    symbol: "slipdress",
    category: "clothing",
  },
  {
    symbol: "chemise",
    category: "clothing",
  },
  {
    symbol: "lingerie",
    category: "clothing",
  },
  {
    symbol: "babydoll",
    category: "clothing",
  },
  {
    symbol: "teddy",
    category: "clothing",
  },
  {
    symbol: "bodystocking",
    category: "clothing",
  },
  {
    symbol: "stockingsbelt",
    category: "clothing",
  },
  {
    symbol: "sockgarter",
    category: "clothing",
  },
  {
    symbol: "armwarmers",
    category: "clothing",
  },
  {
    symbol: "earmuffs",
    category: "clothing",
  },
  {
    symbol: "shawlcoat",
    category: "clothing",
  },
  {
    symbol: "ponchoshawl",
    category: "clothing",
  },
  {
    symbol: "rainponcho",
    category: "clothing",
  },
  {
    symbol: "ski suit",
    category: "clothing",
  },
  {
    symbol: "snow suit",
    category: "clothing",
  },
  {
    symbol: "track suit",
    category: "clothing",
  },
  {
    symbol: "workout clothes",
    category: "clothing",
  },
  {
    symbol: "gym shorts",
    category: "clothing",
  },
  {
    symbol: "yoga pants",
    category: "clothing",
  },
  {
    symbol: "compression shirt",
    category: "clothing",
  },
  {
    symbol: "compression shorts",
    category: "clothing",
  },
  {
    symbol: "cycling jersey",
    category: "clothing",
  },
  {
    symbol: "cycling shorts",
    category: "clothing",
  },
  {
    symbol: "running shorts",
    category: "clothing",
  },
  {
    symbol: "running shirt",
    category: "clothing",
  },
  {
    symbol: "athletic jacket",
    category: "clothing",
  },
  {
    symbol: "athletic pants",
    category: "clothing",
  },
  {
    symbol: "dance costume",
    category: "clothing",
  },
  {
    symbol: "ballet leotard",
    category: "clothing",
  },
  {
    symbol: "ballet tutu",
    category: "clothing",
  },
  {
    symbol: "ballet skirt",
    category: "clothing",
  },
  {
    symbol: "costume",
    category: "clothing",
  },
  {
    symbol: "halloween costume",
    category: "clothing",
  },
  {
    symbol: "mascot suit",
    category: "clothing",
  },
  {
    symbol: "mascot head",
    category: "clothing",
  },
  {
    symbol: "cloak",
    category: "clothing",
  },
  {
    symbol: "cape",
    category: "clothing",
  },
  {
    symbol: "capelet",
    category: "clothing",
  },
  {
    symbol: "mantle",
    category: "clothing",
  },
  {
    symbol: "hooded cloak",
    category: "clothing",
  },
  {
    symbol: "ceremonial robe",
    category: "clothing",
  },
  {
    symbol: "choir robe",
    category: "clothing",
  },
  {
    symbol: "graduation gown",
    category: "clothing",
  },
  {
    symbol: "graduation hood",
    category: "clothing",
  },
  {
    symbol: "graduation cap",
    category: "clothing",
  },
  {
    symbol: "academic robe",
    category: "clothing",
  },
  {
    symbol: "judicial robe",
    category: "clothing",
  },
  {
    symbol: "monk robe",
    category: "clothing",
  },
  {
    symbol: "nun habit",
    category: "clothing",
  },
  {
    symbol: "priest robe",
    category: "clothing",
  },
  {
    symbol: "bishop robe",
    category: "clothing",
  },
  {
    symbol: "armor",
    category: "clothing",
  },
  {
    symbol: "chainmail",
    category: "clothing",
  },
  {
    symbol: "breastplate",
    category: "clothing",
  },
  {
    symbol: "tunic",
    category: "clothing",
  },
  {
    symbol: "toga",
    category: "clothing",
  },
  {
    symbol: "loincloth",
    category: "clothing",
  },
  {
    symbol: "kilt",
    category: "clothing",
  },
  {
    symbol: "sarong",
    category: "clothing",
  },
  {
    symbol: "wrap skirt",
    category: "clothing",
  },
  {
    symbol: "poncho sweater",
    category: "clothing",
  },
  {
    symbol: "cardigan sweater",
    category: "clothing",
  },
  {
    symbol: "fleece pullover",
    category: "clothing",
  },
  {
    symbol: "thermal shirt",
    category: "clothing",
  },
  {
    symbol: "thermal underwear",
    category: "clothing",
  },
  {
    symbol: "base layer",
    category: "clothing",
  },
  {
    symbol: "undershirt",
    category: "clothing",
  },
  {
    symbol: "undershorts",
    category: "clothing",
  },
  {
    symbol: "sleepwear",
    category: "clothing",
  },
  {
    symbol: "loungewear",
    category: "clothing",
  },
  {
    symbol: "housecoat",
    category: "clothing",
  },
  {
    symbol: "duster",
    category: "clothing",
  },
  {
    symbol: "overalls shorts",
    category: "clothing",
  },
  {
    symbol: "coverall suit",
    category: "clothing",
  },
  {
    symbol: "mechanic suit",
    category: "clothing",
  },
  {
    symbol: "painter suit",
    category: "clothing",
  },
  {
    symbol: "hazmat suit",
    category: "clothing",
  },
  {
    symbol: "protective suit",
    category: "clothing",
  },
  {
    symbol: "rain suit",
    category: "clothing",
  },
  {
    symbol: "flight suit",
    category: "clothing",
  },
  {
    symbol: "space suit",
    category: "clothing",
  },
  {
    symbol: "wetsuit hood",
    category: "clothing",
  },
  {
    symbol: "wetsuit gloves",
    category: "clothing",
  },
  {
    symbol: "wetsuit boots",
    category: "clothing",
  },
  { symbol: "armoire", category: "clothing" },
  { symbol: "cloth", category: "clothing" },
  { symbol: "underwrap", category: "clothing" },
  { symbol: "camouflaged", category: "clothing" },
  { symbol: "womenswear", category: "clothing" },
  { symbol: "bedding", category: "clothing" },
  { symbol: "overall", category: "clothing" },
  { symbol: "doff", category: "clothing" },
  { symbol: "leatherwear", category: "clothing" },
  { symbol: "merchandise", category: "clothing" },
  { symbol: "dyer", category: "clothing" },
  { symbol: "inflatable", category: "clothing" },
  { symbol: "furring", category: "clothing" },
  { symbol: "footwear", category: "clothing" },
  { symbol: "draping", category: "clothing" },
  { symbol: "jewellery", category: "clothing" },
  { symbol: "hem", category: "clothing" },
  { symbol: "shelter", category: "clothing" },
  { symbol: "haberdashery", category: "clothing" },
  { symbol: "array", category: "clothing" },
  { symbol: "cottonwear", category: "clothing" },
  { symbol: "change", category: "clothing" },
  { symbol: "shirts", category: "clothing" },
  { symbol: "dressing", category: "clothing" },
  { symbol: "habit", category: "clothing" },
  { symbol: "accessories", category: "clothing" },
  { symbol: "wearing", category: "clothing" },
  { symbol: "winterwear", category: "clothing" },
  { symbol: "dandy", category: "clothing" },
  { symbol: "baggy", category: "clothing" },
  { symbol: "barb", category: "clothing" },
  { symbol: "buckskin", category: "clothing" },
  { symbol: "vestiary", category: "clothing" },
  { symbol: "blue", category: "clothing" },
  { symbol: "designs", category: "clothing" },
  { symbol: "cover", category: "clothing" },
  { symbol: "habiliment", category: "clothing" },
  { symbol: "handwear", category: "clothing" },
  { symbol: "activewear", category: "clothing" },
  { symbol: "cosmetics", category: "clothing" },
  { symbol: "rainwear", category: "clothing" },
  { symbol: "cord", category: "clothing" },
  { symbol: "threads", category: "clothing" },
  { symbol: "overthings", category: "clothing" },
  { symbol: "disguised", category: "clothing" },
  { symbol: "fashion", category: "clothing" },
  { symbol: "equipment", category: "clothing" },
  { symbol: "babywear", category: "clothing" },
  { symbol: "unfabricated", category: "clothing" },
  { symbol: "dye", category: "clothing" },
  { symbol: "kir", category: "clothing" },
  { symbol: "furnishings", category: "clothing" },
  { symbol: "makeup", category: "clothing" },
  { symbol: "woolen", category: "clothing" },
  { symbol: "accessory", category: "clothing" },
  { symbol: "plastic", category: "clothing" },
  { symbol: "casted", category: "clothing" },
  { symbol: "furniture", category: "clothing" },
  { symbol: "caparisoned", category: "clothing" },
  { symbol: "stuff", category: "clothing" },
  { symbol: "dishevel", category: "clothing" },
  { symbol: "outwear", category: "clothing" },
  { symbol: "armour", category: "clothing" },
  { symbol: "card", category: "clothing" },
  { symbol: "swimsuits", category: "clothing" },
  { symbol: "lacewear", category: "clothing" },
  { symbol: "frock", category: "clothing" },
  { symbol: "band", category: "clothing" },
  { symbol: "gingham", category: "clothing" },
  { symbol: "synthetic", category: "clothing" },
  { symbol: "sweatsuits", category: "clothing" },
  { symbol: "bags", category: "clothing" },
  { symbol: "garb", category: "clothing" },
  { symbol: "houseware", category: "clothing" },
  { symbol: "leisurewear", category: "clothing" },
  { symbol: "hats", category: "clothing" },
  { symbol: "bespoken", category: "clothing" },
  { symbol: "garment", category: "clothing" },
  { symbol: "retailer", category: "clothing" },
  { symbol: "textile", category: "clothing" },
  { symbol: "flannel", category: "clothing" },
  { symbol: "held", category: "clothing" },
  { symbol: "claws", category: "clothing" },
  { symbol: "bib", category: "clothing" },
  { symbol: "dressmaker", category: "clothing" },
  { symbol: "changing", category: "clothing" },
  { symbol: "apparel", category: "clothing" },
  { symbol: "housewares", category: "clothing" },
  { symbol: "bare", category: "clothing" },
  { symbol: "garbs", category: "clothing" },
  { symbol: "dresses", category: "clothing" },
  { symbol: "chinchilla", category: "clothing" },
  { symbol: "fashions", category: "clothing" },
  { symbol: "material", category: "clothing" },
  { symbol: "linen", category: "clothing" },
  { symbol: "undergarments", category: "clothing" },
  { symbol: "duds", category: "clothing" },
  { symbol: "food", category: "clothing" },
  { symbol: "garbage", category: "clothing" },
  { symbol: "sweaters", category: "clothing" },
  { symbol: "laundry", category: "clothing" },
  { symbol: "flange", category: "clothing" },
  { symbol: "countrywear", category: "clothing" },
  { symbol: "bugle", category: "clothing" },
  { symbol: "cast", category: "clothing" },
  { symbol: "drape", category: "clothing" },
  { symbol: "cloaked", category: "clothing" },
  { symbol: "beachwear", category: "clothing" },
  { symbol: "dressed", category: "clothing" },
  { symbol: "uniforms", category: "clothing" },
  { symbol: "underclothing", category: "clothing" },
  { symbol: "manufacturer", category: "clothing" },
  { symbol: "bosom", category: "clothing" },
  { symbol: "fabrics", category: "clothing" },
  { symbol: "dacron", category: "clothing" },
  { symbol: "brown", category: "clothing" },
  { symbol: "accoutrement", category: "clothing" },
  { symbol: "clothespress", category: "clothing" },
  { symbol: "hang", category: "clothing" },
  { symbol: "outfits", category: "clothing" },
  { symbol: "cloath", category: "clothing" },
  { symbol: "weeds", category: "clothing" },
  { symbol: "spacesuit", category: "clothing" },
  { symbol: "warmer", category: "clothing" },
  { symbol: "minaret", category: "clothing" },
  { symbol: "violet", category: "clothing" },
  { symbol: "bushel", category: "clothing" },
  { symbol: "disarray", category: "clothing" },
  { symbol: "knitwear", category: "clothing" },
  { symbol: "store", category: "clothing" },
  { symbol: "business", category: "clothing" },
  { symbol: "overcloth", category: "clothing" },
  { symbol: "lap", category: "clothing" },
  { symbol: "wore", category: "clothing" },
  { symbol: "butt", category: "clothing" },
  { symbol: "ellis", category: "clothing" },
  { symbol: "outerwear", category: "clothing" },
  { symbol: "wrapper", category: "clothing" },
  { symbol: "weaponry", category: "clothing" },
  { symbol: "angora", category: "clothing" },
  { symbol: "vestments", category: "clothing" },
  { symbol: "diaper", category: "clothing" },
  { symbol: "coordinate", category: "clothing" },
  { symbol: "breech", category: "clothing" },
  { symbol: "crinoline", category: "clothing" },
  { symbol: "glove", category: "clothing" },
  { symbol: "enrobe", category: "clothing" },
  { symbol: "clobber", category: "clothing" },
  { symbol: "fleece", category: "clothing" },
  { symbol: "vestiture", category: "clothing" },
  { symbol: "button", category: "clothing" },
  { symbol: "bespoke", category: "clothing" },
  { symbol: "headwear", category: "clothing" },
  { symbol: "stores", category: "clothing" },
  { symbol: "brand", category: "clothing" },
  { symbol: "retail", category: "clothing" },
  { symbol: "nightclothes", category: "clothing" },
  { symbol: "agraffe", category: "clothing" },
  { symbol: "suits", category: "clothing" },
  { symbol: "foodstuffs", category: "clothing" },
  { symbol: "grey", category: "clothing" },
  { symbol: "number", category: "clothing" },
  { symbol: "toys", category: "clothing" },
  { symbol: "blanketed", category: "clothing" },
  { symbol: "gauze", category: "clothing" },
  { symbol: "backwater", category: "clothing" },
  { symbol: "undergarment", category: "clothing" },
  { symbol: "textiles", category: "clothing" },
  { symbol: "ermine", category: "clothing" },
  { symbol: "linens", category: "clothing" },
  { symbol: "pelt", category: "clothing" },
  { symbol: "partywear", category: "clothing" },
  { symbol: "ducks", category: "clothing" },
  { symbol: "clothes", category: "clothing" },
  { symbol: "drag", category: "clothing" },
  { symbol: "fashionwear", category: "clothing" },
  { symbol: "bedgown", category: "clothing" },
  { symbol: "duck", category: "clothing" },
  { symbol: "thing", category: "clothing" },
  { symbol: "fabric", category: "clothing" },
  { symbol: "tailored", category: "clothing" },
  { symbol: "tog", category: "clothing" },
  { symbol: "athleticwear", category: "clothing" },
  { symbol: "costumes", category: "clothing" },
  { symbol: "blankets", category: "clothing" },
  { symbol: "groom", category: "clothing" },
  { symbol: "attires", category: "clothing" },
  { symbol: "dressy", category: "clothing" },
  { symbol: "clothier", category: "clothing" },
  { symbol: "draper", category: "clothing" },
  { symbol: "divest", category: "clothing" },
  { symbol: "manufacture", category: "clothing" },
  { symbol: "harness", category: "clothing" },
  { symbol: "fur", category: "clothing" },
  { symbol: "ensemble", category: "clothing" },
  { symbol: "sportswear", category: "clothing" },
  { symbol: "designer", category: "clothing" },
  { symbol: "informalwear", category: "clothing" },
  { symbol: "bak", category: "clothing" },
  { symbol: "coordinates", category: "clothing" },
  { symbol: "finery", category: "clothing" },
  { symbol: "drapery", category: "clothing" },
  { symbol: "caparison", category: "clothing" },
  { symbol: "woolens", category: "clothing" },
  { symbol: "supplies", category: "clothing" },
  { symbol: "don", category: "clothing" },
  { symbol: "outfit", category: "clothing" },
  { symbol: "goods", category: "clothing" },
  { symbol: "overclothing", category: "clothing" },
  { symbol: "closet", category: "clothing" },
  { symbol: "gird", category: "clothing" },
  { symbol: "kut", category: "clothing" },
  { symbol: "mothball", category: "clothing" },
  { symbol: "plugins", category: "clothing" },
  { symbol: "broadcloth", category: "clothing" },
  { symbol: "waterproof", category: "clothing" },
  { symbol: "jackets", category: "clothing" },
  { symbol: "kitchenware", category: "clothing" },
  { symbol: "back", category: "clothing" },
  { symbol: "jewelery", category: "clothing" },
  { symbol: "couturier", category: "clothing" },
  { symbol: "confection", category: "clothing" },
  { symbol: "headgear", category: "clothing" },
  { symbol: "hemming", category: "clothing" },
  { symbol: "cheviot", category: "clothing" },
  { symbol: "snowwear", category: "clothing" },
  { symbol: "habiliments", category: "clothing" },
  { symbol: "footgear", category: "clothing" },
  { symbol: "camo", category: "clothing" },
  { symbol: "menswear", category: "clothing" },
  { symbol: "vesture", category: "clothing" },
  { symbol: "underclothes", category: "clothing" },
  { symbol: "headdress", category: "clothing" },
  { symbol: "gear", category: "clothing" },
  { symbol: "fit", category: "clothing" },
  { symbol: "black", category: "clothing" },
  { symbol: "canvas", category: "clothing" },
  { symbol: "silk", category: "clothing" },
  { symbol: "robes", category: "clothing" },
  { symbol: "styles", category: "clothing" },
  { symbol: "woodworking", category: "clothing" },
  { symbol: "gray", category: "clothing" },
  { symbol: "wear", category: "clothing" },
  { symbol: "brooch", category: "clothing" },
  { symbol: "bibbed", category: "clothing" },
  { symbol: "chain", category: "clothing" },
  { symbol: "factory", category: "clothing" },
  { symbol: "brands", category: "clothing" },
  { symbol: "hater", category: "clothing" },
  { symbol: "dud", category: "clothing" },
  { symbol: "mink", category: "clothing" },
  { symbol: "batiste", category: "clothing" },
  { symbol: "habilatory", category: "clothing" },
  { symbol: "topwear", category: "clothing" },
  { symbol: "shroud", category: "clothing" },
  { symbol: "cutter", category: "clothing" },
  { symbol: "couture", category: "clothing" },
  { symbol: "arrayed", category: "clothing" },
  { symbol: "clotheshorse", category: "clothing" },
  { symbol: "woolwear", category: "clothing" },
  { symbol: "denim", category: "clothing" },
  { symbol: "grooming", category: "clothing" },
  { symbol: "hair", category: "clothing" },
  { symbol: "best", category: "clothing" },
  { symbol: "etamine", category: "clothing" },
  { symbol: "skin", category: "clothing" },
  { symbol: "oil", category: "clothing" },
  { symbol: "disrobe", category: "clothing" },
  { symbol: "tailoring", category: "clothing" },
  { symbol: "frippery", category: "clothing" },
  { symbol: "accouterment", category: "clothing" },
  { symbol: "search", category: "clothing" },
  { symbol: "apparels", category: "clothing" },
  { symbol: "items", category: "clothing" },
  { symbol: "cladding", category: "clothing" },
  { symbol: "chiffon", category: "clothing" },
  { symbol: "russet", category: "clothing" },
  { symbol: "apparelment", category: "clothing" },
  { symbol: "chino", category: "clothing" },
  { symbol: "cleaner", category: "clothing" },
  { symbol: "raiment", category: "clothing" },
  { symbol: "civvies", category: "clothing" },
  { symbol: "garments", category: "clothing" },
  { symbol: "kit", category: "clothing" },
  { symbol: "wardrobe", category: "clothing" },
  { symbol: "getup", category: "clothing" },
  { symbol: "clothesmaking", category: "clothing" },
  { symbol: "overclothes", category: "clothing" },
  { symbol: "fashioning", category: "clothing" },
  { symbol: "leather", category: "clothing" },
  { symbol: "horsehair", category: "clothing" },
  { symbol: "backpacks", category: "clothing" },
  { symbol: "color", category: "clothing" },
  { symbol: "shop", category: "clothing" },
  { symbol: "schoolwear", category: "clothing" },
  { symbol: "children", category: "clothing" },
  { symbol: "disguise", category: "clothing" },
  { symbol: "wraparound", category: "clothing" },
  { symbol: "cloathing", category: "clothing" },
  { symbol: "attire", category: "clothing" },
  { symbol: "jewelry", category: "clothing" },
  { symbol: "jersey", category: "clothing" },
  { symbol: "bedclothes", category: "clothing" },
  { symbol: "cotton", category: "clothing" },
  { symbol: "sweatshirts", category: "clothing" },
  { symbol: "formalwear", category: "clothing" },
  { symbol: "worn", category: "clothing" },
  { symbol: "swimwear", category: "clothing" },
  { symbol: "dressmaking", category: "clothing" },
  { symbol: "wears", category: "clothing" },
  { symbol: "burlap", category: "clothing" },
  { symbol: "togs", category: "clothing" },
  { symbol: "chic", category: "clothing" },
  { symbol: "clobbered", category: "clothing" },
  { symbol: "feather", category: "clothing" },
  { symbol: "topcloth", category: "clothing" },
  { symbol: "duffel", category: "clothing" },
  { symbol: "dryer", category: "clothing" },
  { symbol: "wool", category: "clothing" },
  { symbol: "fitting", category: "clothing" },
  { symbol: "farmwear", category: "clothing" },
  { symbol: "comfortwear", category: "clothing" },
  { symbol: "garnish", category: "clothing" },
  { symbol: "brat", category: "clothing" },
  { symbol: "crease", category: "clothing" },
  { symbol: "sachet", category: "clothing" },
  { symbol: "borrel", category: "clothing" },
  { symbol: "covering", category: "clothing" },
  { symbol: "frill", category: "clothing" },
  { symbol: "furs", category: "clothing" },
  { symbol: "strides", category: "clothing" },
  { symbol: "pluderhose", category: "clothing" },
  { symbol: "khakis", category: "clothing" },
  { symbol: "bluchers", category: "clothing" },
  { symbol: "gumshoe", category: "clothing" },
  { symbol: "aaron", category: "clothing" },
  { symbol: "saddle", category: "clothing" },
  { symbol: "mill", category: "clothing" },
  { symbol: "shiny", category: "clothing" },
  { symbol: "slipper", category: "clothing" },
  { symbol: "cutoffs", category: "clothing" },
  { symbol: "horseshoe", category: "clothing" },
  { symbol: "tops", category: "clothing" },
  { symbol: "herl", category: "clothing" },
  { symbol: "chopine", category: "clothing" },
  { symbol: "pegtops", category: "clothing" },
  { symbol: "sole", category: "clothing" },
  { symbol: "bootcover", category: "clothing" },
  { symbol: "stretch", category: "clothing" },
  { symbol: "kick", category: "clothing" },
  { symbol: "cobblers", category: "clothing" },
  { symbol: "waist", category: "clothing" },
  { symbol: "enclothe", category: "clothing" },
  { symbol: "sagging", category: "clothing" },
  { symbol: "jaw", category: "clothing" },
  { symbol: "anklet", category: "clothing" },
  { symbol: "crampon", category: "clothing" },
  { symbol: "heeled", category: "clothing" },
  { symbol: "drawers", category: "clothing" },
  { symbol: "knee", category: "clothing" },
  { symbol: "shoebag", category: "clothing" },
  { symbol: "conducting", category: "clothing" },
  { symbol: "lop", category: "clothing" },
  { symbol: "paramatta", category: "clothing" },
  { symbol: "heaving", category: "clothing" },
  { symbol: "clothe", category: "clothing" },
  { symbol: "hackles", category: "clothing" },
  { symbol: "looks", category: "clothing" },
  { symbol: "pantalette", category: "clothing" },
  { symbol: "trews", category: "clothing" },
  { symbol: "beck", category: "clothing" },
  { symbol: "retie", category: "clothing" },
  { symbol: "coif", category: "clothing" },
  { symbol: "pantleg", category: "clothing" },
  { symbol: "long", category: "clothing" },
  { symbol: "clogging", category: "clothing" },
  { symbol: "holding", category: "clothing" },
  { symbol: "bruno", category: "clothing" },
  { symbol: "stockingfeet", category: "clothing" },
  { symbol: "toestrap", category: "clothing" },
  { symbol: "rub", category: "clothing" },
  { symbol: "smarts", category: "clothing" },
  { symbol: "prink", category: "clothing" },
  { symbol: "kill", category: "clothing" },
  { symbol: "foxing", category: "clothing" },
  { symbol: "panung", category: "clothing" },
  { symbol: "seats", category: "clothing" },
  { symbol: "fashionize", category: "clothing" },
  { symbol: "relace", category: "clothing" },
  { symbol: "yours", category: "clothing" },
  { symbol: "pumps", category: "clothing" },
  { symbol: "toreador", category: "clothing" },
  { symbol: "dapper", category: "clothing" },
  { symbol: "spank", category: "clothing" },
  { symbol: "dubbing", category: "clothing" },
  { symbol: "toe", category: "clothing" },
  { symbol: "invest", category: "clothing" },
  { symbol: "enamel", category: "clothing" },
  { symbol: "geraniaceous", category: "clothing" },
  { symbol: "cane", category: "clothing" },
  { symbol: "begown", category: "clothing" },
  { symbol: "heelpiece", category: "clothing" },
  { symbol: "sabbaton", category: "clothing" },
  { symbol: "heaves", category: "clothing" },
  { symbol: "pomatum", category: "clothing" },
  { symbol: "adidas", category: "clothing" },
  { symbol: "do", category: "clothing" },
  { symbol: "hackle", category: "clothing" },
  { symbol: "agasp", category: "clothing" },
  { symbol: "eees", category: "clothing" },
  { symbol: "creeper", category: "clothing" },
  { symbol: "underpants", category: "clothing" },
  { symbol: "bandaging", category: "clothing" },
  { symbol: "trainer", category: "clothing" },
  { symbol: "resole", category: "clothing" },
  { symbol: "instep", category: "clothing" },
  { symbol: "blucher", category: "clothing" },
  { symbol: "flats", category: "clothing" },
  { symbol: "shirttail", category: "clothing" },
  { symbol: "mule", category: "clothing" },
  { symbol: "delaine", category: "clothing" },
  { symbol: "mods", category: "clothing" },
  { symbol: "brief", category: "clothing" },
  { symbol: "shoemaking", category: "clothing" },
  { symbol: "pantsuit", category: "clothing" },
  { symbol: "combed", category: "clothing" },
  { symbol: "puffy", category: "clothing" },
  { symbol: "retro", category: "clothing" },
  { symbol: "dauber", category: "clothing" },
  { symbol: "wellington", category: "clothing" },
  { symbol: "platform", category: "clothing" },
  { symbol: "piping", category: "clothing" },
  { symbol: "hanger", category: "clothing" },
  { symbol: "sneaker", category: "clothing" },
  { symbol: "buttocks", category: "clothing" },
  { symbol: "socklike", category: "clothing" },
  { symbol: "cords", category: "clothing" },
  { symbol: "ride", category: "clothing" },
  { symbol: "lacer", category: "clothing" },
  { symbol: "buck", category: "clothing" },
  { symbol: "leg", category: "clothing" },
  { symbol: "klet", category: "clothing" },
  { symbol: "ties", category: "clothing" },
  { symbol: "cargo", category: "clothing" },
  { symbol: "anhelous", category: "clothing" },
  { symbol: "maxi", category: "clothing" },
  { symbol: "bootblack", category: "clothing" },
  { symbol: "ecru", category: "clothing" },
  { symbol: "alligator", category: "clothing" },
  { symbol: "alter", category: "clothing" },
  { symbol: "clop", category: "clothing" },
  { symbol: "pompadour", category: "clothing" },
  { symbol: "sabot", category: "clothing" },
  { symbol: "pinch", category: "clothing" },
  { symbol: "railway", category: "clothing" },
  { symbol: "anklewarmer", category: "clothing" },
  { symbol: "slit", category: "clothing" },
  { symbol: "front", category: "clothing" },
  { symbol: "cosplay", category: "clothing" },
  { symbol: "honest", category: "clothing" },
  { symbol: "pantalet", category: "clothing" },
  { symbol: "tranny", category: "clothing" },
  { symbol: "trouserette", category: "clothing" },
  { symbol: "model", category: "clothing" },
  { symbol: "rich", category: "clothing" },
  { symbol: "eager", category: "clothing" },
  { symbol: "insole", category: "clothing" },
  { symbol: "ghillie", category: "clothing" },
  { symbol: "arrange", category: "clothing" },
  { symbol: "hose", category: "clothing" },
  { symbol: "bedeck", category: "clothing" },
  { symbol: "plaster", category: "clothing" },
  { symbol: "lasting", category: "clothing" },
  { symbol: "culottes", category: "clothing" },
  { symbol: "comb", category: "clothing" },
  { symbol: "lift", category: "clothing" },
  { symbol: "pegs", category: "clothing" },
  { symbol: "convening", category: "clothing" },
  { symbol: "jogger", category: "clothing" },
  { symbol: "jodhpurs", category: "clothing" },
  { symbol: "frocks", category: "clothing" },
  { symbol: "huff", category: "clothing" },
  { symbol: "clamdiggers", category: "clothing" },
  { symbol: "bonnet", category: "clothing" },
  { symbol: "primp", category: "clothing" },
  { symbol: "pantssuit", category: "clothing" },
  { symbol: "sandal", category: "clothing" },
  { symbol: "pantouffle", category: "clothing" },
  { symbol: "petticoat", category: "clothing" },
  { symbol: "ready", category: "clothing" },
  { symbol: "drest", category: "clothing" },
  { symbol: "patch", category: "clothing" },
  { symbol: "tap", category: "clothing" },
  { symbol: "lint", category: "clothing" },
  { symbol: "toebox", category: "clothing" },
  { symbol: "clothing", category: "clothing" },
  { symbol: "dowdy", category: "clothing" },
  { symbol: "sneak", category: "clothing" },
  { symbol: "puff", category: "clothing" },
  { symbol: "king", category: "clothing" },
  { symbol: "rip", category: "clothing" },
  { symbol: "legs", category: "clothing" },
  { symbol: "kirtle", category: "clothing" },
  { symbol: "bootleg", category: "clothing" },
  { symbol: "plastered", category: "clothing" },
  { symbol: "kitchen", category: "clothing" },
  { symbol: "moccasin", category: "clothing" },
  { symbol: "speedos", category: "clothing" },
  { symbol: "transvestite", category: "clothing" },
  { symbol: "smock", category: "clothing" },
  { symbol: "shoetree", category: "clothing" },
  { symbol: "drainpipe", category: "clothing" },
  { symbol: "set", category: "clothing" },
  { symbol: "rehearsal", category: "clothing" },
  { symbol: "polonaise", category: "clothing" },
  { symbol: "readied", category: "clothing" },
  { symbol: "court", category: "clothing" },
  { symbol: "chameleonize", category: "clothing" },
  { symbol: "bootee", category: "clothing" },
  { symbol: "bootie", category: "clothing" },
  { symbol: "pair", category: "clothing" },
  { symbol: "innersole", category: "clothing" },
  { symbol: "cleat", category: "clothing" },
  { symbol: "poulaine", category: "clothing" },
  { symbol: "trousering", category: "clothing" },
  { symbol: "fix", category: "clothing" },
  { symbol: "undertrousers", category: "clothing" },
  { symbol: "neck", category: "clothing" },
  { symbol: "narrow", category: "clothing" },
  { symbol: "plater", category: "clothing" },
  { symbol: "chemisette", category: "clothing" },
  { symbol: "tot", category: "clothing" },
  { symbol: "shoecover", category: "clothing" },
  { symbol: "pajama", category: "clothing" },
  { symbol: "leh", category: "clothing" },
  { symbol: "tire", category: "clothing" },
  { symbol: "crimper", category: "clothing" },
  { symbol: "serve", category: "clothing" },
  { symbol: "rig", category: "clothing" },
  { symbol: "caftan", category: "clothing" },
  { symbol: "breathless", category: "clothing" },
  { symbol: "clicker", category: "clothing" },
  { symbol: "toeplate", category: "clothing" },
  { symbol: "prim", category: "clothing" },
  { symbol: "windpants", category: "clothing" },
  { symbol: "hemline", category: "clothing" },
  { symbol: "trim", category: "clothing" },
  { symbol: "housepants", category: "clothing" },
  { symbol: "preen", category: "clothing" },
  { symbol: "coiffure", category: "clothing" },
  { symbol: "peignoir", category: "clothing" },
  { symbol: "capris", category: "clothing" },
  { symbol: "longs", category: "clothing" },
  { symbol: "code", category: "clothing" },
  { symbol: "poultice", category: "clothing" },
  { symbol: "cutoff", category: "clothing" },
  { symbol: "bandaged", category: "clothing" },
  { symbol: "creased", category: "clothing" },
  { symbol: "sam", category: "clothing" },
  { symbol: "trouserettes", category: "clothing" },
  { symbol: "embellish", category: "clothing" },
  { symbol: "fly", category: "clothing" },
  { symbol: "iron", category: "clothing" },
  { symbol: "inseam", category: "clothing" },
  { symbol: "straw", category: "clothing" },
  { symbol: "basket", category: "clothing" },
  { symbol: "sheath", category: "clothing" },
  { symbol: "spikes", category: "clothing" },
  { symbol: "besit", category: "clothing" },
  { symbol: "toed", category: "clothing" },
  { symbol: "pinny", category: "clothing" },
  { symbol: "fashionable", category: "clothing" },
  { symbol: "seat", category: "clothing" },
  { symbol: "britches", category: "clothing" },
  { symbol: "stool", category: "clothing" },
  { symbol: "visa", category: "clothing" },
  { symbol: "silverside", category: "clothing" },
  { symbol: "barber", category: "clothing" },
  { symbol: "churidar", category: "clothing" },
  { symbol: "guy", category: "clothing" },
  { symbol: "anklets", category: "clothing" },
  { symbol: "wide", category: "clothing" },
  { symbol: "chukka", category: "clothing" },
  { symbol: "crotch", category: "clothing" },
  { symbol: "show", category: "clothing" },
  { symbol: "flapper", category: "clothing" },
  { symbol: "pantdress", category: "clothing" },
  { symbol: "calker", category: "clothing" },
  { symbol: "ballgown", category: "clothing" },
  { symbol: "ornament", category: "clothing" },
  { symbol: "collar", category: "clothing" },
  { symbol: "bootlip", category: "clothing" },
  { symbol: "wingtip", category: "clothing" },
  { symbol: "pettiloon", category: "clothing" },
  { symbol: "cards", category: "clothing" },
  { symbol: "natty", category: "clothing" },
  { symbol: "boot", category: "clothing" },
  { symbol: "kast", category: "clothing" },
  { symbol: "shoelacing", category: "clothing" },
  { symbol: "kiltie", category: "clothing" },
  { symbol: "empire", category: "clothing" },
  { symbol: "tux", category: "clothing" },
  { symbol: "shoe", category: "clothing" },
  { symbol: "gasping", category: "clothing" },
  { symbol: "overclothe", category: "clothing" },
  { symbol: "foot", category: "clothing" },
  { symbol: "accommodate", category: "clothing" },
  { symbol: "gowns", category: "clothing" },
  { symbol: "bandage", category: "clothing" },
  { symbol: "spat", category: "clothing" },
  { symbol: "parade", category: "clothing" },
  { symbol: "hosen", category: "clothing" },
  { symbol: "dressmake", category: "clothing" },
  { symbol: "poplin", category: "clothing" },
  { symbol: "rullion", category: "clothing" },
  { symbol: "avid", category: "clothing" },
  { symbol: "unmentionables", category: "clothing" },
  { symbol: "able", category: "clothing" },
  { symbol: "sweatsuit", category: "clothing" },
  { symbol: "overdressed", category: "clothing" },
  { symbol: "demean", category: "clothing" },
  { symbol: "footglove", category: "clothing" },
  { symbol: "dink", category: "clothing" },
  { symbol: "neckline", category: "clothing" },
  { symbol: "beweapon", category: "clothing" },
  { symbol: "playsuit", category: "clothing" },
  { symbol: "bootwear", category: "clothing" },
  { symbol: "undress", category: "clothing" },
  { symbol: "peruke", category: "clothing" },
  { symbol: "flies", category: "clothing" },
  { symbol: "pantie", category: "clothing" },
  { symbol: "weapon", category: "clothing" },
  { symbol: "absurdly", category: "clothing" },
  { symbol: "underthing", category: "clothing" },
  { symbol: "zapata", category: "clothing" },
  { symbol: "strap", category: "clothing" },
  { symbol: "dungaree", category: "clothing" },
  { symbol: "ski", category: "clothing" },
  { symbol: "bootsole", category: "clothing" },
  { symbol: "masquerade", category: "clothing" },
  { symbol: "tackie", category: "clothing" },
  { symbol: "trunks", category: "clothing" },
  { symbol: "lowriders", category: "clothing" },
  { symbol: "overtrousers", category: "clothing" },
  { symbol: "coiffe", category: "clothing" },
  { symbol: "loafer", category: "clothing" },
  { symbol: "shine", category: "clothing" },
  { symbol: "aguise", category: "clothing" },
  { symbol: "discase", category: "clothing" },
  { symbol: "tent", category: "clothing" },
  { symbol: "calceus", category: "clothing" },
  { symbol: "conduct", category: "clothing" },
  { symbol: "footpiece", category: "clothing" },
  { symbol: "bootheel", category: "clothing" },
  { symbol: "veldtschoon", category: "clothing" },
  { symbol: "pump", category: "clothing" },
  { symbol: "wedding", category: "clothing" },
  { symbol: "guyed", category: "clothing" },
  { symbol: "stocking", category: "clothing" },
  { symbol: "sock", category: "clothing" },
  { symbol: "footbox", category: "clothing" },
  { symbol: "cobbling", category: "clothing" },
  { symbol: "hoof", category: "clothing" },
  { symbol: "keeping", category: "clothing" },
  { symbol: "clodhopper", category: "clothing" },
  { symbol: "panter", category: "clothing" },
  { symbol: "bowyang", category: "clothing" },
  { symbol: "flare", category: "clothing" },
  { symbol: "investure", category: "clothing" },
  { symbol: "blast", category: "clothing" },
  { symbol: "soleret", category: "clothing" },
  { symbol: "dude", category: "clothing" },
  { symbol: "sashoon", category: "clothing" },
  { symbol: "stockingfoot", category: "clothing" },
  { symbol: "modiste", category: "clothing" },
  { symbol: "preening", category: "clothing" },
  { symbol: "green", category: "clothing" },
  { symbol: "pretend", category: "clothing" },
  { symbol: "suede", category: "clothing" },
  { symbol: "vamp", category: "clothing" },
  { symbol: "fantastic", category: "clothing" },
  { symbol: "wedgie", category: "clothing" },
  { symbol: "jocks", category: "clothing" },
  { symbol: "jelly", category: "clothing" },
  { symbol: "tied", category: "clothing" },
  { symbol: "comport", category: "clothing" },
  { symbol: "tutu", category: "clothing" },
  { symbol: "formal", category: "clothing" },
  { symbol: "soulier", category: "clothing" },
  { symbol: "outershell", category: "clothing" },
  { symbol: "portray", category: "clothing" },
  { symbol: "pantywaist", category: "clothing" },
  { symbol: "butcher", category: "clothing" },
  { symbol: "shoetop", category: "clothing" },
  { symbol: "heelplate", category: "clothing" },
  { symbol: "wedge", category: "clothing" },
  { symbol: "rise", category: "clothing" },
  { symbol: "clad", category: "clothing" },
  { symbol: "kecks", category: "clothing" },
  { symbol: "adorn", category: "clothing" },
  { symbol: "heel", category: "clothing" },
  { symbol: "equip", category: "clothing" },
  { symbol: "bluecoat", category: "clothing" },
  { symbol: "trossers", category: "clothing" },
  { symbol: "squeeze", category: "clothing" },
  { symbol: "fins", category: "clothing" },
  { symbol: "greave", category: "clothing" },
  { symbol: "plume", category: "clothing" },
  { symbol: "chinos", category: "clothing" },
  { symbol: "gallant", category: "clothing" },
  { symbol: "paws", category: "clothing" },
  { symbol: "dicky", category: "clothing" },
  { symbol: "abt", category: "clothing" },
  { symbol: "beautify", category: "clothing" },
  { symbol: "overdress", category: "clothing" },
  { symbol: "yearn", category: "clothing" },
  { symbol: "lace", category: "clothing" },
  { symbol: "brogue", category: "clothing" },
  { symbol: "breeks", category: "clothing" },
  { symbol: "rubber", category: "clothing" },
  { symbol: "pettipants", category: "clothing" },
  { symbol: "guise", category: "clothing" },
  { symbol: "dragonfly", category: "clothing" },
  { symbol: "straitjacket", category: "clothing" },
  { symbol: "paunce", category: "clothing" },
  { symbol: "french", category: "clothing" },
  { symbol: "shortclothes", category: "clothing" },
  { symbol: "pantygirdle", category: "clothing" },
  { symbol: "cleavage", category: "clothing" },
  { symbol: "balmoral", category: "clothing" },
  { symbol: "oxford", category: "clothing" },
  { symbol: "throat", category: "clothing" },
  { symbol: "kaftan", category: "clothing" },
  { symbol: "soled", category: "clothing" },
  { symbol: "slingback", category: "clothing" },
  { symbol: "wiseacre", category: "clothing" },
  { symbol: "mini", category: "clothing" },
  { symbol: "cook", category: "clothing" },
  { symbol: "grenadine", category: "clothing" },
  { symbol: "slacks", category: "clothing" },
  { symbol: "pinafore", category: "clothing" },
  { symbol: "panelled", category: "clothing" },
  { symbol: "pantoble", category: "clothing" },
  { symbol: "accessorize", category: "clothing" },
  { symbol: "braces", category: "clothing" },
  { symbol: "article", category: "clothing" },
  { symbol: "flannels", category: "clothing" },
  { symbol: "kid", category: "clothing" },
  { symbol: "hot", category: "clothing" },
  { symbol: "overshoe", category: "clothing" },
  { symbol: "shants", category: "clothing" },
  { symbol: "backstay", category: "clothing" },
  { symbol: "rand", category: "clothing" },
  { symbol: "stohwasser", category: "clothing" },
  { symbol: "rob", category: "clothing" },
  { symbol: "galosh", category: "clothing" },
  { symbol: "mourning", category: "clothing" },
  { symbol: "carry", category: "clothing" },
  { symbol: "basketball", category: "clothing" },
  { symbol: "cocker", category: "clothing" },
  { symbol: "jean", category: "clothing" },
  { symbol: "braw", category: "clothing" },
  { symbol: "give", category: "clothing" },
  { symbol: "sacque", category: "clothing" },
  { symbol: "flat", category: "clothing" },
  { symbol: "palazzos", category: "clothing" },
  { symbol: "slim", category: "clothing" },
  { symbol: "horniness", category: "clothing" },
  { symbol: "beclothe", category: "clothing" },
  { symbol: "turnshoe", category: "clothing" },
  { symbol: "topboot", category: "clothing" },
  { symbol: "mod", category: "clothing" },
  { symbol: "sweatpant", category: "clothing" },
  { symbol: "workshoe", category: "clothing" },
  { symbol: "smalls", category: "clothing" },
  { symbol: "liar", category: "clothing" },
  { symbol: "schynbald", category: "clothing" },
  { symbol: "walker", category: "clothing" },
  { symbol: "clog", category: "clothing" },
  { symbol: "huy", category: "clothing" },
  { symbol: "pleat", category: "clothing" },
  { symbol: "climber", category: "clothing" },
  { symbol: "tree", category: "clothing" },
  { symbol: "runner", category: "clothing" },
  { symbol: "trou", category: "clothing" },
  { symbol: "hip", category: "clothing" },
  { symbol: "clue", category: "clothing" },
  { symbol: "guesstimate", category: "clothing" },
  { symbol: "chamois", category: "clothing" },
  { symbol: "mocassin", category: "clothing" },
  { symbol: "habilitate", category: "clothing" },
  { symbol: "clip", category: "clothing" },
  { symbol: "par", category: "clothing" },
  { symbol: "kook", category: "clothing" },
  { symbol: "look", category: "clothing" },
  { symbol: "channel", category: "clothing" },
  { symbol: "endue", category: "clothing" },
  { symbol: "bootstrap", category: "clothing" },
  { symbol: "calceiform", category: "clothing" },
  { symbol: "trouser", category: "clothing" },
  { symbol: "pantalettes", category: "clothing" },
  { symbol: "corduroy", category: "clothing" },
  { symbol: "anhelose", category: "clothing" },
  { symbol: "seamed", category: "clothing" },
  { symbol: "prune", category: "clothing" },
  { symbol: "gaiter", category: "clothing" },
  { symbol: "heal", category: "clothing" },
  { symbol: "blacking", category: "clothing" },
  { symbol: "gore", category: "clothing" },
  { symbol: "snip", category: "clothing" },
  { symbol: "strip", category: "clothing" },
  { symbol: "chaussure", category: "clothing" },
  { symbol: "elf", category: "clothing" },
  { symbol: "knickers", category: "clothing" },
  { symbol: "cooked", category: "clothing" },
  { symbol: "highlow", category: "clothing" },
  { symbol: "impersonate", category: "clothing" },
  { symbol: "smart", category: "clothing" },
  { symbol: "arch", category: "clothing" },
  { symbol: "casual", category: "clothing" },
  { symbol: "doormat", category: "clothing" },
  { symbol: "top", category: "clothing" },
  { symbol: "patten", category: "clothing" },
  { symbol: "shoepak", category: "clothing" },
  { symbol: "smarty", category: "clothing" },
  { symbol: "biot", category: "clothing" },
  { symbol: "channelling", category: "clothing" },
  { symbol: "underdress", category: "clothing" },
  { symbol: "panelling", category: "clothing" },
  { symbol: "zori", category: "clothing" },
  { symbol: "blown", category: "clothing" },
  { symbol: "spats", category: "clothing" },
  { symbol: "ant", category: "clothing" },
  { symbol: "einstein", category: "clothing" },
  { symbol: "khaki", category: "clothing" },
  { symbol: "cleats", category: "clothing" },
  { symbol: "tongue", category: "clothing" },
  { symbol: "knickerbockers", category: "clothing" },
  { symbol: "crandall", category: "clothing" },
  { symbol: "upper", category: "clothing" },
  { symbol: "spike", category: "clothing" },
  { symbol: "drooler", category: "clothing" },
  { symbol: "uppers", category: "clothing" },
  { symbol: "cuff", category: "clothing" },
  { symbol: "address", category: "clothing" },
  { symbol: "sabatine", category: "clothing" },
  { symbol: "skirts", category: "clothing" },
  { symbol: "chuck", category: "clothing" },
  { symbol: "moccasins", category: "clothing" },
  { symbol: "misfit", category: "clothing" },
  { symbol: "xyz", category: "clothing" },
  { symbol: "crop", category: "clothing" },
  { symbol: "counter", category: "clothing" },
  { symbol: "beclout", category: "clothing" },
  { symbol: "corfam", category: "clothing" },
  { symbol: "cushion", category: "clothing" },
  { symbol: "accouter", category: "clothing" },
  { symbol: "hippie", category: "clothing" },
  { symbol: "capri", category: "clothing" },
  { symbol: "levi", category: "clothing" },
  { symbol: "panty", category: "clothing" },
  { symbol: "eye", category: "clothing" },
  { symbol: "pockets", category: "clothing" },
  { symbol: "gasp", category: "clothing" },
  { symbol: "aas", category: "clothing" },
  { symbol: "toeless", category: "clothing" },
  { symbol: "readying", category: "clothing" },
  { symbol: "curry", category: "clothing" },
  { symbol: "athlete", category: "clothing" },
  { symbol: "accoutre", category: "clothing" },
  { symbol: "manpris", category: "clothing" },
  { symbol: "size", category: "clothing" },
  { symbol: "bellbottoms", category: "clothing" },
  { symbol: "workpants", category: "clothing" },
  { symbol: "unlace", category: "clothing" },
  { symbol: "anhele", category: "clothing" },
  { symbol: "bottomwear", category: "clothing" },
  { symbol: "chaussures", category: "clothing" },
  { symbol: "welt", category: "clothing" },
  { symbol: "flipper", category: "clothing" },
  { symbol: "puffed", category: "clothing" },
  { symbol: "clamper", category: "clothing" },
  { symbol: "cracow", category: "clothing" },
  { symbol: "longies", category: "clothing" },
  { symbol: "crackerjack", category: "clothing" },
  { symbol: "halloween", category: "clothing" },
  { symbol: "shoon", category: "clothing" },
  { symbol: "bottom", category: "clothing" },
  { symbol: "pad", category: "clothing" },
  { symbol: "crepane", category: "clothing" },
  { symbol: "blakey", category: "clothing" },
  { symbol: "pledget", category: "clothing" },
  { symbol: "clump", category: "clothing" },
  { symbol: "last", category: "clothing" },
  { symbol: "shoestring", category: "clothing" },
  { symbol: "jumper", category: "clothing" },
  { symbol: "pech", category: "clothing" },
  { symbol: "dirndl", category: "clothing" },
  { symbol: "hoopskirt", category: "clothing" },
  { symbol: "outsole", category: "clothing" },
  { symbol: "pantaloons", category: "clothing" },
  { symbol: "heels", category: "clothing" },
  { symbol: "brave", category: "clothing" },
  { symbol: "hosiery", category: "clothing" },
  { symbol: "calkin", category: "clothing" },
  { symbol: "solleret", category: "clothing" },
  { symbol: "undies", category: "clothing" },
  { symbol: "nine", category: "clothing" },
  { symbol: "become", category: "clothing" },
  { symbol: "sabaton", category: "clothing" },
  { symbol: "combatively", category: "clothing" },
  { symbol: "unshod", category: "clothing" },
  { symbol: "sea", category: "clothing" },
  { symbol: "flippers", category: "clothing" },
  { symbol: "mirrorize", category: "clothing" },
  { symbol: "tailor", category: "clothing" },
  { symbol: "overblouse", category: "clothing" },
  { symbol: "aaa", category: "clothing" },
  { symbol: "segment", category: "clothing" },
  { symbol: "seated", category: "clothing" },
  { symbol: "panel", category: "clothing" },
  { symbol: "opanka", category: "clothing" },
  { symbol: "reheel", category: "clothing" },
  { symbol: "levis", category: "clothing" },
  { symbol: "gay", category: "clothing" },
  { symbol: "heave", category: "clothing" },
  { symbol: "face", category: "clothing" },
  { symbol: "gaucho", category: "clothing" },
  { symbol: "harem", category: "clothing" },
  { symbol: "peg", category: "clothing" },
  { symbol: "scrub", category: "clothing" },
  { symbol: "shank", category: "clothing" },
  { symbol: "peplum", category: "clothing" },
  { symbol: "furnish", category: "clothing" },
  { symbol: "fop", category: "clothing" },
  { symbol: "blow", category: "clothing" },
  { symbol: "chapette", category: "clothing" },
  { symbol: "zag", category: "clothing" },
  { symbol: "lecture", category: "clothing" },
  { symbol: "tich", category: "clothing" },
  { symbol: "pane", category: "clothing" },
  { symbol: "net", category: "clothing" },
  { symbol: "unclothe", category: "clothing" },
  { symbol: "indispensable", category: "clothing" },
  { symbol: "crepe", category: "clothing" },
  { symbol: "shootie", category: "clothing" },
  { symbol: "myself", category: "clothing" },
  { symbol: "decent", category: "clothing" },
  { symbol: "ass", category: "clothing" },
  { symbol: "solepiece", category: "clothing" },
  { symbol: "wheeze", category: "clothing" },
  { symbol: "sweats", category: "clothing" },
  { symbol: "shinguard", category: "clothing" },
  { symbol: "pomade", category: "clothing" },
  { symbol: "purple", category: "clothing" },
  { symbol: "dishabille", category: "clothing" },
  { symbol: "hotness", category: "clothing" },
  { symbol: "trouse", category: "clothing" },
  { symbol: "serge", category: "clothing" },
  { symbol: "brogan", category: "clothing" },
  { symbol: "pantcuff", category: "clothing" },
  { symbol: "polish", category: "clothing" },
  { symbol: "fancy", category: "clothing" },
  { symbol: "strauss", category: "clothing" },
  { symbol: "readies", category: "clothing" },
  { symbol: "pantalets", category: "clothing" },
  { symbol: "length", category: "clothing" },
  { symbol: "footguard", category: "clothing" },
  { symbol: "clinker", category: "clothing" },
  { symbol: "twill", category: "clothing" },
  { symbol: "mare", category: "clothing" },
  { symbol: "guard", category: "clothing" },
  { symbol: "shell", category: "clothing" },
  { symbol: "platforms", category: "clothing" },
  { symbol: "bootlace", category: "clothing" },
  { symbol: "topline", category: "clothing" },
  { symbol: "jogpants", category: "clothing" },
  { symbol: "make", category: "clothing" },
  { symbol: "channels", category: "clothing" },
  { symbol: "cobra", category: "clothing" },
  { symbol: "foppish", category: "clothing" },
  { symbol: "guys", category: "clothing" },
  { symbol: "hernani", category: "clothing" },
  { symbol: "smarting", category: "clothing" },
  { symbol: "fitted", category: "clothing" },
  { symbol: "chopin", category: "clothing" },
  { symbol: "pantoufle", category: "clothing" },
  { symbol: "baffie", category: "clothing" },
  { symbol: "sweat", category: "clothing" },
  { symbol: "decorate", category: "clothing" },
  { symbol: "calk", category: "clothing" },
  { symbol: "chopines", category: "clothing" },
  { symbol: "trunk", category: "clothing" },
  { symbol: "bloomers", category: "clothing" },
  { symbol: "mof", category: "clothing" },
  { symbol: "fer", category: "clothing" },
  { symbol: "seam", category: "clothing" },
  { symbol: "spiking", category: "clothing" },
  { symbol: "anhelation", category: "clothing" },
  { symbol: "treggings", category: "clothing" },
  { symbol: "dandify", category: "clothing" },
  { symbol: "present", category: "clothing" },
  { symbol: "cages", category: "clothing" },
  { symbol: "buskin", category: "clothing" },
  { symbol: "braid", category: "clothing" },
  { symbol: "stirrup", category: "clothing" },
  { symbol: "uncase", category: "clothing" },
  { symbol: "cage", category: "clothing" },
  { symbol: "gillie", category: "clothing" },
  { symbol: "bottine", category: "clothing" },
  { symbol: "stretched", category: "clothing" },
  { symbol: "breeches", category: "clothing" },
  { symbol: "pantaloon", category: "clothing" },
  { symbol: "dag", category: "clothing" },
  { symbol: "bottoms", category: "clothing" },
  { symbol: "brad", category: "clothing" },
  { symbol: "buckle", category: "clothing" },
  { symbol: "legging", category: "clothing" },
  { symbol: "horn", category: "clothing" },
  { symbol: "mat", category: "clothing" },
  { symbol: "dungarees", category: "clothing" },
  { symbol: "pantyline", category: "clothing" },
  { symbol: "toecap", category: "clothing" },
  { symbol: "pose", category: "clothing" },
  { symbol: "espadrille", category: "clothing" },
  { symbol: "muumuu", category: "clothing" },
  { symbol: "eveningwear", category: "clothing" },
  { symbol: "lederhosen", category: "clothing" },
  { symbol: "footing", category: "clothing" },
  { symbol: "integument", category: "clothing" },
  { symbol: "above", category: "clothing" },
  { symbol: "pantofle", category: "clothing" },
  { symbol: "empanoply", category: "clothing" },
  { symbol: "bushhammer", category: "clothing" },
  { symbol: "behave", category: "clothing" },
  { symbol: "yaw", category: "clothing" },
  { symbol: "circle", category: "clothing" },
  { symbol: "shinpad", category: "clothing" },
  { symbol: "batt", category: "clothing" },
  { symbol: "aldo", category: "clothing" },
  { symbol: "crampoon", category: "clothing" },
  { symbol: "ironed", category: "clothing" },
  { symbol: "fin", category: "clothing" },
  { symbol: "sockette", category: "clothing" },
  { symbol: "flashy", category: "clothing" },
  { symbol: "drapings", category: "clothing" },
  { symbol: "tracksuit", category: "clothing" },
  { symbol: "calf", category: "clothing" },


];
