import { SingleWordSymbol } from "../dreamSingularSymbols";

export const electronics_symbols: SingleWordSymbol[] = [
  { symbol: "cagewire", category: "electronics" },
  { symbol: "tabletmount", category: "electronics" },
  { symbol: "screwdriverbit", category: "electronics" },
  { symbol: "drive", category: "electronics" },
  { symbol: "screen", category: "electronics" },
  { symbol: "car charger", category: "electronics" },
  { symbol: "switchboard", category: "electronics" },
  { symbol: "screwdriverhandle", category: "electronics" },
  { symbol: "tabletcase", category: "electronics" },
  { symbol: "smartspeaker", category: "electronics" },
  { symbol: "laptopbag", category: "electronics" },
  { symbol: "radio transmitter", category: "electronics" },
  { symbol: "cableplug", category: "electronics" },
  { symbol: "megaphone", category: "electronics" },
  { symbol: "cable clip", category: "electronics" },
  { symbol: "tabletcharger", category: "electronics" },
  { symbol: "phone charger", category: "electronics" },
  { symbol: "cable sleeve", category: "electronics" },
  { symbol: "charger", category: "electronics" },
  { symbol: "animationtablet", category: "electronics" },
  { symbol: "phone", category: "electronics" },
  { symbol: "voltageadapter", category: "electronics" },
  { symbol: "radio receiver", category: "electronics" },
  { symbol: "externaldrive", category: "electronics" },
  { symbol: "camera tripod", category: "electronics" },
  { symbol: "cableorganizer", category: "electronics" },
  { symbol: "meshrouter", category: "electronics" },
  { symbol: "doorcamera", category: "electronics" },
  { symbol: "radio", category: "electronics" },
  { symbol: "windowscreen", category: "electronics" },
  { symbol: "switchplate", category: "electronics" },
  { symbol: "switch", category: "electronics" },
  { symbol: "loudspeaker", category: "electronics" },
  { symbol: "wirelesscharger", category: "electronics" },
  { symbol: "laptopstand", category: "electronics" },
  { symbol: "phonemount", category: "electronics" },
  { symbol: "earplug", category: "electronics" },
  { symbol: "sparkplugwire", category: "electronics" },
  { symbol: "camera strap", category: "electronics" },
  { symbol: "wirebrush", category: "electronics" },
  { symbol: "switchpanel", category: "electronics" },
  { symbol: "modem", category: "electronics" },
  { symbol: "screwdriver", category: "electronics" },
  { symbol: "mobilephone", category: "electronics" },
  { symbol: "cablebox", category: "electronics" },
  { symbol: "laptop", category: "electronics" },
  { symbol: "monitorarm", category: "electronics" },
  { symbol: "monitorstand", category: "electronics" },
  { symbol: "phonegrip", category: "electronics" },
  { symbol: "tabletpen", category: "electronics" },
  { symbol: "sensorchip", category: "electronics" },
  { symbol: "touchscreen", category: "electronics" },
  { symbol: "wire tray", category: "electronics" },
  { symbol: "extensionplug", category: "electronics" },
  { symbol: "cable holder", category: "electronics" },
  { symbol: "window sensor", category: "electronics" },
  { symbol: "smartphone", category: "electronics" },
  { symbol: "harddrive", category: "electronics" },
  { symbol: "securitycamera", category: "electronics" },
  { symbol: "babymonitor", category: "electronics" },
  { symbol: "usb charger", category: "electronics" },
  { symbol: "phonecharger", category: "electronics" },
  { symbol: "camerabag", category: "electronics" },
  { symbol: "earbuds", category: "electronics" },
  { symbol: "microphone", category: "electronics" },
  { symbol: "networkswitch", category: "electronics" },
  { symbol: "console", category: "electronics" },
  { symbol: "dashboardscreen", category: "electronics" },
  { symbol: "speakerbox", category: "electronics" },
  { symbol: "phonering", category: "electronics" },
  { symbol: "smartwatchcharger", category: "electronics" },
  { symbol: "cablelock", category: "electronics" },
  { symbol: "alarmclockradio", category: "electronics" },
  { symbol: "windowsensor", category: "electronics" },
  { symbol: "videocamera", category: "electronics" },
  { symbol: "door sensor", category: "electronics" },
  { symbol: "sensor", category: "electronics" },
  { symbol: "phonestand", category: "electronics" },
  { symbol: "plug", category: "electronics" },
  { symbol: "motion sensor", category: "electronics" },
  { symbol: "cableholder", category: "electronics" },
  { symbol: "mousepad", category: "electronics" },
  { symbol: "keyboard", category: "electronics" },
  { symbol: "smartswitch", category: "electronics" },
  { symbol: "earphone", category: "electronics" },
  { symbol: "usbdrive", category: "electronics" },
  { symbol: "cable", category: "electronics" },
  { symbol: "usbhub", category: "electronics" },
  { symbol: "camera bag", category: "electronics" },
  { symbol: "cellphone", category: "electronics" },
  { symbol: "impactdriver", category: "electronics" },
  { symbol: "carcharger", category: "electronics" },
  { symbol: "bluetoothspeaker", category: "electronics" },
  { symbol: "drawingtablet", category: "electronics" },
  { symbol: "sparkplug", category: "electronics" },
  { symbol: "tablet charger", category: "electronics" },
  { symbol: "gamingconsole", category: "electronics" },
  { symbol: "headphones", category: "electronics" },
  { symbol: "wire", category: "electronics" },
  { symbol: "tvmount", category: "electronics" },
  { symbol: "datacable", category: "electronics" },
  { symbol: "opticaldrive", category: "electronics" },
  { symbol: "tabletstand", category: "electronics" },
  { symbol: "detector", category: "electronics" },
  { symbol: "cable organizer", category: "electronics" },
  { symbol: "flashdrive", category: "electronics" },
  { symbol: "tabletcover", category: "electronics" },
  { symbol: "ethernetcable", category: "electronics" },
  { symbol: "camerastrap", category: "electronics" },
  { symbol: "radioantenna", category: "electronics" },
  { symbol: "doorsensor", category: "electronics" },
  { symbol: "smartplug", category: "electronics" },
  { symbol: "laptopsleeve", category: "electronics" },
  { symbol: "wirecutter", category: "electronics" },
  { symbol: "router", category: "electronics" },
  { symbol: "phoneholder", category: "electronics" },
  { symbol: "cablesleeve", category: "electronics" },
  { symbol: "wireconnector", category: "electronics" },
  { symbol: "mousetrap", category: "electronics" },
  { symbol: "windscreen", category: "electronics" },
  { symbol: "wiretray", category: "electronics" },
  { symbol: "lightswitch", category: "electronics" },
  { symbol: "buttplug", category: "electronics" },
  { symbol: "hdmicable", category: "electronics" },
  { symbol: "earplugs", category: "electronics" },
  { symbol: "bluetoothadapter", category: "electronics" },
  { symbol: "motionsensor", category: "electronics" },
  { symbol: "camera", category: "electronics" },
  { symbol: "computer", category: "electronics" },
  { symbol: "chargerplug", category: "electronics" },
  { symbol: "poweradapter", category: "electronics" },
  { symbol: "usbcharger", category: "electronics" },
  { symbol: "usbcable", category: "electronics" },
  { symbol: "drilldriver", category: "electronics" },
  { symbol: "adapter", category: "electronics" },
  { symbol: "laptopcharger", category: "electronics" },
  { symbol: "tvstand", category: "electronics" },
  { symbol: "toycharger", category: "electronics" },
  { symbol: "buttonswitch", category: "electronics" },
  { symbol: "phonecase", category: "electronics" },
  { symbol: "telephone", category: "electronics" },
  { symbol: "wirehanger", category: "electronics" },
  { symbol: "wire rack", category: "electronics" },
  { symbol: "speaker", category: "electronics" },
  { symbol: "camerastand", category: "electronics" },
  { symbol: "chargingcable", category: "electronics" },
  { symbol: "coilwire", category: "electronics" },
  { symbol: "mouse", category: "electronics" },
  { symbol: "antennawire", category: "electronics" },
  { symbol: "jumpercables", category: "electronics" },
  { symbol: "smarttv", category: "electronics" },
  { symbol: "tablet", category: "electronics" },
  { symbol: "monitor", category: "electronics" },
  { symbol: "metaldetector", category: "electronics" },
  { symbol: "plugboard", category: "electronics" },
  { symbol: "cableclip", category: "electronics" },
  { symbol: "keyboardtray", category: "electronics" },
  { symbol: "earbudscase", category: "electronics" },
  { symbol: "wirerack", category: "electronics" },
  { symbol: "cameralens", category: "electronics" },
  { symbol: "laptop charger", category: "electronics" },
];
