import { SingleWordSymbol } from "../dreamSingularSymbols";

export const good_fortunes_symbols: SingleWordSymbol[] = [
  { symbol: "success", category: "good_fortunes" },
  { symbol: "victory", category: "good_fortunes" },
  { symbol: "achievement", category: "good_fortunes" },
  { symbol: "accomplishment", category: "good_fortunes" },
  { symbol: "triumph", category: "good_fortunes" },
  { symbol: "progress", category: "good_fortunes" },
  { symbol: "improvement", category: "good_fortunes" },
  { symbol: "growth", category: "good_fortunes" },
  { symbol: "advancement", category: "good_fortunes" },
  { symbol: "promotion", category: "good_fortunes" },
  { symbol: "reward", category: "good_fortunes" },
  { symbol: "recognition", category: "good_fortunes" },
  { symbol: "approval", category: "good_fortunes" },
  { symbol: "validation", category: "good_fortunes" },
  { symbol: "acceptance", category: "good_fortunes" },
  { symbol: "respect", category: "good_fortunes" },
  { symbol: "honor", category: "good_fortunes" },
  { symbol: "praise", category: "good_fortunes" },
  { symbol: "celebration", category: "good_fortunes" },
  { symbol: "joy", category: "good_fortunes" },
  { symbol: "happiness", category: "good_fortunes" },
  { symbol: "delight", category: "good_fortunes" },
  { symbol: "excitement", category: "good_fortunes" },
  { symbol: "pleasure", category: "good_fortunes" },
  { symbol: "comfort", category: "good_fortunes" },
  { symbol: "peace", category: "good_fortunes" },
  { symbol: "relief", category: "good_fortunes" },
  { symbol: "hope", category: "good_fortunes" },
  { symbol: "optimism", category: "good_fortunes" },
  { symbol: "confidence", category: "good_fortunes" },
  { symbol: "love", category: "good_fortunes" },
  { symbol: "affection", category: "good_fortunes" },
  { symbol: "connection", category: "good_fortunes" },
  { symbol: "friendship", category: "good_fortunes" },
  { symbol: "companionship", category: "good_fortunes" },
  { symbol: "partnership", category: "good_fortunes" },
  { symbol: "marriage", category: "good_fortunes" },
  { symbol: "reunion", category: "good_fortunes" },
  { symbol: "reconciliation", category: "good_fortunes" },
  { symbol: "forgiveness", category: "good_fortunes" },
  { symbol: "support", category: "good_fortunes" },
  { symbol: "assistance", category: "good_fortunes" },
  { symbol: "help", category: "good_fortunes" },
  { symbol: "guidance", category: "good_fortunes" },
  { symbol: "mentorship", category: "good_fortunes" },
  { symbol: "protection", category: "good_fortunes" },
  { symbol: "rescue", category: "good_fortunes" },
  { symbol: "salvation", category: "good_fortunes" },
  { symbol: "escape", category: "good_fortunes" },
  { symbol: "freedom", category: "good_fortunes" },
  { symbol: "liberation", category: "good_fortunes" },
  { symbol: "release", category: "good_fortunes" },
  { symbol: "recovery", category: "good_fortunes" },
  { symbol: "healing", category: "good_fortunes" },
  { symbol: "restoration", category: "good_fortunes" },
  { symbol: "renewal", category: "good_fortunes" },
  { symbol: "revival", category: "good_fortunes" },
  { symbol: "rebirth", category: "good_fortunes" },
  { symbol: "awakening", category: "good_fortunes" },
  { symbol: "enlightenment", category: "good_fortunes" },
  { symbol: "clarity", category: "good_fortunes" },
  { symbol: "understanding", category: "good_fortunes" },
  { symbol: "realization", category: "good_fortunes" },
  { symbol: "discovery", category: "good_fortunes" },
  { symbol: "insight", category: "good_fortunes" },
  { symbol: "wisdom", category: "good_fortunes" },
  { symbol: "knowledge", category: "good_fortunes" },
  { symbol: "learning", category: "good_fortunes" },
  { symbol: "mastery", category: "good_fortunes" },
  { symbol: "skill", category: "good_fortunes" },
  { symbol: "creativity", category: "good_fortunes" },
  { symbol: "invention", category: "good_fortunes" },
  { symbol: "creation", category: "good_fortunes" },
  { symbol: "innovation", category: "good_fortunes" },
  { symbol: "solution", category: "good_fortunes" },
  { symbol: "resolution", category: "good_fortunes" },
  { symbol: "completion", category: "good_fortunes" },
  { symbol: "fulfillment", category: "good_fortunes" },
  { symbol: "satisfaction", category: "good_fortunes" },
  { symbol: "contentment", category: "good_fortunes" },
  { symbol: "prosperity", category: "good_fortunes" },
  { symbol: "abundance", category: "good_fortunes" },
  { symbol: "wealth", category: "good_fortunes" },
  { symbol: "fortune", category: "good_fortunes" },
  { symbol: "profit", category: "good_fortunes" },
  { symbol: "gain", category: "good_fortunes" },
  { symbol: "earnings", category: "good_fortunes" },
  { symbol: "bonus", category: "good_fortunes" },
  { symbol: "gift", category: "good_fortunes" },
  { symbol: "treasure", category: "good_fortunes" },
  { symbol: "inheritance", category: "good_fortunes" },
  { symbol: "windfall", category: "good_fortunes" },
  { symbol: "lottery", category: "good_fortunes" },
  { symbol: "luck", category: "good_fortunes" },
  { symbol: "goodluck", category: "good_fortunes" },
  { symbol: "blessing", category: "good_fortunes" },
  { symbol: "miracle", category: "good_fortunes" },
  { symbol: "grace", category: "good_fortunes" },
  { symbol: "favor", category: "good_fortunes" },
  { symbol: "opportunity", category: "good_fortunes" },
  { symbol: "chance", category: "good_fortunes" },
  { symbol: "breakthrough", category: "good_fortunes" },
  { symbol: "opening", category: "good_fortunes" },
  { symbol: "arrival", category: "good_fortunes" },
  { symbol: "return", category: "good_fortunes" },
  { symbol: "meeting", category: "good_fortunes" },
  { symbol: "alliance", category: "good_fortunes" },
  { symbol: "cooperation", category: "good_fortunes" },
  { symbol: "teamwork", category: "good_fortunes" },
  { symbol: "collaboration", category: "good_fortunes" },
  { symbol: "unity", category: "good_fortunes" },
  { symbol: "bond", category: "good_fortunes" },
  { symbol: "trust", category: "good_fortunes" },
  { symbol: "loyalty", category: "good_fortunes" },
  { symbol: "faith", category: "good_fortunes" },
  { symbol: "devotion", category: "good_fortunes" },
  { symbol: "commitment", category: "good_fortunes" },
  { symbol: "safety", category: "good_fortunes" },
  { symbol: "security", category: "good_fortunes" },
  { symbol: "shelter", category: "good_fortunes" },
  { symbol: "refuge", category: "good_fortunes" },
  { symbol: "stability", category: "good_fortunes" },
  { symbol: "balance", category: "good_fortunes" },
  { symbol: "harmony", category: "good_fortunes" },
  { symbol: "calm", category: "good_fortunes" },
  { symbol: "relaxation", category: "good_fortunes" },
  { symbol: "rest", category: "good_fortunes" },
  { symbol: "refreshment", category: "good_fortunes" },
  { symbol: "rejuvenation", category: "good_fortunes" },
  { symbol: "energy", category: "good_fortunes" },
  { symbol: "vitality", category: "good_fortunes" },
  { symbol: "strength", category: "good_fortunes" },
  { symbol: "power", category: "good_fortunes" },
  { symbol: "empowerment", category: "good_fortunes" },
  { symbol: "graduation", category: "good_fortunes" },
  { symbol: "award", category: "good_fortunes" },
  { symbol: "medal", category: "good_fortunes" },
  { symbol: "trophy", category: "good_fortunes" },
  { symbol: "party", category: "good_fortunes" },
  { symbol: "festival", category: "good_fortunes" },
  { symbol: "gathering", category: "good_fortunes" },
  { symbol: "union", category: "good_fortunes" },
  { symbol: "birth", category: "good_fortunes" },
  { symbol: "exploration", category: "good_fortunes" },
  { symbol: "adventure", category: "good_fortunes" },
  { symbol: "journey", category: "good_fortunes" },
  { symbol: "travel", category: "good_fortunes" },
  { symbol: "landing", category: "good_fortunes" },
  { symbol: "homecoming", category: "good_fortunes" },
  { symbol: "finding", category: "good_fortunes" },
  { symbol: "development", category: "good_fortunes" },
  { symbol: "evolution", category: "good_fortunes" },
  { symbol: "transformation", category: "good_fortunes" },
  { symbol: "change", category: "good_fortunes" },
  { symbol: "expansion", category: "good_fortunes" },
  {
    symbol: "win",
    category: "good_fortunes",
  },
  {
    symbol: "prize",
    category: "good_fortunes",
  },
  {
    symbol: "jackpot",
    category: "good_fortunes",
  },
  {
    symbol: "appreciation",
    category: "good_fortunes",
  },
  {
    symbol: "gratitude",
    category: "good_fortunes",
  },
  {
    symbol: "advantage",
    category: "good_fortunes",
  },
  {
    symbol: "benefit",
    category: "good_fortunes",
  },
  {
    symbol: "surprise",
    category: "good_fortunes",
  },
  {
    symbol: "riches",
    category: "good_fortunes",
  },
  {
    symbol: "gold",
    category: "good_fortunes",
  },
  {
    symbol: "money",
    category: "good_fortunes",
  },
  {
    symbol: "scholarship",
    category: "good_fortunes",
  },
  {
    symbol: "grant",
    category: "good_fortunes",
  },
  {
    symbol: "offer",
    category: "good_fortunes",
  },
  {
    symbol: "encouragement",
    category: "good_fortunes",
  },
  {
    symbol: "admiration",
    category: "good_fortunes",
  },
  {
    symbol: "belonging",
    category: "good_fortunes",
  },
  {
    symbol: "redemption",
    category: "good_fortunes",
  },
  {
    symbol: "inspiration",
    category: "good_fortunes",
  },
  {
    symbol: "motivation",
    category: "good_fortunes",
  },
  {
    symbol: "answer",
    category: "good_fortunes",
  },
  {
    symbol: "possibility",
    category: "good_fortunes",
  },
  {
    symbol: "pathway",
    category: "good_fortunes",
  },
  {
    symbol: "doorway",
    category: "good_fortunes",
  },
  {
    symbol: "destination",
    category: "good_fortunes",
  },
  {
    symbol: "leadership",
    category: "good_fortunes",
  },
  {
    symbol: "influence",
    category: "good_fortunes",
  },
  {
    symbol: "authority",
    category: "good_fortunes",
  },
  {
    symbol: "courage",
    category: "good_fortunes",
  },
  {
    symbol: "resilience",
    category: "good_fortunes",
  },
  {
    symbol: "perseverance",
    category: "good_fortunes",
  },
  {
    symbol: "endurance",
    category: "good_fortunes",
  },
  {
    symbol: "survival",
    category: "good_fortunes",
  },
  {
    symbol: "winning",
    category: "good_fortunes",
  },
  {
    symbol: "findingmoney",
    category: "good_fortunes",
  },
  {
    symbol: "findinggold",
    category: "good_fortunes",
  },
  {
    symbol: "findingtreasure",
    category: "good_fortunes",
  },
  {
    symbol: "findingwallet",
    category: "good_fortunes",
  },
  {
    symbol: "findingkeys",
    category: "good_fortunes",
  },
  {
    symbol: "findingring",
    category: "good_fortunes",
  },
  {
    symbol: "findingjewelry",
    category: "good_fortunes",
  },
  {
    symbol: "findingphone",
    category: "good_fortunes",
  },
  {
    symbol: "findinglostitem",
    category: "good_fortunes",
  },
  {
    symbol: "solvingproblem",
    category: "good_fortunes",
  },
  {
    symbol: "solvingmystery",
    category: "good_fortunes",
  },
  {
    symbol: "solvingpuzzle",
    category: "good_fortunes",
  },
  {
    symbol: "joboffer",
    category: "good_fortunes",
  },
  {
    symbol: "newjob",
    category: "good_fortunes",
  },
  {
    symbol: "raise",
    category: "good_fortunes",
  },
  {
    symbol: "salaryincrease",
    category: "good_fortunes",
  },
  {
    symbol: "contract",
    category: "good_fortunes",
  },
  {
    symbol: "agreement",
    category: "good_fortunes",
  },
  {
    symbol: "apologyaccepted",
    category: "good_fortunes",
  },
  {
    symbol: "helpreceived",
    category: "good_fortunes",
  },
  {
    symbol: "rescuearrival",
    category: "good_fortunes",
  },
  {
    symbol: "safeescape",
    category: "good_fortunes",
  },
  {
    symbol: "cure",
    category: "good_fortunes",
  },
  {
    symbol: "treatmentworking",
    category: "good_fortunes",
  },
  {
    symbol: "medicineworking",
    category: "good_fortunes",
  },
  {
    symbol: "shelterfound",
    category: "good_fortunes",
  },
  {
    symbol: "homefound",
    category: "good_fortunes",
  },
  {
    symbol: "housepurchase",
    category: "good_fortunes",
  },
  {
    symbol: "newhome",
    category: "good_fortunes",
  },
  {
    symbol: "movingforward",
    category: "good_fortunes",
  },
  {
    symbol: "skillgain",
    category: "good_fortunes",
  },
  {
    symbol: "confidencegain",
    category: "good_fortunes",
  },
  {
    symbol: "couragegain",
    category: "good_fortunes",
  },
  {
    symbol: "strengthgain",
    category: "good_fortunes",
  },
  {
    symbol: "successcelebration",
    category: "good_fortunes",
  },
  {
    symbol: "wedding",
    category: "good_fortunes",
  },
  {
    symbol: "engagement",
    category: "good_fortunes",
  },
  {
    symbol: "proposalaccepted",
    category: "good_fortunes",
  },
  {
    symbol: "babybirth",
    category: "good_fortunes",
  },
  {
    symbol: "pregnancy",
    category: "good_fortunes",
  },
  {
    symbol: "adoption",
    category: "good_fortunes",
  },
  {
    symbol: "familyreunion",
    category: "good_fortunes",
  },
  {
    symbol: "meetingfriend",
    category: "good_fortunes",
  },
  {
    symbol: "meetingpartner",
    category: "good_fortunes",
  },
  {
    symbol: "meetingmentor",
    category: "good_fortunes",
  },
  {
    symbol: "findinglove",
    category: "good_fortunes",
  },
  {
    symbol: "fallinginlove",
    category: "good_fortunes",
  },
  {
    symbol: "mutuallove",
    category: "good_fortunes",
  },
  {
    symbol: "affectionreceived",
    category: "good_fortunes",
  },
  {
    symbol: "hugreceived",
    category: "good_fortunes",
  },
  {
    symbol: "kindnessreceived",
    category: "good_fortunes",
  },
  {
    symbol: "generosityreceived",
    category: "good_fortunes",
  },
  {
    symbol: "giftreceived",
    category: "good_fortunes",
  },
  {
    symbol: "presentreceived",
    category: "good_fortunes",
  },
  {
    symbol: "surprisegift",
    category: "good_fortunes",
  },
  {
    symbol: "luckybreak",
    category: "good_fortunes",
  },
  {
    symbol: "chanceencounter",
    category: "good_fortunes",
  },
  {
    symbol: "helpfulstranger",
    category: "good_fortunes",
  },
  {
    symbol: "doorsopening",
    category: "good_fortunes",
  },
  {
    symbol: "pathappearing",
    category: "good_fortunes",
  },
  {
    symbol: "doorunlocking",
    category: "good_fortunes",
  },
  {
    symbol: "barrierremoved",
    category: "good_fortunes",
  },
  {
    symbol: "obstaclecleared",
    category: "good_fortunes",
  },
  {
    symbol: "roadopening",
    category: "good_fortunes",
  },
  {
    symbol: "passageopening",
    category: "good_fortunes",
  },
  {
    symbol: "safepassage",
    category: "good_fortunes",
  },
  {
    symbol: "arrivalhome",
    category: "good_fortunes",
  },
  {
    symbol: "reachingdestination",
    category: "good_fortunes",
  },
  {
    symbol: "finishingrace",
    category: "good_fortunes",
  },
  {
    symbol: "completingtask",
    category: "good_fortunes",
  },
  {
    symbol: "completingmission",
    category: "good_fortunes",
  },
  {
    symbol: "completinggoal",
    category: "good_fortunes",
  },
  {
    symbol: "achievinggoal",
    category: "good_fortunes",
  },
  {
    symbol: "achievingdream",
    category: "good_fortunes",
  },
  {
    symbol: "achievingtarget",
    category: "good_fortunes",
  },
  {
    symbol: "earningrespect",
    category: "good_fortunes",
  },
  {
    symbol: "gainingtrust",
    category: "good_fortunes",
  },
  {
    symbol: "gainingfriends",
    category: "good_fortunes",
  },
  {
    symbol: "gainingallies",
    category: "good_fortunes",
  },
  {
    symbol: "gainingknowledge",
    category: "good_fortunes",
  },
  {
    symbol: "gainingexperience",
    category: "good_fortunes",
  },
  {
    symbol: "gainingpower",
    category: "good_fortunes",
  },
  {
    symbol: "gainingposition",
    category: "good_fortunes",
  },
  {
    symbol: "gainingcontrol",
    category: "good_fortunes",
  },
  {
    symbol: "gainingfreedom",
    category: "good_fortunes",
  },
  {
    symbol: "gainingindependence",
    category: "good_fortunes",
  },
  {
    symbol: "gainingrecognition",
    category: "good_fortunes",
  },
  {
    symbol: "gainingwealth",
    category: "good_fortunes",
  },
  {
    symbol: "gainingfortune",
    category: "good_fortunes",
  },
  {
    symbol: "financialgain",
    category: "good_fortunes",
  },
  {
    symbol: "investmentgain",
    category: "good_fortunes",
  },
  {
    symbol: "businesssuccess",
    category: "good_fortunes",
  },
  {
    symbol: "dealcompleted",
    category: "good_fortunes",
  },
  {
    symbol: "salecompleted",
    category: "good_fortunes",
  },
  {
    symbol: "projectsuccess",
    category: "good_fortunes",
  },
  {
    symbol: "projectapproval",
    category: "good_fortunes",
  },
  {
    symbol: "exampassed",
    category: "good_fortunes",
  },
  {
    symbol: "testpassed",
    category: "good_fortunes",
  },
  {
    symbol: "licensegranted",
    category: "good_fortunes",
  },
  {
    symbol: "permitgranted",
    category: "good_fortunes",
  },
  {
    symbol: "clearancegranted",
    category: "good_fortunes",
  },
  {
    symbol: "visaapproved",
    category: "good_fortunes",
  },
  {
    symbol: "citizenshipgranted",
    category: "good_fortunes",
  },
  {
    symbol: "awardceremony",
    category: "good_fortunes",
  },
  {
    symbol: "medalawarded",
    category: "good_fortunes",
  },
  {
    symbol: "trophyawarded",
    category: "good_fortunes",
  },
  {
    symbol: "ribbonawarded",
    category: "good_fortunes",
  },
  {
    symbol: "certificateawarded",
    category: "good_fortunes",
  },
  {
    symbol: "honorreceived",
    category: "good_fortunes",
  },
  {
    symbol: "standingovation",
    category: "good_fortunes",
  },
  {
    symbol: "applause",
    category: "good_fortunes",
  },
  {
    symbol: "cheer",
    category: "good_fortunes",
  },
  {
    symbol: "crowdsupport",
    category: "good_fortunes",
  },
  {
    symbol: "fanpraise",
    category: "good_fortunes",
  },
  {
    symbol: "leaderappointed",
    category: "good_fortunes",
  },
  {
    symbol: "captainappointed",
    category: "good_fortunes",
  },
  {
    symbol: "rolegranted",
    category: "good_fortunes",
  },
  {
    symbol: "responsibilitygranted",
    category: "good_fortunes",
  },
  {
    symbol: "authoritygranted",
    category: "good_fortunes",
  },
  {
    symbol: "leadershipgranted",
    category: "good_fortunes",
  },
  {
    symbol: "challengewon",
    category: "good_fortunes",
  },
  {
    symbol: "competitionwon",
    category: "good_fortunes",
  },
  {
    symbol: "contestwon",
    category: "good_fortunes",
  },
  {
    symbol: "electionwon",
    category: "good_fortunes",
  },
  {
    symbol: "debatewon",
    category: "good_fortunes",
  },
  {
    symbol: "argumentwon",
    category: "good_fortunes",
  },
  {
    symbol: "conflictresolved",
    category: "good_fortunes",
  },
  {
    symbol: "peacemade",
    category: "good_fortunes",
  },
  {
    symbol: "truceformed",
    category: "good_fortunes",
  },
  {
    symbol: "allianceformed",
    category: "good_fortunes",
  },
  {
    symbol: "enemydefeated",
    category: "good_fortunes",
  },
  {
    symbol: "rivaldefeated",
    category: "good_fortunes",
  },
  {
    symbol: "problemfixed",
    category: "good_fortunes",
  },
  {
    symbol: "repaircompleted",
    category: "good_fortunes",
  },
  {
    symbol: "buildingcompleted",
    category: "good_fortunes",
  },
  {
    symbol: "creationfinished",
    category: "good_fortunes",
  },
  {
    symbol: "inventioncompleted",
    category: "good_fortunes",
  },
  {
    symbol: "idearecognized",
    category: "good_fortunes",
  },
  {
    symbol: "ideaaccepted",
    category: "good_fortunes",
  },
  {
    symbol: "planworking",
    category: "good_fortunes",
  },
  {
    symbol: "strategyworking",
    category: "good_fortunes",
  },
  {
    symbol: "missionaccomplished",
    category: "good_fortunes",
  },
  {
    symbol: "targethit",
    category: "good_fortunes",
  },
  {
    symbol: "recordbroken",
    category: "good_fortunes",
  },
  {
    symbol: "milestoneachieved",
    category: "good_fortunes",
  },
  {
    symbol: "recordset",
    category: "good_fortunes",
  },
  {
    symbol: "highscore",
    category: "good_fortunes",
  },
  {
    symbol: "personalbest",
    category: "good_fortunes",
  },
  {
    symbol: "championcrowned",
    category: "good_fortunes",
  },
  {
    symbol: "titlewon",
    category: "good_fortunes",
  },
  {
    symbol: "crownreceived",
    category: "good_fortunes",
  },
  {
    symbol: "thronegained",
    category: "good_fortunes",
  },
  {
    symbol: "kingdomgained",
    category: "good_fortunes",
  },
  {
    symbol: "territorygained",
    category: "good_fortunes",
  },
  {
    symbol: "promotionreceived",
    category: "good_fortunes",
  },
  {
    symbol: "rankincreased",
    category: "good_fortunes",
  },
  {
    symbol: "levelup",
    category: "good_fortunes",
  },
  {
    symbol: "progressmade",
    category: "good_fortunes",
  },
  {
    symbol: "stepforward",
    category: "good_fortunes",
  },
  {
    symbol: "breakthroughmoment",
    category: "good_fortunes",
  },
  {
    symbol: "realizationmoment",
    category: "good_fortunes",
  },
  {
    symbol: "newbeginning",
    category: "good_fortunes",
  },
  {
    symbol: "freshstart",
    category: "good_fortunes",
  },
  {
    symbol: "secondchance",
    category: "good_fortunes",
  },
  {
    symbol: "redemptionearned",
    category: "good_fortunes",
  },
  {
    symbol: "forgivenessreceived",
    category: "good_fortunes",
  },
  {
    symbol: "guiltreleased",
    category: "good_fortunes",
  },
  {
    symbol: "burdenlifted",
    category: "good_fortunes",
  },
  {
    symbol: "stressreleased",
    category: "good_fortunes",
  },
  {
    symbol: "relieffelt",
    category: "good_fortunes",
  },
  {
    symbol: "peacefelt",
    category: "good_fortunes",
  },
  {
    symbol: "calmfelt",
    category: "good_fortunes",
  },
  {
    symbol: "joyfelt",
    category: "good_fortunes",
  },
  {
    symbol: "happinessfelt",
    category: "good_fortunes",
  },
  {
    symbol: "satisfactionfelt",
    category: "good_fortunes",
  },
  {
    symbol: "fulfillmentfelt",
    category: "good_fortunes",
  },
  {
    symbol: "pridefelt",
    category: "good_fortunes",
  },
  {
    symbol: "hopefelt",
    category: "good_fortunes",
  },
  {
    symbol: "optimismfelt",
    category: "good_fortunes",
  },
  {
    symbol: "confidencefelt",
    category: "good_fortunes",
  },
  {
    symbol: "couragefelt",
    category: "good_fortunes",
  },
  {
    symbol: "admirationreceived",
    category: "good_fortunes",
  },
  {
    symbol: "respectreceived",
    category: "good_fortunes",
  },
  {
    symbol: "loyaltyreceived",
    category: "good_fortunes",
  },
  {
    symbol: "trustreceived",
    category: "good_fortunes",
  },
  {
    symbol: "belongingfelt",
    category: "good_fortunes",
  },
  {
    symbol: "connectionfelt",
    category: "good_fortunes",
  },
  {
    symbol: "unityfelt",
    category: "good_fortunes",
  },
  {
    symbol: "harmonyfelt",
    category: "good_fortunes",
  },
  {
    symbol: "lovefelt",
    category: "good_fortunes",
  },
  {
    symbol: "friendshipformed",
    category: "good_fortunes",
  },
  {
    symbol: "partnershipformed",
    category: "good_fortunes",
  },
  {
    symbol: "teamworksuccess",
    category: "good_fortunes",
  },
  {
    symbol: "cooperationworking",
    category: "good_fortunes",
  },
  {
    symbol: "supportarriving",
    category: "good_fortunes",
  },
  {
    symbol: "helparriving",
    category: "good_fortunes",
  },
  {
    symbol: "assistancereceived",
    category: "good_fortunes",
  },
  {
    symbol: "guidancereceived",
    category: "good_fortunes",
  },
  {
    symbol: "mentorshipreceived",
    category: "good_fortunes",
  },
  {
    symbol: "adviceworking",
    category: "good_fortunes",
  },
  {
    symbol: "directionfound",
    category: "good_fortunes",
  },
  {
    symbol: "pathedfound",
    category: "good_fortunes",
  },
  {
    symbol: "routefound",
    category: "good_fortunes",
  },
  {
    symbol: "exitfound",
    category: "good_fortunes",
  },
  {
    symbol: "solutionfound",
    category: "good_fortunes",
  },
  {
    symbol: "answerfound",
    category: "good_fortunes",
  },
  {
    symbol: "itemrecovered",
    category: "good_fortunes",
  },
  {
    symbol: "itemreturned",
    category: "good_fortunes",
  },
  {
    symbol: "moneyreturned",
    category: "good_fortunes",
  },
  {
    symbol: "walletreturned",
    category: "good_fortunes",
  },
  {
    symbol: "phonefound",
    category: "good_fortunes",
  },
  {
    symbol: "keysfound",
    category: "good_fortunes",
  },
  {
    symbol: "ringfound",
    category: "good_fortunes",
  },
  {
    symbol: "treasurefound",
    category: "good_fortunes",
  },
  {
    symbol: "artifactfound",
    category: "good_fortunes",
  },
  {
    symbol: "discoverymade",
    category: "good_fortunes",
  },
  {
    symbol: "landfound",
    category: "good_fortunes",
  },
  {
    symbol: "islandfound",
    category: "good_fortunes",
  },
  {
    symbol: "resourcefound",
    category: "good_fortunes",
  },
  {
    symbol: "waterfound",
    category: "good_fortunes",
  },
  {
    symbol: "foodfound",
    category: "good_fortunes",
  },
  {
    symbol: "supplyfound",
    category: "good_fortunes",
  },
  {
    symbol: "safeplacefound",
    category: "good_fortunes",
  },
  {
    symbol: "hiddenplacefound",
    category: "good_fortunes",
  },
  {
    symbol: "shortcutfound",
    category: "good_fortunes",
  },
  {
    symbol: "secretdoorfound",
    category: "good_fortunes",
  },
  {
    symbol: "hiddenpathfound",
    category: "good_fortunes",
  },
  {
    symbol: "tunnelescape",
    category: "good_fortunes",
  },
  {
    symbol: "doorwayescape",
    category: "good_fortunes",
  },
  {
    symbol: "passageescape",
    category: "good_fortunes",
  },
  {
    symbol: "safejourney",
    category: "good_fortunes",
  },
  {
    symbol: "smoothjourney",
    category: "good_fortunes",
  },
  {
    symbol: "easytravel",
    category: "good_fortunes",
  },
  {
    symbol: "safearrival",
    category: "good_fortunes",
  },
  {
    symbol: "journeycompleted",
    category: "good_fortunes",
  },
  {
    symbol: "questcompleted",
    category: "good_fortunes",
  },
  {
    symbol: "adventurecompleted",
    category: "good_fortunes",
  },
  {
    symbol: "explorationsuccess",
    category: "good_fortunes",
  },
  {
    symbol: "expeditionsuccess",
    category: "good_fortunes",
  },
  {
    symbol: "discoverysuccess",
    category: "good_fortunes",
  },
  {
    symbol: "missioncompleted",
    category: "good_fortunes",
  },
  {
    symbol: "giftgiven",
    category: "good_fortunes",
  },
  {
    symbol: "kindnessshown",
    category: "good_fortunes",
  },
  {
    symbol: "favorgranted",
    category: "good_fortunes",
  },
  {
    symbol: "blessingreceived",
    category: "good_fortunes",
  },
  {
    symbol: "promisefulfilled",
    category: "good_fortunes",
  },
  {
    symbol: "wishgranted",
    category: "good_fortunes",
  },
  {
    symbol: "dreamfulfilled",
    category: "good_fortunes",
  },
  {
    symbol: "luckyfind",
    category: "good_fortunes",
  },
  {
    symbol: "chancewin",
    category: "good_fortunes",
  },
  {
    symbol: "rafflewin",
    category: "good_fortunes",
  },
  {
    symbol: "lotterywin",
    category: "good_fortunes",
  },
  {
    symbol: "contestprize",
    category: "good_fortunes",
  },
  {
    symbol: "prizeclaimed",
    category: "good_fortunes",
  },
  {
    symbol: "treasureclaimed",
    category: "good_fortunes",
  },
  {
    symbol: "goldfound",
    category: "good_fortunes",
  },
  {
    symbol: "coinfound",
    category: "good_fortunes",
  },
  {
    symbol: "diamondfound",
    category: "good_fortunes",
  },
  {
    symbol: "gemfound",
    category: "good_fortunes",
  },
  {
    symbol: "artifactrecovered",
    category: "good_fortunes",
  },
  {
    symbol: "relicfound",
    category: "good_fortunes",
  },
  {
    symbol: "mapfound",
    category: "good_fortunes",
  },
  {
    symbol: "shortcutdiscovered",
    category: "good_fortunes",
  },
  {
    symbol: "pathcleared",
    category: "good_fortunes",
  },
  {
    symbol: "safeexit",
    category: "good_fortunes",
  },
  {
    symbol: "safearrivalhome",
    category: "good_fortunes",
  },
  {
    symbol: "shelterprovided",
    category: "good_fortunes",
  },
  {
    symbol: "protectiongiven",
    category: "good_fortunes",
  },
  {
    symbol: "guardarrives",
    category: "good_fortunes",
  },
  {
    symbol: "dangeravoided",
    category: "good_fortunes",
  },
  {
    symbol: "trapavoided",
    category: "good_fortunes",
  },
  {
    symbol: "attackavoided",
    category: "good_fortunes",
  },
  {
    symbol: "conflictavoided",
    category: "good_fortunes",
  },
  {
    symbol: "dangerescaped",
    category: "good_fortunes",
  },
  {
    symbol: "threatended",
    category: "good_fortunes",
  },
  {
    symbol: "enemyretreats",
    category: "good_fortunes",
  },
  {
    symbol: "rivalwithdraws",
    category: "good_fortunes",
  },
  {
    symbol: "disputeended",
    category: "good_fortunes",
  },
  {
    symbol: "agreementreached",
    category: "good_fortunes",
  },
  {
    symbol: "compromiseformed",
    category: "good_fortunes",
  },
  {
    symbol: "peacetreaty",
    category: "good_fortunes",
  },
  {
    symbol: "truceaccepted",
    category: "good_fortunes",
  },
  {
    symbol: "misunderstandingcleared",
    category: "good_fortunes",
  },
  {
    symbol: "apologygiven",
    category: "good_fortunes",
  },
  {
    symbol: "apologyreceived",
    category: "good_fortunes",
  },
  {
    symbol: "gratitudeexpressed",
    category: "good_fortunes",
  },
  {
    symbol: "praisegiven",
    category: "good_fortunes",
  },
  {
    symbol: "complimentreceived",
    category: "good_fortunes",
  },
  {
    symbol: "recognitionearned",
    category: "good_fortunes",
  },
  {
    symbol: "respectearned",
    category: "good_fortunes",
  },
  {
    symbol: "honorbestowed",
    category: "good_fortunes",
  },
  {
    symbol: "titlegranted",
    category: "good_fortunes",
  },
  {
    symbol: "rankgranted",
    category: "good_fortunes",
  },
  {
    symbol: "authoritygiven",
    category: "good_fortunes",
  },
  {
    symbol: "trustgranted",
    category: "good_fortunes",
  },
  {
    symbol: "responsibilityearned",
    category: "good_fortunes",
  },
  {
    symbol: "leadershiprecognized",
    category: "good_fortunes",
  },
  {
    symbol: "guidancefound",
    category: "good_fortunes",
  },
  {
    symbol: "mentorappears",
    category: "good_fortunes",
  },
  {
    symbol: "teacherappears",
    category: "good_fortunes",
  },
  {
    symbol: "helperarrives",
    category: "good_fortunes",
  },
  {
    symbol: "allyappears",
    category: "good_fortunes",
  },
  {
    symbol: "friendreturns",
    category: "good_fortunes",
  },
  {
    symbol: "partnerreturns",
    category: "good_fortunes",
  },
  {
    symbol: "reunionhappens",
    category: "good_fortunes",
  },
  {
    symbol: "relationshipheals",
    category: "good_fortunes",
  },
  {
    symbol: "friendshiprestored",
    category: "good_fortunes",
  },
  {
    symbol: "familyreconnects",
    category: "good_fortunes",
  },
  {
    symbol: "bondstrengthens",
    category: "good_fortunes",
  },
  {
    symbol: "cooperationbegins",
    category: "good_fortunes",
  },
  {
    symbol: "teamworkforms",
    category: "good_fortunes",
  },
  {
    symbol: "alliancecreated",
    category: "good_fortunes",
  },
  {
    symbol: "partnershipbegins",
    category: "good_fortunes",
  },
  {
    symbol: "collaborationstarts",
    category: "good_fortunes",
  },
  {
    symbol: "supportgrows",
    category: "good_fortunes",
  },
  {
    symbol: "encouragementgiven",
    category: "good_fortunes",
  },
  {
    symbol: "hopeappears",
    category: "good_fortunes",
  },
  {
    symbol: "optimismrises",
    category: "good_fortunes",
  },
  {
    symbol: "moraleimproves",
    category: "good_fortunes",
  },
  {
    symbol: "spiritslifted",
    category: "good_fortunes",
  },
  {
    symbol: "reliefarrives",
    category: "good_fortunes",
  },
  {
    symbol: "stressfades",
    category: "good_fortunes",
  },
  {
    symbol: "burdenremoved",
    category: "good_fortunes",
  },
  {
    symbol: "problemresolved",
    category: "good_fortunes",
  },
  {
    symbol: "obstaclevanishes",
    category: "good_fortunes",
  },
  {
    symbol: "barrierbreaks",
    category: "good_fortunes",
  },
  {
    symbol: "wallopens",
    category: "good_fortunes",
  },
  {
    symbol: "gateopens",
    category: "good_fortunes",
  },
  {
    symbol: "doorappears",
    category: "good_fortunes",
  },
  {
    symbol: "passageopens",
    category: "good_fortunes",
  },
  {
    symbol: "pathrevealed",
    category: "good_fortunes",
  },
  {
    symbol: "roademerges",
    category: "good_fortunes",
  },
  {
    symbol: "journeycontinues",
    category: "good_fortunes",
  },
  {
    symbol: "guidanceappears",
    category: "good_fortunes",
  },
  {
    symbol: "directionclear",
    category: "good_fortunes",
  },
  {
    symbol: "answerrevealed",
    category: "good_fortunes",
  },
  {
    symbol: "truthrevealed",
    category: "good_fortunes",
  },
  {
    symbol: "secretrevealed",
    category: "good_fortunes",
  },
  {
    symbol: "knowledgegained",
    category: "good_fortunes",
  },
  {
    symbol: "lessonlearned",
    category: "good_fortunes",
  },
  {
    symbol: "wisdomgained",
    category: "good_fortunes",
  },
  {
    symbol: "ideaworks",
    category: "good_fortunes",
  },
  {
    symbol: "planworks",
    category: "good_fortunes",
  },
  {
    symbol: "strategyworks",
    category: "good_fortunes",
  },
  {
    symbol: "inventionworks",
    category: "good_fortunes",
  },
  {
    symbol: "creationrecognized",
    category: "good_fortunes",
  },
  {
    symbol: "talentnoticed",
    category: "good_fortunes",
  },
  {
    symbol: "abilityrecognized",
    category: "good_fortunes",
  },
  {
    symbol: "skillmastered",
    category: "good_fortunes",
  },
  {
    symbol: "masteryachieved",
    category: "good_fortunes",
  },
  {
    symbol: "expertisegained",
    category: "good_fortunes",
  },
  {
    symbol: "craftperfected",
    category: "good_fortunes",
  },
  {
    symbol: "performancepraised",
    category: "good_fortunes",
  },
  {
    symbol: "effortrecognized",
    category: "good_fortunes",
  },
  {
    symbol: "diligencepaidoff",
    category: "good_fortunes",
  },
  {
    symbol: "dedicationrewarded",
    category: "good_fortunes",
  },
  {
    symbol: "progressnoticed",
    category: "good_fortunes",
  },
  {
    symbol: "milestonepassed",
    category: "good_fortunes",
  },
  {
    symbol: "leveladvanced",
    category: "good_fortunes",
  },
  {
    symbol: "rankingimproves",
    category: "good_fortunes",
  },
  {
    symbol: "reputationgrows",
    category: "good_fortunes",
  },
  {
    symbol: "influencegrows",
    category: "good_fortunes",
  },
  {
    symbol: "networkexpands",
    category: "good_fortunes",
  },
  {
    symbol: "connectionsgrow",
    category: "good_fortunes",
  },
  {
    symbol: "supportnetwork",
    category: "good_fortunes",
  },
  {
    symbol: "communitysupport",
    category: "good_fortunes",
  },
  {
    symbol: "backingreceived",
    category: "good_fortunes",
  },
  {
    symbol: "fundingreceived",
    category: "good_fortunes",
  },
  {
    symbol: "sponsorshipreceived",
    category: "good_fortunes",
  },
  {
    symbol: "patronfound",
    category: "good_fortunes",
  },
  {
    symbol: "investorfound",
    category: "good_fortunes",
  },
  {
    symbol: "businessgrows",
    category: "good_fortunes",
  },
  {
    symbol: "dealclosed",
    category: "good_fortunes",
  },
  {
    symbol: "saleapproved",
    category: "good_fortunes",
  },
  {
    symbol: "contractwon",
    category: "good_fortunes",
  },
  {
    symbol: "marketgained",
    category: "good_fortunes",
  },
  {
    symbol: "profitearned",
    category: "good_fortunes",
  },
  {
    symbol: "savingsgrow",
    category: "good_fortunes",
  },
  {
    symbol: "wealthincreases",
    category: "good_fortunes",
  },
  {
    symbol: "fortuneexpands",
    category: "good_fortunes",
  },
  {
    symbol: "assetgained",
    category: "good_fortunes",
  },
  {
    symbol: "propertygained",
    category: "good_fortunes",
  },
  {
    symbol: "landacquired",
    category: "good_fortunes",
  },
  {
    symbol: "estateacquired",
    category: "good_fortunes",
  },
  {
    symbol: "territorysecured",
    category: "good_fortunes",
  },
  {
    symbol: "positionsecured",
    category: "good_fortunes",
  },
  {
    symbol: "seatsecured",
    category: "good_fortunes",
  },
  {
    symbol: "roleconfirmed",
    category: "good_fortunes",
  },
  {
    symbol: "promotionannounced",
    category: "good_fortunes",
  },
  {
    symbol: "positionoffered",
    category: "good_fortunes",
  },
  {
    symbol: "opportunityopens",
    category: "good_fortunes",
  },
  {
    symbol: "dooroffered",
    category: "good_fortunes",
  },
  {
    symbol: "invitationreceived",
    category: "good_fortunes",
  },
  {
    symbol: "admissiongranted",
    category: "good_fortunes",
  },
  {
    symbol: "enrollmentaccepted",
    category: "good_fortunes",
  },
  {
    symbol: "entrygranted",
    category: "good_fortunes",
  },
  {
    symbol: "accessgranted",
    category: "good_fortunes",
  },
  {
    symbol: "clearanceapproved",
    category: "good_fortunes",
  },
  {
    symbol: "permitissued",
    category: "good_fortunes",
  },
  {
    symbol: "licenseapproved",
    category: "good_fortunes",
  },
  {
    symbol: "credentialearned",
    category: "good_fortunes",
  },
  {
    symbol: "qualificationearned",
    category: "good_fortunes",
  },
  {
    symbol: "certificategranted",
    category: "good_fortunes",
  },
  {
    symbol: "degreereceived",
    category: "good_fortunes",
  },
  {
    symbol: "diplomareceived",
    category: "good_fortunes",
  },
  {
    symbol: "awardgiven",
    category: "good_fortunes",
  },
  {
    symbol: "medalearned",
    category: "good_fortunes",
  },
  {
    symbol: "trophygiven",
    category: "good_fortunes",
  },
  {
    symbol: "ribbonwon",
    category: "good_fortunes",
  },
  {
    symbol: "honorceremony",
    category: "good_fortunes",
  },
  {
    symbol: "applausegiven",
    category: "good_fortunes",
  },
  {
    symbol: "cheeringheard",
    category: "good_fortunes",
  },
  {
    symbol: "ovationgiven",
    category: "good_fortunes",
  },
  {
    symbol: "recognitionmoment",
    category: "good_fortunes",
  },
  {
    symbol: "famegained",
    category: "good_fortunes",
  },
  {
    symbol: "popularitygrows",
    category: "good_fortunes",
  },
  {
    symbol: "admirationgained",
    category: "good_fortunes",
  },
  {
    symbol: "reputationimproves",
    category: "good_fortunes",
  },
  {
    symbol: "goodwillgained",
    category: "good_fortunes",
  },
  {
    symbol: "loyaltyearned",
    category: "good_fortunes",
  },
  {
    symbol: "truststrengthens",
    category: "good_fortunes",
  },
  {
    symbol: "bonddeepens",
    category: "good_fortunes",
  },
  {
    symbol: "unitystrengthens",
    category: "good_fortunes",
  },
  {
    symbol: "harmonyreturns",
    category: "good_fortunes",
  },
  {
    symbol: "peaceachieved",
    category: "good_fortunes",
  },
  {
    symbol: "stabilityachieved",
    category: "good_fortunes",
  },
  {
    symbol: "balanceachieved",
    category: "good_fortunes",
  },
  {
    symbol: "orderrestored",
    category: "good_fortunes",
  },
  {
    symbol: "situationstabilized",
    category: "good_fortunes",
  },
  {
    symbol: "securityrestored",
    category: "good_fortunes",
  },
  {
    symbol: "safetyrises",
    category: "good_fortunes",
  },
  {
    symbol: "comfortreturns",
    category: "good_fortunes",
  },
  {
    symbol: "healthimproves",
    category: "good_fortunes",
  },
  {
    symbol: "strengthreturns",
    category: "good_fortunes",
  },
  {
    symbol: "recoverycontinues",
    category: "good_fortunes",
  },
  {
    symbol: "healingprogress",
    category: "good_fortunes",
  },
  {
    symbol: "curefound",
    category: "good_fortunes",
  },
  {
    symbol: "remedyworks",
    category: "good_fortunes",
  },
  {
    symbol: "treatmentworks",
    category: "good_fortunes",
  },
  {
    symbol: "painends",
    category: "good_fortunes",
  },
  {
    symbol: "illnessends",
    category: "good_fortunes",
  },
  {
    symbol: "energyreturns",
    category: "good_fortunes",
  },
  {
    symbol: "vitalityreturns",
    category: "good_fortunes",
  },
  {
    symbol: "renewalbegins",
    category: "good_fortunes",
  },
  {
    symbol: "rebirthmoment",
    category: "good_fortunes",
  },
  {
    symbol: "transformationpositive",
    category: "good_fortunes",
  },
  {
    symbol: "breakthroughachieved",
    category: "good_fortunes",
  },
  {
    symbol: "changepositive",
    category: "good_fortunes",
  },
  {
    symbol: "growthaccelerates",
    category: "good_fortunes",
  },
  {
    symbol: "potentialrealized",
    category: "good_fortunes",
  },
  {
    symbol: "talentrevealed",
    category: "good_fortunes",
  },
  {
    symbol: "purposefound",
    category: "good_fortunes",
  },
  {
    symbol: "destinyfound",
    category: "good_fortunes",
  },
  {
    symbol: "callingfound",
    category: "good_fortunes",
  },
  {
    symbol: "pathchosen",
    category: "good_fortunes",
  },
  {
    symbol: "futurebrightens",
    category: "good_fortunes",
  },
  {
    symbol: "horizonopens",
    category: "good_fortunes",
  },
  {
    symbol: "journeybegins",
    category: "good_fortunes",
  },
  {
    symbol: "adventurebegins",
    category: "good_fortunes",
  },
  {
    symbol: "questaccepted",
    category: "good_fortunes",
  },
  {
    symbol: "missionaccepted",
    category: "good_fortunes",
  },
  {
    symbol: "goalreached",
    category: "good_fortunes",
  },
  {
    symbol: "destinationreached",
    category: "good_fortunes",
  },
  {
    symbol: "summitreached",
    category: "good_fortunes",
  },
  {
    symbol: "finishlinecrossed",
    category: "good_fortunes",
  },
  {
    symbol: "victorycelebrated",
    category: "good_fortunes",
  },
  {
    symbol: "triumphdeclared",
    category: "good_fortunes",
  },
  {
    symbol: "championrecognized",
    category: "good_fortunes",
  },
  {
    symbol: "crownawarded",
    category: "good_fortunes",
  },
  {
    symbol: "leadershipclaimed",
    category: "good_fortunes",
  },
  {
    symbol: "bannerraised",
    category: "good_fortunes",
  },
  {
    symbol: "flagraised",
    category: "good_fortunes",
  },
  {
    symbol: "victoryparade",
    category: "good_fortunes",
  },
  { symbol: "fruitful", category: "good_fortunes" },
  { symbol: "yes", category: "good_fortunes" },
  { symbol: "termination", category: "good_fortunes" },
  { symbol: "investment", category: "good_fortunes" },
  { symbol: "envy", category: "good_fortunes" },
  { symbol: "winner", category: "good_fortunes" },
  { symbol: "doom", category: "good_fortunes" },
  { symbol: "hazard", category: "good_fortunes" },
  { symbol: "rich", category: "good_fortunes" },
  { symbol: "fatiloquist", category: "good_fortunes" },
  { symbol: "stories", category: "good_fortunes" },
  { symbol: "achieved", category: "good_fortunes" },
  { symbol: "ashe", category: "good_fortunes" },
  { symbol: "clap", category: "good_fortunes" },
  { symbol: "savin", category: "good_fortunes" },
  { symbol: "capriciousness", category: "good_fortunes" },
  { symbol: "conciliation", category: "good_fortunes" },
  { symbol: "passed", category: "good_fortunes" },
  { symbol: "richness", category: "good_fortunes" },
  { symbol: "jealousy", category: "good_fortunes" },
  { symbol: "costing", category: "good_fortunes" },
  { symbol: "gravy", category: "good_fortunes" },
  { symbol: "well", category: "good_fortunes" },
  { symbol: "dedication", category: "good_fortunes" },
  { symbol: "going", category: "good_fortunes" },
  { symbol: "albatross", category: "good_fortunes" },
  { symbol: "crown", category: "good_fortunes" },
  { symbol: "assets", category: "good_fortunes" },
  { symbol: "fruition", category: "good_fortunes" },
  { symbol: "gyromancy", category: "good_fortunes" },
  { symbol: "avail", category: "good_fortunes" },
  { symbol: "project", category: "good_fortunes" },
  { symbol: "milestone", category: "good_fortunes" },
  { symbol: "rejoicing", category: "good_fortunes" },
  { symbol: "calculated", category: "good_fortunes" },
  { symbol: "cinderella", category: "good_fortunes" },
  { symbol: "divination", category: "good_fortunes" },
  { symbol: "cartomancy", category: "good_fortunes" },
  { symbol: "bravo", category: "good_fortunes" },
  { symbol: "gimme", category: "good_fortunes" },
  { symbol: "head", category: "good_fortunes" },
  { symbol: "cruel", category: "good_fortunes" },
  { symbol: "cost", category: "good_fortunes" },
  { symbol: "portion", category: "good_fortunes" },
  { symbol: "popularity", category: "good_fortunes" },
  { symbol: "devil", category: "good_fortunes" },
  { symbol: "compliments", category: "good_fortunes" },
  { symbol: "savings", category: "good_fortunes" },
  { symbol: "succesful", category: "good_fortunes" },
  { symbol: "event", category: "good_fortunes" },
  { symbol: "godspeed", category: "good_fortunes" },
  { symbol: "teller", category: "good_fortunes" },
  { symbol: "making", category: "good_fortunes" },
  { symbol: "hunters", category: "good_fortunes" },
  { symbol: "futuna", category: "good_fortunes" },
  { symbol: "sequel", category: "good_fortunes" },
  { symbol: "resources", category: "good_fortunes" },
  { symbol: "contribution", category: "good_fortunes" },
  { symbol: "hack", category: "good_fortunes" },
  { symbol: "maxim", category: "good_fortunes" },
  { symbol: "heritage", category: "good_fortunes" },
  { symbol: "congratulate", category: "good_fortunes" },
  { symbol: "misfortunes", category: "good_fortunes" },
  { symbol: "purpose", category: "good_fortunes" },
  { symbol: "desperate", category: "good_fortunes" },
  { symbol: "succeeded", category: "good_fortunes" },
  { symbol: "cent", category: "good_fortunes" },
  { symbol: "risked", category: "good_fortunes" },
  { symbol: "performance", category: "good_fortunes" },
  { symbol: "fortunetelling", category: "good_fortunes" },
  { symbol: "effort", category: "good_fortunes" },
  { symbol: "hessian", category: "good_fortunes" },
  { symbol: "successes", category: "good_fortunes" },
  { symbol: "peaking", category: "good_fortunes" },
  { symbol: "companies", category: "good_fortunes" },
  { symbol: "faring", category: "good_fortunes" },
  { symbol: "mony", category: "good_fortunes" },
  { symbol: "disadvantage", category: "good_fortunes" },
  { symbol: "fisting", category: "good_fortunes" },
  { symbol: "upcoming", category: "good_fortunes" },
  { symbol: "goal", category: "good_fortunes" },
  { symbol: "prediction", category: "good_fortunes" },
  { symbol: "accomplishments", category: "good_fortunes" },
  { symbol: "mansion", category: "good_fortunes" },
  { symbol: "merit", category: "good_fortunes" },
  { symbol: "importance", category: "good_fortunes" },
  { symbol: "save", category: "good_fortunes" },
  { symbol: "shirt", category: "good_fortunes" },
  { symbol: "bonanza", category: "good_fortunes" },
  { symbol: "profitability", category: "good_fortunes" },
  { symbol: "cookies", category: "good_fortunes" },
  { symbol: "moolah", category: "good_fortunes" },
  { symbol: "billboard", category: "good_fortunes" },
  { symbol: "frick", category: "good_fortunes" },
  { symbol: "outcome", category: "good_fortunes" },
  { symbol: "score", category: "good_fortunes" },
  { symbol: "reproductive", category: "good_fortunes" },
  { symbol: "flourishing", category: "good_fortunes" },
  { symbol: "comeback", category: "good_fortunes" },
  { symbol: "better", category: "good_fortunes" },
  { symbol: "break", category: "good_fortunes" },
  { symbol: "get", category: "good_fortunes" },
  { symbol: "gamester", category: "good_fortunes" },
  { symbol: "big", category: "good_fortunes" },
  { symbol: "upswing", category: "good_fortunes" },
  { symbol: "fortuna", category: "good_fortunes" },
  { symbol: "apex", category: "good_fortunes" },
  { symbol: "tarot", category: "good_fortunes" },
  { symbol: "misspend", category: "good_fortunes" },
  { symbol: "inflation", category: "good_fortunes" },
  { symbol: "gambled", category: "good_fortunes" },
  { symbol: "preferring", category: "good_fortunes" },
  { symbol: "casted", category: "good_fortunes" },
  { symbol: "ceo", category: "good_fortunes" },
  { symbol: "lubricity", category: "good_fortunes" },
  { symbol: "hopeful", category: "good_fortunes" },
  { symbol: "reaching", category: "good_fortunes" },
  { symbol: "inauspicious", category: "good_fortunes" },
  { symbol: "pittance", category: "good_fortunes" },
  { symbol: "thriving", category: "good_fortunes" },
  { symbol: "succeeds", category: "good_fortunes" },
  { symbol: "welcoming", category: "good_fortunes" },
  { symbol: "certain", category: "good_fortunes" },
  { symbol: "cheering", category: "good_fortunes" },
  { symbol: "eminence", category: "good_fortunes" },
  { symbol: "penny", category: "good_fortunes" },
  { symbol: "begrudge", category: "good_fortunes" },
  { symbol: "selfimprovement", category: "good_fortunes" },
  { symbol: "empire", category: "good_fortunes" },
  { symbol: "disaster", category: "good_fortunes" },
  { symbol: "card", category: "good_fortunes" },
  { symbol: "blockbuster", category: "good_fortunes" },
  { symbol: "operation", category: "good_fortunes" },
  { symbol: "contingent", category: "good_fortunes" },
  { symbol: "godsend", category: "good_fortunes" },
  { symbol: "quitting", category: "good_fortunes" },
  { symbol: "bombing", category: "good_fortunes" },
  { symbol: "peaked", category: "good_fortunes" },
  { symbol: "fate", category: "good_fortunes" },
  { symbol: "high", category: "good_fortunes" },
  { symbol: "fist", category: "good_fortunes" },
  { symbol: "issue", category: "good_fortunes" },
  { symbol: "capital", category: "good_fortunes" },
  { symbol: "work", category: "good_fortunes" },
  { symbol: "adventurer", category: "good_fortunes" },
  { symbol: "persistence", category: "good_fortunes" },
  { symbol: "megabucks", category: "good_fortunes" },
  { symbol: "fortunize", category: "good_fortunes" },
  { symbol: "efficiencies", category: "good_fortunes" },
  { symbol: "mission", category: "good_fortunes" },
  { symbol: "downgraded", category: "good_fortunes" },
  { symbol: "effective", category: "good_fortunes" },
  { symbol: "pile", category: "good_fortunes" },
  { symbol: "inc", category: "good_fortunes" },
  { symbol: "promotability", category: "good_fortunes" },
  { symbol: "aspirational", category: "good_fortunes" },
  { symbol: "pride", category: "good_fortunes" },
  { symbol: "efficiency", category: "good_fortunes" },
  { symbol: "bring", category: "good_fortunes" },
  { symbol: "successfully", category: "good_fortunes" },
  { symbol: "worth", category: "good_fortunes" },
  { symbol: "expedience", category: "good_fortunes" },
  { symbol: "accomplishing", category: "good_fortunes" },
  { symbol: "longevity", category: "good_fortunes" },
  { symbol: "piles", category: "good_fortunes" },
  { symbol: "succession", category: "good_fortunes" },
  { symbol: "track", category: "good_fortunes" },
  { symbol: "cos", category: "good_fortunes" },
  { symbol: "lucky", category: "good_fortunes" },
  { symbol: "squandering", category: "good_fortunes" },
  { symbol: "cash", category: "good_fortunes" },
  { symbol: "complaint", category: "good_fortunes" },
  { symbol: "intention", category: "good_fortunes" },
  { symbol: "esteem", category: "good_fortunes" },
  { symbol: "esp", category: "good_fortunes" },
  { symbol: "astor", category: "good_fortunes" },
  { symbol: "duckets", category: "good_fortunes" },
  { symbol: "asset", category: "good_fortunes" },
  { symbol: "felicitation", category: "good_fortunes" },
  { symbol: "nonstarter", category: "good_fortunes" },
  { symbol: "results", category: "good_fortunes" },
  { symbol: "done", category: "good_fortunes" },
  { symbol: "wheel", category: "good_fortunes" },
  { symbol: "loeb", category: "good_fortunes" },
  { symbol: "doomed", category: "good_fortunes" },
  { symbol: "thanks", category: "good_fortunes" },
  { symbol: "constellation", category: "good_fortunes" },
  { symbol: "poorhouse", category: "good_fortunes" },
  { symbol: "bomb", category: "good_fortunes" },
  { symbol: "foom", category: "good_fortunes" },
  { symbol: "weal", category: "good_fortunes" },
  { symbol: "vantage", category: "good_fortunes" },
  { symbol: "limo", category: "good_fortunes" },
  { symbol: "fruits", category: "good_fortunes" },
  { symbol: "spending", category: "good_fortunes" },
  { symbol: "career", category: "good_fortunes" },
  { symbol: "foretelling", category: "good_fortunes" },
  { symbol: "achieving", category: "good_fortunes" },
  { symbol: "heiress", category: "good_fortunes" },
  { symbol: "feat", category: "good_fortunes" },
  { symbol: "forward", category: "good_fortunes" },
  { symbol: "astrologer", category: "good_fortunes" },
  { symbol: "calamity", category: "good_fortunes" },
  { symbol: "fruit", category: "good_fortunes" },
  { symbol: "inherited", category: "good_fortunes" },
  { symbol: "hap", category: "good_fortunes" },
  { symbol: "adaptability", category: "good_fortunes" },
  { symbol: "dosh", category: "good_fortunes" },
  { symbol: "landscape", category: "good_fortunes" },
  { symbol: "dependable", category: "good_fortunes" },
  { symbol: "cast", category: "good_fortunes" },
  { symbol: "strategy", category: "good_fortunes" },
  { symbol: "luckless", category: "good_fortunes" },
  { symbol: "bandwagon", category: "good_fortunes" },
  { symbol: "availing", category: "good_fortunes" },
  { symbol: "cunningman", category: "good_fortunes" },
  { symbol: "notoriety", category: "good_fortunes" },
  { symbol: "achiever", category: "good_fortunes" },
  { symbol: "profitted", category: "good_fortunes" },
  { symbol: "bacon", category: "good_fortunes" },
  { symbol: "bundle", category: "good_fortunes" },
  { symbol: "sum", category: "good_fortunes" },
  { symbol: "prolificness", category: "good_fortunes" },
  { symbol: "consistency", category: "good_fortunes" },
  { symbol: "ease", category: "good_fortunes" },
  { symbol: "denominator", category: "good_fortunes" },
  { symbol: "expectation", category: "good_fortunes" },
  { symbol: "effectiveness", category: "good_fortunes" },
  { symbol: "ascendancy", category: "good_fortunes" },
  { symbol: "luce", category: "good_fortunes" },
  { symbol: "carpetbag", category: "good_fortunes" },
  { symbol: "chopped", category: "good_fortunes" },
  { symbol: "property", category: "good_fortunes" },
  { symbol: "risking", category: "good_fortunes" },
  { symbol: "glory", category: "good_fortunes" },
  { symbol: "hits", category: "good_fortunes" },
  { symbol: "accomplish", category: "good_fortunes" },
  { symbol: "plight", category: "good_fortunes" },
  { symbol: "point", category: "good_fortunes" },
  { symbol: "lifetime", category: "good_fortunes" },
  { symbol: "conquest", category: "good_fortunes" },
  { symbol: "upshot", category: "good_fortunes" },
  { symbol: "benefactor", category: "good_fortunes" },
  { symbol: "baf", category: "good_fortunes" },
  { symbol: "lines", category: "good_fortunes" },
  { symbol: "action", category: "good_fortunes" },
  { symbol: "qualifying", category: "good_fortunes" },
  { symbol: "outcoming", category: "good_fortunes" },
  { symbol: "feast", category: "good_fortunes" },
  { symbol: "achieve", category: "good_fortunes" },
  { symbol: "lake", category: "good_fortunes" },
  { symbol: "bliss", category: "good_fortunes" },
  { symbol: "likely", category: "good_fortunes" },
  { symbol: "auspice", category: "good_fortunes" },
  { symbol: "selling", category: "good_fortunes" },
  { symbol: "wretchedness", category: "good_fortunes" },
  { symbol: "downgrade", category: "good_fortunes" },
  { symbol: "aspiration", category: "good_fortunes" },
  { symbol: "ambitiousness", category: "good_fortunes" },
  { symbol: "opulence", category: "good_fortunes" },
  { symbol: "carpetbagger", category: "good_fortunes" },
  { symbol: "cope", category: "good_fortunes" },
  { symbol: "confident", category: "good_fortunes" },
  { symbol: "fair", category: "good_fortunes" },
  { symbol: "greatness", category: "good_fortunes" },
  { symbol: "impact", category: "good_fortunes" },
  { symbol: "ambitious", category: "good_fortunes" },
  { symbol: "firms", category: "good_fortunes" },
  { symbol: "exult", category: "good_fortunes" },
  { symbol: "task", category: "good_fortunes" },
  { symbol: "attainment", category: "good_fortunes" },
  { symbol: "satisfactory", category: "good_fortunes" },
  { symbol: "target", category: "good_fortunes" },
  { symbol: "optimum", category: "good_fortunes" },
  { symbol: "probable", category: "good_fortunes" },
  { symbol: "decay", category: "good_fortunes" },
  { symbol: "adventuring", category: "good_fortunes" },
  { symbol: "extraordinaire", category: "good_fortunes" },
  { symbol: "exultation", category: "good_fortunes" },
  { symbol: "right", category: "good_fortunes" },
  { symbol: "kismet", category: "good_fortunes" },
  { symbol: "predictable", category: "good_fortunes" },
  { symbol: "cinch", category: "good_fortunes" },
  { symbol: "successfulness", category: "good_fortunes" },
  { symbol: "tellers", category: "good_fortunes" },
  { symbol: "serendipity", category: "good_fortunes" },
  { symbol: "reverse", category: "good_fortunes" },
  { symbol: "bunce", category: "good_fortunes" },
  { symbol: "magazine", category: "good_fortunes" },
  { symbol: "platinum", category: "good_fortunes" },
  { symbol: "distance", category: "good_fortunes" },
  { symbol: "vicissitude", category: "good_fortunes" },
  { symbol: "devious", category: "good_fortunes" },
  { symbol: "sortie", category: "good_fortunes" },
  { symbol: "treasury", category: "good_fortunes" },
  { symbol: "providence", category: "good_fortunes" },
  { symbol: "forewit", category: "good_fortunes" },
  { symbol: "culmination", category: "good_fortunes" },
  { symbol: "coattail", category: "good_fortunes" },
  { symbol: "bankroll", category: "good_fortunes" },
  { symbol: "destiny", category: "good_fortunes" },
  { symbol: "attaining", category: "good_fortunes" },
  { symbol: "enthusiasm", category: "good_fortunes" },
  { symbol: "bankable", category: "good_fortunes" },
  { symbol: "efforts", category: "good_fortunes" },
  { symbol: "fortunate", category: "good_fortunes" },
  { symbol: "bucks", category: "good_fortunes" },
  { symbol: "lakshmi", category: "good_fortunes" },
  { symbol: "malignant", category: "good_fortunes" },
  { symbol: "cheers", category: "good_fortunes" },
  { symbol: "billion", category: "good_fortunes" },
  { symbol: "acclaim", category: "good_fortunes" },
  { symbol: "marker", category: "good_fortunes" },
  { symbol: "wow", category: "good_fortunes" },
  { symbol: "capstone", category: "good_fortunes" },
  { symbol: "charts", category: "good_fortunes" },
  { symbol: "defeat", category: "good_fortunes" },
  { symbol: "circumstances", category: "good_fortunes" },
  { symbol: "multimillions", category: "good_fortunes" },
  { symbol: "beachhead", category: "good_fortunes" },
  { symbol: "livelihood", category: "good_fortunes" },
  { symbol: "gracefulness", category: "good_fortunes" },
  { symbol: "close", category: "good_fortunes" },
  { symbol: "lots", category: "good_fortunes" },
  { symbol: "wish", category: "good_fortunes" },
  { symbol: "product", category: "good_fortunes" },
  { symbol: "outlay", category: "good_fortunes" },
  { symbol: "chances", category: "good_fortunes" },
  { symbol: "congratulation", category: "good_fortunes" },
  { symbol: "luckiness", category: "good_fortunes" },
  { symbol: "accord", category: "good_fortunes" },
  { symbol: "graces", category: "good_fortunes" },
  { symbol: "investments", category: "good_fortunes" },
  { symbol: "having", category: "good_fortunes" },
  { symbol: "wealthy", category: "good_fortunes" },
  { symbol: "perseverence", category: "good_fortunes" },
  { symbol: "aesthetic", category: "good_fortunes" },
  { symbol: "demise", category: "good_fortunes" },
  { symbol: "conclusive", category: "good_fortunes" },
  { symbol: "considering", category: "good_fortunes" },
  { symbol: "lowness", category: "good_fortunes" },
  { symbol: "ahead", category: "good_fortunes" },
  { symbol: "investing", category: "good_fortunes" },
  { symbol: "risktaking", category: "good_fortunes" },
  { symbol: "devout", category: "good_fortunes" },
  { symbol: "catastrophe", category: "good_fortunes" },
  { symbol: "foresense", category: "good_fortunes" },
  { symbol: "coup", category: "good_fortunes" },
  { symbol: "disadvantageous", category: "good_fortunes" },
  { symbol: "forehand", category: "good_fortunes" },
  { symbol: "disadvantaged", category: "good_fortunes" },
  { symbol: "ability", category: "good_fortunes" },
  { symbol: "profited", category: "good_fortunes" },
  { symbol: "spare", category: "good_fortunes" },
  { symbol: "grubstake", category: "good_fortunes" },
  { symbol: "countenance", category: "good_fortunes" },
  { symbol: "inevitable", category: "good_fortunes" },
  { symbol: "prospect", category: "good_fortunes" },
  { symbol: "millionaire", category: "good_fortunes" },
  { symbol: "carry", category: "good_fortunes" },
  { symbol: "unsuccessful", category: "good_fortunes" },
  { symbol: "participation", category: "good_fortunes" },
  { symbol: "fuk", category: "good_fortunes" },
  { symbol: "positive", category: "good_fortunes" },
  { symbol: "result", category: "good_fortunes" },
  { symbol: "spend", category: "good_fortunes" },
  { symbol: "closing", category: "good_fortunes" },
  { symbol: "misery", category: "good_fortunes" },
  { symbol: "smooth", category: "good_fortunes" },
  { symbol: "born", category: "good_fortunes" },
  { symbol: "besteading", category: "good_fortunes" },
  { symbol: "object", category: "good_fortunes" },
  { symbol: "coalition", category: "good_fortunes" },
  { symbol: "bang", category: "good_fortunes" },
  { symbol: "achievements", category: "good_fortunes" },
  { symbol: "deify", category: "good_fortunes" },
  { symbol: "frown", category: "good_fortunes" },
  { symbol: "expense", category: "good_fortunes" },
  { symbol: "chequered", category: "good_fortunes" },
  { symbol: "succeeding", category: "good_fortunes" },
  { symbol: "unsuccess", category: "good_fortunes" },
  { symbol: "milliary", category: "good_fortunes" },
  { symbol: "sibyl", category: "good_fortunes" },
  { symbol: "profiting", category: "good_fortunes" },
  { symbol: "clients", category: "good_fortunes" },
  { symbol: "competitive", category: "good_fortunes" },
  { symbol: "viability", category: "good_fortunes" },
  { symbol: "fortuitously", category: "good_fortunes" },
  { symbol: "bootless", category: "good_fortunes" },
  { symbol: "bak", category: "good_fortunes" },
  { symbol: "jeopardy", category: "good_fortunes" },
  { symbol: "plan", category: "good_fortunes" },
  { symbol: "edu", category: "good_fortunes" },
  { symbol: "dime", category: "good_fortunes" },
  { symbol: "considered", category: "good_fortunes" },
  { symbol: "advance", category: "good_fortunes" },
  { symbol: "tycoon", category: "good_fortunes" },
  { symbol: "promising", category: "good_fortunes" },
  { symbol: "geloscopy", category: "good_fortunes" },
  { symbol: "suit", category: "good_fortunes" },
  { symbol: "mercenary", category: "good_fortunes" },
  { symbol: "cut", category: "good_fortunes" },
  { symbol: "natural", category: "good_fortunes" },
  { symbol: "failure", category: "good_fortunes" },
  { symbol: "pennies", category: "good_fortunes" },
  { symbol: "proceeding", category: "good_fortunes" },
  { symbol: "efficacy", category: "good_fortunes" },
  { symbol: "bad", category: "good_fortunes" },
  { symbol: "breast", category: "good_fortunes" },
  { symbol: "coming", category: "good_fortunes" },
  { symbol: "walk", category: "good_fortunes" },
  { symbol: "ruin", category: "good_fortunes" },
  { symbol: "guarantee", category: "good_fortunes" },
  { symbol: "privilege", category: "good_fortunes" },
  { symbol: "succeed", category: "good_fortunes" },
  { symbol: "boon", category: "good_fortunes" },
  { symbol: "chirosophist", category: "good_fortunes" },
  { symbol: "saving", category: "good_fortunes" },
  { symbol: "back", category: "good_fortunes" },
  { symbol: "lucre", category: "good_fortunes" },
  { symbol: "pelf", category: "good_fortunes" },
  { symbol: "ambition", category: "good_fortunes" },
  { symbol: "guerdon", category: "good_fortunes" },
  { symbol: "popular", category: "good_fortunes" },
  { symbol: "fortuneless", category: "good_fortunes" },
  { symbol: "smash", category: "good_fortunes" },
  { symbol: "felicity", category: "good_fortunes" },
  { symbol: "cookie", category: "good_fortunes" },
  { symbol: "effect", category: "good_fortunes" },
  { symbol: "disappointment", category: "good_fortunes" },
  { symbol: "betide", category: "good_fortunes" },
  { symbol: "desirable", category: "good_fortunes" },
  { symbol: "creature", category: "good_fortunes" },
  { symbol: "udas", category: "good_fortunes" },
  { symbol: "great", category: "good_fortunes" },
  { symbol: "felicitous", category: "good_fortunes" },
  { symbol: "chancing", category: "good_fortunes" },
  { symbol: "gamble", category: "good_fortunes" },
  { symbol: "clairvoyant", category: "good_fortunes" },
  { symbol: "laugh", category: "good_fortunes" },
  { symbol: "capacity", category: "good_fortunes" },
  { symbol: "involvement", category: "good_fortunes" },
  { symbol: "aiken", category: "good_fortunes" },
  { symbol: "corp", category: "good_fortunes" },
  { symbol: "mantology", category: "good_fortunes" },
  { symbol: "gong", category: "good_fortunes" },
  { symbol: "choo", category: "good_fortunes" },
  { symbol: "story", category: "good_fortunes" },
  { symbol: "choice", category: "good_fortunes" },
  { symbol: "ambitionless", category: "good_fortunes" },
  { symbol: "speed", category: "good_fortunes" },
  { symbol: "pass", category: "good_fortunes" },
  { symbol: "physiognomy", category: "good_fortunes" },
  { symbol: "fook", category: "good_fortunes" },
  { symbol: "bafflement", category: "good_fortunes" },
  { symbol: "beneficial", category: "good_fortunes" },
  { symbol: "future", category: "good_fortunes" },
  { symbol: "deserving", category: "good_fortunes" },
  { symbol: "passing", category: "good_fortunes" },
  { symbol: "heir", category: "good_fortunes" },
  { symbol: "miser", category: "good_fortunes" },
  { symbol: "headway", category: "good_fortunes" },
  { symbol: "delusion", category: "good_fortunes" },
  { symbol: "happily", category: "good_fortunes" },
  { symbol: "demimonde", category: "good_fortunes" },
  { symbol: "cheung", category: "good_fortunes" },
  { symbol: "affluence", category: "good_fortunes" },
  { symbol: "boatload", category: "good_fortunes" },
  { symbol: "lucks", category: "good_fortunes" },
  { symbol: "brands", category: "good_fortunes" },
  { symbol: "diploma", category: "good_fortunes" },
  { symbol: "moola", category: "good_fortunes" },
  { symbol: "lead", category: "good_fortunes" },
  { symbol: "gambling", category: "good_fortunes" },
  { symbol: "buster", category: "good_fortunes" },
  { symbol: "confirmation", category: "good_fortunes" },
  { symbol: "good", category: "good_fortunes" },
  { symbol: "max", category: "good_fortunes" },
  { symbol: "failures", category: "good_fortunes" },
  { symbol: "gobs", category: "good_fortunes" },
  { symbol: "ill", category: "good_fortunes" },
  { symbol: "decaying", category: "good_fortunes" },
  { symbol: "dice", category: "good_fortunes" },
  { symbol: "careerist", category: "good_fortunes" },
  { symbol: "supremacy", category: "good_fortunes" },
  { symbol: "prognostic", category: "good_fortunes" },
  { symbol: "surety", category: "good_fortunes" },
  { symbol: "clapping", category: "good_fortunes" },
  { symbol: "loss", category: "good_fortunes" },
  { symbol: "promise", category: "good_fortunes" },
  { symbol: "breeding", category: "good_fortunes" },
  { symbol: "prodigally", category: "good_fortunes" },
  { symbol: "edit", category: "good_fortunes" },
  { symbol: "thrive", category: "good_fortunes" },
  { symbol: "boom", category: "good_fortunes" },
  { symbol: "fare", category: "good_fortunes" },
  { symbol: "prompted", category: "good_fortunes" },
  { symbol: "blessed", category: "good_fortunes" },
  { symbol: "squander", category: "good_fortunes" },
  { symbol: "fame", category: "good_fortunes" },
  { symbol: "life", category: "good_fortunes" },
  { symbol: "grossing", category: "good_fortunes" },
  { symbol: "profits", category: "good_fortunes" },
  { symbol: "best", category: "good_fortunes" },
  { symbol: "conclusion", category: "good_fortunes" },
  { symbol: "yeah", category: "good_fortunes" },
  { symbol: "worthy", category: "good_fortunes" },
  { symbol: "bsd", category: "good_fortunes" },
  { symbol: "showing", category: "good_fortunes" },
  { symbol: "frugal", category: "good_fortunes" },
  { symbol: "mint", category: "good_fortunes" },
  { symbol: "lucking", category: "good_fortunes" },
  { symbol: "wasting", category: "good_fortunes" },
  { symbol: "squandered", category: "good_fortunes" },
  { symbol: "amass", category: "good_fortunes" },
  { symbol: "spent", category: "good_fortunes" },
  { symbol: "package", category: "good_fortunes" },
  { symbol: "mark", category: "good_fortunes" },
  { symbol: "alger", category: "good_fortunes" },
  { symbol: "lot", category: "good_fortunes" },
  { symbol: "omen", category: "good_fortunes" },
  { symbol: "marry", category: "good_fortunes" },
  { symbol: "hit", category: "good_fortunes" },
  { symbol: "means", category: "good_fortunes" },
  { symbol: "occasion", category: "good_fortunes" },
  { symbol: "auspicious", category: "good_fortunes" },
  { symbol: "decided", category: "good_fortunes" },
  { symbol: "sink", category: "good_fortunes" },
  { symbol: "possible", category: "good_fortunes" },
  { symbol: "bombe", category: "good_fortunes" },
  { symbol: "outcomes", category: "good_fortunes" },
  { symbol: "clicking", category: "good_fortunes" },
  { symbol: "boffo", category: "good_fortunes" },
  { symbol: "congratulatory", category: "good_fortunes" },
  { symbol: "chart", category: "good_fortunes" },
  { symbol: "oncome", category: "good_fortunes" },
  { symbol: "stake", category: "good_fortunes" },
  { symbol: "hand", category: "good_fortunes" },
  { symbol: "triumphs", category: "good_fortunes" },
  { symbol: "made", category: "good_fortunes" },
  { symbol: "multimillionaire", category: "good_fortunes" },
  { symbol: "invest", category: "good_fortunes" },
  { symbol: "ane", category: "good_fortunes" },
  { symbol: "smoothly", category: "good_fortunes" },
  { symbol: "correct", category: "good_fortunes" },
  { symbol: "attain", category: "good_fortunes" },
  { symbol: "lightning", category: "good_fortunes" },
  { symbol: "findings", category: "good_fortunes" },
  { symbol: "defeated", category: "good_fortunes" },
  { symbol: "downgrading", category: "good_fortunes" },
  { symbol: "aspect", category: "good_fortunes" },
  { symbol: "careerism", category: "good_fortunes" },
  { symbol: "congratulations", category: "good_fortunes" },
  { symbol: "coot", category: "good_fortunes" },
  { symbol: "reversal", category: "good_fortunes" },
  { symbol: "victories", category: "good_fortunes" },
  { symbol: "excellence", category: "good_fortunes" },
  { symbol: "mischance", category: "good_fortunes" },
  { symbol: "enjoyment", category: "good_fortunes" },
  { symbol: "millionairess", category: "good_fortunes" },
  { symbol: "prestige", category: "good_fortunes" },
  { symbol: "arrive", category: "good_fortunes" },
  { symbol: "idea", category: "good_fortunes" },
  { symbol: "fortunately", category: "good_fortunes" },
  { symbol: "infelicity", category: "good_fortunes" },
  { symbol: "victoire", category: "good_fortunes" },
  { symbol: "goodness", category: "good_fortunes" },
  { symbol: "hing", category: "good_fortunes" },
  { symbol: "copying", category: "good_fortunes" },
  { symbol: "day", category: "good_fortunes" },
  { symbol: "priority", category: "good_fortunes" },
  { symbol: "sort", category: "good_fortunes" },
  { symbol: "trouble", category: "good_fortunes" },
  { symbol: "dame", category: "good_fortunes" },
  { symbol: "accident", category: "good_fortunes" },
  { symbol: "advances", category: "good_fortunes" },
  { symbol: "fluke", category: "good_fortunes" },
  { symbol: "happen", category: "good_fortunes" },
  { symbol: "chaldean", category: "good_fortunes" },
  { symbol: "experience", category: "good_fortunes" },
  { symbol: "spot", category: "good_fortunes" },
  { symbol: "paying", category: "good_fortunes" },
  { symbol: "come", category: "good_fortunes" },
  { symbol: "forbes", category: "good_fortunes" },
  { symbol: "answering", category: "good_fortunes" },
  { symbol: "luckily", category: "good_fortunes" },
  { symbol: "ace", category: "good_fortunes" },
  { symbol: "assure", category: "good_fortunes" },
  { symbol: "click", category: "good_fortunes" },
  { symbol: "lay", category: "good_fortunes" },
  { symbol: "kung", category: "good_fortunes" },
  { symbol: "estate", category: "good_fortunes" },
  { symbol: "finish", category: "good_fortunes" },
  { symbol: "mone", category: "good_fortunes" },
  { symbol: "checkered", category: "good_fortunes" },
  { symbol: "singles", category: "good_fortunes" },
  { symbol: "march", category: "good_fortunes" },
  { symbol: "rate", category: "good_fortunes" },
  { symbol: "misfortune", category: "good_fortunes" },
  { symbol: "fatidic", category: "good_fortunes" },
  { symbol: "thankability", category: "good_fortunes" },
  { symbol: "ample", category: "good_fortunes" },
  { symbol: "wasted", category: "good_fortunes" },
  { symbol: "stardom", category: "good_fortunes" },
  { symbol: "pursuit", category: "good_fortunes" },
  { symbol: "lowliness", category: "good_fortunes" },
  { symbol: "downfall", category: "good_fortunes" },
  { symbol: "adversity", category: "good_fortunes" },
  { symbol: "successful", category: "good_fortunes" },
  { symbol: "comer", category: "good_fortunes" },
  { symbol: "loser", category: "good_fortunes" },
  { symbol: "happy", category: "good_fortunes" },
  { symbol: "farthing", category: "good_fortunes" },
  { symbol: "millions", category: "good_fortunes" },
  { symbol: "closure", category: "good_fortunes" },
  { symbol: "all", category: "good_fortunes" },
  { symbol: "strike", category: "good_fortunes" },
  { symbol: "mean", category: "good_fortunes" },
  { symbol: "telling", category: "good_fortunes" },

];
