import { SingleWordSymbol } from "../dreamSingularSymbols";

export const household_symbols: SingleWordSymbol[] = [
  { symbol: "ziplock", category: "household" },
  { symbol: "faucet lever", category: "household" },
  { symbol: "faucetknob", category: "household" },
  { symbol: "broom", category: "household" },
  { symbol: "table", category: "household" },
  { symbol: "toiletbrush", category: "household" },
  { symbol: "heatlamp", category: "household" },
  { symbol: "rug", category: "household" },
  { symbol: "pillow", category: "household" },
  { symbol: "towel", category: "household" },
  { symbol: "faucethead", category: "household" },
  { symbol: "bell", category: "household" },
  { symbol: "sunlamp", category: "household" },
  { symbol: "heatsink", category: "household" },
  { symbol: "vacuumhose", category: "household" },
  { symbol: "padlock", category: "household" },
  { symbol: "footlocker", category: "household" },
  { symbol: "dishsoap", category: "household" },
  { symbol: "keyfob", category: "household" },
  { symbol: "pipe clamp", category: "household" },
  { symbol: "gamingchair", category: "household" },
  { symbol: "keyhook", category: "household" },
  { symbol: "plasticdrawer", category: "household" },
  { symbol: "sinkdrain", category: "household" },
  { symbol: "deckplate", category: "household" },
  { symbol: "bedrestraints", category: "household" },
  { symbol: "sofa", category: "household" },
  { symbol: "wallhook", category: "household" },
  { symbol: "doorhinge", category: "household" },
  { symbol: "floorlamp", category: "household" },
  { symbol: "latchplate", category: "household" },
  { symbol: "nailbrush", category: "household" },
  { symbol: "alarm keypad", category: "household" },
  { symbol: "papertowelroll", category: "household" },
  { symbol: "paperplatestack", category: "household" },
  { symbol: "carpet", category: "household" },
  { symbol: "toolboxdrawer", category: "household" },
  { symbol: "ironplate", category: "household" },
  { symbol: "filingcabinet", category: "household" },
  { symbol: "doorknob", category: "household" },
  { symbol: "boltlock", category: "household" },
  { symbol: "walloutlet", category: "household" },
  { symbol: "doorlatch", category: "household" },
  { symbol: "calculatordesk", category: "household" },
  { symbol: "doorbell", category: "household" },
  { symbol: "paperplate", category: "household" },
  { symbol: "moppad", category: "household" },
  { symbol: "toothbrushholder", category: "household" },
  { symbol: "desktray", category: "household" },
  { symbol: "plate", category: "household" },
  { symbol: "deskdrawer", category: "household" },
  { symbol: "lampbase", category: "household" },
  { symbol: "key", category: "household" },
  { symbol: "indicatorlamp", category: "household" },
  { symbol: "cabinetdoor", category: "household" },
  { symbol: "soappump", category: "household" },
  { symbol: "doorframe", category: "household" },
  { symbol: "brickwall", category: "household" },
  { symbol: "drawerunit", category: "household" },
  { symbol: "bedframe", category: "household" },
  { symbol: "drawerorganizer", category: "household" },
  { symbol: "luggagelock", category: "household" },
  { symbol: "wheellock", category: "household" },
  { symbol: "wallshelf", category: "household" },
  { symbol: "faucetsprayer", category: "household" },
  { symbol: "keyrack", category: "household" },
  { symbol: "windowhandle", category: "household" },
  { symbol: "turntable", category: "household" },
  { symbol: "handtowel", category: "household" },
  { symbol: "traytable", category: "household" },
  { symbol: "keypad", category: "household" },
  { symbol: "hairbrush", category: "household" },
  { symbol: "wallcalendar", category: "household" },
  { symbol: "curtainrod", category: "household" },
  { symbol: "paintbrush", category: "household" },
  { symbol: "pipeclamp", category: "household" },
  { symbol: "locker", category: "household" },
  { symbol: "sinkstopper", category: "household" },
  { symbol: "faucet knob", category: "household" },
  { symbol: "shelf", category: "household" },
  { symbol: "vacuumbag", category: "household" },
  { symbol: "wallet", category: "household" },
  { symbol: "fittingroom", category: "household" },
  { symbol: "pantryshelf", category: "household" },
  { symbol: "mop", category: "household" },
  { symbol: "clock", category: "household" },
  { symbol: "throwpillow", category: "household" },
  { symbol: "woodblock", category: "household" },
  { symbol: "soapbar", category: "household" },
  { symbol: "alarmclock", category: "household" },
  { symbol: "deckchair", category: "household" },
  { symbol: "floorpanel", category: "household" },
  { symbol: "lock", category: "household" },
  { symbol: "windowblind", category: "household" },
  { symbol: "lamp", category: "household" },
  { symbol: "doorstop", category: "household" },
  { symbol: "metalplate", category: "household" },
  { symbol: "barbell", category: "household" },
  { symbol: "foglamp", category: "household" },
  { symbol: "dishtowel", category: "household" },
  { symbol: "changingroommirror", category: "household" },
  { symbol: "bed", category: "household" },
  { symbol: "deskcalendar", category: "household" },
  { symbol: "walletchain", category: "household" },
  { symbol: "foldingtable", category: "household" },
  { symbol: "gaslamp", category: "household" },
  { symbol: "keybox", category: "household" },
  { symbol: "laundrysoap", category: "household" },
  { symbol: "smartlock", category: "household" },
  { symbol: "pillowcase", category: "household" },
  { symbol: "hockeystick", category: "household" },
  { symbol: "drawerdivider", category: "household" },
  { symbol: "vacuumhead", category: "household" },
  { symbol: "bellows", category: "household" },
  { symbol: "lampshade", category: "household" },
  { symbol: "hospitalbed", category: "household" },
  { symbol: "bedpillow", category: "household" },
  { symbol: "blanket", category: "household" },
  { symbol: "makeupbrush", category: "household" },
  { symbol: "drawer", category: "household" },
  { symbol: "papertowelholder", category: "household" },
  { symbol: "doorknocker", category: "household" },
  { symbol: "toothbrush", category: "household" },
  { symbol: "block", category: "household" },
  { symbol: "vacuumseal", category: "household" },
  { symbol: "doorlock", category: "household" },
  { symbol: "towelrack", category: "household" },
  { symbol: "couch", category: "household" },
  { symbol: "lockerbench", category: "household" },
  { symbol: "broomhandle", category: "household" },
  { symbol: "bulletproofvest", category: "household" },
  { symbol: "videodoorbell", category: "household" },
  { symbol: "keyholder", category: "household" },
  { symbol: "digitalclock", category: "household" },
  { symbol: "arcadecabinet", category: "household" },
  { symbol: "showerlocker", category: "household" },
  { symbol: "brush", category: "household" },
  { symbol: "curtainhook", category: "household" },
  { symbol: "keychain", category: "household" },
  { symbol: "sandingblock", category: "household" },
  { symbol: "bedsidetray", category: "household" },
  { symbol: "storeshelflabel", category: "household" },
  { symbol: "alarmkeypad", category: "household" },
  { symbol: "artbrush", category: "household" },
  { symbol: "diffuserlamp", category: "household" },
  { symbol: "electricblanket", category: "household" },
  { symbol: "door", category: "household" },
  { symbol: "faceplate", category: "household" },
  { symbol: "locknut", category: "household" },
  { symbol: "keypadlock", category: "household" },
  { symbol: "floorvent", category: "household" },
  { symbol: "bikelock", category: "household" },
  { symbol: "lampstand", category: "household" },
  { symbol: "dustbrush", category: "household" },
  { symbol: "papertowel", category: "household" },
  { symbol: "doormat", category: "household" },
  { symbol: "faucet sprayer", category: "household" },
  { symbol: "cashdrawer", category: "household" },
  { symbol: "desk", category: "household" },
  { symbol: "neckpillow", category: "household" },
  { symbol: "dishsoapbottle", category: "household" },
  { symbol: "vacuumfilter", category: "household" },
  { symbol: "mophead", category: "household" },
  { symbol: "soapdispenser", category: "household" },
  { symbol: "soapbottle", category: "household" },
  { symbol: "deskorganizer", category: "household" },
  { symbol: "bellring", category: "household" },
  { symbol: "windowframe", category: "household" },
  { symbol: "wallclock", category: "household" },
  { symbol: "windowcrank", category: "household" },
  { symbol: "kettlebell", category: "household" },
  { symbol: "floormat", category: "household" },
  { symbol: "travelpillow", category: "household" },
  { symbol: "bedsheet", category: "household" },
  { symbol: "soap", category: "household" },
  { symbol: "showercurtain", category: "household" },
  { symbol: "window", category: "household" },
  { symbol: "faucet", category: "household" },
  { symbol: "paper towel", category: "household" },
  { symbol: "cardwallet", category: "household" },
  { symbol: "vacuum", category: "household" },
  { symbol: "wheelchair", category: "household" },
  { symbol: "shelfunit", category: "household" },
  { symbol: "hoseclamp", category: "household" },
  { symbol: "cabinet", category: "household" },
  { symbol: "bookshelf", category: "household" },
  { symbol: "dishbrush", category: "household" },
  { symbol: "fittingmirror", category: "household" },
  { symbol: "lockerkey", category: "household" },
  { symbol: "sink stopper", category: "household" },
  { symbol: "sink", category: "household" },
  { symbol: "pooltable", category: "household" },
  { symbol: "doorhandle", category: "household" },
  { symbol: "mopbucket", category: "household" },
  { symbol: "foldingchair", category: "household" },
  { symbol: "bedtray", category: "household" },
  { symbol: "roofrack", category: "household" },
  { symbol: "spotlightlamp", category: "household" },
  { symbol: "bellframe", category: "household" },
  { symbol: "bedsidelamp", category: "household" },
  { symbol: "lockerroommirror", category: "household" },
  { symbol: "broomstick", category: "household" },
  { symbol: "doorstopper", category: "household" },
  { symbol: "writingdesk", category: "household" },
  { symbol: "desklamp", category: "household" },
  { symbol: "timerclock", category: "household" },
  { symbol: "kitchenware", category: "household" },
  { symbol: "coverplate", category: "household" },
  { symbol: "straplock", category: "household" },
  { symbol: "kitchenscale", category: "household" },
  { symbol: "carvacuum", category: "household" },
  { symbol: "dumbbell", category: "household" },
  { symbol: "lovepillow", category: "household" },
  { symbol: "eraserblock", category: "household" },
  { symbol: "hingeplate", category: "household" },
  { symbol: "deskclock", category: "household" },
  { symbol: "clamp", category: "household" },
  { symbol: "headlamp", category: "household" },
  { symbol: "tablecloth", category: "household" },
  { symbol: "blastdoor", category: "household" },
  { symbol: "doorchain", category: "household" },
  { symbol: "wall", category: "household" },
  { symbol: "tablefork", category: "household" },
  { symbol: "kitchentowel", category: "household" },
  { symbol: "deskfan", category: "household" },
  { symbol: "windowlatch", category: "household" },
  { symbol: "sinkstrainer", category: "household" },
  { symbol: "walletcard", category: "household" },
  { symbol: "mirror", category: "household" },
  { symbol: "tablelamp", category: "household" },
  { symbol: "kitchentimer", category: "household" },
  { symbol: "deskpad", category: "household" },
  { symbol: "chargingblock", category: "household" },
  { symbol: "fireproofsafe", category: "household" },
  { symbol: "pulleyblock", category: "household" },
  { symbol: "nippleclamps", category: "household" },
  { symbol: "faucetlever", category: "household" },
  { symbol: "curtain", category: "household" },
  { symbol: "doorpanel", category: "household" },
  { symbol: "makeupmirror", category: "household" },
  { symbol: "gardenbed", category: "household" },
  { symbol: "lockbox", category: "household" },
  { symbol: "weightplate", category: "household" },
  { symbol: "carpetroller", category: "household" },
  { symbol: "guardplate", category: "household" },
  { symbol: "towelholder", category: "household" },
  { symbol: "shelfdivider", category: "household" },
  { symbol: "drawerliner", category: "household" },
  { symbol: "lintbrush", category: "household" },
  { symbol: "mirrorframe", category: "household" },
  { symbol: "chair", category: "household" },
  { symbol: "loveseat", category: "household" },
  { symbol: "armchair", category: "household" },
  { symbol: "recliner", category: "household" },
  { symbol: "rocking chair", category: "household" },
  { symbol: "stool", category: "household" },
  { symbol: "bench", category: "household" },
  { symbol: "ottoman", category: "household" },
  { symbol: "coffee table", category: "household" },
  { symbol: "side table", category: "household" },
  { symbol: "end table", category: "household" },
  { symbol: "dining table", category: "household" },
  { symbol: "kitchen table", category: "household" },
  { symbol: "nightstand", category: "household" },
  { symbol: "dresser", category: "household" },
  { symbol: "wardrobe", category: "household" },
  { symbol: "cupboard", category: "household" },
  { symbol: "bookcase", category: "household" },
  { symbol: "display cabinet", category: "household" },
  { symbol: "china cabinet", category: "household" },
  { symbol: "tv stand", category: "household" },
  { symbol: "media console", category: "household" },
  { symbol: "storage bench", category: "household" },
  { symbol: "shoe bench", category: "household" },
  { symbol: "coat rack", category: "household" },
  { symbol: "clothes rack", category: "household" },
  { symbol: "hat rack", category: "household" },
  { symbol: "umbrella stand", category: "household" },
  { symbol: "full mirror", category: "household" },
  { symbol: "wall mirror", category: "household" },
  { symbol: "floor mirror", category: "household" },
  { symbol: "picture frame", category: "household" },
  { symbol: "photo frame", category: "household" },
  { symbol: "wall clock", category: "household" },
  { symbol: "alarm clock", category: "household" },
  { symbol: "digital clock", category: "household" },
  { symbol: "table lamp", category: "household" },
  { symbol: "floor lamp", category: "household" },
  { symbol: "desk lamp", category: "household" },
  { symbol: "lamp shade", category: "household" },
  { symbol: "light bulb", category: "household" },
  { symbol: "ceiling light", category: "household" },
  { symbol: "chandelier", category: "household" },
  { symbol: "pendant light", category: "household" },
  { symbol: "light fixture", category: "household" },
  { symbol: "wall sconce", category: "household" },
  { symbol: "string lights", category: "household" },
  { symbol: "led strip", category: "household" },
  { symbol: "extension cord", category: "household" },
  { symbol: "power strip", category: "household" },
  { symbol: "surge protector", category: "household" },
  { symbol: "wall outlet", category: "household" },
  { symbol: "outlet cover", category: "household" },
  { symbol: "light switch", category: "household" },
  { symbol: "switch plate", category: "household" },
  { symbol: "door knob", category: "household" },
  { symbol: "door handle", category: "household" },
  { symbol: "door hinge", category: "household" },
  { symbol: "door stopper", category: "household" },
  { symbol: "door chain", category: "household" },
  { symbol: "door latch", category: "household" },
  { symbol: "door mat", category: "household" },
  { symbol: "welcome mat", category: "household" },
  { symbol: "boot tray", category: "household" },
  { symbol: "window blind", category: "household" },
  { symbol: "window shade", category: "household" },
  { symbol: "window screen", category: "household" },
  { symbol: "curtain rod", category: "household" },
  { symbol: "curtain hook", category: "household" },
  { symbol: "curtain ring", category: "household" },
  { symbol: "curtain tieback", category: "household" },
  { symbol: "window latch", category: "household" },
  { symbol: "window crank", category: "household" },
  { symbol: "window lock", category: "household" },
  { symbol: "bed frame", category: "household" },
  { symbol: "headboard", category: "household" },
  { symbol: "mattress", category: "household" },
  { symbol: "box spring", category: "household" },
  { symbol: "throw blanket", category: "household" },
  { symbol: "comforter", category: "household" },
  { symbol: "duvet", category: "household" },
  { symbol: "duvet cover", category: "household" },
  { symbol: "bed sheet", category: "household" },
  { symbol: "fitted sheet", category: "household" },
  { symbol: "flat sheet", category: "household" },
  { symbol: "bed skirt", category: "household" },
  { symbol: "mattress topper", category: "household" },
  { symbol: "mattress cover", category: "household" },
  { symbol: "bed tray", category: "household" },
  { symbol: "bedside lamp", category: "household" },
  { symbol: "laundry basket", category: "household" },
  { symbol: "laundry hamper", category: "household" },
  { symbol: "clothes hanger", category: "household" },
  { symbol: "shoe rack", category: "household" },
  { symbol: "drawer divider", category: "household" },
  { symbol: "storage bin", category: "household" },
  { symbol: "storage box", category: "household" },
  { symbol: "storage tote", category: "household" },
  { symbol: "plastic bin", category: "household" },
  { symbol: "basket", category: "household" },
  { symbol: "wicker basket", category: "household" },
  { symbol: "organizer bin", category: "household" },
  { symbol: "drawer organizer", category: "household" },
  { symbol: "drawer liner", category: "household" },
  { symbol: "closet organizer", category: "household" },
  { symbol: "shelf divider", category: "household" },
  { symbol: "shelf organizer", category: "household" },
  { symbol: "cabinet organizer", category: "household" },
  { symbol: "underbed storage", category: "household" },
  { symbol: "tool drawer", category: "household" },
  { symbol: "file box", category: "household" },
  { symbol: "document box", category: "household" },
  { symbol: "keepsake box", category: "household" },
  { symbol: "lock box", category: "household" },
  { symbol: "safe box", category: "household" },
  { symbol: "dustpan", category: "household" },
  { symbol: "mop bucket", category: "household" },
  { symbol: "sponge", category: "household" },
  { symbol: "scrub brush", category: "household" },
  { symbol: "cleaning brush", category: "household" },
  { symbol: "duster", category: "household" },
  { symbol: "feather duster", category: "household" },
  { symbol: "cleaning cloth", category: "household" },
  { symbol: "microfiber cloth", category: "household" },
  { symbol: "paper towel holder", category: "household" },
  { symbol: "spray bottle", category: "household" },
  { symbol: "cleaning spray", category: "household" },
  { symbol: "glass cleaner", category: "household" },
  { symbol: "disinfectant spray", category: "household" },
  { symbol: "surface wipes", category: "household" },
  { symbol: "cleaning wipes", category: "household" },
  { symbol: "vacuum cleaner", category: "household" },
  { symbol: "vacuum hose", category: "household" },
  { symbol: "vacuum brush", category: "household" },
  { symbol: "vacuum filter", category: "household" },
  { symbol: "lint roller", category: "household" },
  { symbol: "trash can", category: "household" },
  { symbol: "recycle bin", category: "household" },
  { symbol: "compost bin", category: "household" },
  { symbol: "garbage bag", category: "household" },
  { symbol: "recycle bag", category: "household" },
  { symbol: "dish rack", category: "household" },
  { symbol: "drying rack", category: "household" },
  { symbol: "dish tray", category: "household" },
  { symbol: "sink strainer", category: "household" },
  { symbol: "dish sponge", category: "household" },
  { symbol: "dish brush", category: "household" },
  { symbol: "dish towel", category: "household" },
  { symbol: "dish cloth", category: "household" },
  { symbol: "paper towel roll", category: "household" },
  { symbol: "soap dispenser", category: "household" },
  { symbol: "soap pump", category: "household" },
  { symbol: "kitchen towel", category: "household" },
  { symbol: "oven mitt", category: "household" },
  { symbol: "pot holder", category: "household" },
  { symbol: "cutting board", category: "household" },
  { symbol: "food container", category: "household" },
  { symbol: "storage container", category: "household" },
  { symbol: "bread box", category: "household" },
  { symbol: "fruit bowl", category: "household" },
  { symbol: "utensil holder", category: "household" },
  { symbol: "knife block", category: "household" },
  { symbol: "spice rack", category: "household" },
  { symbol: "jar opener", category: "household" },
  { symbol: "toilet brush", category: "household" },
  { symbol: "toilet plunger", category: "household" },
  { symbol: "toilet paper holder", category: "household" },
  { symbol: "tissue box", category: "household" },
  { symbol: "soap dish", category: "household" },
  { symbol: "shower caddy", category: "household" },
  { symbol: "shower shelf", category: "household" },
  { symbol: "bath mat", category: "household" },
  { symbol: "bath towel", category: "household" },
  { symbol: "hand towel", category: "household" },
  { symbol: "wash cloth", category: "household" },
  { symbol: "toothbrush holder", category: "household" },
  { symbol: "razor holder", category: "household" },
  { symbol: "mirror cabinet", category: "household" },
  { symbol: "vase", category: "household" },
  { symbol: "plant pot", category: "household" },
  { symbol: "flower pot", category: "household" },
  { symbol: "planter", category: "household" },
  { symbol: "decor tray", category: "household" },
  { symbol: "candle holder", category: "household" },
  { symbol: "candle jar", category: "household" },
  { symbol: "incense holder", category: "household" },
  { symbol: "diffuser", category: "household" },
  { symbol: "aroma diffuser", category: "household" },
  { symbol: "decor basket", category: "household" },
  { symbol: "wall art", category: "household" },
  { symbol: "wall decor", category: "household" },
  { symbol: "sculpture", category: "household" },
  { symbol: "ornament", category: "household" },
  { symbol: "figurine", category: "household" },
  { symbol: "photo album", category: "household" },
  { symbol: "magazine rack", category: "household" },
  { symbol: "mail organizer", category: "household" },
  { symbol: "key holder", category: "household" },
  { symbol: "key rack", category: "household" },
  { symbol: "adhesive hook", category: "household" },
  { symbol: "air mattress", category: "household" },
  { symbol: "air purifier filter", category: "household" },
  { symbol: "air vent cover", category: "household" },
  { symbol: "alarm panel", category: "household" },
  { symbol: "aluminum foil", category: "household" },
  { symbol: "appliance dolly", category: "household" },
  { symbol: "appliance mat", category: "household" },
  { symbol: "area rug", category: "household" },
  { symbol: "art easel", category: "household" },
  { symbol: "ash bucket", category: "household" },
  { symbol: "ash shovel", category: "household" },
  { symbol: "ashtray stand", category: "household" },
  { symbol: "attic ladder", category: "household" },
  { symbol: "attic light", category: "household" },
  { symbol: "audio receiver", category: "household" },
  { symbol: "audio switch", category: "household" },
  { symbol: "auto feeder", category: "household" },
  { symbol: "auto litterbox", category: "household" },
  { symbol: "baby gate", category: "household" },
  { symbol: "baby monitor", category: "household" },
  { symbol: "baby swing", category: "household" },
  { symbol: "baby walker", category: "household" },
  { symbol: "baking rack", category: "household" },
  { symbol: "baking stone", category: "household" },
  { symbol: "balloon pump", category: "household" },
  { symbol: "bar cabinet", category: "household" },
  { symbol: "bar cart", category: "household" },
  { symbol: "bar stool", category: "household" },
  { symbol: "bar tray", category: "household" },
  { symbol: "bath pillow", category: "household" },
  { symbol: "bath stool", category: "household" },
  { symbol: "bath tray", category: "household" },
  { symbol: "bathrobe hook", category: "household" },
  { symbol: "battery tester", category: "household" },
  { symbol: "bed riser", category: "household" },
  { symbol: "bed rail", category: "household" },
  { symbol: "bed wedge", category: "household" },
  { symbol: "bedspread", category: "household" },
  { symbol: "bedstep", category: "household" },
  { symbol: "bell chime", category: "household" },
  { symbol: "belt hanger", category: "household" },
  { symbol: "beverage dispenser", category: "household" },
  { symbol: "bike hook", category: "household" },
  { symbol: "bike stand", category: "household" },
  { symbol: "bird cage", category: "household" },
  { symbol: "bird perch", category: "household" },
  { symbol: "blackout curtain", category: "household" },
  { symbol: "blanket ladder", category: "household" },
  { symbol: "blanket chest", category: "household" },
  { symbol: "blender jar", category: "household" },
  { symbol: "blinds wand", category: "household" },
  { symbol: "blinds valance", category: "household" },
  { symbol: "bluetooth speaker", category: "household" },
  { symbol: "board game shelf", category: "household" },
  { symbol: "boiler gauge", category: "household" },
  { symbol: "boot jack", category: "household" },
  { symbol: "boot rack", category: "household" },
  { symbol: "bottle brush", category: "household" },
  { symbol: "bottle rack", category: "household" },
  { symbol: "bottle stopper", category: "household" },
  { symbol: "bowl rack", category: "household" },
  { symbol: "bread slicer", category: "household" },
  { symbol: "bread knife", category: "household" },
  { symbol: "bread bin", category: "household" },
  { symbol: "breakfast tray", category: "household" },
  { symbol: "broom holder", category: "household" },
  { symbol: "broom rack", category: "household" },
  { symbol: "brush holder", category: "household" },
  { symbol: "bucket wringer", category: "household" },
  { symbol: "buffing pad", category: "household" },
  { symbol: "bulletin board", category: "household" },
  { symbol: "butter crock", category: "household" },
  { symbol: "butter knife", category: "household" },
  { symbol: "butter tray", category: "household" },
  { symbol: "cabinet hinge", category: "household" },
  { symbol: "cabinet latch", category: "household" },
  { symbol: "cabinet knob", category: "household" },
  { symbol: "cabinet pull", category: "household" },
  { symbol: "cabinet shelf", category: "household" },
  { symbol: "cabinet liner", category: "household" },
  { symbol: "cabinet doorstop", category: "household" },
  { symbol: "cable box", category: "household" },
  { symbol: "cable hook", category: "household" },
  { symbol: "cable sleeve", category: "household" },
  { symbol: "cable tray", category: "household" },
  { symbol: "cake carrier", category: "household" },
  { symbol: "cake dome", category: "household" },
  { symbol: "cake stand", category: "household" },
  { symbol: "calendar board", category: "household" },
  { symbol: "can crusher", category: "household" },
  { symbol: "can dispenser", category: "household" },
  { symbol: "can rack", category: "household" },
  { symbol: "candle snuffer", category: "household" },
  { symbol: "candle tray", category: "household" },
  { symbol: "candle lantern", category: "household" },
  { symbol: "candle mold", category: "household" },
  { symbol: "candy dish", category: "household" },
  { symbol: "candy jar", category: "household" },
  { symbol: "canning jar", category: "household" },
  { symbol: "canning lid", category: "household" },
  { symbol: "canning rack", category: "household" },
  { symbol: "canning funnel", category: "household" },
  { symbol: "car vacuum", category: "household" },
  { symbol: "carpet beater", category: "household" },
  { symbol: "carpet sweeper", category: "household" },
  { symbol: "carpet cleaner", category: "household" },
  { symbol: "carpet brush", category: "household" },
  { symbol: "carpet protector", category: "household" },
  { symbol: "carpet runner", category: "household" },
  { symbol: "cast iron skillet", category: "household" },
  { symbol: "ceiling fan", category: "household" },
  { symbol: "ceiling hook", category: "household" },
  { symbol: "ceiling vent", category: "household" },
  { symbol: "cell phone stand", category: "household" },
  { symbol: "ceramic dish", category: "household" },
  { symbol: "chair cushion", category: "household" },
  { symbol: "chair leg cap", category: "household" },
  { symbol: "chair mat", category: "household" },
  { symbol: "chalk board", category: "household" },
  { symbol: "charging station", category: "household" },
  { symbol: "cheese board", category: "household" },
  { symbol: "cheese slicer", category: "household" },
  { symbol: "cheese dome", category: "household" },
  { symbol: "cheese knife", category: "household" },
  { symbol: "child lock", category: "household" },
  { symbol: "china plate", category: "household" },
  { symbol: "chip clip", category: "household" },
  { symbol: "chip bowl", category: "household" },
  { symbol: "chip tray", category: "household" },
  { symbol: "chocolate mold", category: "household" },
  { symbol: "chopping knife", category: "household" },
  { symbol: "cleaning caddy", category: "household" },
  { symbol: "clothes basket", category: "household" },
  { symbol: "clothes steamer", category: "household" },
  { symbol: "clothesline", category: "household" },
  { symbol: "clothespin bag", category: "household" },
  { symbol: "coat hook", category: "household" },
  { symbol: "coat hanger rack", category: "household" },
  { symbol: "coffee carafe", category: "household" },
  { symbol: "coffee filter holder", category: "household" },
  { symbol: "coffee grinder burr", category: "household" },
  { symbol: "coffee pod holder", category: "household" },
  { symbol: "coffee scoop", category: "household" },
  { symbol: "coffee tamper", category: "household" },
  { symbol: "coffee warmer", category: "household" },
  { symbol: "coil burner", category: "household" },
  { symbol: "coil brush", category: "household" },
  { symbol: "coil cover", category: "household" },
  { symbol: "coil rack", category: "household" },
  { symbol: "collapsible basket", category: "household" },
  { symbol: "collapsible stool", category: "household" },
  { symbol: "collapsible table", category: "household" },
  { symbol: "color printer", category: "household" },
  { symbol: "comb holder", category: "household" },
  { symbol: "comfort fan", category: "household" },
  { symbol: "command hook", category: "household" },
  { symbol: "command strip", category: "household" },
  { symbol: "compost bucket", category: "household" },
  { symbol: "computer desk", category: "household" },
  { symbol: "computer tower stand", category: "household" },
  { symbol: "condiment caddy", category: "household" },
  { symbol: "condiment rack", category: "household" },
  { symbol: "condiment tray", category: "household" },
  { symbol: "contact paper", category: "household" },
  { symbol: "control knob", category: "household" },
  { symbol: "cooling rack", category: "household" },
  { symbol: "corner cabinet", category: "household" },
  { symbol: "corner shelf", category: "household" },
  { symbol: "corner table", category: "household" },
  { symbol: "cotton holder", category: "household" },
  { symbol: "counter organizer", category: "household" },
  { symbol: "counter mat", category: "household" },
  { symbol: "counter tray", category: "household" },
  { symbol: "countertop oven", category: "household" },
  { symbol: "craft box", category: "household" },
  { symbol: "craft drawer", category: "household" },
  { symbol: "craft table", category: "household" },
  { symbol: "cream pitcher", category: "household" },
  { symbol: "credit card holder", category: "household" },
  { symbol: "curio cabinet", category: "household" },
  { symbol: "curtain track", category: "household" },
  { symbol: "cutlery tray", category: "household" },
  { symbol: "cutting knife", category: "household" },
  { symbol: "cycle rack", category: "household" },
  { symbol: "dairy container", category: "household" },
  { symbol: "desk blotter", category: "household" },
  { symbol: "desk caddy", category: "household" },
  { symbol: "desk shelf", category: "household" },
  { symbol: "desk riser", category: "household" },
  { symbol: "desk drawer tray", category: "household" },
  { symbol: "desk hutch", category: "household" },
  { symbol: "desk fan mini", category: "household" },
  { symbol: "detergent cup", category: "household" },
  { symbol: "detergent tray", category: "household" },
  { symbol: "digital frame", category: "household" },
  { symbol: "digital scale", category: "household" },
  { symbol: "dish drainer", category: "household" },
  { symbol: "dish pan", category: "household" },
  { symbol: "dish rack tray", category: "household" },
  { symbol: "dish scraper", category: "household" },
  { symbol: "dish wand", category: "household" },
  { symbol: "dishwasher rack", category: "household" },
  { symbol: "dishwasher basket", category: "household" },
  { symbol: "dishwasher magnet", category: "household" },
  { symbol: "dishwasher tablet", category: "household" },
  { symbol: "display shelf", category: "household" },
  { symbol: "display stand", category: "household" },
  { symbol: "door alarm", category: "household" },
  { symbol: "door bumper", category: "household" },
  { symbol: "door closer", category: "household" },
  { symbol: "door guard", category: "household" },
  { symbol: "door hanger", category: "household" },
  { symbol: "door hook", category: "household" },
  { symbol: "door viewer", category: "household" },
  { symbol: "door wedge", category: "household" },
  { symbol: "door plate", category: "household" },
  { symbol: "door track", category: "household" },
  { symbol: "drawer knob", category: "household" },
  { symbol: "drawer pull", category: "household" },
  { symbol: "drawer stop", category: "household" },
  { symbol: "drawer slide", category: "household" },
  { symbol: "drawer tray", category: "household" },
  { symbol: "drawer lock", category: "household" },
  { symbol: "drip tray", category: "household" },
  { symbol: "drip pan", category: "household" },
  { symbol: "dry erase board", category: "household" },
  { symbol: "dry erase marker", category: "household" },
  { symbol: "drying hook", category: "household" },
  { symbol: "drying mat", category: "household" },
  { symbol: "drying rail", category: "household" },
  { symbol: "dust brush", category: "household" },
  { symbol: "dust mop", category: "household" },
  { symbol: "dust cover", category: "household" },
  { symbol: "dust mask", category: "household" },
  { symbol: "dust bin", category: "household" },
  { symbol: "dvd rack", category: "household" },
  { symbol: "egg holder", category: "household" },
  { symbol: "egg separator", category: "household" },
  { symbol: "egg timer", category: "household" },
  { symbol: "electric griddle", category: "household" },
  { symbol: "electric skillet", category: "household" },
  { symbol: "electric blanket controller", category: "household" },
  { symbol: "electric kettle base", category: "household" },
  { symbol: "electric lighter", category: "household" },
  { symbol: "electric toothbrush", category: "household" },
  { symbol: "electric wine opener", category: "household" },
  { symbol: "embroidery hoop", category: "household" },
  { symbol: "energy monitor", category: "household" },
  { symbol: "entry bench", category: "household" },
  { symbol: "entry console", category: "household" },
  { symbol: "entry table", category: "household" },
  { symbol: "envelope opener", category: "household" },
  { symbol: "essential oil bottle", category: "household" },
  { symbol: "essential oil diffuser", category: "household" },
  { symbol: "fan guard", category: "household" },
  { symbol: "fan remote", category: "household" },
  { symbol: "fan stand", category: "household" },
  { symbol: "fan mount", category: "household" },
  { symbol: "fan switch", category: "household" },
  { symbol: "fan timer", category: "household" },
  { symbol: "faucet aerator", category: "household" },
  { symbol: "faucet filter", category: "household" },
  { symbol: "faucet extender", category: "household" },
  { symbol: "fence gate", category: "household" },
  { symbol: "fiber basket", category: "household" },
  { symbol: "file sorter", category: "household" },
  { symbol: "filing tray", category: "household" },
  { symbol: "filter cartridge", category: "household" },
  { symbol: "fire blanket", category: "household" },
  { symbol: "fire poker", category: "household" },
  { symbol: "fire grate", category: "household" },
  { symbol: "fire screen", category: "household" },
  { symbol: "fireplace bellows", category: "household" },
  { symbol: "fireplace toolset", category: "household" },
  { symbol: "firewood rack", category: "household" },
  { symbol: "first aid box", category: "household" },
  { symbol: "fish bowl", category: "household" },
  { symbol: "fish net", category: "household" },
  { symbol: "fish tank", category: "household" },
  { symbol: "fish tank lid", category: "household" },
  { symbol: "fishing reel", category: "household" },
  { symbol: "flame lighter", category: "household" },
  { symbol: "flat iron holder", category: "household" },
  { symbol: "flatware tray", category: "household" },
  { symbol: "floor cushion", category: "household" },
  { symbol: "floor scrubber", category: "household" },
  { symbol: "floor sweeper", category: "household" },
  { symbol: "floor waxer", category: "household" },
  { symbol: "floor fan", category: "household" },
  { symbol: "floor outlet", category: "household" },
  { symbol: "floor protector", category: "household" },
  { symbol: "floor tray", category: "household" },
  { symbol: "flower vase", category: "household" },
  { symbol: "flower bucket", category: "household" },
  { symbol: "flower stand", category: "household" },
  { symbol: "foam pillow", category: "household" },
  { symbol: "food dehydrator", category: "household" },
  { symbol: "food mill", category: "household" },
  { symbol: "food slicer", category: "household" },
  { symbol: "foot stool", category: "household" },
  { symbol: "foot warmer", category: "household" },
  { symbol: "fork holder", category: "household" },
  { symbol: "frying pan lid", category: "household" },
  { symbol: "funnel set", category: "household" },
  { symbol: "furniture pad", category: "household" },
  { symbol: "furniture slider", category: "household" },
  { symbol: "furniture dolly", category: "household" },
  { symbol: "furniture polish", category: "household" },
  { symbol: "furniture wax", category: "household" },
  { symbol: "garbage disposer", category: "household" },
  { symbol: "garbage pail", category: "household" },
  { symbol: "garbage lid", category: "household" },
  { symbol: "garden stool", category: "household" },
  { symbol: "garden sprayer", category: "household" },
  { symbol: "garden cart", category: "household" },
  { symbol: "garden shears", category: "household" },
  { symbol: "garden shovel", category: "household" },
  { symbol: "garden rake", category: "household" },
  { symbol: "garden fork", category: "household" },
  { symbol: "garden hoe", category: "household" },
  { symbol: "garden trellis", category: "household" },
  { symbol: "garden lantern", category: "household" },
  { symbol: "garden bench", category: "household" },
  { symbol: "garden statue", category: "household" },
  { symbol: "garden arch", category: "household" },
  { symbol: "garden hose reel", category: "household" },
  { symbol: "garden hose nozzle", category: "household" },
  { symbol: "garden hose timer", category: "household" },
  { symbol: "garden edging", category: "household" },
  { symbol: "garden basket", category: "household" },
  { symbol: "garden planter box", category: "household" },
  { symbol: "garden bucket", category: "household" },
  { symbol: "garden watering spike", category: "household" },
  { symbol: "garden watering globe", category: "household" },
  { symbol: "garden soil scoop", category: "household" },
  { symbol: "garden seed box", category: "household" },
  { symbol: "garden seed tray", category: "household" },
  { symbol: "garden plant tag", category: "household" },
  { symbol: "garden twine", category: "household" },
  { symbol: "garden tie", category: "household" },
  { symbol: "garden kneeler", category: "household" },
  { symbol: "garden apron", category: "household" },
  { symbol: "garden gloves", category: "household" },
  { symbol: "garden bag", category: "household" },
  { symbol: "garden net", category: "household" },
  { symbol: "garden mesh", category: "household" },
  { symbol: "garden shade", category: "household" },
  { symbol: "garden cover", category: "household" },
  { symbol: "garden frame", category: "household" },
  { symbol: "garden cage", category: "household" },
  { symbol: "garden cloche", category: "household" },
  { symbol: "garden compost tumbler", category: "household" },
  { symbol: "garden compost bin", category: "household" },
  { symbol: "garden mulch fork", category: "household" },
  { symbol: "garden bulb planter", category: "household" },
  { symbol: "garden cultivator", category: "household" },
  { symbol: "garden weeder", category: "household" },
  { symbol: "garden dibber", category: "household" },
  { symbol: "garden watering wand", category: "household" },
  { symbol: "garden watering sprayer", category: "household" },
  { symbol: "garden sprout tray", category: "household" },
  { symbol: "garden grow tray", category: "household" },
  { symbol: "garden grow mat", category: "household" },
  { symbol: "garden light solar", category: "household" },
  { symbol: "garden spotlight", category: "household" },
  { symbol: "garden path light", category: "household" },
  { symbol: "garden string light", category: "household" },
  { symbol: "garden fence panel", category: "household" },
  { symbol: "garden gate latch", category: "household" },
  { symbol: "garden gate hinge", category: "household" },
  { symbol: "garden gate lock", category: "household" },
  { symbol: "garden fence cap", category: "household" },
  { symbol: "garden fence post", category: "household" },
  { symbol: "garden fence hook", category: "household" },
  { symbol: "garden fence clip", category: "household" },
  { symbol: "garden fence bracket", category: "household" },
  { symbol: "garden border stone", category: "household" },
  { symbol: "garden border brick", category: "household" },
  { symbol: "garden stepping stone", category: "household" },
  { symbol: "garden bird house", category: "household" },
  { symbol: "garden bird feeder", category: "household" },
  { symbol: "garden bird bath", category: "household" },
  { symbol: "garden bird perch", category: "household" },
  { symbol: "garden bird seed tray", category: "household" },
  { symbol: "garden bird water dish", category: "household" },
  { symbol: "garden bird cage stand", category: "household" },
  { symbol: "garden bird swing", category: "household" },
  { symbol: "garden bird toy", category: "household" },
  { symbol: "garden wind chime", category: "household" },
  { symbol: "garden wind spinner", category: "household" },
  { symbol: "garden weather vane", category: "household" },
  { symbol: "garden rain gauge", category: "household" },
  { symbol: "garden thermometer", category: "household" },
  { symbol: "garden barometer", category: "household" },
  { symbol: "garden hygrometer", category: "household" },
  { symbol: "garden watering jug", category: "household" },
  { symbol: "garden watering can metal", category: "household" },
  { symbol: "garden watering can plastic", category: "household" },
  { symbol: "garden watering can longspout", category: "household" },
  { symbol: "garden watering can shortspout", category: "household" },
  { symbol: "garden hose hanger", category: "household" },
  { symbol: "garden hose guide", category: "household" },
  { symbol: "garden hose connector", category: "household" },
  { symbol: "garden hose coupler", category: "household" },
  { symbol: "garden hose splitter", category: "household" },
  { symbol: "garden hose repair kit", category: "household" },
  { symbol: "garden hose clamp", category: "household" },
  { symbol: "garden hose washer", category: "household" },
  { symbol: "garden hose plug", category: "household" },
  { symbol: "garden hose valve", category: "household" },
  { symbol: "garden hose faucet", category: "household" },
  { symbol: "garden hose spigot", category: "household" },
  { symbol: "garden hose bib", category: "household" },
  { symbol: "garden hose bracket", category: "household" },
  { symbol: "garden hose holder wall", category: "household" },
  { symbol: "garden hose storage pot", category: "household" },
  { symbol: "garden hose storage box", category: "household" },
  { symbol: "garden hose storage basket", category: "household" },
  { symbol: "garden hose storage reel wall", category: "household" },
  { symbol: "garden hose storage reel cart", category: "household" },
  { symbol: "garden hose storage reel stand", category: "household" },
];
