import { SingleWordSymbol } from "../dreamSingularSymbols";

export const medical_items_symbols: SingleWordSymbol[] = [
  { symbol: "compassneedle", category: "medical_items" },
  { symbol: "medicine", category: "medical_items" },
  { symbol: "facemask", category: "medical_items" },
  { symbol: "needle", category: "medical_items" },
  { symbol: "surgicalmask", category: "medical_items" },
  { symbol: "sewingneedle", category: "medical_items" },
  { symbol: "thermometer", category: "medical_items" },
  { symbol: "razorhandle", category: "medical_items" },
  { symbol: "oxygenmask", category: "medical_items" },
  { symbol: "needlecase", category: "medical_items" },
  { symbol: "bandage", category: "medical_items" },
  { symbol: "crutch", category: "medical_items" },
  { symbol: "floss", category: "medical_items" },
  { symbol: "syringe", category: "medical_items" },
  { symbol: "flosspick", category: "medical_items" },
  { symbol: "sleepmask", category: "medical_items" },
  { symbol: "knittingneedle", category: "medical_items" },
  { symbol: "eyemask", category: "medical_items" },
  { symbol: "razor", category: "medical_items" },
  { symbol: "mask", category: "medical_items" },
  { symbol: "bandagewrap", category: "medical_items" },
  { symbol: "electricrazor", category: "medical_items" },
  { symbol: "stethoscope", category: "medical_items" },
  { symbol: "bandage wrap", category: "medical_items" },
  { symbol: "adhesive bandage", category: "medical_items" },
  { symbol: "gauze pad", category: "medical_items" },
  { symbol: "gauze roll", category: "medical_items" },
  { symbol: "medical tape", category: "medical_items" },
  { symbol: "surgical tape", category: "medical_items" },
  { symbol: "elastic bandage", category: "medical_items" },
  { symbol: "compression bandage", category: "medical_items" },
  { symbol: "triangular bandage", category: "medical_items" },
  { symbol: "antiseptic wipe", category: "medical_items" },
  { symbol: "alcohol wipe", category: "medical_items" },
  { symbol: "antiseptic spray", category: "medical_items" },
  { symbol: "antiseptic bottle", category: "medical_items" },
  { symbol: "disinfectant bottle", category: "medical_items" },
  { symbol: "iodine bottle", category: "medical_items" },
  { symbol: "hydrogen peroxide", category: "medical_items" },
  { symbol: "first aid kit", category: "medical_items" },
  { symbol: "medical kit", category: "medical_items" },
  { symbol: "emergency kit", category: "medical_items" },
  { symbol: "trauma kit", category: "medical_items" },
  { symbol: "digital thermometer", category: "medical_items" },
  { symbol: "forehead thermometer", category: "medical_items" },
  { symbol: "ear thermometer", category: "medical_items" },
  { symbol: "blood pressure monitor", category: "medical_items" },
  { symbol: "blood pressure cuff", category: "medical_items" },
  { symbol: "pulse oximeter", category: "medical_items" },
  { symbol: "heart monitor", category: "medical_items" },
  { symbol: "ekg monitor", category: "medical_items" },
  { symbol: "otoscope", category: "medical_items" },
  { symbol: "ophthalmoscope", category: "medical_items" },
  { symbol: "injection syringe", category: "medical_items" },
  { symbol: "insulin syringe", category: "medical_items" },
  { symbol: "hypodermic needle", category: "medical_items" },
  { symbol: "medicine bottle", category: "medical_items" },
  { symbol: "pill bottle", category: "medical_items" },
  { symbol: "pill container", category: "medical_items" },
  { symbol: "pill organizer", category: "medical_items" },
  { symbol: "pill splitter", category: "medical_items" },
  { symbol: "pill cutter", category: "medical_items" },
  { symbol: "capsule", category: "medical_items" },
  { symbol: "tablet pill", category: "medical_items" },
  { symbol: "medicine cup", category: "medical_items" },
  { symbol: "medicine spoon", category: "medical_items" },
  { symbol: "medicine dropper", category: "medical_items" },
  { symbol: "inhaler", category: "medical_items" },
  { symbol: "nebulizer", category: "medical_items" },
  { symbol: "nebulizer mask", category: "medical_items" },
  { symbol: "oxygen tank", category: "medical_items" },
  { symbol: "oxygen mask", category: "medical_items" },
  { symbol: "oxygen tubing", category: "medical_items" },
  { symbol: "face mask", category: "medical_items" },
  { symbol: "surgical mask", category: "medical_items" },
  { symbol: "respirator mask", category: "medical_items" },
  { symbol: "n95 mask", category: "medical_items" },
  { symbol: "medical gloves", category: "medical_items" },
  { symbol: "latex gloves", category: "medical_items" },
  { symbol: "nitrile gloves", category: "medical_items" },
  { symbol: "rubber gloves", category: "medical_items" },
  { symbol: "tongue depressor", category: "medical_items" },
  { symbol: "cotton swab", category: "medical_items" },
  { symbol: "cotton ball", category: "medical_items" },
  { symbol: "heating pad", category: "medical_items" },
  { symbol: "ice pack", category: "medical_items" },
  { symbol: "cold pack", category: "medical_items" },
  { symbol: "hot pack", category: "medical_items" },
  { symbol: "medical brace", category: "medical_items" },
  { symbol: "knee brace", category: "medical_items" },
  { symbol: "ankle brace", category: "medical_items" },
  { symbol: "wrist brace", category: "medical_items" },
  { symbol: "back brace", category: "medical_items" },
  { symbol: "arm sling", category: "medical_items" },
  { symbol: "neck brace", category: "medical_items" },
  { symbol: "splint", category: "medical_items" },
  { symbol: "cast", category: "medical_items" },
  { symbol: "walking cane", category: "medical_items" },
  { symbol: "walker", category: "medical_items" },
  { symbol: "wheelchair", category: "medical_items" },
  { symbol: "hospital bed", category: "medical_items" },
  { symbol: "bed rail", category: "medical_items" },
  { symbol: "bed pan", category: "medical_items" },
  { symbol: "urine bottle", category: "medical_items" },
  { symbol: "urine container", category: "medical_items" },
  { symbol: "surgical scissors", category: "medical_items" },
  { symbol: "medical scissors", category: "medical_items" },
  { symbol: "forceps", category: "medical_items" },
  { symbol: "tweezers", category: "medical_items" },
  { symbol: "scalpel", category: "medical_items" },
  { symbol: "surgical scalpel", category: "medical_items" },
  { symbol: "surgical clamp", category: "medical_items" },
  { symbol: "hemostat", category: "medical_items" },
  { symbol: "medical tray", category: "medical_items" },
  { symbol: "instrument tray", category: "medical_items" },
  { symbol: "iv bag", category: "medical_items" },
  { symbol: "iv stand", category: "medical_items" },
  { symbol: "iv tubing", category: "medical_items" },
  { symbol: "iv catheter", category: "medical_items" },
  { symbol: "defibrillator", category: "medical_items" },
  { symbol: "aed device", category: "medical_items" },
  { symbol: "glucose meter", category: "medical_items" },
  { symbol: "glucose strip", category: "medical_items" },
  { symbol: "lancet", category: "medical_items" },
  { symbol: "lancet device", category: "medical_items" },
  { symbol: "insulin pen", category: "medical_items" },
  { symbol: "insulin pump", category: "medical_items" },
  { symbol: "hearing aid", category: "medical_items" },
  { symbol: "ear thermometer cover", category: "medical_items" },
  { symbol: "contact lens", category: "medical_items" },
  { symbol: "contact lens case", category: "medical_items" },
  { symbol: "contact lens solution", category: "medical_items" },
  { symbol: "eye drop bottle", category: "medical_items" },
  { symbol: "eye wash cup", category: "medical_items" },
  { symbol: "dental floss", category: "medical_items" },
  { symbol: "dental pick", category: "medical_items" },
  { symbol: "mouth guard", category: "medical_items" },
  { symbol: "retainer", category: "medical_items" },
  { symbol: "denture case", category: "medical_items" },
  { symbol: "orthotic insert", category: "medical_items" },
  { symbol: "shoe orthotic", category: "medical_items" },
  { symbol: "mobility scooter", category: "medical_items" },
  { symbol: "medical chart", category: "medical_items" },
  { symbol: "patient chart", category: "medical_items" },
  { symbol: "clipboard chart", category: "medical_items" },
  { symbol: "exam table", category: "medical_items" },
  { symbol: "stool chair", category: "medical_items" },
  { symbol: "privacy curtain", category: "medical_items" },
  { symbol: "medical screen", category: "medical_items" },
  { symbol: "surgical gown", category: "medical_items" },
  { symbol: "medical gown", category: "medical_items" },
  { symbol: "hospital gown", category: "medical_items" },
  { symbol: "face shield", category: "medical_items" },
  { symbol: "protective visor", category: "medical_items" },
  { symbol: "medical bag", category: "medical_items" },
  { symbol: "doctor bag", category: "medical_items" },
  { symbol: "biohazard bag", category: "medical_items" },
  { symbol: "sharps container", category: "medical_items" },
  { symbol: "lab vial", category: "medical_items" },
  { symbol: "sample vial", category: "medical_items" },
  { symbol: "specimen cup", category: "medical_items" },
  { symbol: "test tube", category: "medical_items" },
  { symbol: "test tube rack", category: "medical_items" },
  { symbol: "petri dish", category: "medical_items" },
  { symbol: "microscope", category: "medical_items" },
  { symbol: "centrifuge", category: "medical_items" },
  { symbol: "lab scale", category: "medical_items" },
  { symbol: "lab timer", category: "medical_items" },
  { symbol: "pipette", category: "medical_items" },
  { symbol: "pipette bulb", category: "medical_items" },
  { symbol: "lab flask", category: "medical_items" },
  { symbol: "lab beaker", category: "medical_items" },
  { symbol: "lab funnel", category: "medical_items" },
  { symbol: "lab spatula", category: "medical_items" },
  { symbol: "lab stirrer", category: "medical_items" },
  { symbol: "lab rack", category: "medical_items" },
  { symbol: "lab tray", category: "medical_items" },
  { symbol: "lab container", category: "medical_items" },
  { symbol: "lab bottle", category: "medical_items" },
  { symbol: "lab clamp", category: "medical_items" },
  { symbol: "lab stand", category: "medical_items" },
  { symbol: "lab burner", category: "medical_items" },
  { symbol: "lab tongs", category: "medical_items" },
  { symbol: "lab brush", category: "medical_items" },
  { symbol: "lab stopper", category: "medical_items" },
  { symbol: "lab cork", category: "medical_items" },
  { symbol: "lab lid", category: "medical_items" },
  { symbol: "lab label", category: "medical_items" },
  { symbol: "lab marker", category: "medical_items" },
  { symbol: "lab notebook", category: "medical_items" },
  { symbol: "lab gloves", category: "medical_items" },
  { symbol: "lab coat", category: "medical_items" },
  { symbol: "lab goggles", category: "medical_items" },
  { symbol: "lab mask", category: "medical_items" },
  { symbol: "lab hood", category: "medical_items" },
  { symbol: "lab cabinet", category: "medical_items" },
  { symbol: "lab drawer", category: "medical_items" },
  { symbol: "lab freezer", category: "medical_items" },
  { symbol: "lab fridge", category: "medical_items" },
  { symbol: "lab incubator", category: "medical_items" },
  { symbol: "lab shaker", category: "medical_items" },
  { symbol: "lab mixer", category: "medical_items" },
  { symbol: "lab stir plate", category: "medical_items" },
  { symbol: "lab thermometer", category: "medical_items" },
  { symbol: "lab probe", category: "medical_items" },
  { symbol: "lab sensor", category: "medical_items" },
  { symbol: "lab analyzer", category: "medical_items" },
  { symbol: "lab detector", category: "medical_items" },
  { symbol: "lab scanner", category: "medical_items" },
  { symbol: "lab monitor", category: "medical_items" },
  { symbol: "lab computer", category: "medical_items" },
  { symbol: "lab printer", category: "medical_items" },
  { symbol: "lab storage", category: "medical_items" },
  { symbol: "lab shelf", category: "medical_items" },
  { symbol: "lab cart", category: "medical_items" },
  { symbol: "lab trolley", category: "medical_items" },
  { symbol: "lab stool", category: "medical_items" },
  { symbol: "lab bench", category: "medical_items" },
  { symbol: "lab table", category: "medical_items" },
  { symbol: "lab counter", category: "medical_items" },
  { symbol: "lab sink", category: "medical_items" },
  { symbol: "lab faucet", category: "medical_items" },
  { symbol: "lab drain", category: "medical_items" },
  { symbol: "lab waste bin", category: "medical_items" },
  { symbol: "lab disposal container", category: "medical_items" },
];
