import { SingleWordSymbol } from "../dreamSingularSymbols";

export const office_items_symbols: SingleWordSymbol[] = [
  { symbol: "pencilcase", category: "office_items" },
  { symbol: "notebook", category: "office_items" },
  { symbol: "wineopener", category: "office_items" },
  { symbol: "clipboardcover", category: "office_items" },
  { symbol: "pen", category: "office_items" },
  { symbol: "highlighterpen", category: "office_items" },
  { symbol: "penispump", category: "office_items" },
  { symbol: "cordclip", category: "office_items" },
  { symbol: "styluspen", category: "office_items" },
  { symbol: "marker", category: "office_items" },
  { symbol: "paper", category: "office_items" },
  { symbol: "parchmentpaper", category: "office_items" },
  { symbol: "notebookpaper", category: "office_items" },
  { symbol: "papernapkin", category: "office_items" },
  { symbol: "engraverpen", category: "office_items" },
  { symbol: "pendulum", category: "office_items" },
  { symbol: "calculator", category: "office_items" },
  { symbol: "eraser", category: "office_items" },
  { symbol: "penissleeve", category: "office_items" },
  { symbol: "pencilsharpener", category: "office_items" },
  { symbol: "penholder", category: "office_items" },
  { symbol: "paperclip", category: "office_items" },
  { symbol: "pencil", category: "office_items" },
  { symbol: "fastenerclip", category: "office_items" },
  { symbol: "pacifierclip", category: "office_items" },
  { symbol: "foldertab", category: "office_items" },
  { symbol: "badgeclip", category: "office_items" },
  { symbol: "hingeclip", category: "office_items" },
  { symbol: "notebookcover", category: "office_items" },
  { symbol: "fountainpen", category: "office_items" },
  { symbol: "garageopener", category: "office_items" },
  { symbol: "printerpaper", category: "office_items" },
  { symbol: "mechanicalpencil", category: "office_items" },
  { symbol: "napkindispenser", category: "office_items" },
  { symbol: "playpen", category: "office_items" },
  { symbol: "photopaper", category: "office_items" },
  { symbol: "gelpen", category: "office_items" },
  { symbol: "toiletpaper", category: "office_items" },
  { symbol: "folder", category: "office_items" },
  { symbol: "pencillead", category: "office_items" },
  { symbol: "markerpen", category: "office_items" },
  { symbol: "filefolder", category: "office_items" },
  { symbol: "folderdivider", category: "office_items" },
  { symbol: "opener", category: "office_items" },
  { symbol: "calculatorpad", category: "office_items" },
  { symbol: "clipboard", category: "office_items" },
  { symbol: "hairclip", category: "office_items" },
  { symbol: "graphpaper", category: "office_items" },
  { symbol: "desk", category: "office_items" },
  { symbol: "office chair", category: "office_items" },
  { symbol: "swivel chair", category: "office_items" },
  { symbol: "desk lamp", category: "office_items" },
  { symbol: "desk fan", category: "office_items" },
  { symbol: "desk organizer", category: "office_items" },
  { symbol: "desk tray", category: "office_items" },
  { symbol: "desk mat", category: "office_items" },
  { symbol: "desk pad", category: "office_items" },
  { symbol: "desk riser", category: "office_items" },
  { symbol: "desk shelf", category: "office_items" },
  { symbol: "keyboard", category: "office_items" },
  { symbol: "mouse", category: "office_items" },
  { symbol: "mousepad", category: "office_items" },
  { symbol: "monitor", category: "office_items" },
  { symbol: "monitor stand", category: "office_items" },
  { symbol: "monitor arm", category: "office_items" },
  { symbol: "laptop", category: "office_items" },
  { symbol: "laptop stand", category: "office_items" },
  { symbol: "laptop charger", category: "office_items" },
  { symbol: "docking station", category: "office_items" },
  { symbol: "usb hub", category: "office_items" },
  { symbol: "flash drive", category: "office_items" },
  { symbol: "external hard drive", category: "office_items" },
  { symbol: "router", category: "office_items" },
  { symbol: "modem", category: "office_items" },
  { symbol: "printer", category: "office_items" },
  { symbol: "laser printer", category: "office_items" },
  { symbol: "inkjet printer", category: "office_items" },
  { symbol: "photocopier", category: "office_items" },
  { symbol: "scanner", category: "office_items" },
  { symbol: "shredder", category: "office_items" },
  { symbol: "laminator", category: "office_items" },
  { symbol: "label printer", category: "office_items" },
  { symbol: "barcode scanner", category: "office_items" },
  { symbol: "adding machine", category: "office_items" },
  { symbol: "notepad", category: "office_items" },
  { symbol: "legal pad", category: "office_items" },
  { symbol: "memo pad", category: "office_items" },
  { symbol: "sticky notes", category: "office_items" },
  { symbol: "sticky note pad", category: "office_items" },
  { symbol: "index cards", category: "office_items" },
  { symbol: "flash cards", category: "office_items" },
  { symbol: "binder", category: "office_items" },
  { symbol: "ring binder", category: "office_items" },
  { symbol: "binder clips", category: "office_items" },
  { symbol: "paper clips", category: "office_items" },
  { symbol: "rubber bands", category: "office_items" },
  { symbol: "file folder", category: "office_items" },
  { symbol: "hanging file folder", category: "office_items" },
  { symbol: "expanding folder", category: "office_items" },
  { symbol: "accordion folder", category: "office_items" },
  { symbol: "document tray", category: "office_items" },
  { symbol: "file organizer", category: "office_items" },
  { symbol: "filing cabinet", category: "office_items" },
  { symbol: "file box", category: "office_items" },
  { symbol: "archive box", category: "office_items" },
  { symbol: "clipboard folder", category: "office_items" },
  { symbol: "stapler", category: "office_items" },
  { symbol: "staple remover", category: "office_items" },
  { symbol: "staples", category: "office_items" },
  { symbol: "hole punch", category: "office_items" },
  { symbol: "tape dispenser", category: "office_items" },
  { symbol: "tape roll", category: "office_items" },
  { symbol: "packing tape", category: "office_items" },
  { symbol: "masking tape", category: "office_items" },
  { symbol: "scissors", category: "office_items" },
  { symbol: "letter opener", category: "office_items" },
  { symbol: "envelope opener", category: "office_items" },
  { symbol: "envelopes", category: "office_items" },
  { symbol: "padded envelopes", category: "office_items" },
  { symbol: "mailing envelopes", category: "office_items" },
  { symbol: "postage stamps", category: "office_items" },
  { symbol: "stamp pad", category: "office_items" },
  { symbol: "date stamp", category: "office_items" },
  { symbol: "ink pad", category: "office_items" },
  { symbol: "ballpoint pen", category: "office_items" },
  { symbol: "gel pen", category: "office_items" },
  { symbol: "fountain pen", category: "office_items" },
  { symbol: "permanent marker", category: "office_items" },
  { symbol: "dry erase marker", category: "office_items" },
  { symbol: "highlighter", category: "office_items" },
  { symbol: "mechanical pencil", category: "office_items" },
  { symbol: "colored pencils", category: "office_items" },
  { symbol: "pencil sharpener", category: "office_items" },
  { symbol: "correction tape", category: "office_items" },
  { symbol: "correction fluid", category: "office_items" },
  { symbol: "whiteboard", category: "office_items" },
  { symbol: "whiteboard eraser", category: "office_items" },
  { symbol: "bulletin board", category: "office_items" },
  { symbol: "cork board", category: "office_items" },
  { symbol: "push pins", category: "office_items" },
  { symbol: "thumb tacks", category: "office_items" },
  { symbol: "magnets", category: "office_items" },
  { symbol: "whiteboard markers", category: "office_items" },
  { symbol: "dry erase board", category: "office_items" },
  { symbol: "projector", category: "office_items" },
  { symbol: "projector screen", category: "office_items" },
  { symbol: "presentation remote", category: "office_items" },
  { symbol: "laser pointer", category: "office_items" },
  { symbol: "speakerphone", category: "office_items" },
  { symbol: "conference phone", category: "office_items" },
  { symbol: "headset", category: "office_items" },
  { symbol: "webcam", category: "office_items" },
  { symbol: "microphone", category: "office_items" },
  { symbol: "desk clock", category: "office_items" },
  { symbol: "wall clock", category: "office_items" },
  { symbol: "calendar", category: "office_items" },
  { symbol: "desk calendar", category: "office_items" },
  { symbol: "planner", category: "office_items" },
  { symbol: "appointment book", category: "office_items" },
  { symbol: "time clock", category: "office_items" },
  { symbol: "key cabinet", category: "office_items" },
  { symbol: "key holder", category: "office_items" },
  { symbol: "office safe", category: "office_items" },
  { symbol: "storage cabinet", category: "office_items" },
  { symbol: "bookcase", category: "office_items" },
  { symbol: "bookshelf", category: "office_items" },
  { symbol: "storage bins", category: "office_items" },
  { symbol: "storage boxes", category: "office_items" },
  { symbol: "cable organizer", category: "office_items" },
  { symbol: "cord clip", category: "office_items" },
  { symbol: "power strip", category: "office_items" },
  { symbol: "surge protector", category: "office_items" },
  { symbol: "extension cord", category: "office_items" },
  { symbol: "charging station", category: "office_items" },
  { symbol: "phone charger", category: "office_items" },
  { symbol: "tablet charger", category: "office_items" },
  { symbol: "paper shred bin", category: "office_items" },
  { symbol: "recycling bin", category: "office_items" },
  { symbol: "trash can", category: "office_items" },
  { symbol: "trash liner", category: "office_items" },
  { symbol: "mail sorter", category: "office_items" },
  { symbol: "mail tray", category: "office_items" },
  { symbol: "inbox tray", category: "office_items" },
  { symbol: "outbox tray", category: "office_items" },
  { symbol: "document holder", category: "office_items" },
  { symbol: "magazine rack", category: "office_items" },
  { symbol: "literature rack", category: "office_items" },
  { symbol: "brochure holder", category: "office_items" },
  { symbol: "coat rack", category: "office_items" },
  { symbol: "umbrella stand", category: "office_items" },
  { symbol: "office rug", category: "office_items" },
  { symbol: "chair mat", category: "office_items" },
  { symbol: "footrest", category: "office_items" },
  { symbol: "document scanner", category: "office_items" },
  { symbol: "id badge holder", category: "office_items" },
  { symbol: "badge reel", category: "office_items" },
  { symbol: "lanyard", category: "office_items" },
  { symbol: "visitor badge", category: "office_items" },
  { symbol: "name plate", category: "office_items" },
  { symbol: "desk name plate", category: "office_items" },
  { symbol: "desk divider", category: "office_items" },
  { symbol: "cubicle panel", category: "office_items" },
  { symbol: "cubicle shelf", category: "office_items" },
  { symbol: "cubicle hook", category: "office_items" },
  { symbol: "cubicle organizer", category: "office_items" },
  { symbol: "wall shelf", category: "office_items" },
  { symbol: "wall organizer", category: "office_items" },
  { symbol: "wall file holder", category: "office_items" },
  { symbol: "office cart", category: "office_items" },
  { symbol: "rolling cart", category: "office_items" },
  { symbol: "utility cart", category: "office_items" },
  { symbol: "supply cabinet", category: "office_items" },
  { symbol: "supply drawer", category: "office_items" },
  { symbol: "supply caddy", category: "office_items" },
  { symbol: "supply organizer", category: "office_items" },
];
