import { SingleWordSymbol } from "../dreamSingularSymbols";

export const settings_symbols: SingleWordSymbol[] = [
  { symbol: "house", category: "settings" },
  { symbol: "home", category: "settings" },
  { symbol: "apartment", category: "settings" },
  { symbol: "room", category: "settings" },
  { symbol: "bedroom", category: "settings" },
  { symbol: "bathroom", category: "settings" },
  { symbol: "kitchen", category: "settings" },
  { symbol: "basement", category: "settings" },
  { symbol: "attic", category: "settings" },
  { symbol: "hallway", category: "settings" },
  { symbol: "garage", category: "settings" },
  { symbol: "porch", category: "settings" },
  { symbol: "balcony", category: "settings" },
  { symbol: "yard", category: "settings" },
  { symbol: "garden", category: "settings" },
  { symbol: "courtyard", category: "settings" },
  { symbol: "driveway", category: "settings" },
  { symbol: "roof", category: "settings" },
  { symbol: "window", category: "settings" },
  { symbol: "door", category: "settings" },
  { symbol: "school", category: "settings" },
  { symbol: "classroom", category: "settings" },
  { symbol: "hall", category: "settings" },
  { symbol: "library", category: "settings" },
  { symbol: "cafeteria", category: "settings" },
  { symbol: "playground", category: "settings" },
  { symbol: "gymnasium", category: "settings" },
  { symbol: "lockerroom", category: "settings" },
  { symbol: "auditorium", category: "settings" },
  { symbol: "campus", category: "settings" },
  { symbol: "office", category: "settings" },
  { symbol: "workplace", category: "settings" },
  { symbol: "cubicle", category: "settings" },
  { symbol: "conference", category: "settings" },
  { symbol: "boardroom", category: "settings" },
  { symbol: "studio", category: "settings" },
  { symbol: "workshop", category: "settings" },
  { symbol: "factory", category: "settings" },
  { symbol: "warehouse", category: "settings" },
  { symbol: "laboratory", category: "settings" },
  { symbol: "hospital", category: "settings" },
  { symbol: "clinic", category: "settings" },
  { symbol: "ward", category: "settings" },
  { symbol: "operatingroom", category: "settings" },
  { symbol: "pharmacy", category: "settings" },
  { symbol: "reception", category: "settings" },
  { symbol: "waitingroom", category: "settings" },
  { symbol: "ambulance", category: "settings" },
  { symbol: "medicalcenter", category: "settings" },
  { symbol: "asylum", category: "settings" },
  { symbol: "church", category: "settings" },
  { symbol: "temple", category: "settings" },
  { symbol: "mosque", category: "settings" },
  { symbol: "synagogue", category: "settings" },
  { symbol: "chapel", category: "settings" },
  { symbol: "cathedral", category: "settings" },
  { symbol: "sanctuary", category: "settings" },
  { symbol: "altar", category: "settings" },
  { symbol: "monastery", category: "settings" },
  { symbol: "shrine", category: "settings" },
  { symbol: "graveyard", category: "settings" },
  { symbol: "cemetery", category: "settings" },
  { symbol: "crypt", category: "settings" },
  { symbol: "tomb", category: "settings" },
  { symbol: "mausoleum", category: "settings" },
  { symbol: "memorial", category: "settings" },
  { symbol: "funeralhome", category: "settings" },
  { symbol: "burialground", category: "settings" },
  { symbol: "grave", category: "settings" },
  { symbol: "city", category: "settings" },
  { symbol: "town", category: "settings" },
  { symbol: "village", category: "settings" },
  { symbol: "suburb", category: "settings" },
  { symbol: "street", category: "settings" },
  { symbol: "avenue", category: "settings" },
  { symbol: "alley", category: "settings" },
  { symbol: "boulevard", category: "settings" },
  { symbol: "intersection", category: "settings" },
  { symbol: "crosswalk", category: "settings" },
  { symbol: "bridge", category: "settings" },
  { symbol: "tunnel", category: "settings" },
  { symbol: "highway", category: "settings" },
  { symbol: "road", category: "settings" },
  { symbol: "path", category: "settings" },
  { symbol: "trail", category: "settings" },
  { symbol: "sidewalk", category: "settings" },
  { symbol: "roundabout", category: "settings" },
  { symbol: "parkinglot", category: "settings" },
  { symbol: "park", category: "settings" },
  { symbol: "square", category: "settings" },
  { symbol: "plaza", category: "settings" },
  { symbol: "market", category: "settings" },
  { symbol: "bazaar", category: "settings" },
  { symbol: "mall", category: "settings" },
  { symbol: "store", category: "settings" },
  { symbol: "shop", category: "settings" },
  { symbol: "supermarket", category: "settings" },
  { symbol: "restaurant", category: "settings" },
  { symbol: "cafe", category: "settings" },
  { symbol: "bar", category: "settings" },
  { symbol: "pub", category: "settings" },
  { symbol: "club", category: "settings" },
  { symbol: "theater", category: "settings" },
  { symbol: "cinema", category: "settings" },
  { symbol: "stadium", category: "settings" },
  { symbol: "arena", category: "settings" },
  { symbol: "gallery", category: "settings" },
  { symbol: "museum", category: "settings" },
  { symbol: "forest", category: "settings" },
  { symbol: "woods", category: "settings" },
  { symbol: "jungle", category: "settings" },
  { symbol: "grove", category: "settings" },
  { symbol: "clearing", category: "settings" },
  { symbol: "meadow", category: "settings" },
  { symbol: "field", category: "settings" },
  { symbol: "farm", category: "settings" },
  { symbol: "pasture", category: "settings" },
  { symbol: "orchard", category: "settings" },
  { symbol: "mountain", category: "settings" },
  { symbol: "hill", category: "settings" },
  { symbol: "valley", category: "settings" },
  { symbol: "canyon", category: "settings" },
  { symbol: "cliff", category: "settings" },
  { symbol: "plateau", category: "settings" },
  { symbol: "ridge", category: "settings" },
  { symbol: "summit", category: "settings" },
  { symbol: "peak", category: "settings" },
  { symbol: "slope", category: "settings" },
  { symbol: "desert", category: "settings" },
  { symbol: "dune", category: "settings" },
  { symbol: "oasis", category: "settings" },
  { symbol: "wasteland", category: "settings" },
  { symbol: "plain", category: "settings" },
  { symbol: "prairie", category: "settings" },
  { symbol: "tundra", category: "settings" },
  { symbol: "savanna", category: "settings" },
  { symbol: "steppe", category: "settings" },
  { symbol: "marsh", category: "settings" },
  { symbol: "swamp", category: "settings" },
  { symbol: "bog", category: "settings" },
  { symbol: "wetland", category: "settings" },
  { symbol: "lagoon", category: "settings" },
  { symbol: "island", category: "settings" },
  { symbol: "peninsula", category: "settings" },
  { symbol: "coast", category: "settings" },
  { symbol: "shore", category: "settings" },
  { symbol: "beach", category: "settings" },
  { symbol: "harbor", category: "settings" },
  { symbol: "port", category: "settings" },
  { symbol: "dock", category: "settings" },
  { symbol: "pier", category: "settings" },
  { symbol: "marina", category: "settings" },
  { symbol: "ocean", category: "settings" },
  { symbol: "sea", category: "settings" },
  { symbol: "lake", category: "settings" },
  { symbol: "pond", category: "settings" },
  { symbol: "river", category: "settings" },
  { symbol: "stream", category: "settings" },
  { symbol: "waterfall", category: "settings" },
  { symbol: "spring", category: "settings" },
  { symbol: "geyser", category: "settings" },
  { symbol: "pool", category: "settings" },
  { symbol: "reservoir", category: "settings" },
  { symbol: "dam", category: "settings" },
  { symbol: "canal", category: "settings" },
  { symbol: "delta", category: "settings" },
  { symbol: "bay", category: "settings" },
  { symbol: "cove", category: "settings" },
  { symbol: "airport", category: "settings" },
  { symbol: "runway", category: "settings" },
  { symbol: "terminal", category: "settings" },
  { symbol: "hangar", category: "settings" },
  { symbol: "station", category: "settings" },
  { symbol: "platform", category: "settings" },
  { symbol: "subway", category: "settings" },
  { symbol: "metro", category: "settings" },
  { symbol: "trainyard", category: "settings" },
  { symbol: "depot", category: "settings" },
  { symbol: "busstop", category: "settings" },
  { symbol: "parking", category: "settings" },
  { symbol: "roadway", category: "settings" },
  { symbol: "interstate", category: "settings" },
  { symbol: "expressway", category: "settings" },
  { symbol: "overpass", category: "settings" },
  { symbol: "underpass", category: "settings" },
  { symbol: "hotel", category: "settings" },
  { symbol: "motel", category: "settings" },
  { symbol: "hostel", category: "settings" },
  { symbol: "resort", category: "settings" },
  { symbol: "lodge", category: "settings" },
  { symbol: "inn", category: "settings" },
  { symbol: "guesthouse", category: "settings" },
  { symbol: "cabin", category: "settings" },
  { symbol: "hut", category: "settings" },
  { symbol: "tent", category: "settings" },
  { symbol: "camp", category: "settings" },
  { symbol: "campground", category: "settings" },
  { symbol: "basecamp", category: "settings" },
  { symbol: "shelter", category: "settings" },
  { symbol: "refuge", category: "settings" },
  { symbol: "hideout", category: "settings" },
  { symbol: "bunker", category: "settings" },
  { symbol: "fort", category: "settings" },
  { symbol: "castle", category: "settings" },
  { symbol: "palace", category: "settings" },
  { symbol: "tower", category: "settings" },
  { symbol: "skyscraper", category: "settings" },
  { symbol: "building", category: "settings" },
  { symbol: "structure", category: "settings" },
  { symbol: "complex", category: "settings" },
  { symbol: "facility", category: "settings" },
  { symbol: "compound", category: "settings" },
  { symbol: "estate", category: "settings" },
  { symbol: "mansion", category: "settings" },
  { symbol: "neighborhood", category: "settings" },
  { symbol: "district", category: "settings" },
  { symbol: "quarter", category: "settings" },
  { symbol: "sector", category: "settings" },
  { symbol: "zone", category: "settings" },
  { symbol: "territory", category: "settings" },
  { symbol: "region", category: "settings" },
  { symbol: "province", category: "settings" },
  { symbol: "state", category: "settings" },
  { symbol: "country", category: "settings" },
  { symbol: "continent", category: "settings" },
  { symbol: "planet", category: "settings" },
  { symbol: "world", category: "settings" },
  { symbol: "galaxy", category: "settings" },
  { symbol: "universe", category: "settings" },
  { symbol: "dimension", category: "settings" },
  { symbol: "realm", category: "settings" },
  { symbol: "kingdom", category: "settings" },
  { symbol: "empire", category: "settings" },
  { symbol: "colony", category: "settings" },
  { symbol: "space", category: "settings" },
  { symbol: "orbit", category: "settings" },
  { symbol: "spaceship", category: "settings" },
  { symbol: "observatory", category: "settings" },
  { symbol: "planetarium", category: "settings" },
  { symbol: "controlroom", category: "settings" },
  { symbol: "cockpit", category: "settings" },
  { symbol: "ship", category: "settings" },
  { symbol: "boat", category: "settings" },
  { symbol: "vessel", category: "settings" },
  { symbol: "raft", category: "settings" },
  { symbol: "canoe", category: "settings" },
  { symbol: "kayak", category: "settings" },
  { symbol: "submarine", category: "settings" },
  { symbol: "yacht", category: "settings" },
  { symbol: "ferry", category: "settings" },
  { symbol: "liner", category: "settings" },
  { symbol: "car", category: "settings" },
  { symbol: "vehicle", category: "settings" },
  { symbol: "truck", category: "settings" },
  { symbol: "van", category: "settings" },
  { symbol: "bus", category: "settings" },
  { symbol: "taxi", category: "settings" },
  { symbol: "train", category: "settings" },
  { symbol: "tram", category: "settings" },
  { symbol: "bicycle", category: "settings" },
  { symbol: "motorcycle", category: "settings" },
  { symbol: "elevator", category: "settings" },
  { symbol: "staircase", category: "settings" },
  { symbol: "escalator", category: "settings" },
  { symbol: "corridor", category: "settings" },
  { symbol: "lobby", category: "settings" },
  { symbol: "atrium", category: "settings" },
  { symbol: "terrace", category: "settings" },
  { symbol: "cellar", category: "settings" },
  { symbol: "vault", category: "settings" },
  { symbol: "safe", category: "settings" },
  { symbol: "archive", category: "settings" },
  { symbol: "storage", category: "settings" },
  { symbol: "pantry", category: "settings" },
  { symbol: "closet", category: "settings" },
  { symbol: "wardrobe", category: "settings" },
  { symbol: "mirrorroom", category: "settings" },
  { symbol: "ballroom", category: "settings" },
  { symbol: "banquet", category: "settings" },
  { symbol: "kitchenette", category: "settings" },
  { symbol: "laundry", category: "settings" },
  { symbol: "bathhouse", category: "settings" },
  { symbol: "sauna", category: "settings" },
  { symbol: "greenhouse", category: "settings" },
  { symbol: "arboretum", category: "settings" },
  { symbol: "conservatory", category: "settings" },
  { symbol: "nursery", category: "settings" },
  { symbol: "vineyard", category: "settings" },
  { symbol: "farmhouse", category: "settings" },
  { symbol: "barn", category: "settings" },
  { symbol: "stable", category: "settings" },
  { symbol: "ranch", category: "settings" },
  { symbol: "volcano", category: "settings" },
  { symbol: "crater", category: "settings" },
  { symbol: "lavafield", category: "settings" },
  { symbol: "cave", category: "settings" },
  { symbol: "cavern", category: "settings" },
  { symbol: "grotto", category: "settings" },
  { symbol: "mine", category: "settings" },
  { symbol: "quarry", category: "settings" },
  { symbol: "pit", category: "settings" },
  { symbol: "archway", category: "settings" },
  { symbol: "gate", category: "settings" },
  { symbol: "entrance", category: "settings" },
  { symbol: "exit", category: "settings" },
  { symbol: "doorway", category: "settings" },
  { symbol: "portal", category: "settings" },
  { symbol: "passage", category: "settings" },
  { symbol: "pathway", category: "settings" },
  { symbol: "living room", category: "settings" },
  { symbol: "dining room", category: "settings" },
  { symbol: "laundry room", category: "settings" },
  { symbol: "patio", category: "settings" },
  { symbol: "backyard", category: "settings" },
  { symbol: "front yard", category: "settings" },
  { symbol: "apartment building", category: "settings" },
  { symbol: "dorm", category: "settings" },
  { symbol: "cottage", category: "settings" },
  { symbol: "conference room", category: "settings" },
  { symbol: "waiting room", category: "settings" },
  { symbol: "university", category: "settings" },
  { symbol: "emergency room", category: "settings" },
  { symbol: "operating room", category: "settings" },
  { symbol: "dentist office", category: "settings" },
  { symbol: "therapist office", category: "settings" },
  { symbol: "courtroom", category: "settings" },
  { symbol: "police station", category: "settings" },
  { symbol: "jail", category: "settings" },
  { symbol: "prison", category: "settings" },
  { symbol: "fire station", category: "settings" },
  { symbol: "bank", category: "settings" },
  { symbol: "grocery store", category: "settings" },
  { symbol: "convenience store", category: "settings" },
  { symbol: "department store", category: "settings" },
  { symbol: "clothing store", category: "settings" },
  { symbol: "diner", category: "settings" },
  { symbol: "bakery", category: "settings" },
  { symbol: "nightclub", category: "settings" },
  { symbol: "movie theater", category: "settings" },
  { symbol: "gym", category: "settings" },
  { symbol: "fitness center", category: "settings" },
  { symbol: "swimming pool", category: "settings" },
  { symbol: "locker room", category: "settings" },
  { symbol: "spa", category: "settings" },
  { symbol: "salon", category: "settings" },
  { symbol: "rainforest", category: "settings" },
  { symbol: "mountain trail", category: "settings" },
  { symbol: "shoreline", category: "settings" },
  { symbol: "lighthouse", category: "settings" },
  { symbol: "freeway", category: "settings" },
  { symbol: "parking lot", category: "settings" },
  { symbol: "parking garage", category: "settings" },
  { symbol: "gas station", category: "settings" },
  { symbol: "bus stop", category: "settings" },
  { symbol: "train station", category: "settings" },
  { symbol: "subway station", category: "settings" },
  { symbol: "airplane cabin", category: "settings" },
  { symbol: "space station", category: "settings" },
  { symbol: "battlefield", category: "settings" },
  { symbol: "warzone", category: "settings" },
  { symbol: "military base", category: "settings" },
  { symbol: "refugee camp", category: "settings" },
  { symbol: "construction site", category: "settings" },
  { symbol: "storage facility", category: "settings" },
  { symbol: "power plant", category: "settings" },
  { symbol: "lighthouse tower", category: "settings" },
  { symbol: "art gallery", category: "settings" },
  { symbol: "amusement park", category: "settings" },
  { symbol: "carnival", category: "settings" },
  { symbol: "fairground", category: "settings" },
  { symbol: "zoo", category: "settings" },
  { symbol: "aquarium", category: "settings" },
  { symbol: "theme park", category: "settings" },
  { symbol: "campsite", category: "settings" },
  { symbol: "hiking trail", category: "settings" },
  { symbol: "ski resort", category: "settings" },
  { symbol: "ski lodge", category: "settings" },
  { symbol: "glacier", category: "settings" },
  { symbol: "arctic", category: "settings" },
  { symbol: "wetlands", category: "settings" },
  { symbol: "ruins", category: "settings" },
  { symbol: "underground tunnel", category: "settings" },
  { symbol: "subway tunnel", category: "settings" },
  { symbol: "sewer", category: "settings" },
  { symbol: "storm drain", category: "settings" },
  { symbol: "rooftop", category: "settings" },
  { symbol: "rooftop garden", category: "settings" },
  { symbol: "balcony edge", category: "settings" },
  { symbol: "treehouse", category: "settings" },
  { symbol: "secret room", category: "settings" },
  { symbol: "hidden passage", category: "settings" },
  { symbol: "maze", category: "settings" },
  { symbol: "labyrinth", category: "settings" },
  { symbol: "dreamscape", category: "settings" },
  { symbol: "boiler room", category: "settings" },
  { symbol: "furnace room", category: "settings" },
  { symbol: "utility room", category: "settings" },
  { symbol: "mudroom", category: "settings" },
  { symbol: "wine cellar", category: "settings" },
  { symbol: "root cellar", category: "settings" },
  { symbol: "storm cellar", category: "settings" },
  { symbol: "safe room", category: "settings" },
  { symbol: "guest room", category: "settings" },
  { symbol: "playroom", category: "settings" },
  { symbol: "game room", category: "settings" },
  { symbol: "craft room", category: "settings" },
  { symbol: "sewing room", category: "settings" },
  { symbol: "sunroom", category: "settings" },
  { symbol: "veranda", category: "settings" },
  { symbol: "breezeway", category: "settings" },
  { symbol: "rooftop deck", category: "settings" },
  { symbol: "rooftop bar", category: "settings" },
  { symbol: "rooftop pool", category: "settings" },
  { symbol: "garden path", category: "settings" },
  { symbol: "garden shed", category: "settings" },
  { symbol: "tool shed", category: "settings" },
  { symbol: "potting shed", category: "settings" },
  { symbol: "chicken coop", category: "settings" },
  { symbol: "pig pen", category: "settings" },
  { symbol: "hay loft", category: "settings" },
  { symbol: "grain silo", category: "settings" },
  { symbol: "windmill", category: "settings" },
  { symbol: "water tower", category: "settings" },
  { symbol: "pump house", category: "settings" },
  { symbol: "well house", category: "settings" },
  { symbol: "irrigation ditch", category: "settings" },
  { symbol: "cornfield", category: "settings" },
  { symbol: "wheat field", category: "settings" },
  { symbol: "rice field", category: "settings" },
  { symbol: "sunflower field", category: "settings" },
  { symbol: "pumpkin patch", category: "settings" },
  { symbol: "berry field", category: "settings" },
  { symbol: "bamboo forest", category: "settings" },
  { symbol: "mangrove", category: "settings" },
  { symbol: "woodland", category: "settings" },
  { symbol: "boiler area", category: "settings" },
  { symbol: "engine room", category: "settings" },
  { symbol: "control room", category: "settings" },
  { symbol: "control tower", category: "settings" },
  { symbol: "radio station", category: "settings" },
  { symbol: "television studio", category: "settings" },
  { symbol: "film studio", category: "settings" },
  { symbol: "recording studio", category: "settings" },
  { symbol: "rehearsal room", category: "settings" },
  { symbol: "stage", category: "settings" },
  { symbol: "backstage", category: "settings" },
  { symbol: "dressing room", category: "settings" },
  { symbol: "makeup room", category: "settings" },
  { symbol: "costume room", category: "settings" },
  { symbol: "orchestra pit", category: "settings" },
  { symbol: "concert hall", category: "settings" },
  { symbol: "opera house", category: "settings" },
  { symbol: "recital hall", category: "settings" },
  { symbol: "dance studio", category: "settings" },
  { symbol: "yoga studio", category: "settings" },
  { symbol: "martial arts dojo", category: "settings" },
  { symbol: "boxing gym", category: "settings" },
  { symbol: "weight room", category: "settings" },
  { symbol: "steam room", category: "settings" },
  { symbol: "massage room", category: "settings" },
  { symbol: "therapy office", category: "settings" },
  { symbol: "counseling office", category: "settings" },
  { symbol: "doctor office", category: "settings" },
  { symbol: "exam room", category: "settings" },
  { symbol: "hospital ward", category: "settings" },
  { symbol: "recovery room", category: "settings" },
  { symbol: "maternity ward", category: "settings" },
  { symbol: "delivery room", category: "settings" },
  { symbol: "nurse station", category: "settings" },
  { symbol: "pharmacy counter", category: "settings" },
  { symbol: "testing lab", category: "settings" },
  { symbol: "xray room", category: "settings" },
  { symbol: "mri room", category: "settings" },
  { symbol: "ct room", category: "settings" },
  { symbol: "operating theater", category: "settings" },
  { symbol: "supply room", category: "settings" },
  { symbol: "ambulance bay", category: "settings" },
  { symbol: "emergency entrance", category: "settings" },
  { symbol: "triage area", category: "settings" },
  { symbol: "waiting lobby", category: "settings" },
  { symbol: "chapel room", category: "settings" },
  { symbol: "nursing home", category: "settings" },
  { symbol: "rehabilitation center", category: "settings" },
  { symbol: "therapy room", category: "settings" },
  { symbol: "dental clinic", category: "settings" },
  { symbol: "orthodontist office", category: "settings" },
  { symbol: "optometrist office", category: "settings" },
  { symbol: "veterinary clinic", category: "settings" },
  { symbol: "animal hospital", category: "settings" },
  { symbol: "kennel", category: "settings" },
  { symbol: "grooming salon", category: "settings" },
  { symbol: "pet daycare", category: "settings" },
  { symbol: "dog park", category: "settings" },
  { symbol: "riding arena", category: "settings" },
  { symbol: "rodeo arena", category: "settings" },
  { symbol: "dairy farm", category: "settings" },
  { symbol: "butcher shop", category: "settings" },
  { symbol: "fish hatchery", category: "settings" },
  { symbol: "botanical garden", category: "settings" },
  { symbol: "rose garden", category: "settings" },
  { symbol: "hedge maze", category: "settings" },
  { symbol: "public square", category: "settings" },
  { symbol: "town square", category: "settings" },
  { symbol: "civic center", category: "settings" },
  { symbol: "government office", category: "settings" },
  { symbol: "city hall", category: "settings" },
  { symbol: "parliament hall", category: "settings" },
  { symbol: "capitol building", category: "settings" },
  { symbol: "embassy", category: "settings" },
  { symbol: "consulate", category: "settings" },
  { symbol: "courthouse", category: "settings" },
  { symbol: "jury room", category: "settings" },
  { symbol: "holding cell", category: "settings" },
  { symbol: "interrogation room", category: "settings" },
  { symbol: "evidence room", category: "settings" },
  { symbol: "police locker room", category: "settings" },
  { symbol: "firehouse", category: "settings" },
  { symbol: "training tower", category: "settings" },
  { symbol: "command center", category: "settings" },
  { symbol: "border crossing", category: "settings" },
  { symbol: "customs office", category: "settings" },
  { symbol: "immigration office", category: "settings" },
  { symbol: "passport control", category: "settings" },
  { symbol: "baggage claim", category: "settings" },
  { symbol: "departure gate", category: "settings" },
  { symbol: "arrival hall", category: "settings" },
  { symbol: "airport lounge", category: "settings" },
  { symbol: "rail yard", category: "settings" },
  { symbol: "freight depot", category: "settings" },
  { symbol: "bus depot", category: "settings" },
  { symbol: "metro platform", category: "settings" },
  { symbol: "tram station", category: "settings" },
  { symbol: "trolley stop", category: "settings" },
  { symbol: "taxi stand", category: "settings" },
  { symbol: "car wash", category: "settings" },
  { symbol: "auto shop", category: "settings" },
  { symbol: "mechanic garage", category: "settings" },
  { symbol: "tire shop", category: "settings" },
  { symbol: "body shop", category: "settings" },
  { symbol: "gas pump", category: "settings" },
  { symbol: "truck stop", category: "settings" },
  { symbol: "rest area", category: "settings" },
  { symbol: "toll booth", category: "settings" },
  { symbol: "checkpoint", category: "settings" },
  { symbol: "guard tower", category: "settings" },
  { symbol: "prison yard", category: "settings" },
  { symbol: "prison block", category: "settings" },
  { symbol: "prison cafeteria", category: "settings" },
  { symbol: "prison cell", category: "settings" },
  { symbol: "watchtower", category: "settings" },
  { symbol: "fortress", category: "settings" },
  { symbol: "castle hall", category: "settings" },
  { symbol: "throne room", category: "settings" },
  { symbol: "dungeon", category: "settings" },
  { symbol: "catacombs", category: "settings" },
  { symbol: "burial chamber", category: "settings" },
  { symbol: "memorial park", category: "settings" },
  { symbol: "trench", category: "settings" },
  { symbol: "command bunker", category: "settings" },
  { symbol: "airfield", category: "settings" },
  { symbol: "radar station", category: "settings" },
  { symbol: "simulator room", category: "settings" },
  { symbol: "launch pad", category: "settings" },
  { symbol: "mission control", category: "settings" },
  { symbol: "telescope dome", category: "settings" },
  { symbol: "satellite station", category: "settings" },
  { symbol: "research station", category: "settings" },
  { symbol: "polar station", category: "settings" },
  { symbol: "base camp", category: "settings" },
  { symbol: "marine lab", category: "settings" },
  { symbol: "underwater lab", category: "settings" },
  { symbol: "underwater tunnel", category: "settings" },
  { symbol: "underwater cave", category: "settings" },
  { symbol: "floating platform", category: "settings" },
  { symbol: "oil rig", category: "settings" },
  { symbol: "drilling platform", category: "settings" },
  { symbol: "mining camp", category: "settings" },
  { symbol: "coal mine", category: "settings" },
  { symbol: "gold mine", category: "settings" },
  { symbol: "mine shaft", category: "settings" },
  { symbol: "refinery", category: "settings" },
  { symbol: "chemical plant", category: "settings" },
  { symbol: "steel mill", category: "settings" },
  { symbol: "assembly plant", category: "settings" },
  { symbol: "production line", category: "settings" },
  { symbol: "shipping warehouse", category: "settings" },
  { symbol: "logistics hub", category: "settings" },
  { symbol: "cargo terminal", category: "settings" },
  { symbol: "distribution center", category: "settings" },
  { symbol: "cold storage", category: "settings" },
  { symbol: "auction house", category: "settings" },
  { symbol: "antique shop", category: "settings" },
  { symbol: "pawn shop", category: "settings" },
  { symbol: "flea market", category: "settings" },
  { symbol: "farmers market", category: "settings" },
  { symbol: "street market", category: "settings" },
  { symbol: "spice market", category: "settings" },
  { symbol: "fabric market", category: "settings" },
  { symbol: "fish market", category: "settings" },
  { symbol: "butcher market", category: "settings" },
  { symbol: "produce market", category: "settings" },
  { symbol: "craft fair", category: "settings" },
  { symbol: "festival grounds", category: "settings" },
  { symbol: "parade route", category: "settings" },
  { symbol: "midway", category: "settings" },
  { symbol: "dormitory", category: "settings" },
  { symbol: "hotel room", category: "settings" },
  { symbol: "motel room", category: "settings" },
  { symbol: "cabin room", category: "settings" },
  { symbol: "tower room", category: "settings" },
  { symbol: "patio deck", category: "settings" },
  { symbol: "front porch", category: "settings" },
  { symbol: "back porch", category: "settings" },
  { symbol: "driveway gate", category: "settings" },
  { symbol: "garden gate", category: "settings" },
  { symbol: "greenhouse aisle", category: "settings" },
  { symbol: "greenhouse bench", category: "settings" },
  { symbol: "plant shop", category: "settings" },
  { symbol: "flower shop", category: "settings" },
  { symbol: "bakery shop", category: "settings" },
  { symbol: "coffee shop", category: "settings" },
  { symbol: "tea shop", category: "settings" },
  { symbol: "bookshop", category: "settings" },
  { symbol: "stationery shop", category: "settings" },
  { symbol: "toy store", category: "settings" },
  { symbol: "electronics store", category: "settings" },
  { symbol: "hardware store", category: "settings" },
  { symbol: "furniture store", category: "settings" },
  { symbol: "shoe store", category: "settings" },
  { symbol: "jewelry store", category: "settings" },
  { symbol: "watch shop", category: "settings" },
  { symbol: "clothing boutique", category: "settings" },
  { symbol: "tailor shop", category: "settings" },
  { symbol: "barber shop", category: "settings" },
  { symbol: "hair salon", category: "settings" },
  { symbol: "nail salon", category: "settings" },
  { symbol: "spa room", category: "settings" },
  { symbol: "massage studio", category: "settings" },
  { symbol: "tattoo shop", category: "settings" },
  { symbol: "piercing shop", category: "settings" },
  { symbol: "photo studio", category: "settings" },
  { symbol: "print shop", category: "settings" },
  { symbol: "copy shop", category: "settings" },
  { symbol: "shipping store", category: "settings" },
  { symbol: "package center", category: "settings" },
  { symbol: "recycling center", category: "settings" },
  { symbol: "landfill", category: "settings" },
  { symbol: "dump site", category: "settings" },
  { symbol: "water treatment plant", category: "settings" },
  { symbol: "aqueduct", category: "settings" },
  { symbol: "dam wall", category: "settings" },
  { symbol: "spillway", category: "settings" },
  { symbol: "lock chamber", category: "settings" },
  { symbol: "harbor dock", category: "settings" },
  { symbol: "cargo dock", category: "settings" },
  { symbol: "ferry dock", category: "settings" },
  { symbol: "boat launch", category: "settings" },
  { symbol: "marina pier", category: "settings" },
  { symbol: "shipyard", category: "settings" },
  { symbol: "dry dock", category: "settings" },
  { symbol: "naval dock", category: "settings" },
  { symbol: "fishing dock", category: "settings" },
  { symbol: "fish pier", category: "settings" },
  { symbol: "boat house", category: "settings" },
  { symbol: "canoe launch", category: "settings" },
  { symbol: "kayak launch", category: "settings" },
  { symbol: "boat ramp", category: "settings" },

  {
    symbol: "condo",
    category: "settings",
  },
  {
    symbol: "villa",
    category: "settings",
  },
  {
    symbol: "bungalow",
    category: "settings",
  },
  {
    symbol: "townhouse",
    category: "settings",
  },
  {
    symbol: "trailer",
    category: "settings",
  },
  {
    symbol: "rv park",
    category: "settings",
  },
  {
    symbol: "metropolis",
    category: "settings",
  },
  {
    symbol: "downtown",
    category: "settings",
  },
  {
    symbol: "bus station",
    category: "settings",
  },
  {
    symbol: "reef",
    category: "settings",
  },
  {
    symbol: "icefield",
    category: "settings",
  },
  {
    symbol: "farmland",
    category: "settings",
  },
  {
    symbol: "bookstore",
    category: "settings",
  },
  {
    symbol: "boutique",
    category: "settings",
  },
  {
    symbol: "dentist",
    category: "settings",
  },
  {
    symbol: "therapist",
    category: "settings",
  },
  {
    symbol: "dockyard",
    category: "settings",
  },
  {
    symbol: "barracks",
    category: "settings",
  },
  {
    symbol: "parliament",
    category: "settings",
  },
  {
    symbol: "capitol",
    category: "settings",
  },
  {
    symbol: "monument",
    category: "settings",
  },
  {
    symbol: "tower block",
    category: "settings",
  },
  {
    symbol: "office tower",
    category: "settings",
  },
  {
    symbol: "college",
    category: "settings",
  },
  {
    symbol: "academy",
    category: "settings",
  },
  {
    symbol: "kindergarten",
    category: "settings",
  },
  {
    symbol: "daycare",
    category: "settings",
  },
  {
    symbol: "playground park",
    category: "settings",
  },
  {
    symbol: "sports field",
    category: "settings",
  },
  {
    symbol: "soccer field",
    category: "settings",
  },
  {
    symbol: "baseball field",
    category: "settings",
  },
  {
    symbol: "basketball court",
    category: "settings",
  },
  {
    symbol: "tennis court",
    category: "settings",
  },
  {
    symbol: "ice rink",
    category: "settings",
  },
  {
    symbol: "golf course",
    category: "settings",
  },
  {
    symbol: "racetrack",
    category: "settings",
  },
  {
    symbol: "shooting range",
    category: "settings",
  },
  {
    symbol: "dojo",
    category: "settings",
  },
  {
    symbol: "training ground",
    category: "settings",
  },
  {
    symbol: "campsite forest",
    category: "settings",
  },
  {
    symbol: "summer camp",
    category: "settings",
  },
  {
    symbol: "scout camp",
    category: "settings",
  },
  {
    symbol: "customs",
    category: "settings",
  },
  {
    symbol: "embassy compound",
    category: "settings",
  },
  {
    symbol: "harbor town",
    category: "settings",
  },
  {
    symbol: "fishing village",
    category: "settings",
  },
  {
    symbol: "port city",
    category: "settings",
  },
  {
    symbol: "industrial park",
    category: "settings",
  },
  {
    symbol: "business district",
    category: "settings",
  },
  {
    symbol: "technology park",
    category: "settings",
  },
  {
    symbol: "television station",
    category: "settings",
  },
  {
    symbol: "spa resort",
    category: "settings",
  },
  {
    symbol: "spa center",
    category: "settings",
  },
  {
    symbol: "therapy center",
    category: "settings",
  },
  {
    symbol: "assisted living",
    category: "settings",
  },
  {
    symbol: "animal shelter",
    category: "settings",
  },
  {
    symbol: "pet shop",
    category: "settings",
  },
  {
    symbol: "slaughterhouse",
    category: "settings",
  },
  {
    symbol: "government building",
    category: "settings",
  },
  {
    symbol: "courthouse plaza",
    category: "settings",
  },
  {
    symbol: "parliament building",
    category: "settings",
  },
  {
    symbol: "embassy grounds",
    category: "settings",
  },
  {
    symbol: "consulate grounds",
    category: "settings",
  },
  {
    symbol: "cathedral grounds",
    category: "settings",
  },
  {
    symbol: "monastery grounds",
    category: "settings",
  },
  {
    symbol: "temple grounds",
    category: "settings",
  },
  {
    symbol: "shrine grounds",
    category: "settings",
  },
  {
    symbol: "graveyard grounds",
    category: "settings",
  },
  {
    symbol: "cemetery grounds",
    category: "settings",
  },
  {
    symbol: "citadel",
    category: "settings",
  },
  {
    symbol: "castle grounds",
    category: "settings",
  },
  {
    symbol: "palace grounds",
    category: "settings",
  },
  {
    symbol: "tower summit",
    category: "settings",
  },
  {
    symbol: "mountaintop",
    category: "settings",
  },
  {
    symbol: "ridgeline",
    category: "settings",
  },
  {
    symbol: "canyon floor",
    category: "settings",
  },
  {
    symbol: "river delta",
    category: "settings",
  },
  {
    symbol: "floodplain",
    category: "settings",
  },
  {
    symbol: "estuary",
    category: "settings",
  },
  {
    symbol: "coastal cliff",
    category: "settings",
  },
  {
    symbol: "sea cave",
    category: "settings",
  },
  {
    symbol: "iceberg field",
    category: "settings",
  },
  {
    symbol: "ice cave",
    category: "settings",
  },
  {
    symbol: "arctic base",
    category: "settings",
  },
  {
    symbol: "antarctic base",
    category: "settings",
  },
  {
    symbol: "research base",
    category: "settings",
  },
  {
    symbol: "underwater station",
    category: "settings",
  },
  {
    symbol: "quarry pit",
    category: "settings",
  },
  {
    symbol: "refinery plant",
    category: "settings",
  },
  {
    symbol: "production plant",
    category: "settings",
  },
  {
    symbol: "water plant",
    category: "settings",
  },
  {
    symbol: "treatment plant",
    category: "settings",
  },
  {
    symbol: "reservoir dam",
    category: "settings",
  },
  {
    symbol: "ferry terminal",
    category: "settings",
  },
  {
    symbol: "marina harbor",
    category: "settings",
  },
  {
    symbol: "shipyard dock",
    category: "settings",
  },
  {
    symbol: "naval base",
    category: "settings",
  },
  {
    symbol: "coast guard station",
    category: "settings",
  },
  {
    symbol: "submarine base",
    category: "settings",
  },
  {
    symbol: "training camp",
    category: "settings",
  },
  {
    symbol: "obstacle course",
    category: "settings",
  },
  {
    symbol: "archery range",
    category: "settings",
  },
  {
    symbol: "driving range",
    category: "settings",
  },
  {
    symbol: "batting cage",
    category: "settings",
  },
  {
    symbol: "skating rink",
    category: "settings",
  },
  {
    symbol: "trampoline park",
    category: "settings",
  },
  {
    symbol: "bowling alley",
    category: "settings",
  },
  {
    symbol: "arcade",
    category: "settings",
  },
  {
    symbol: "gaming center",
    category: "settings",
  },
  {
    symbol: "escape room",
    category: "settings",
  },
  {
    symbol: "billiards hall",
    category: "settings",
  },
  {
    symbol: "pool hall",
    category: "settings",
  },
  {
    symbol: "internet cafe",
    category: "settings",
  },
  {
    symbol: "coworking space",
    category: "settings",
  },
  {
    symbol: "startup office",
    category: "settings",
  },
  {
    symbol: "corporate office",
    category: "settings",
  },
  {
    symbol: "executive office",
    category: "settings",
  },
  {
    symbol: "conference center",
    category: "settings",
  },
  {
    symbol: "convention center",
    category: "settings",
  },
  {
    symbol: "expo center",
    category: "settings",
  },
  {
    symbol: "fairgrounds",
    category: "settings",
  },
  {
    symbol: "water park",
    category: "settings",
  },

  {
    symbol: "boathouse",
    category: "settings",
  },
  {
    symbol: "ferryboat",
    category: "settings",
  },
  {
    symbol: "cruise ship",
    category: "settings",
  },
  {
    symbol: "cargo ship",
    category: "settings",
  },
  {
    symbol: "container ship",
    category: "settings",
  },
  {
    symbol: "submersible",
    category: "settings",
  },
  {
    symbol: "sailboat",
    category: "settings",
  },
  {
    symbol: "speedboat",
    category: "settings",
  },
  {
    symbol: "motorboat",
    category: "settings",
  },
  {
    symbol: "paddleboat",
    category: "settings",
  },
  {
    symbol: "rowboat",
    category: "settings",
  },
  {
    symbol: "hovercraft",
    category: "settings",
  },
  {
    symbol: "jet ski",
    category: "settings",
  },
  {
    symbol: "gondola",
    category: "settings",
  },
  {
    symbol: "cable car",
    category: "settings",
  },
  {
    symbol: "ski lift",
    category: "settings",
  },
  {
    symbol: "monorail",
    category: "settings",
  },
  {
    symbol: "trolley",
    category: "settings",
  },
  {
    symbol: "bullet train",
    category: "settings",
  },
  {
    symbol: "locomotive",
    category: "settings",
  },
  {
    symbol: "freight yard",
    category: "settings",
  },
  {
    symbol: "ship channel",
    category: "settings",
  },
  {
    symbol: "canal lock",
    category: "settings",
  },
  {
    symbol: "dam reservoir",
    category: "settings",
  },
  {
    symbol: "irrigation canal",
    category: "settings",
  },
  {
    symbol: "drainage ditch",
    category: "settings",
  },
  {
    symbol: "flood channel",
    category: "settings",
  },
  {
    symbol: "flood basin",
    category: "settings",
  },
  {
    symbol: "watershed",
    category: "settings",
  },
  {
    symbol: "gulf",
    category: "settings",
  },
  {
    symbol: "archipelago",
    category: "settings",
  },
  {
    symbol: "atoll",
    category: "settings",
  },
  {
    symbol: "sandbar",
    category: "settings",
  },
  {
    symbol: "reef island",
    category: "settings",
  },
  {
    symbol: "tidepool area",
    category: "settings",
  },
  {
    symbol: "salt flat",
    category: "settings",
  },
  {
    symbol: "badlands",
    category: "settings",
  },
  {
    symbol: "mesa",
    category: "settings",
  },
  {
    symbol: "butte",
    category: "settings",
  },
  {
    symbol: "volcanic crater",
    category: "settings",
  },
  {
    symbol: "caldera",
    category: "settings",
  },
  {
    symbol: "lava field",
    category: "settings",
  },
  {
    symbol: "lava tube",
    category: "settings",
  },
  {
    symbol: "geyser basin",
    category: "settings",
  },
  {
    symbol: "hot spring",
    category: "settings",
  },
  {
    symbol: "sinkhole",
    category: "settings",
  },
  {
    symbol: "cave chamber",
    category: "settings",
  },
  {
    symbol: "cave system",
    category: "settings",
  },
  {
    symbol: "underground river",
    category: "settings",
  },
  {
    symbol: "underground lake",
    category: "settings",
  },
  {
    symbol: "mine tunnel",
    category: "settings",
  },
  {
    symbol: "mineshaft chamber",
    category: "settings",
  },
  {
    symbol: "quarry wall",
    category: "settings",
  },
  {
    symbol: "quarry basin",
    category: "settings",
  },
  {
    symbol: "quarry yard",
    category: "settings",
  },
  {
    symbol: "gravel pit",
    category: "settings",
  },
  {
    symbol: "sand pit",
    category: "settings",
  },
  {
    symbol: "drilling field",
    category: "settings",
  },
  {
    symbol: "oil field",
    category: "settings",
  },
  {
    symbol: "gas field",
    category: "settings",
  },
  {
    symbol: "pipeline corridor",
    category: "settings",
  },
  {
    symbol: "wind farm",
    category: "settings",
  },
  {
    symbol: "solar farm",
    category: "settings",
  },
  {
    symbol: "power substation",
    category: "settings",
  },
  {
    symbol: "transmission yard",
    category: "settings",
  },
  {
    symbol: "water tower base",
    category: "settings",
  },
  {
    symbol: "pump station",
    category: "settings",
  },
  {
    symbol: "water reservoir dam",
    category: "settings",
  },
  {
    symbol: "canal bridge",
    category: "settings",
  },
  {
    symbol: "railway bridge",
    category: "settings",
  },
  {
    symbol: "suspension bridge",
    category: "settings",
  },
  {
    symbol: "drawbridge",
    category: "settings",
  },
  {
    symbol: "causeway",
    category: "settings",
  },
  {
    symbol: "viaduct",
    category: "settings",
  },
  {
    symbol: "toll plaza",
    category: "settings",
  },
  {
    symbol: "interchange",
    category: "settings",
  },
  {
    symbol: "rest stop",
    category: "settings",
  },
  {
    symbol: "weigh station",
    category: "settings",
  },
  {
    symbol: "truck depot",
    category: "settings",
  },
  {
    symbol: "truck yard",
    category: "settings",
  },
  {
    symbol: "freight terminal",
    category: "settings",
  },
  {
    symbol: "cargo yard",
    category: "settings",
  },
  {
    symbol: "container yard",
    category: "settings",
  },
  {
    symbol: "shipping yard",
    category: "settings",
  },
  {
    symbol: "distribution hub",
    category: "settings",
  },
  {
    symbol: "loading dockyard",
    category: "settings",
  },
  {
    symbol: "port terminal",
    category: "settings",
  },
  {
    symbol: "harbor basin",
    category: "settings",
  },
  {
    symbol: "harbor wall",
    category: "settings",
  },
  {
    symbol: "marina basin",
    category: "settings",
  },
  {
    symbol: "boatyard",
    category: "settings",
  },
  {
    symbol: "repair yard",
    category: "settings",
  },
  {
    symbol: "aircraft carrier",
    category: "settings",
  },
  {
    symbol: "aircraft deck",
    category: "settings",
  },
  {
    symbol: "helipad",
    category: "settings",
  },
  {
    symbol: "helicopter pad",
    category: "settings",
  },
  {
    symbol: "airstrip",
    category: "settings",
  },
  {
    symbol: "runway field",
    category: "settings",
  },
  {
    symbol: "hangar bay",
    category: "settings",
  },
  {
    symbol: "aircraft hangar",
    category: "settings",
  },
  {
    symbol: "aircraft terminal",
    category: "settings",
  },
  {
    symbol: "boarding gate",
    category: "settings",
  },
  {
    symbol: "baggage hall",
    category: "settings",
  },
  {
    symbol: "radar tower",
    category: "settings",
  },
  {
    symbol: "observation deck",
    category: "settings",
  },
  {
    symbol: "lookout tower",
    category: "settings",
  },
  {
    symbol: "watchtower platform",
    category: "settings",
  },
  {
    symbol: "beacon tower",
    category: "settings",
  },
  {
    symbol: "clock tower",
    category: "settings",
  },
  {
    symbol: "bell tower",
    category: "settings",
  },
  {
    symbol: "signal tower",
    category: "settings",
  },
  {
    symbol: "radio tower",
    category: "settings",
  },
  {
    symbol: "transmission tower",
    category: "settings",
  },
  {
    symbol: "water tower platform",
    category: "settings",
  },
  {
    symbol: "fire lookout",
    category: "settings",
  },
  {
    symbol: "ranger outpost",
    category: "settings",
  },
  {
    symbol: "ranger station",
    category: "settings",
  },
  {
    symbol: "trailhead",
    category: "settings",
  },
  {
    symbol: "trail junction",
    category: "settings",
  },
  {
    symbol: "trail crossing",
    category: "settings",
  },
  {
    symbol: "trail overlook",
    category: "settings",
  },
  {
    symbol: "scenic overlook",
    category: "settings",
  },
  {
    symbol: "mountain pass",
    category: "settings",
  },
  {
    symbol: "ridge path",
    category: "settings",
  },
  {
    symbol: "cliffside path",
    category: "settings",
  },
  {
    symbol: "canyon pass",
    category: "settings",
  },
  {
    symbol: "canyon overlook",
    category: "settings",
  },
  {
    symbol: "canyon basin",
    category: "settings",
  },
  {
    symbol: "valley floor",
    category: "settings",
  },
  {
    symbol: "valley pass",
    category: "settings",
  },
  {
    symbol: "plateau edge",
    category: "settings",
  },
  {
    symbol: "plateau rim",
    category: "settings",
  },
  {
    symbol: "grassland",
    category: "settings",
  },
  {
    symbol: "heathland",
    category: "settings",
  },
  {
    symbol: "moorland",
    category: "settings",
  },
  {
    symbol: "scrubland",
    category: "settings",
  },
  {
    symbol: "thicket",
    category: "settings",
  },
  {
    symbol: "glade",
    category: "settings",
  },
  {
    symbol: "bamboo grove",
    category: "settings",
  },
  {
    symbol: "orchard grove",
    category: "settings",
  },
  {
    symbol: "palm grove",
    category: "settings",
  },
  {
    symbol: "mangrove forest",
    category: "settings",
  },
  {
    symbol: "pine forest",
    category: "settings",
  },
  {
    symbol: "redwood forest",
    category: "settings",
  },
  {
    symbol: "oak forest",
    category: "settings",
  },
  {
    symbol: "cedar forest",
    category: "settings",
  },
  {
    symbol: "spruce forest",
    category: "settings",
  },
  {
    symbol: "peat bog",
    category: "settings",
  },
  {
    symbol: "fen",
    category: "settings",
  },
  {
    symbol: "marshland delta",
    category: "settings",
  },
  {
    symbol: "floodplain meadow",
    category: "settings",
  },
  {
    symbol: "river delta marsh",
    category: "settings",
  },
  {
    symbol: "river island",
    category: "settings",
  },
  {
    symbol: "oxbow lake",
    category: "settings",
  },
  {
    symbol: "creek bend",
    category: "settings",
  },
  {
    symbol: "river crossing",
    category: "settings",
  },
  {
    symbol: "ford",
    category: "settings",
  },
  {
    symbol: "river mouth",
    category: "settings",
  },
  {
    symbol: "river delta island",
    category: "settings",
  },
  {
    symbol: "coastal plain",
    category: "settings",
  },
  {
    symbol: "coastal shelf",
    category: "settings",
  },
  {
    symbol: "sea cliff",
    category: "settings",
  },
  {
    symbol: "sea stack",
    category: "settings",
  },
  {
    symbol: "sea arch",
    category: "settings",
  },
  {
    symbol: "sea tunnel",
    category: "settings",
  },
  {
    symbol: "coastal cave",
    category: "settings",
  },
  {
    symbol: "coastal inlet",
    category: "settings",
  },
  {
    symbol: "harbor inlet",
    category: "settings",
  },
  {
    symbol: "tidal basin",
    category: "settings",
  },
  {
    symbol: "tidal marsh",
    category: "settings",
  },
  {
    symbol: "tidal flat",
    category: "settings",
  },
  {
    symbol: "tidal pool",
    category: "settings",
  },
  {
    symbol: "harbor quay",
    category: "settings",
  },
  {
    symbol: "quay wall",
    category: "settings",
  },
  {
    symbol: "fishing harbor",
    category: "settings",
  },
  {
    symbol: "fishing village harbor",
    category: "settings",
  },
  {
    symbol: "dock basin",
    category: "settings",
  },
  {
    symbol: "harbor slip",
    category: "settings",
  },
  {
    symbol: "marina slip",
    category: "settings",
  },
  {
    symbol: "boat slip",
    category: "settings",
  },
  {
    symbol: "mooring field",
    category: "settings",
  },
  {
    symbol: "mooring dock",
    category: "settings",
  },
  {
    symbol: "floating dock",
    category: "settings",
  },
  {
    symbol: "cruise terminal",
    category: "settings",
  },
  {
    symbol: "harbor terminal",
    category: "settings",
  },
  {
    symbol: "ship berth",
    category: "settings",
  },
  {
    symbol: "ship berth basin",
    category: "settings",
  },
  {
    symbol: "ship channel entrance",
    category: "settings",
  },
  {
    symbol: "port entrance",
    category: "settings",
  },
  {
    symbol: "port basin",
    category: "settings",
  },
  {
    symbol: "harbor breakwater",
    category: "settings",
  },
  {
    symbol: "breakwater wall",
    category: "settings",
  },
  {
    symbol: "seawall",
    category: "settings",
  },
  {
    symbol: "jetty",
    category: "settings",
  },
  {
    symbol: "groyne",
    category: "settings",
  },
  {
    symbol: "boat channel",
    category: "settings",
  },
  {
    symbol: "navigation channel",
    category: "settings",
  },
  {
    symbol: "lighthouse island",
    category: "settings",
  },
  {
    symbol: "lighthouse station",
    category: "settings",
  },
  {
    symbol: "coast guard base",
    category: "settings",
  },
  {
    symbol: "naval yard",
    category: "settings",
  },
  {
    symbol: "naval harbor",
    category: "settings",
  },
  {
    symbol: "naval dockyard",
    category: "settings",
  },
  {
    symbol: "naval pier",
    category: "settings",
  },
  {
    symbol: "submarine dock",
    category: "settings",
  },
  {
    symbol: "submarine pen",
    category: "settings",
  },
  {
    symbol: "submarine harbor",
    category: "settings",
  },
  {
    symbol: "submarine station",
    category: "settings",
  },
  {
    symbol: "naval base harbor",
    category: "settings",
  },
  {
    symbol: "naval command base",
    category: "settings",
  },
  {
    symbol: "military compound",
    category: "settings",
  },
  {
    symbol: "drill ground",
    category: "settings",
  },
  {
    symbol: "parade ground",
    category: "settings",
  },
  {
    symbol: "shooting field",
    category: "settings",
  },
  {
    symbol: "proving ground",
    category: "settings",
  },
  {
    symbol: "missile range",
    category: "settings",
  },
  {
    symbol: "rocket range",
    category: "settings",
  },
  {
    symbol: "launch complex",
    category: "settings",
  },
  {
    symbol: "spaceport",
    category: "settings",
  },
  {
    symbol: "landing pad",
    category: "settings",
  },
  {
    symbol: "landing zone",
    category: "settings",
  },
  {
    symbol: "landing strip",
    category: "settings",
  },
  {
    symbol: "space launch complex",
    category: "settings",
  },
  {
    symbol: "mission complex",
    category: "settings",
  },
  {
    symbol: "astronaut base",
    category: "settings",
  },
  {
    symbol: "research base camp",
    category: "settings",
  },
  {
    symbol: "polar camp",
    category: "settings",
  },
  {
    symbol: "ice camp",
    category: "settings",
  },
  {
    symbol: "glacier camp",
    category: "settings",
  },
  {
    symbol: "desert camp",
    category: "settings",
  },
  {
    symbol: "jungle camp",
    category: "settings",
  },
  {
    symbol: "mountain camp",
    category: "settings",
  },
  {
    symbol: "exploration camp",
    category: "settings",
  },
  {
    symbol: "expedition camp",
    category: "settings",
  },
  {
    symbol: "hunting camp",
    category: "settings",
  },
  {
    symbol: "fishing camp",
    category: "settings",
  },
  {
    symbol: "logging camp",
    category: "settings",
  },
  {
    symbol: "mining campyard",
    category: "settings",
  },
  {
    symbol: "quarry camp",
    category: "settings",
  },
  {
    symbol: "oil camp",
    category: "settings",
  },
  {
    symbol: "drilling camp",
    category: "settings",
  },
  {
    symbol: "refugee settlement",
    category: "settings",
  },
  {
    symbol: "tent city",
    category: "settings",
  },
  {
    symbol: "border post",
    category: "settings",
  },
  {
    symbol: "border gate",
    category: "settings",
  },
  {
    symbol: "border checkpoint yard",
    category: "settings",
  },
  {
    symbol: "immigration checkpoint yard",
    category: "settings",
  },
  {
    symbol: "customs checkpoint yard",
    category: "settings",
  },
  {
    symbol: "detention center",
    category: "settings",
  },
  {
    symbol: "holding facility",
    category: "settings",
  },
  {
    symbol: "correctional facility",
    category: "settings",
  },
  {
    symbol: "penitentiary",
    category: "settings",
  },
  {
    symbol: "correctional yard",
    category: "settings",
  },
  {
    symbol: "watch post",
    category: "settings",
  },
  {
    symbol: "guard post",
    category: "settings",
  },
  {
    symbol: "security checkpoint",
    category: "settings",
  },
  {
    symbol: "security gate",
    category: "settings",
  },
  {
    symbol: "patrol base",
    category: "settings",
  },
  {
    symbol: "forward base",
    category: "settings",
  },
  {
    symbol: "outpost",
    category: "settings",
  },
  {
    symbol: "checkpoint base",
    category: "settings",
  },
  {
    symbol: "patrol camp",
    category: "settings",
  },
  {
    symbol: "garrison",
    category: "settings",
  },
  {
    symbol: "stronghold",
    category: "settings",
  },
  {
    symbol: "citadel complex",
    category: "settings",
  },
  {
    symbol: "bastion",
    category: "settings",
  },
  {
    symbol: "rampart",
    category: "settings",
  },
  {
    symbol: "battlement",
    category: "settings",
  },
  {
    symbol: "parapet",
    category: "settings",
  },
  {
    symbol: "fortress yard",
    category: "settings",
  },
  {
    symbol: "castle gate",
    category: "settings",
  },
  {
    symbol: "palace court",
    category: "settings",
  },
  {
    symbol: "palace gardens",
    category: "settings",
  },
  {
    symbol: "royal court",
    category: "settings",
  },
  {
    symbol: "throne hall",
    category: "settings",
  },
  {
    symbol: "audience hall",
    category: "settings",
  },
  {
    symbol: "council chamber",
    category: "settings",
  },
  {
    symbol: "council hall",
    category: "settings",
  },
  {
    symbol: "assembly hall",
    category: "settings",
  },
  {
    symbol: "senate hall",
    category: "settings",
  },
  {
    symbol: "legislative chamber",
    category: "settings",
  },
  {
    symbol: "council chamber hall",
    category: "settings",
  },
  {
    symbol: "government plaza",
    category: "settings",
  },
  {
    symbol: "civic plaza",
    category: "settings",
  },
  {
    symbol: "justice center",
    category: "settings",
  },
  {
    symbol: "administration center",
    category: "settings",
  },
  {
    symbol: "government complex",
    category: "settings",
  },
  {
    symbol: "federal complex",
    category: "settings",
  },
  {
    symbol: "municipal complex",
    category: "settings",
  },
  {
    symbol: "civic complex",
    category: "settings",
  },
  {
    symbol: "embassy complex",
    category: "settings",
  },
  {
    symbol: "diplomatic compound",
    category: "settings",
  },
  {
    symbol: "consulate compound",
    category: "settings",
  },
  {
    symbol: "government compound",
    category: "settings",
  },
  {
    symbol: "industrial complex",
    category: "settings",
  },
  {
    symbol: "factory complex",
    category: "settings",
  },
  {
    symbol: "refinery complex",
    category: "settings",
  },
  {
    symbol: "power complex",
    category: "settings",
  },
  {
    symbol: "research complex",
    category: "settings",
  },
  {
    symbol: "technology campus",
    category: "settings",
  },
  {
    symbol: "industrial yard",
    category: "settings",
  },
  {
    symbol: "mill yard",
    category: "settings",
  },
  {
    symbol: "lumber yard",
    category: "settings",
  },
  {
    symbol: "rail depot",
    category: "settings",
  },
  {
    symbol: "grain depot",
    category: "settings",
  },
  {
    symbol: "grain elevator",
    category: "settings",
  },
  {
    symbol: "grain terminal",
    category: "settings",
  },
  {
    symbol: "stockyard",
    category: "settings",
  },
  {
    symbol: "cattle yard",
    category: "settings",
  },
  {
    symbol: "livestock yard",
    category: "settings",
  },
  {
    symbol: "slaughter yard",
    category: "settings",
  },
  {
    symbol: "meatpacking plant",
    category: "settings",
  },
  {
    symbol: "dairy plant",
    category: "settings",
  },
  {
    symbol: "processing plant",
    category: "settings",
  },
  {
    symbol: "bottling plant",
    category: "settings",
  },
  {
    symbol: "brewery",
    category: "settings",
  },
  {
    symbol: "distillery",
    category: "settings",
  },
  {
    symbol: "winery",
    category: "settings",
  },
  {
    symbol: "vineyard estate",
    category: "settings",
  },
  {
    symbol: "orchard estate",
    category: "settings",
  },
  {
    symbol: "plantation",
    category: "settings",
  },
  {
    symbol: "plantation house grounds",
    category: "settings",
  },
  {
    symbol: "estate grounds",
    category: "settings",
  },
  {
    symbol: "manor grounds",
    category: "settings",
  },
  {
    symbol: "manor house",
    category: "settings",
  },
  {
    symbol: "villa estate",
    category: "settings",
  },
  {
    symbol: "retreat center",
    category: "settings",
  },
  {
    symbol: "convention hall",
    category: "settings",
  },
  {
    symbol: "exhibition hall",
    category: "settings",
  },
  {
    symbol: "trade hall",
    category: "settings",
  },
  {
    symbol: "expo hall",
    category: "settings",
  },
  {
    symbol: "fair pavilion",
    category: "settings",
  },
  {
    symbol: "fair hall",
    category: "settings",
  },
  {
    symbol: "pavilion",
    category: "settings",
  },
  {
    symbol: "bandstand",
    category: "settings",
  },
  {
    symbol: "amphitheater",
    category: "settings",
  },
  {
    symbol: "amphitheatre",
    category: "settings",
  },
  {
    symbol: "coliseum",
    category: "settings",
  },
  {
    symbol: "hippodrome",
    category: "settings",
  },
  {
    symbol: "arena grounds",
    category: "settings",
  },
  {
    symbol: "stadium grounds",
    category: "settings",
  },
  {
    symbol: "racecourse",
    category: "settings",
  },
  {
    symbol: "racetrack oval",
    category: "settings",
  },
  {
    symbol: "speedway",
    category: "settings",
  },
  {
    symbol: "motor speedway",
    category: "settings",
  },
  {
    symbol: "kart track",
    category: "settings",
  },
  {
    symbol: "drag strip",
    category: "settings",
  },
  {
    symbol: "motocross track",
    category: "settings",
  },
  {
    symbol: "cycling track",
    category: "settings",
  },
  {
    symbol: "velodrome",
    category: "settings",
  },
  {
    symbol: "athletics track",
    category: "settings",
  },
  {
    symbol: "cricket ground",
    category: "settings",
  },
  {
    symbol: "rugby ground",
    category: "settings",
  },
  {
    symbol: "polo field",
    category: "settings",
  },
  {
    symbol: "polo ground",
    category: "settings",
  },
  {
    symbol: "training field",
    category: "settings",
  },
  {
    symbol: "practice field",
    category: "settings",
  },
  {
    symbol: "sports complex",
    category: "settings",
  },
  {
    symbol: "recreation complex",
    category: "settings",
  },
  {
    symbol: "recreation center",
    category: "settings",
  },
  {
    symbol: "community center",
    category: "settings",
  },
  {
    symbol: "youth center",
    category: "settings",
  },
  {
    symbol: "senior center",
    category: "settings",
  },
  {
    symbol: "cultural center",
    category: "settings",
  },
  {
    symbol: "arts center",
    category: "settings",
  },
  {
    symbol: "performing arts center",
    category: "settings",
  },
  {
    symbol: "music hall",
    category: "settings",
  },
  {
    symbol: "recital room",
    category: "settings",
  },
  {
    symbol: "dance hall",
    category: "settings",
  },
  {
    symbol: "banquet hall",
    category: "settings",
  },
  {
    symbol: "reception hall",
    category: "settings",
  },
  {
    symbol: "wedding hall",
    category: "settings",
  },
  {
    symbol: "lodge hall",
    category: "settings",
  },
  {
    symbol: "meeting hall",
    category: "settings",
  },
  {
    symbol: "guild hall",
    category: "settings",
  },
  {
    symbol: "town hall complex",
    category: "settings",
  },
  {
    symbol: "guild house",
    category: "settings",
  },
  {
    symbol: "trade house",
    category: "settings",
  },
  {
    symbol: "merchant hall",
    category: "settings",
  },
  {
    symbol: "marketplace square",
    category: "settings",
  },
  {
    symbol: "bazaar square",
    category: "settings",
  },
  {
    symbol: "trading post",
    category: "settings",
  },
  {
    symbol: "trading station",
    category: "settings",
  },
  {
    symbol: "supply depot",
    category: "settings",
  },
  {
    symbol: "supply station",
    category: "settings",
  },
  {
    symbol: "relief station",
    category: "settings",
  },
  {
    symbol: "aid station",
    category: "settings",
  },
  {
    symbol: "field hospital",
    category: "settings",
  },
  {
    symbol: "mobile hospital",
    category: "settings",
  },
  {
    symbol: "emergency shelter",
    category: "settings",
  },
  {
    symbol: "disaster shelter",
    category: "settings",
  },
  {
    symbol: "storm shelter",
    category: "settings",
  },
  {
    symbol: "fallout shelter",
    category: "settings",
  },
];
