import { SingleWordSymbol } from "../dreamSingularSymbols";

export const sexual_objects_symbols: SingleWordSymbol[] = [
  { symbol: "floggerwhip", category: "sexual_objects" },
  { symbol: "analbeads", category: "sexual_objects" },
  { symbol: "dildo", category: "sexual_objects" },
  { symbol: "cocktailshaker", category: "sexual_objects" },
  { symbol: "cockring", category: "sexual_objects" },
  { symbol: "condomwrapper", category: "sexual_objects" },
  { symbol: "bead", category: "sexual_objects" },
  { symbol: "vibrator", category: "sexual_objects" },
  { symbol: "butt plug", category: "sexual_objects" },
  { symbol: "anal beads", category: "sexual_objects" },
  { symbol: "cock ring", category: "sexual_objects" },
  { symbol: "penis sleeve", category: "sexual_objects" },
  { symbol: "penis pump", category: "sexual_objects" },
  { symbol: "prostate massager", category: "sexual_objects" },
  { symbol: "bullet vibrator", category: "sexual_objects" },
  { symbol: "wand massager", category: "sexual_objects" },
  { symbol: "rabbit vibrator", category: "sexual_objects" },
  { symbol: "g spot vibrator", category: "sexual_objects" },
  { symbol: "clitoral stimulator", category: "sexual_objects" },
  { symbol: "suction vibrator", category: "sexual_objects" },
  { symbol: "remote vibrator", category: "sexual_objects" },
  { symbol: "wearable vibrator", category: "sexual_objects" },
  { symbol: "vibrating ring", category: "sexual_objects" },
  { symbol: "delay ring", category: "sexual_objects" },
  { symbol: "chastity cage", category: "sexual_objects" },
  { symbol: "chastity belt", category: "sexual_objects" },
  { symbol: "masturbator sleeve", category: "sexual_objects" },
  { symbol: "pocket masturbator", category: "sexual_objects" },
  { symbol: "male masturbator", category: "sexual_objects" },
  { symbol: "stroker", category: "sexual_objects" },
  { symbol: "sex doll", category: "sexual_objects" },
  { symbol: "love doll", category: "sexual_objects" },
  { symbol: "inflatable doll", category: "sexual_objects" },
  { symbol: "bondage rope", category: "sexual_objects" },
  { symbol: "bondage cuffs", category: "sexual_objects" },
  { symbol: "handcuffs", category: "sexual_objects" },
  { symbol: "ankle cuffs", category: "sexual_objects" },
  { symbol: "wrist cuffs", category: "sexual_objects" },
  { symbol: "spreader bar", category: "sexual_objects" },
  { symbol: "bondage tape", category: "sexual_objects" },
  { symbol: "ball gag", category: "sexual_objects" },
  { symbol: "ring gag", category: "sexual_objects" },
  { symbol: "bit gag", category: "sexual_objects" },
  { symbol: "mouth gag", category: "sexual_objects" },
  { symbol: "blindfold", category: "sexual_objects" },
  { symbol: "hood mask", category: "sexual_objects" },
  { symbol: "leather hood", category: "sexual_objects" },
  { symbol: "latex hood", category: "sexual_objects" },
  { symbol: "paddle", category: "sexual_objects" },
  { symbol: "spanking paddle", category: "sexual_objects" },
  { symbol: "flogger", category: "sexual_objects" },
  { symbol: "whip", category: "sexual_objects" },
  { symbol: "riding crop", category: "sexual_objects" },
  { symbol: "cane rod", category: "sexual_objects" },
  { symbol: "tickler feather", category: "sexual_objects" },
  { symbol: "nipple clamps", category: "sexual_objects" },
  { symbol: "nipple suckers", category: "sexual_objects" },
  { symbol: "nipple pump", category: "sexual_objects" },
  { symbol: "breast pump", category: "sexual_objects" },
  { symbol: "suction cup toy", category: "sexual_objects" },
  { symbol: "vacuum pump", category: "sexual_objects" },
  { symbol: "vacuum cylinder", category: "sexual_objects" },
  { symbol: "dilator set", category: "sexual_objects" },
  { symbol: "anal trainer", category: "sexual_objects" },
  { symbol: "butt trainer", category: "sexual_objects" },
  { symbol: "anal hook", category: "sexual_objects" },
  { symbol: "prostate toy", category: "sexual_objects" },
  { symbol: "prostate plug", category: "sexual_objects" },
  { symbol: "vibrating plug", category: "sexual_objects" },
  { symbol: "silicone dildo", category: "sexual_objects" },
  { symbol: "glass dildo", category: "sexual_objects" },
  { symbol: "metal dildo", category: "sexual_objects" },
  { symbol: "double dildo", category: "sexual_objects" },
  { symbol: "strap on", category: "sexual_objects" },
  { symbol: "harness strap", category: "sexual_objects" },
  { symbol: "strap harness", category: "sexual_objects" },
  { symbol: "hollow strap", category: "sexual_objects" },
  { symbol: "dildo harness", category: "sexual_objects" },
  { symbol: "cock sheath", category: "sexual_objects" },
  { symbol: "penis extender", category: "sexual_objects" },
  { symbol: "vibrating panties", category: "sexual_objects" },
  { symbol: "vibrating egg", category: "sexual_objects" },
  { symbol: "vibrating bullet", category: "sexual_objects" },
  { symbol: "wearable panty vibrator", category: "sexual_objects" },
  { symbol: "suction toy", category: "sexual_objects" },
  { symbol: "tongue vibrator", category: "sexual_objects" },
  { symbol: "couples vibrator", category: "sexual_objects" },
  { symbol: "finger vibrator", category: "sexual_objects" },
  { symbol: "finger sleeve", category: "sexual_objects" },
  { symbol: "finger stimulator", category: "sexual_objects" },
  { symbol: "lubebottle", category: "sexual_objects" },
  { symbol: "lubricant tube", category: "sexual_objects" },
  { symbol: "lubricant pump", category: "sexual_objects" },
  { symbol: "lubricant sachet", category: "sexual_objects" },
  { symbol: "condom box", category: "sexual_objects" },
  { symbol: "condom wrapper", category: "sexual_objects" },
  { symbol: "condom packet", category: "sexual_objects" },
  { symbol: "condom case", category: "sexual_objects" },
  { symbol: "dental dam", category: "sexual_objects" },
  { symbol: "toy cleaner", category: "sexual_objects" },
  { symbol: "toy spray", category: "sexual_objects" },
  { symbol: "toy wipes", category: "sexual_objects" },
  { symbol: "toy charger", category: "sexual_objects" },
  { symbol: "toy cable", category: "sexual_objects" },
  { symbol: "toy storage bag", category: "sexual_objects" },
  { symbol: "toy storage box", category: "sexual_objects" },
  { symbol: "toy storage case", category: "sexual_objects" },
  { symbol: "toy stand", category: "sexual_objects" },
  { symbol: "toy holder", category: "sexual_objects" },
  { symbol: "toy mount", category: "sexual_objects" },
  { symbol: "suction mount", category: "sexual_objects" },
  { symbol: "bed restraints", category: "sexual_objects" },
  { symbol: "door restraints", category: "sexual_objects" },
  { symbol: "underbed restraints", category: "sexual_objects" },
  { symbol: "bondage bed frame", category: "sexual_objects" },
  { symbol: "bondage pillow", category: "sexual_objects" },
  { symbol: "wedge pillow", category: "sexual_objects" },
  { symbol: "sex wedge", category: "sexual_objects" },
  { symbol: "positioning pillow", category: "sexual_objects" },
  { symbol: "intimacy pillow", category: "sexual_objects" },
  { symbol: "liberator wedge", category: "sexual_objects" },
  { symbol: "liberator ramp", category: "sexual_objects" },
  { symbol: "sex swing", category: "sexual_objects" },
  { symbol: "door swing", category: "sexual_objects" },
  { symbol: "swing harness", category: "sexual_objects" },
  { symbol: "swing straps", category: "sexual_objects" },
  { symbol: "swing frame", category: "sexual_objects" },
  { symbol: "massage candle", category: "sexual_objects" },
  { symbol: "massage oil", category: "sexual_objects" },
  { symbol: "massage roller", category: "sexual_objects" },
  { symbol: "massage wand", category: "sexual_objects" },
  { symbol: "massage ball", category: "sexual_objects" },
  { symbol: "massage stick", category: "sexual_objects" },
  { symbol: "massage stone", category: "sexual_objects" },
  { symbol: "body oil", category: "sexual_objects" },
  { symbol: "body powder", category: "sexual_objects" },
  { symbol: "feather tickler", category: "sexual_objects" },
  { symbol: "silk scarf", category: "sexual_objects" },
  { symbol: "satin blindfold", category: "sexual_objects" },
  { symbol: "leather cuffs", category: "sexual_objects" },
  { symbol: "steel cuffs", category: "sexual_objects" },
  { symbol: "rope cuffs", category: "sexual_objects" },
  { symbol: "restraint straps", category: "sexual_objects" },
  { symbol: "collar ring", category: "sexual_objects" },
  { symbol: "leather collar", category: "sexual_objects" },
  { symbol: "posture collar", category: "sexual_objects" },
  { symbol: "training collar", category: "sexual_objects" },
  { symbol: "leash chain", category: "sexual_objects" },
  { symbol: "leash handle", category: "sexual_objects" },
  { symbol: "bondage collar", category: "sexual_objects" },
  { symbol: "bondage chain", category: "sexual_objects" },
  { symbol: "chain leash", category: "sexual_objects" },
  { symbol: "chain cuffs", category: "sexual_objects" },
  { symbol: "spreader cuffs", category: "sexual_objects" },
  { symbol: "ankle spreader", category: "sexual_objects" },
  { symbol: "wrist spreader", category: "sexual_objects" },
  { symbol: "thigh cuffs", category: "sexual_objects" },
  { symbol: "thigh restraints", category: "sexual_objects" },
  { symbol: "body harness", category: "sexual_objects" },
  { symbol: "chest harness", category: "sexual_objects" },
  { symbol: "rope harness", category: "sexual_objects" },
  { symbol: "latex suit", category: "sexual_objects" },
  { symbol: "latex gloves", category: "sexual_objects" },
  { symbol: "latex stockings", category: "sexual_objects" },
  { symbol: "latex mask", category: "sexual_objects" },
  { symbol: "latex collar", category: "sexual_objects" },
  { symbol: "latex cuffs", category: "sexual_objects" },
  { symbol: "latex dress", category: "sexual_objects" },
  { symbol: "latex bodysuit", category: "sexual_objects" },
  { symbol: "lingerie set", category: "sexual_objects" },
  { symbol: "lace lingerie", category: "sexual_objects" },
  { symbol: "garter belt", category: "sexual_objects" },
  { symbol: "garter straps", category: "sexual_objects" },
  { symbol: "thigh garter", category: "sexual_objects" },
  { symbol: "thigh stockings", category: "sexual_objects" },
  { symbol: "fishnet stockings", category: "sexual_objects" },
  { symbol: "thigh highs", category: "sexual_objects" },
  { symbol: "crotchless panties", category: "sexual_objects" },
  { symbol: "crotchless bodysuit", category: "sexual_objects" },
  { symbol: "open bra", category: "sexual_objects" },
  { symbol: "open cup bra", category: "sexual_objects" },
  { symbol: "strapless bra", category: "sexual_objects" },
  { symbol: "pushup bra", category: "sexual_objects" },
  { symbol: "harness bra", category: "sexual_objects" },
  { symbol: "chain bra", category: "sexual_objects" },
  { symbol: "body chain", category: "sexual_objects" },
  { symbol: "waist chain", category: "sexual_objects" },
  { symbol: "ankle chain", category: "sexual_objects" },
  { symbol: "nipple jewelry", category: "sexual_objects" },
  { symbol: "nipple rings", category: "sexual_objects" },
  { symbol: "nipple bars", category: "sexual_objects" },
  { symbol: "nipple covers", category: "sexual_objects" },
  { symbol: "nipple stickers", category: "sexual_objects" },
  { symbol: "nipple shields", category: "sexual_objects" },
  { symbol: "piercing rings", category: "sexual_objects" },
  { symbol: "piercing barbell", category: "sexual_objects" },
  { symbol: "piercing stud", category: "sexual_objects" },
  { symbol: "piercing clamp", category: "sexual_objects" },
  { symbol: "piercing needle", category: "sexual_objects" },
];
