import { SingleWordSymbol } from "../dreamSingularSymbols";

export const sports_equipment_symbols: SingleWordSymbol[] = [
  { symbol: "yogamat", category: "sports_equipment" },
  { symbol: "rope", category: "sports_equipment" },
  { symbol: "jump rope", category: "sports_equipment" },
  { symbol: "landingnet", category: "sports_equipment" },
  { symbol: "bassinet", category: "sports_equipment" },
  { symbol: "magnet", category: "sports_equipment" },
  { symbol: "soccerball", category: "sports_equipment" },
  { symbol: "gagball", category: "sports_equipment" },
  { symbol: "magnetcoil", category: "sports_equipment" },
  { symbol: "racket", category: "sports_equipment" },
  { symbol: "crystalball", category: "sports_equipment" },
  { symbol: "cottonball", category: "sports_equipment" },
  { symbol: "goal", category: "sports_equipment" },
  { symbol: "jumprope", category: "sports_equipment" },
  { symbol: "ballpointpen", category: "sports_equipment" },
  { symbol: "refrigeratormagnet", category: "sports_equipment" },
  { symbol: "fishnet", category: "sports_equipment" },
  { symbol: "gymmat", category: "sports_equipment" },
  { symbol: "tennisracket", category: "sports_equipment" },
  { symbol: "propeller", category: "sports_equipment" },
  { symbol: "football", category: "sports_equipment" },
  { symbol: "magnetron", category: "sports_equipment" },
  { symbol: "paperweight", category: "sports_equipment" },
  { symbol: "dronepropeller", category: "sports_equipment" },
  { symbol: "yoga mat", category: "sports_equipment" },
  { symbol: "bondagerope", category: "sports_equipment" },
  { symbol: "yarnball", category: "sports_equipment" },
  { symbol: "ropecoil", category: "sports_equipment" },
  { symbol: "ball", category: "sports_equipment" },
  { symbol: "fridgemagnet", category: "sports_equipment" },
  { symbol: "treadmill", category: "sports_equipment" },
  { symbol: "net", category: "sports_equipment" },
  { symbol: "basketball", category: "sports_equipment" },
  { symbol: "soccer ball", category: "sports_equipment" },
  { symbol: "baseball", category: "sports_equipment" },
  { symbol: "softball", category: "sports_equipment" },
  { symbol: "tennis ball", category: "sports_equipment" },
  { symbol: "tennis racket", category: "sports_equipment" },
  { symbol: "badminton racket", category: "sports_equipment" },
  { symbol: "badminton shuttlecock", category: "sports_equipment" },
  { symbol: "ping pong paddle", category: "sports_equipment" },
  { symbol: "ping pong ball", category: "sports_equipment" },
  { symbol: "ping pong table", category: "sports_equipment" },
  { symbol: "golf club", category: "sports_equipment" },
  { symbol: "golf ball", category: "sports_equipment" },
  { symbol: "golf tee", category: "sports_equipment" },
  { symbol: "hockey stick", category: "sports_equipment" },
  { symbol: "hockey puck", category: "sports_equipment" },
  { symbol: "lacrosse stick", category: "sports_equipment" },
  { symbol: "lacrosse ball", category: "sports_equipment" },
  { symbol: "cricket bat", category: "sports_equipment" },
  { symbol: "cricket ball", category: "sports_equipment" },
  { symbol: "rugby ball", category: "sports_equipment" },
  { symbol: "volleyball", category: "sports_equipment" },
  { symbol: "dodgeball", category: "sports_equipment" },
  { symbol: "handball", category: "sports_equipment" },
  { symbol: "bocce ball", category: "sports_equipment" },
  { symbol: "bowling ball", category: "sports_equipment" },
  { symbol: "bowling pin", category: "sports_equipment" },
  { symbol: "dart board", category: "sports_equipment" },
  { symbol: "darts", category: "sports_equipment" },
  { symbol: "shuffleboard puck", category: "sports_equipment" },
  { symbol: "curling stone", category: "sports_equipment" },
  { symbol: "billiard ball", category: "sports_equipment" },
  { symbol: "pool cue", category: "sports_equipment" },
  { symbol: "cue chalk", category: "sports_equipment" },
  { symbol: "air hockey paddle", category: "sports_equipment" },
  { symbol: "air hockey puck", category: "sports_equipment" },
  { symbol: "frisbee", category: "sports_equipment" },
  { symbol: "flying disc", category: "sports_equipment" },
  { symbol: "disc golf disc", category: "sports_equipment" },
  { symbol: "skate board", category: "sports_equipment" },
  { symbol: "longboard", category: "sports_equipment" },
  { symbol: "scooter", category: "sports_equipment" },
  { symbol: "kick scooter", category: "sports_equipment" },
  { symbol: "roller skates", category: "sports_equipment" },
  { symbol: "roller blades", category: "sports_equipment" },
  { symbol: "ice skates", category: "sports_equipment" },
  { symbol: "skate helmet", category: "sports_equipment" },
  { symbol: "skate pads", category: "sports_equipment" },
  { symbol: "ski poles", category: "sports_equipment" },
  { symbol: "skis", category: "sports_equipment" },
  { symbol: "snowboard", category: "sports_equipment" },
  { symbol: "snow goggles", category: "sports_equipment" },
  { symbol: "ski helmet", category: "sports_equipment" },
  { symbol: "sled", category: "sports_equipment" },
  { symbol: "snow tube", category: "sports_equipment" },
  { symbol: "toboggan", category: "sports_equipment" },
  { symbol: "snowshoes", category: "sports_equipment" },
  { symbol: "climbing rope", category: "sports_equipment" },
  { symbol: "climbing harness", category: "sports_equipment" },
  { symbol: "climbing carabiner", category: "sports_equipment" },
  { symbol: "climbing helmet", category: "sports_equipment" },
  { symbol: "chalk bag", category: "sports_equipment" },
  { symbol: "belay device", category: "sports_equipment" },
  { symbol: "pull up bar", category: "sports_equipment" },
  { symbol: "foam roller", category: "sports_equipment" },
  { symbol: "resistance band", category: "sports_equipment" },
  { symbol: "exercise band", category: "sports_equipment" },
  { symbol: "ankle weights", category: "sports_equipment" },
  { symbol: "wrist weights", category: "sports_equipment" },
  { symbol: "dumbbell", category: "sports_equipment" },
  { symbol: "barbell", category: "sports_equipment" },
  { symbol: "weight plate", category: "sports_equipment" },
  { symbol: "kettlebell", category: "sports_equipment" },
  { symbol: "medicine ball", category: "sports_equipment" },
  { symbol: "balance ball", category: "sports_equipment" },
  { symbol: "stability ball", category: "sports_equipment" },
  { symbol: "exercise bike", category: "sports_equipment" },
  { symbol: "rowing machine", category: "sports_equipment" },
  { symbol: "elliptical trainer", category: "sports_equipment" },
  { symbol: "punching bag", category: "sports_equipment" },
  { symbol: "speed bag", category: "sports_equipment" },
  { symbol: "boxing gloves", category: "sports_equipment" },
  { symbol: "boxing wraps", category: "sports_equipment" },
  { symbol: "focus mitts", category: "sports_equipment" },
  { symbol: "head guard", category: "sports_equipment" },
  { symbol: "shin guards", category: "sports_equipment" },
  { symbol: "mouth guard", category: "sports_equipment" },
  { symbol: "athletic tape", category: "sports_equipment" },
  { symbol: "batting helmet", category: "sports_equipment" },
  { symbol: "catcher mask", category: "sports_equipment" },
  { symbol: "catcher mitt", category: "sports_equipment" },
  { symbol: "baseball glove", category: "sports_equipment" },
  { symbol: "batting tee", category: "sports_equipment" },
  { symbol: "batting cage net", category: "sports_equipment" },
  { symbol: "soccer goal", category: "sports_equipment" },
  { symbol: "soccer net", category: "sports_equipment" },
  { symbol: "goalie gloves", category: "sports_equipment" },
  { symbol: "goal post", category: "sports_equipment" },
  { symbol: "training cones", category: "sports_equipment" },
  { symbol: "agility ladder", category: "sports_equipment" },
  { symbol: "hurdle set", category: "sports_equipment" },
  { symbol: "training parachute", category: "sports_equipment" },
  { symbol: "reaction ball", category: "sports_equipment" },
  { symbol: "rebound net", category: "sports_equipment" },
  { symbol: "pitching machine", category: "sports_equipment" },
  { symbol: "pitching net", category: "sports_equipment" },
  { symbol: "kickboard", category: "sports_equipment" },
  { symbol: "swim goggles", category: "sports_equipment" },
  { symbol: "swim cap", category: "sports_equipment" },
  { symbol: "swim fins", category: "sports_equipment" },
  { symbol: "snorkel", category: "sports_equipment" },
  { symbol: "diving mask", category: "sports_equipment" },
  { symbol: "diving fins", category: "sports_equipment" },
  { symbol: "water polo ball", category: "sports_equipment" },
  { symbol: "paddle board", category: "sports_equipment" },
  { symbol: "kayak paddle", category: "sports_equipment" },
  { symbol: "canoe paddle", category: "sports_equipment" },
  { symbol: "rowing oar", category: "sports_equipment" },
  { symbol: "fishing rod", category: "sports_equipment" },
  { symbol: "fishing reel", category: "sports_equipment" },
  { symbol: "tackle box", category: "sports_equipment" },
  { symbol: "bait bucket", category: "sports_equipment" },
  { symbol: "landing net", category: "sports_equipment" },
  { symbol: "archery bow", category: "sports_equipment" },
  { symbol: "compound bow", category: "sports_equipment" },
  { symbol: "recurve bow", category: "sports_equipment" },
  { symbol: "crossbow", category: "sports_equipment" },
  { symbol: "archery arrows", category: "sports_equipment" },
  { symbol: "archery target", category: "sports_equipment" },
  { symbol: "archery quiver", category: "sports_equipment" },
  { symbol: "fencing foil", category: "sports_equipment" },
  { symbol: "fencing epee", category: "sports_equipment" },
  { symbol: "fencing mask", category: "sports_equipment" },
  { symbol: "fencing jacket", category: "sports_equipment" },
  { symbol: "martial arts belt", category: "sports_equipment" },
  { symbol: "karate gloves", category: "sports_equipment" },
  { symbol: "taekwondo pads", category: "sports_equipment" },
  { symbol: "judo mat", category: "sports_equipment" },
  { symbol: "sparring helmet", category: "sports_equipment" },
  { symbol: "sparring gloves", category: "sports_equipment" },
  { symbol: "sparring shin guards", category: "sports_equipment" },
  { symbol: "wrestling mat", category: "sports_equipment" },
  { symbol: "wrestling headgear", category: "sports_equipment" },
  { symbol: "shot put", category: "sports_equipment" },
  { symbol: "discus", category: "sports_equipment" },
  { symbol: "javelin", category: "sports_equipment" },
  { symbol: "pole vault pole", category: "sports_equipment" },
  { symbol: "relay baton", category: "sports_equipment" },
  { symbol: "starting blocks", category: "sports_equipment" },
  { symbol: "stopwatch", category: "sports_equipment" },
  { symbol: "whistle", category: "sports_equipment" },
  { symbol: "scoreboard", category: "sports_equipment" },
  { symbol: "trophy", category: "sports_equipment" },
  { symbol: "medal", category: "sports_equipment" },
  { symbol: "ribbon", category: "sports_equipment" },
  { symbol: "award plaque", category: "sports_equipment" },
];
