import { SingleWordSymbol } from "../dreamSingularSymbols";

export const striving_symbols: SingleWordSymbol[] = [
  { symbol: "trying", category: "striving" },
  { symbol: "attempting", category: "striving" },
  { symbol: "aiming", category: "striving" },
  { symbol: "targeting", category: "striving" },
  { symbol: "reaching", category: "striving" },
  { symbol: "grasping", category: "striving" },
  { symbol: "striving", category: "striving" },
  { symbol: "pressing", category: "striving" },
  { symbol: "progressing", category: "striving" },
  { symbol: "improving", category: "striving" },
  { symbol: "developing", category: "striving" },
  { symbol: "strategizing", category: "striving" },
  { symbol: "calculating", category: "striving" },
  { symbol: "considering", category: "striving" },
  { symbol: "deciding", category: "striving" },
  { symbol: "choosing", category: "striving" },
  { symbol: "selecting", category: "striving" },
  { symbol: "committing", category: "striving" },
  { symbol: "starting", category: "striving" },
  { symbol: "beginning", category: "striving" },
  { symbol: "initiating", category: "striving" },
  { symbol: "launching", category: "striving" },
  { symbol: "undertaking", category: "striving" },
  { symbol: "engaging", category: "striving" },
  { symbol: "moving", category: "striving" },
  { symbol: "continuing", category: "striving" },
  { symbol: "persisting", category: "striving" },
  { symbol: "enduring", category: "striving" },
  { symbol: "persevering", category: "striving" },
  { symbol: "surviving", category: "striving" },
  { symbol: "tolerating", category: "striving" },
  { symbol: "withstanding", category: "striving" },
  { symbol: "overcoming", category: "striving" },
  { symbol: "conquering", category: "striving" },
  { symbol: "achieving", category: "striving" },
  { symbol: "accomplishing", category: "striving" },
  { symbol: "succeeding", category: "striving" },
  { symbol: "prevailing", category: "striving" },
  { symbol: "mastering", category: "striving" },
  { symbol: "solving", category: "striving" },
  { symbol: "completing", category: "striving" },
  { symbol: "finishing", category: "striving" },
  { symbol: "concluding", category: "striving" },
  { symbol: "ending", category: "striving" },
  { symbol: "delivering", category: "striving" },
  { symbol: "establishing", category: "striving" },
  { symbol: "earning", category: "striving" },
  { symbol: "gaining", category: "striving" },
  { symbol: "obtaining", category: "striving" },
  { symbol: "acquiring", category: "striving" },
  { symbol: "capturing", category: "striving" },
  { symbol: "claiming", category: "striving" },
  { symbol: "collecting", category: "striving" },
  { symbol: "receiving", category: "striving" },
  { symbol: "proving", category: "striving" },
  { symbol: "demonstrating", category: "striving" },
  { symbol: "displaying", category: "striving" },
  { symbol: "revealing", category: "striving" },
  { symbol: "exposing", category: "striving" },
  { symbol: "validating", category: "striving" },
  { symbol: "confirming", category: "striving" },
  { symbol: "justifying", category: "striving" },
  { symbol: "preserving", category: "striving" },
  { symbol: "sustaining", category: "striving" },
  { symbol: "balancing", category: "striving" },
  { symbol: "ascending", category: "striving" },
  { symbol: "mounting", category: "striving" },
  { symbol: "rising", category: "striving" },
  { symbol: "standing", category: "striving" },
  { symbol: "extending", category: "striving" },
  { symbol: "accelerating", category: "striving" },
  { symbol: "speeding", category: "striving" },
  { symbol: "rushing", category: "striving" },
  { symbol: "dashing", category: "striving" },
  { symbol: "sprinting", category: "striving" },
  { symbol: "concealing", category: "striving" },
  { symbol: "recovering", category: "striving" },
  { symbol: "healing", category: "striving" },
  { symbol: "rebuilding", category: "striving" },
  { symbol: "restarting", category: "striving" },
  { symbol: "retrying", category: "striving" },
  { symbol: "repeating", category: "striving" },
  { symbol: "reworking", category: "striving" },
  { symbol: "revising", category: "striving" },
  { symbol: "correcting", category: "striving" },
  { symbol: "modifying", category: "striving" },
  { symbol: "altering", category: "striving" },
  { symbol: "changing", category: "striving" },
  { symbol: "enhancing", category: "striving" },
  { symbol: "strengthening", category: "striving" },
  { symbol: "fortifying", category: "striving" },
  { symbol: "motivating", category: "striving" },
  { symbol: "inspiring", category: "striving" },
  { symbol: "encouraging", category: "striving" },
  { symbol: "empowering", category: "striving" },
  { symbol: "energizing", category: "striving" },
  { symbol: "stimulating", category: "striving" },
  { symbol: "activating", category: "striving" },
  { symbol: "mobilizing", category: "striving" },
  { symbol: "commanding", category: "striving" },
  { symbol: "coordinating", category: "striving" },
  { symbol: "administering", category: "striving" },
  { symbol: "supervising", category: "striving" },
  { symbol: "negotiating", category: "striving" },
  { symbol: "bargaining", category: "striving" },
  { symbol: "arguing", category: "striving" },
  { symbol: "persuading", category: "striving" },
  { symbol: "convincing", category: "striving" },
  { symbol: "requesting", category: "striving" },
  { symbol: "demanding", category: "striving" },
  { symbol: "insisting", category: "striving" },
  { symbol: "appealing", category: "striving" },
  { symbol: "petitioning", category: "striving" },
  { symbol: "challenging", category: "striving" },
  { symbol: "contesting", category: "striving" },
  { symbol: "opposing", category: "striving" },
  { symbol: "struggling", category: "striving" },
  { symbol: "battling", category: "striving" },
  { symbol: "confronting", category: "striving" },
  { symbol: "stopping", category: "striving" },
  { symbol: "preventing", category: "striving" },
  { symbol: "hindering", category: "striving" },
  { symbol: "interrupting", category: "striving" },
  { symbol: "delaying", category: "striving" },
  { symbol: "analyzing", category: "striving" },
  { symbol: "evaluating", category: "striving" },
  { symbol: "measuring", category: "striving" },
  { symbol: "estimating", category: "striving" },
  { symbol: "guessing", category: "striving" },
  { symbol: "predicting", category: "striving" },
  { symbol: "anticipating", category: "striving" },
  { symbol: "expecting", category: "striving" },
  { symbol: "hoping", category: "striving" },
  { symbol: "wishing", category: "striving" },
  { symbol: "imagining", category: "striving" },
  { symbol: "visualizing", category: "striving" },
  { symbol: "envisioning", category: "striving" },
  { symbol: "remembering", category: "striving" },
  { symbol: "recalling", category: "striving" },
  { symbol: "understanding", category: "striving" },
  { symbol: "realizing", category: "striving" },
  { symbol: "identifying", category: "striving" },
  { symbol: "recognizing", category: "striving" },
  { symbol: "preferring", category: "striving" },
  { symbol: "prioritizing", category: "striving" },
  { symbol: "ranking", category: "striving" },
  { symbol: "sorting", category: "striving" },
  { symbol: "classifying", category: "striving" },
  { symbol: "grouping", category: "striving" },
  { symbol: "drafting", category: "striving" },
  { symbol: "mapping", category: "striving" },
  { symbol: "plotting", category: "striving" },
  { symbol: "scheduling", category: "striving" },
  { symbol: "timing", category: "striving" },
  { symbol: "aligning", category: "striving" },
  { symbol: "stabilizing", category: "striving" },
  { symbol: "centering", category: "striving" },
  { symbol: "grounding", category: "striving" },
  { symbol: "hardening", category: "striving" },
  { symbol: "toughening", category: "striving" },
  { symbol: "conditioning", category: "striving" },
  { symbol: "forcing", category: "striving" },
  { symbol: "urging", category: "striving" },
  { symbol: "straining", category: "striving" },
  { symbol: "clutching", category: "striving" },
  { symbol: "gripping", category: "striving" },
  { symbol: "securing", category: "striving" },
  { symbol: "fastening", category: "striving" },
  { symbol: "tying", category: "striving" },
  { symbol: "binding", category: "striving" },
  { symbol: "anchoring", category: "striving" },
  { symbol: "attaching", category: "striving" },
  { symbol: "scaling", category: "striving" },
  { symbol: "hoisting", category: "striving" },
  { symbol: "elevating", category: "striving" },
  { symbol: "uplifting", category: "striving" },
  { symbol: "boosting", category: "striving" },
  { symbol: "reviving", category: "striving" },
  { symbol: "renewing", category: "striving" },
  { symbol: "refreshing", category: "striving" },
  { symbol: "rejuvenating", category: "striving" },
  { symbol: "reforming", category: "striving" },
  { symbol: "redoing", category: "striving" },
  { symbol: "upgrading", category: "striving" },
  { symbol: "lasting", category: "striving" },
  { symbol: "seeking", category: "striving" },
  { symbol: "pursuing", category: "striving" },
  { symbol: "pushing", category: "striving" },
  { symbol: "advancing", category: "striving" },
  { symbol: "growing", category: "striving" },
  { symbol: "learning", category: "striving" },
  { symbol: "practicing", category: "striving" },
  { symbol: "training", category: "striving" },
  { symbol: "preparing", category: "striving" },
  { symbol: "planning", category: "striving" },
  { symbol: "organizing", category: "striving" },
  { symbol: "arranging", category: "striving" },
  { symbol: "entering", category: "striving" },
  { symbol: "approaching", category: "striving" },
  { symbol: "resisting", category: "striving" },
  { symbol: "winning", category: "striving" },
  { symbol: "fixing", category: "striving" },
  { symbol: "repairing", category: "striving" },
  { symbol: "producing", category: "striving" },
  { symbol: "building", category: "striving" },
  { symbol: "creating", category: "striving" },
  { symbol: "forming", category: "striving" },
  { symbol: "gathering", category: "striving" },
  { symbol: "showing", category: "striving" },
  { symbol: "defending", category: "striving" },
  { symbol: "protecting", category: "striving" },
  { symbol: "guarding", category: "striving" },
  { symbol: "saving", category: "striving" },
  { symbol: "rescuing", category: "striving" },
  { symbol: "maintaining", category: "striving" },
  { symbol: "supporting", category: "striving" },
  { symbol: "holding", category: "striving" },
  { symbol: "lifting", category: "striving" },
  { symbol: "raising", category: "striving" },
  { symbol: "pulling", category: "striving" },
  { symbol: "dragging", category: "striving" },
  { symbol: "climbing", category: "striving" },
  { symbol: "stretching", category: "striving" },
  { symbol: "expanding", category: "striving" },
  { symbol: "charging", category: "striving" },
  { symbol: "escaping", category: "striving" },
  { symbol: "fleeing", category: "striving" },
  { symbol: "avoiding", category: "striving" },
  { symbol: "dodging", category: "striving" },
  { symbol: "evading", category: "striving" },
  { symbol: "hiding", category: "striving" },
  { symbol: "shielding", category: "striving" },
  { symbol: "retreating", category: "striving" },
  { symbol: "restoring", category: "striving" },
  { symbol: "adjusting", category: "striving" },
  { symbol: "transforming", category: "striving" },
  { symbol: "driving", category: "striving" },
  { symbol: "leading", category: "striving" },
  { symbol: "guiding", category: "striving" },
  { symbol: "directing", category: "striving" },
  { symbol: "steering", category: "striving" },
  { symbol: "managing", category: "striving" },
  { symbol: "competing", category: "striving" },
  { symbol: "defying", category: "striving" },
  { symbol: "rebelling", category: "striving" },
  { symbol: "protesting", category: "striving" },
  { symbol: "fighting", category: "striving" },
  { symbol: "attacking", category: "striving" },
  { symbol: "blocking", category: "striving" },
  { symbol: "searching", category: "striving" },
  { symbol: "investigating", category: "striving" },
  { symbol: "examining", category: "striving" },
  { symbol: "studying", category: "striving" },
  { symbol: "dreaming", category: "striving" },
  { symbol: "memorizing", category: "striving" },
  { symbol: "discovering", category: "striving" },
  { symbol: "designing", category: "striving" },
  { symbol: "sketching", category: "striving" },
  { symbol: "grabbing", category: "striving" },
  { symbol: "locking", category: "striving" },
  {
    symbol: "chasing",
    category: "striving",
  },
  {
    symbol: "looking",
    category: "striving",
  },
  {
    symbol: "exploring",
    category: "striving",
  },
  {
    symbol: "finding",
    category: "striving",
  },
  {
    symbol: "descending",
    category: "striving",
  },
  {
    symbol: "jumping",
    category: "striving",
  },
  {
    symbol: "leaping",
    category: "striving",
  },
  {
    symbol: "running",
    category: "striving",
  },
  {
    symbol: "racing",
    category: "striving",
  },
  {
    symbol: "wrestling",
    category: "striving",
  },
  {
    symbol: "constructing",
    category: "striving",
  },
  {
    symbol: "inventing",
    category: "striving",
  },
  {
    symbol: "figuring",
    category: "striving",
  },
  {
    symbol: "navigating",
    category: "striving",
  },
  {
    symbol: "controlling",
    category: "striving",
  },
  {
    symbol: "judging",
    category: "striving",
  },
  {
    symbol: "testing",
    category: "striving",
  },
  {
    symbol: "presenting",
    category: "striving",
  },
  {
    symbol: "explaining",
    category: "striving",
  },
  {
    symbol: "teaching",
    category: "striving",
  },
  {
    symbol: "influencing",
    category: "striving",
  },
  {
    symbol: "helping",
    category: "striving",
  },
  {
    symbol: "assisting",
    category: "striving",
  },
  {
    symbol: "adapting",
    category: "striving",
  },
  {
    symbol: "evolving",
    category: "striving",
  },
  {
    symbol: "reinforcing",
    category: "striving",
  },
  {
    symbol: "triggering",
    category: "striving",
  },
  {
    symbol: "advancingforward",
    category: "striving",
  },
  {
    symbol: "pressingforward",
    category: "striving",
  },
  {
    symbol: "forgingahead",
    category: "striving",
  },
  {
    symbol: "pushingforward",
    category: "striving",
  },
  {
    symbol: "breakingthrough",
    category: "striving",
  },
  {
    symbol: "breakingfree",
    category: "striving",
  },
  {
    symbol: "overcomingobstacles",
    category: "striving",
  },
  {
    symbol: "climbinghigher",
    category: "striving",
  },
  {
    symbol: "reachingtop",
    category: "striving",
  },
  {
    symbol: "focusing",
    category: "striving",
  },
  {
    symbol: "concentrating",
    category: "striving",
  },
  {
    symbol: "dedicating",
    category: "striving",
  },
  {
    symbol: "enduringhardship",
    category: "striving",
  },
  {
    symbol: "persistinglong",
    category: "striving",
  },
  {
    symbol: "strivingharder",
    category: "striving",
  },
  {
    symbol: "pursuinggoals",
    category: "striving",
  },
  {
    symbol: "achievingdreams",
    category: "striving",
  },
  {
    symbol: "winningchallenge",
    category: "striving",
  },
  {
    symbol: "beatingcompetition",
    category: "striving",
  },
  {
    symbol: "conqueringfear",
    category: "striving",
  },
  {
    symbol: "provingability",
    category: "striving",
  },
  {
    symbol: "demonstratingstrength",
    category: "striving",
  },
  {
    symbol: "overcomingbarrier",
    category: "striving",
  },
  {
    symbol: "achievingsuccess",
    category: "striving",
  },
  {
    symbol: "accomplishinggoal",
    category: "striving",
  },
  {
    symbol: "completingtask",
    category: "striving",
  },
  {
    symbol: "finishingwork",
    category: "striving",
  },
  {
    symbol: "fulfillingduty",
    category: "striving",
  },
  {
    symbol: "attainingtarget",
    category: "striving",
  },
  {
    symbol: "reachinggoal",
    category: "striving",
  },
  {
    symbol: "securingvictory",
    category: "striving",
  },
  {
    symbol: "claimingreward",
    category: "striving",
  },
  {
    symbol: "earningrespect",
    category: "striving",
  },
  {
    symbol: "gainingconfidence",
    category: "striving",
  },
  {
    symbol: "gainingpower",
    category: "striving",
  },
  {
    symbol: "gainingcontrol",
    category: "striving",
  },
  {
    symbol: "gainingknowledge",
    category: "striving",
  },
  {
    symbol: "gainingexperience",
    category: "striving",
  },
  {
    symbol: "improvingability",
    category: "striving",
  },
  {
    symbol: "masteringskill",
    category: "striving",
  },
  {
    symbol: "strengtheningresolve",
    category: "striving",
  },
  {
    symbol: "maintainingeffort",
    category: "striving",
  },
  {
    symbol: "sustainingfocus",
    category: "striving",
  },
  {
    symbol: "continuingeffort",
    category: "striving",
  },
  {
    symbol: "persistingforward",
    category: "striving",
  },
  {
    symbol: "enduringchallenge",
    category: "striving",
  },
  {
    symbol: "survivingtrial",
    category: "striving",
  },
  {
    symbol: "conqueringdifficulty",
    category: "striving",
  },
  {
    symbol: "overcomingfailure",
    category: "striving",
  },
  {
    symbol: "rebounding",
    category: "striving",
  },
  {
    symbol: "recoveringstrength",
    category: "striving",
  },
  {
    symbol: "rebuildingconfidence",
    category: "striving",
  },
  {
    symbol: "renewingeffort",
    category: "striving",
  },
  {
    symbol: "reattempting",
    category: "striving",
  },
  {
    symbol: "reevaluating",
    category: "striving",
  },
  {
    symbol: "redirecting",
    category: "striving",
  },
  {
    symbol: "refocusing",
    category: "striving",
  },
  {
    symbol: "recalculating",
    category: "striving",
  },
  {
    symbol: "rethinking",
    category: "striving",
  },
  {
    symbol: "reorganizing",
    category: "striving",
  },
  {
    symbol: "redefining",
    category: "striving",
  },
  {
    symbol: "reimagining",
    category: "striving",
  },
  {
    symbol: "reinventing",
    category: "striving",
  },
  {
    symbol: "evolvingforward",
    category: "striving",
  },
  {
    symbol: "progressingforward",
    category: "striving",
  },
  {
    symbol: "growingstronger",
    category: "striving",
  },
  {
    symbol: "expandingability",
    category: "striving",
  },
  {
    symbol: "strengtheningmind",
    category: "striving",
  },
  {
    symbol: "strengtheningbody",
    category: "striving",
  },
  {
    symbol: "strengtheningskill",
    category: "striving",
  },
  {
    symbol: "sharpeningfocus",
    category: "striving",
  },
  {
    symbol: "sharpeningmind",
    category: "striving",
  },
  {
    symbol: "buildingmomentum",
    category: "striving",
  },
  {
    symbol: "generatingeffort",
    category: "striving",
  },
  {
    symbol: "producingresults",
    category: "striving",
  },
  {
    symbol: "deliveringperformance",
    category: "striving",
  },
  {
    symbol: "meetingchallenge",
    category: "striving",
  },
  {
    symbol: "answeringchallenge",
    category: "striving",
  },
  {
    symbol: "facingchallenge",
    category: "striving",
  },
  {
    symbol: "confrontingfear",
    category: "striving",
  },
  {
    symbol: "facingdifficulty",
    category: "striving",
  },
  {
    symbol: "confrontingobstacle",
    category: "striving",
  },
  {
    symbol: "challenginglimits",
    category: "striving",
  },
  {
    symbol: "pushinglimits",
    category: "striving",
  },
  {
    symbol: "exceedinglimits",
    category: "striving",
  },
  {
    symbol: "surpassinglimits",
    category: "striving",
  },
  {
    symbol: "breakingrecords",
    category: "striving",
  },
  {
    symbol: "settingrecords",
    category: "striving",
  },
  {
    symbol: "establishingleadership",
    category: "striving",
  },
  {
    symbol: "claimingleadership",
    category: "striving",
  },
  {
    symbol: "gainingadvantage",
    category: "striving",
  },
  {
    symbol: "gainingposition",
    category: "striving",
  },
  {
    symbol: "securingposition",
    category: "striving",
  },
  {
    symbol: "achievingmastery",
    category: "striving",
  },
  {
    symbol: "reachingpeak",
    category: "striving",
  },
  {
    symbol: "achievingpeak",
    category: "striving",
  },
  {
    symbol: "attainingmastery",
    category: "striving",
  },
  {
    symbol: "earningvictory",
    category: "striving",
  },
  {
    symbol: "achievingdominance",
    category: "striving",
  },
  {
    symbol: "securingwin",
    category: "striving",
  },
  {
    symbol: "finishingrace",
    category: "striving",
  },
  {
    symbol: "completingmission",
    category: "striving",
  },
  {
    symbol: "accomplishingobjective",
    category: "striving",
  },
  {
    symbol: "fulfillingpurpose",
    category: "striving",
  },
  {
    symbol: "achievingprogress",
    category: "striving",
  },
  {
    symbol: "reachingdestination",
    category: "striving",
  },
];
