import { SingleWordSymbol } from "../dreamSingularSymbols";

export const tools_symbols: SingleWordSymbol[] = [
  { symbol: "tapemeasure", category: "tools" },
  { symbol: "lanternhook", category: "tools" },
  { symbol: "chisel", category: "tools" },
  { symbol: "gluebottle", category: "tools" },
  { symbol: "hook", category: "tools" },
  { symbol: "screw", category: "tools" },
  { symbol: "stapler", category: "tools" },
  { symbol: "tape", category: "tools" },
  { symbol: "spiritlevel", category: "tools" },
  { symbol: "hammer", category: "tools" },
  { symbol: "tapedispenser", category: "tools" },
  { symbol: "wrenchhandle", category: "tools" },
  { symbol: "toolkit", category: "tools" },
  { symbol: "scotchtape", category: "tools" },
  { symbol: "crochet hook", category: "tools" },
  { symbol: "pipe cutter", category: "tools" },
  { symbol: "hotglue", category: "tools" },
  { symbol: "tapeholder", category: "tools" },
  { symbol: "boathook", category: "tools" },
  { symbol: "craftscissors", category: "tools" },
  { symbol: "videotape", category: "tools" },
  { symbol: "crochethook", category: "tools" },
  { symbol: "drill", category: "tools" },
  { symbol: "linehook", category: "tools" },
  { symbol: "toolboxlid", category: "tools" },
  { symbol: "level", category: "tools" },
  { symbol: "saw", category: "tools" },
  { symbol: "tape dispenser", category: "tools" },
  { symbol: "wrenchset", category: "tools" },
  { symbol: "stapleremover", category: "tools" },
  { symbol: "displayhook", category: "tools" },
  { symbol: "ruler", category: "tools" },
  { symbol: "scissors", category: "tools" },
  { symbol: "toolbox", category: "tools" },
  { symbol: "wrench", category: "tools" },
  { symbol: "tapeworm", category: "tools" },
  { symbol: "rotarycutter", category: "tools" },
  { symbol: "taperoll", category: "tools" },
  { symbol: "pliers", category: "tools" },
  { symbol: "maskingtape", category: "tools" },
  { symbol: "toolboxcase", category: "tools" },
  { symbol: "fishhook", category: "tools" },
  { symbol: "hangerhook", category: "tools" },
  { symbol: "staplerpin", category: "tools" },
  { symbol: "measuringtape", category: "tools" },
  { symbol: "laserlevel", category: "tools" },
  { symbol: "hammerhead", category: "tools" },
  { symbol: "nailfile", category: "tools" },
  { symbol: "nail", category: "tools" },
  { symbol: "rackhook", category: "tools" },
  { symbol: "chainsaw", category: "tools" },
  { symbol: "pizzacutter", category: "tools" },
  { symbol: "fretsaw", category: "tools" },
  { symbol: "pipe wrench", category: "tools" },
  { symbol: "corkscrew", category: "tools" },
  { symbol: "pipewrench", category: "tools" },
  { symbol: "framehook", category: "tools" },
  { symbol: "hammerhandle", category: "tools" },
  { symbol: "drillbit", category: "tools" },
  { symbol: "pipecutter", category: "tools" },
  { symbol: "circularsaw", category: "tools" },
  { symbol: "nailclipper", category: "tools" },
  { symbol: "fabricscissors", category: "tools" },
  { symbol: "ducttape", category: "tools" },
  { symbol: "handdrill", category: "tools" },
  { symbol: "staplestrip", category: "tools" },
  { symbol: "boltcutters", category: "tools" },
  { symbol: "packingtape", category: "tools" },
  { symbol: "claw hammer", category: "tools" },
  { symbol: "sledgehammer", category: "tools" },
  { symbol: "mallet", category: "tools" },
  { symbol: "rubber mallet", category: "tools" },
  { symbol: "ball peen hammer", category: "tools" },
  { symbol: "framing hammer", category: "tools" },
  { symbol: "tack hammer", category: "tools" },
  { symbol: "nail set", category: "tools" },
  { symbol: "nail puller", category: "tools" },
  { symbol: "crowbar", category: "tools" },
  { symbol: "pry bar", category: "tools" },
  { symbol: "wrecking bar", category: "tools" },
  { symbol: "utility knife", category: "tools" },
  { symbol: "box cutter", category: "tools" },
  { symbol: "wire cutter", category: "tools" },
  { symbol: "bolt cutter", category: "tools" },
  { symbol: "tin snips", category: "tools" },
  { symbol: "needle nose pliers", category: "tools" },
  { symbol: "locking pliers", category: "tools" },
  { symbol: "slip joint pliers", category: "tools" },
  { symbol: "channel lock pliers", category: "tools" },
  { symbol: "adjustable wrench", category: "tools" },
  { symbol: "monkey wrench", category: "tools" },
  { symbol: "torque wrench", category: "tools" },
  { symbol: "socket wrench", category: "tools" },
  { symbol: "ratchet wrench", category: "tools" },
  { symbol: "socket set", category: "tools" },
  { symbol: "hex key", category: "tools" },
  { symbol: "allen wrench", category: "tools" },
  { symbol: "screwdriver", category: "tools" },
  { symbol: "flathead screwdriver", category: "tools" },
  { symbol: "phillips screwdriver", category: "tools" },
  { symbol: "precision screwdriver", category: "tools" },
  { symbol: "nut driver", category: "tools" },
  { symbol: "hand drill", category: "tools" },
  { symbol: "power drill", category: "tools" },
  { symbol: "drill press", category: "tools" },
  { symbol: "drill bit", category: "tools" },
  { symbol: "impact driver", category: "tools" },
  { symbol: "impact wrench", category: "tools" },
  { symbol: "rotary tool", category: "tools" },
  { symbol: "angle grinder", category: "tools" },
  { symbol: "bench grinder", category: "tools" },
  { symbol: "circular saw", category: "tools" },
  { symbol: "table saw", category: "tools" },
  { symbol: "miter saw", category: "tools" },
  { symbol: "band saw", category: "tools" },
  { symbol: "jigsaw", category: "tools" },
  { symbol: "coping saw", category: "tools" },
  { symbol: "hacksaw", category: "tools" },
  { symbol: "hand saw", category: "tools" },
  { symbol: "pruning saw", category: "tools" },
  { symbol: "wood saw", category: "tools" },
  { symbol: "tubing cutter", category: "tools" },
  { symbol: "glass cutter", category: "tools" },
  { symbol: "tile cutter", category: "tools" },
  { symbol: "staple gun", category: "tools" },
  { symbol: "nail gun", category: "tools" },
  { symbol: "rivet gun", category: "tools" },
  { symbol: "caulking gun", category: "tools" },
  { symbol: "glue gun", category: "tools" },
  { symbol: "heat gun", category: "tools" },
  { symbol: "soldering iron", category: "tools" },
  { symbol: "solder sucker", category: "tools" },
  { symbol: "desolder pump", category: "tools" },
  { symbol: "multimeter", category: "tools" },
  { symbol: "voltage tester", category: "tools" },
  { symbol: "stud finder", category: "tools" },
  { symbol: "laser level", category: "tools" },
  { symbol: "bubble level", category: "tools" },
  { symbol: "plumb bob", category: "tools" },
  { symbol: "chalk line", category: "tools" },
  { symbol: "measuring tape", category: "tools" },
  { symbol: "carpenter square", category: "tools" },
  { symbol: "speed square", category: "tools" },
  { symbol: "framing square", category: "tools" },
  { symbol: "bevel gauge", category: "tools" },
  { symbol: "marking gauge", category: "tools" },
  { symbol: "center punch", category: "tools" },
  { symbol: "awl", category: "tools" },
  { symbol: "wood chisel", category: "tools" },
  { symbol: "cold chisel", category: "tools" },
  { symbol: "scraper", category: "tools" },
  { symbol: "putty knife", category: "tools" },
  { symbol: "drywall knife", category: "tools" },
  { symbol: "drywall saw", category: "tools" },
  { symbol: "trowel", category: "tools" },
  { symbol: "brick trowel", category: "tools" },
  { symbol: "pointing trowel", category: "tools" },
  { symbol: "finishing trowel", category: "tools" },
  { symbol: "float trowel", category: "tools" },
  { symbol: "grout float", category: "tools" },
  { symbol: "paint scraper", category: "tools" },
  { symbol: "wire brush", category: "tools" },
  { symbol: "sanding block", category: "tools" },
  { symbol: "sandpaper", category: "tools" },
  { symbol: "orbital sander", category: "tools" },
  { symbol: "belt sander", category: "tools" },
  { symbol: "palm sander", category: "tools" },
  { symbol: "wood plane", category: "tools" },
  { symbol: "block plane", category: "tools" },
  { symbol: "jack plane", category: "tools" },
  { symbol: "spokeshave", category: "tools" },
  { symbol: "lathe", category: "tools" },
  { symbol: "wood lathe", category: "tools" },
  { symbol: "metal lathe", category: "tools" },
  { symbol: "clamp", category: "tools" },
  { symbol: "bar clamp", category: "tools" },
  { symbol: "c clamp", category: "tools" },
  { symbol: "spring clamp", category: "tools" },
  { symbol: "pipe clamp", category: "tools" },
  { symbol: "bench vise", category: "tools" },
  { symbol: "vise grip", category: "tools" },
  { symbol: "anvil", category: "tools" },
  { symbol: "tool box", category: "tools" },
  { symbol: "tool chest", category: "tools" },
  { symbol: "tool cabinet", category: "tools" },
  { symbol: "tool bag", category: "tools" },
  { symbol: "tool belt", category: "tools" },
  { symbol: "tool tray", category: "tools" },
  { symbol: "socket tray", category: "tools" },
  { symbol: "parts tray", category: "tools" },
  { symbol: "magnetic tray", category: "tools" },
  { symbol: "ladder", category: "tools" },
  { symbol: "step ladder", category: "tools" },
  { symbol: "extension ladder", category: "tools" },
  { symbol: "scaffold", category: "tools" },
  { symbol: "workbench", category: "tools" },
  { symbol: "sawhorse", category: "tools" },
  { symbol: "wheelbarrow", category: "tools" },
  { symbol: "hand truck", category: "tools" },
  { symbol: "dolly", category: "tools" },
  { symbol: "shovel", category: "tools" },
  { symbol: "spade", category: "tools" },
  { symbol: "garden trowel", category: "tools" },
  { symbol: "garden fork", category: "tools" },
  { symbol: "garden rake", category: "tools" },
  { symbol: "hoe", category: "tools" },
  { symbol: "pickaxe", category: "tools" },
  { symbol: "mattock", category: "tools" },
  { symbol: "post hole digger", category: "tools" },
  { symbol: "tamper", category: "tools" },
  { symbol: "sledge", category: "tools" },
  { symbol: "axe", category: "tools" },
  { symbol: "hatchet", category: "tools" },
  { symbol: "splitting maul", category: "tools" },
  { symbol: "log splitter", category: "tools" },
  { symbol: "hedge trimmer", category: "tools" },
  { symbol: "pole saw", category: "tools" },
  { symbol: "leaf blower", category: "tools" },
  { symbol: "pressure washer", category: "tools" },
  { symbol: "grease gun", category: "tools" },
  { symbol: "oil can", category: "tools" },
  { symbol: "funnel", category: "tools" },
  { symbol: "shop vacuum", category: "tools" },
  { symbol: "air compressor", category: "tools" },
  { symbol: "air hose", category: "tools" },
  { symbol: "tire inflator", category: "tools" },
  { symbol: "spray gun", category: "tools" },
  { symbol: "paint sprayer", category: "tools" },
  { symbol: "paint roller", category: "tools" },
  { symbol: "paint brush", category: "tools" },
  { symbol: "paint tray", category: "tools" },
  { symbol: "drop cloth", category: "tools" },
  { symbol: "mixing paddle", category: "tools" },
  { symbol: "mortar mixer", category: "tools" },
  { symbol: "cement mixer", category: "tools" },
];
