import { SingleWordSymbol } from "../dreamSingularSymbols";

export const weapons_symbols: SingleWordSymbol[] = [
  { symbol: "gun", category: "weapons" },
  { symbol: "birdbath", category: "weapons" },
  { symbol: "spear", category: "weapons" },
  { symbol: "baseballbat", category: "weapons" },
  { symbol: "windshield", category: "weapons" },
  { symbol: "sword", category: "weapons" },
  { symbol: "carbattery", category: "weapons" },
  { symbol: "batterycase", category: "weapons" },
  { symbol: "elbowpad", category: "weapons" },
  { symbol: "bathsponge", category: "weapons" },
  { symbol: "fanblade", category: "weapons" },
  { symbol: "razorblade", category: "weapons" },
  { symbol: "bowlingball", category: "weapons" },
  { symbol: "arrow", category: "weapons" },
  { symbol: "rivetgun", category: "weapons" },
  { symbol: "saladbowl", category: "weapons" },
  { symbol: "rainshield", category: "weapons" },
  { symbol: "bowl", category: "weapons" },
  { symbol: "rollerblades", category: "weapons" },
  { symbol: "blade", category: "weapons" },
  { symbol: "batterybank", category: "weapons" },
  { symbol: "dagger", category: "weapons" },
  { symbol: "bathmat", category: "weapons" },
  { symbol: "bathtowel", category: "weapons" },
  { symbol: "axe", category: "weapons" },
  { symbol: "butterknife", category: "weapons" },
  { symbol: "giftbow", category: "weapons" },
  { symbol: "steakknife", category: "weapons" },
  { symbol: "utilityknife", category: "weapons" },
  { symbol: "bodyarmor", category: "weapons" },
  { symbol: "battery", category: "weapons" },
  { symbol: "armorplate", category: "weapons" },
  { symbol: "knifesheath", category: "weapons" },
  { symbol: "plasticknife", category: "weapons" },
  { symbol: "bow", category: "weapons" },
  { symbol: "sawblade", category: "weapons" },
  { symbol: "barcodegun", category: "weapons" },
  { symbol: "rifle", category: "weapons" },
  { symbol: "kitchenknife", category: "weapons" },
  { symbol: "staplegun", category: "weapons" },
  { symbol: "mixingbowl", category: "weapons" },
  { symbol: "gluegun", category: "weapons" },
  { symbol: "pistol", category: "weapons" },
  { symbol: "paletteknife", category: "weapons" },
  { symbol: "bat", category: "weapons" },
  { symbol: "puttyknife", category: "weapons" },
  { symbol: "mixerblade", category: "weapons" },
  { symbol: "golfclub", category: "weapons" },
  { symbol: "breadknife", category: "weapons" },
  { symbol: "knifeblock", category: "weapons" },
  { symbol: "bathroomscale", category: "weapons" },
  { symbol: "baton", category: "weapons" },
  { symbol: "sugarbowl", category: "weapons" },
  { symbol: "cerealbowl", category: "weapons" },
  { symbol: "shield", category: "weapons" },
  { symbol: "wheelbarrow", category: "weapons" },
  { symbol: "pickaxe", category: "weapons" },
  { symbol: "batterytray", category: "weapons" },
  { symbol: "heatshield", category: "weapons" },
  { symbol: "pipe elbow", category: "weapons" },
  { symbol: "pipeelbow", category: "weapons" },
  { symbol: "plasticbowl", category: "weapons" },
  { symbol: "pricegun", category: "weapons" },
  { symbol: "fruitbowl", category: "weapons" },
  { symbol: "servingbowl", category: "weapons" },
  { symbol: "batterypack", category: "weapons" },
  { symbol: "knife", category: "weapons" },
  { symbol: "armor", category: "weapons" },
  { symbol: "longsword", category: "weapons" },
  { symbol: "shortsword", category: "weapons" },
  { symbol: "broadsword", category: "weapons" },
  { symbol: "rapier", category: "weapons" },
  { symbol: "saber", category: "weapons" },
  { symbol: "katana", category: "weapons" },
  { symbol: "wakizashi", category: "weapons" },
  { symbol: "tanto", category: "weapons" },
  { symbol: "scimitar", category: "weapons" },
  { symbol: "cutlass", category: "weapons" },
  { symbol: "machete", category: "weapons" },
  { symbol: "kukri", category: "weapons" },
  { symbol: "bayonet", category: "weapons" },
  { symbol: "lance", category: "weapons" },
  { symbol: "pike", category: "weapons" },
  { symbol: "halberd", category: "weapons" },
  { symbol: "poleaxe", category: "weapons" },
  { symbol: "glaive", category: "weapons" },
  { symbol: "trident", category: "weapons" },
  { symbol: "harpoon", category: "weapons" },
  { symbol: "javelin", category: "weapons" },
  { symbol: "throwing spear", category: "weapons" },
  { symbol: "throwing knife", category: "weapons" },
  { symbol: "throwing star", category: "weapons" },
  { symbol: "shuriken", category: "weapons" },
  { symbol: "chakram", category: "weapons" },
  { symbol: "boomerang", category: "weapons" },
  { symbol: "club", category: "weapons" },
  { symbol: "cudgel", category: "weapons" },
  { symbol: "nightstick", category: "weapons" },
  { symbol: "billy club", category: "weapons" },
  { symbol: "mace", category: "weapons" },
  { symbol: "flail", category: "weapons" },
  { symbol: "morningstar", category: "weapons" },
  { symbol: "warhammer", category: "weapons" },
  { symbol: "battle axe", category: "weapons" },
  { symbol: "tomahawk", category: "weapons" },
  { symbol: "hatchet", category: "weapons" },
  { symbol: "crowbar", category: "weapons" },
  { symbol: "sling", category: "weapons" },
  { symbol: "slingshot", category: "weapons" },
  { symbol: "blowgun", category: "weapons" },
  { symbol: "dart gun", category: "weapons" },
  { symbol: "longbow", category: "weapons" },
  { symbol: "recurve bow", category: "weapons" },
  { symbol: "compound bow", category: "weapons" },
  { symbol: "crossbow", category: "weapons" },
  { symbol: "ballista", category: "weapons" },
  { symbol: "catapult", category: "weapons" },
  { symbol: "trebuchet", category: "weapons" },
  { symbol: "revolver", category: "weapons" },
  { symbol: "handgun", category: "weapons" },
  { symbol: "derringer", category: "weapons" },
  { symbol: "shotgun", category: "weapons" },
  { symbol: "sniper rifle", category: "weapons" },
  { symbol: "assault rifle", category: "weapons" },
  { symbol: "carbine", category: "weapons" },
  { symbol: "musket", category: "weapons" },
  { symbol: "blunderbuss", category: "weapons" },
  { symbol: "machine gun", category: "weapons" },
  { symbol: "submachine gun", category: "weapons" },
  { symbol: "gatling gun", category: "weapons" },
  { symbol: "minigun", category: "weapons" },
  { symbol: "grenade", category: "weapons" },
  { symbol: "hand grenade", category: "weapons" },
  { symbol: "smoke grenade", category: "weapons" },
  { symbol: "flashbang", category: "weapons" },
  { symbol: "stun grenade", category: "weapons" },
  { symbol: "fragmentation grenade", category: "weapons" },
  { symbol: "molotov cocktail", category: "weapons" },
  { symbol: "rocket launcher", category: "weapons" },
  { symbol: "grenade launcher", category: "weapons" },
  { symbol: "missile launcher", category: "weapons" },
  { symbol: "flamethrower", category: "weapons" },
  { symbol: "taser", category: "weapons" },
  { symbol: "stun gun", category: "weapons" },
  { symbol: "cattle prod", category: "weapons" },
  { symbol: "whip", category: "weapons" },
  { symbol: "riding crop", category: "weapons" },
  { symbol: "switchblade", category: "weapons" },
  { symbol: "folding knife", category: "weapons" },
  { symbol: "pocket knife", category: "weapons" },
  { symbol: "utility knife", category: "weapons" },
  { symbol: "box cutter", category: "weapons" },
  { symbol: "razor blade", category: "weapons" },
  { symbol: "scalpel", category: "weapons" },
  { symbol: "brass knuckles", category: "weapons" },
  { symbol: "knuckle duster", category: "weapons" },
  { symbol: "sap", category: "weapons" },
  { symbol: "blackjack", category: "weapons" },
  { symbol: "garrote", category: "weapons" },
  { symbol: "chain whip", category: "weapons" },
  { symbol: "nunchaku", category: "weapons" },
  { symbol: "tonfa", category: "weapons" },
  { symbol: "sai", category: "weapons" },
  { symbol: "kama", category: "weapons" },
  { symbol: "bo staff", category: "weapons" },
  { symbol: "quarterstaff", category: "weapons" },
  { symbol: "shepherd staff", category: "weapons" },
  { symbol: "spear gun", category: "weapons" },
  { symbol: "harpoon gun", category: "weapons" },
  { symbol: "nail gun", category: "weapons" },
  { symbol: "flare gun", category: "weapons" },
  { symbol: "spear thrower", category: "weapons" },
  { symbol: "blow dart", category: "weapons" },
  { symbol: "dart", category: "weapons" },
  { symbol: "fire lance", category: "weapons" },
  { symbol: "cannon", category: "weapons" },
  { symbol: "mortar", category: "weapons" },
  { symbol: "artillery", category: "weapons" },
  { symbol: "howitzer", category: "weapons" },
  { symbol: "tank cannon", category: "weapons" },
  { symbol: "railgun", category: "weapons" },
  { symbol: "laser rifle", category: "weapons" },
  { symbol: "plasma rifle", category: "weapons" },
  { symbol: "energy weapon", category: "weapons" },
];
